### PR TITLE
Skip Rangepolicy conversion check if roundtrip convertibility is not provided

### LINKED ISSUE #7005: RangePolicy construction fails if input bound types are not convertible to the policy's IndexType
Reported from https://github.com/ECP-copa/Cabana/pull/753#issuecomment-2103376470.
 
Changes made in #6754 expects `RangePolicy`'s input bound types to be convertible to the `RangePolicy`'s `IndexType`.

However, the conversion safety check in `RangePolicy` actually requires a full roundtrip convertibility:
https://github.com/kokkos/kokkos/blob/506da184f0aa8af9fbbca5bccd8c500b81865af5/core/src/Kokkos_ExecPolicy.hpp#L271-L272
and fails if only one way conversion is available.

Few options to mitigate this include:
- Adding constraints to the `RangePolicy` constructors (more conditions in `enable_if`)
- Making roundtrip convertibility a mandate (with a `static_assert`)
- Skipping the value preserving/narrowing check if only convertible one way (output a warning message about skipping the check)

### PR DESCRIPTION
**Pull request by ldh4**
Resolves #7005

`check_conversion_safety` in `RangePolicy` was requiring roundtrip convertibility between `member_type` and `IndexType`. The RangePolicy construction would fail to compile if convertibility is not supported for either direction.

This PR loosens that requirement, allowing RangePolicy be constructible as long as the user input index type (`IndexType`) is convertible to `member_type`. If `member_type` is not convertible to `IndexType`, the conversion safety check will be skipped.

### CODE REVIEW

File: core/src/Kokkos_ExecPolicy.hpp [hunk 1]
```diff
@@ -249,45 +249,55 @@ class RangePolicy : public Impl::PolicyTraits<Properties...> {
...
+      }
 #else
-    (void)bound;
+      (void)bound;
+#endif
+    } else {
+#ifdef KOKKOS_ENABLE_DEPRECATION_WARNINGS
+      std::string msg =
+          "Kokkos RangePolicy bound type warning: Two-way convertibility requirement on policy index type and input bound type is not met.
+          Conversion safety check is skipped."
```
Comment (ldh4) [inline core/src/Kokkos_ExecPolicy.hpp:297]: I think this could be better worded. If there's any suggestion, please let me know.

File: core/unit_test/TestRangePolicyConstructors.hpp [hunk 2]
```diff
@@ -128,6 +128,8 @@ TEST(TEST_CATEGORY_DEATH, range_policy_implicitly_converted_bounds) {
   using IntIndexType  = Kokkos::IndexType<int>;
   using UIntPolicy    = Kokkos::RangePolicy<TEST_EXECSPACE, UIntIndexType>;
   using IntPolicy     = Kokkos::RangePolicy<TEST_EXECSPACE, IntIndexType>;
+  using IntAtomicDataElementType =
+      Kokkos::Impl::AtomicDataElement<Kokkos::ViewTraits<int>>;
```
Comment (dalg24) [inline core/unit_test/TestRangePolicyConstructors.hpp:132]: Please define a type that is convertible to the range policy integral type but not constructible from it instead.
It will improve readability and avoid introducing an unnecessary dependency with implementation details from other facilities in the codebase.

File: core/src/Kokkos_ExecPolicy.hpp (hunk 1 above)
Comment (dalg24) [reply core/src/Kokkos_ExecPolicy.hpp:297]: I don't think we should warn at all.
We only want to raise warnings when we know for sure that something is wrong.  The current version would yield false positive and would force users to disable warnings and potential miss things they should be aware of.

**Review by dalg24 — CHANGES_REQUESTED** [review]

File: core/src/Kokkos_ExecPolicy.hpp (hunk 1 above)
Comment (ldh4) [reply core/src/Kokkos_ExecPolicy.hpp]: That's a fair point, that this warning is a false positive in many cases.
Removed this warning message.

File: core/unit_test/TestRangePolicyConstructors.hpp (hunk 2 above)
Comment (ldh4) [reply core/unit_test/TestRangePolicyConstructors.hpp]: Replaced to use a simple struct that is convertible to rangepolicy index_type instead.

File: core/src/Kokkos_ExecPolicy.hpp [hunk 3]
```diff
@@ -249,45 +249,48 @@ class RangePolicy : public Impl::PolicyTraits<Properties...> {
   // To be replaced with std::in_range (c++20)
   template <typename IndexType>
   static void check_conversion_safety(const IndexType bound) {
+    if constexpr (std::is_convertible_v<member_type, IndexType>) {
```
Comment (dalg24) [inline core/src/Kokkos_ExecPolicy.hpp:252]: Please add a comment above this line, something like
"Checking that the round-trip conversion preserve the value"

File: core/unit_test/TestRangePolicyConstructors.hpp [hunk 4]
```diff
@@ -158,6 +166,14 @@ TEST(TEST_CATEGORY_DEATH, range_policy_implicitly_converted_bounds) {
...
                  get_error_msg(expected, test_val));
   }
+  {
+    typename IntIndexType::type test_val = -1;
+    ASSERT_NO_THROW((void)IntPolicy(
+        -2,
+        TestIndexConversionCheck<typename IntPolicy::index_type>(test_val)));
+    ASSERT_NO_THROW((void)UIntPolicy(
+        0, TestIndexConversionCheck<typename IntPolicy::index_type>(test_val)));
+  }
```
Comment (dalg24) [inline core/unit_test/TestRangePolicyConstructors.hpp:176]: Shouldn't that pass regardless of whether deprecated code 4 is enabled or not?

File: core/unit_test/TestRangePolicyConstructors.hpp [hunk 5]
```diff
@@ -158,6 +166,14 @@ TEST(TEST_CATEGORY_DEATH, range_policy_implicitly_converted_bounds) {
     ASSERT_DEATH({ (void)UIntPolicy(test_val, 10, Kokkos::ChunkSize(2)); },
                  get_error_msg(expected, test_val));
   }
+  {
+    typename IntIndexType::type test_val = -1;
+    ASSERT_NO_THROW((void)IntPolicy(
+        -2,
+        TestIndexConversionCheck<typename IntPolicy::index_type>(test_val)));
+    ASSERT_NO_THROW((void)UIntPolicy(
+        0, TestIndexConversionCheck<typename IntPolicy::index_type>(test_val)));
```
Comment (dalg24) [inline core/unit_test/TestRangePolicyConstructors.hpp:175]:
```suggestion
        0, TestIndexConversionCheck<typename UIntPolicy::index_type>(test_val)));
```

File: core/unit_test/TestRangePolicyConstructors.hpp (hunk 4 above)
Comment (dalg24) [reply core/unit_test/TestRangePolicyConstructors.hpp:176]: Also I expect we only care about testing that a non-value preserving construction goes through, that is just the 2nd assertion?

File: core/src/Kokkos_ExecPolicy.hpp (hunk 3 above)
Comment (ldh4) [reply core/src/Kokkos_ExecPolicy.hpp:253]: Added a comment.

File: core/unit_test/TestRangePolicyConstructors.hpp (hunk 5 above)
Comment (ldh4) [reply core/unit_test/TestRangePolicyConstructors.hpp]: Ended up removing this line.

File: core/unit_test/TestRangePolicyConstructors.hpp (hunk 4 above)
Comment (ldh4) [reply core/unit_test/TestRangePolicyConstructors.hpp]: Fixed the test. Also removed a redundant test.
Whether `KOKKOS_ENABLE_DEPRECATED_CODE_4` is enabled or not doesn't affect the test, but it now will fail to compile without `if constexpr (std::is_convertible_v<member_type, IndexType>)` at the beginning of `check_conversion_safety()`.

**Review by nliber — APPROVED** [review]

File: core/unit_test/TestRangePolicyConstructors.hpp [hunk 6]
```diff
@@ -158,6 +166,15 @@ TEST(TEST_CATEGORY_DEATH, range_policy_implicitly_converted_bounds) {
...
                  get_error_msg(expected, test_val));
   }
+  {
+    using test_type = TestIndexConversionCheck<typename IntPolicy::index_type>;
+
+    static_assert(std::is_convertible_v<test_type, IntPolicy::index_type>);
+    static_assert(!std::is_convertible_v<IntPolicy::index_type, test_type>);
+
+    typename IntIndexType::type test_val = -1;
+    ASSERT_NO_THROW((void)IntPolicy(-2, test_type(&test_val)));
```
Comment (dalg24) [inline core/unit_test/TestRangePolicyConstructors.hpp:176]:
```suggestion
    using test_type = TestIndexConversionCheck<UIntPolicy::index_type>;

    static_assert(std::is_convertible_v<test_type, UIntPolicy::index_type>);
    static_assert(!std::is_convertible_v<UIntPolicy::index_type, test_type>);

    UIntPolicy::index_type test_val = -1;
    ASSERT_NO_THROW((void)UIntPolicy(-2, &test_val));
```
When you pick the signed integer version, you only test that it compiles.  If you pick the unsigned one, you also reveal that we would not currently catch that the issue.  I think it makes it a better choice.

File: core/unit_test/TestRangePolicyConstructors.hpp (hunk 4 above)
Comment (dalg24) [reply core/unit_test/TestRangePolicyConstructors.hpp]: > Whether `KOKKOS_ENABLE_DEPRECATED_CODE_4` is enabled or not doesn't affect the test, but it now will fail to compile without `if constexpr (std::is_convertible_v<member_type, IndexType>)` at the beginning of `check_conversion_safety()`.

My point is the test you added is guarded by `#ifndef KOKKOS_ENABLE_DEPRECATED_CODE_4` and that it should not be guarded.

Comment (ldh4) [reply core/unit_test/TestRangePolicyConstructors.hpp]: Moved this out of `#ifndef KOKKOS_ENABLE_DEPRECATED_CODE_4` guard and made into its own test.

File: core/unit_test/TestRangePolicyConstructors.hpp (hunk 6 above)
Comment (ldh4) [reply core/unit_test/TestRangePolicyConstructors.hpp]: Converted to unsigned.

**Review by masterleinad — APPROVED** [review]

**Comment by masterleinad** [comment]
```
/__w/kokkos/kokkos/core/unit_test/TestRangePolicyConstructors.hpp(143): error #68: integer conversion resulted in a change of sign
    UIntIndexType::type test_val = -1;
                                   ^

/__w/kokkos/kokkos/core/src/Kokkos_ExecPolicy.hpp(251): error #869: parameter "bound" was never referenced
    static void check_conversion_safety(const IndexType bound) {
                                                        ^
          detected during:
            instantiation of "void Kokkos::RangePolicy<Properties...>::check_conversion_safety(IndexType) [with Properties=<Kokkos::OpenMP, Kokkos::IndexType<unsigned int>>, IndexType=<unnamed>::TestIndexConversionCheck<unsigned int>]" at line 143
            instantiation of "Kokkos::RangePolicy<Properties...>::RangePolicy(const Kokkos::Impl::PolicyTraits<Properties...>::execution_space &, IndexType1, IndexType2) [with Properties=<Kokkos::OpenMP, Kokkos::IndexType<unsigned int>>, IndexType1=int, IndexType2=<unnamed>::TestIndexConversionCheck<unsigned int>, <unnamed>=false]" at line 128
            instantiation of "Kokkos::RangePolicy<Properties...>::RangePolicy(IndexType1, IndexType2) [with Properties=<Kokkos::OpenMP, Kokkos::IndexType<unsigned int>>, IndexType1=int, IndexType2=<unnamed>::TestIndexConversionCheck<unsigned int>, <unnamed>=false]" at line 144 of "/__w/kokkos/kokkos/core/unit_test/Te
```

File: core/unit_test/TestRangePolicyConstructors.hpp [hunk 7]
```diff
@@ -131,6 +131,19 @@ struct TestIndexConversionCheck {
   T* const value;
 };
 
+TEST(TEST_CATEGORAY, range_policy_one_way_convertible_bounds) {
```
Comment (nliber) [inline core/unit_test/TestRangePolicyConstructors.hpp:134]:
```suggestion
TEST(TEST_CATEGORY, range_policy_one_way_convertible_bounds) {
```

**Review by nliber — CHANGES_REQUESTED** [review]

**Review by nliber — APPROVED** [review]

**Comment by masterleinad** [comment]
Segfaulting in `range_policy_round_trip_conversion_fires`.

**Comment by dalg24** [comment]
Please fix

File: core/src/Kokkos_ExecPolicy.hpp [hunk 8]
```diff
@@ -247,46 +247,50 @@ class RangePolicy : public Impl::PolicyTraits<Properties...> {
...
-    }
+      std::string msg =
+          "Kokkos::RangePolicy bound type error: an unsafe implicit conversion "
+          "is performed on a bound (" +
+          std::to_string(bound) +
+          "), which may "
+          "not preserve its original value.\n";
+      bool warn = false;
+
+      if constexpr (std::is_arithmetic_v<IndexType> &&
```
[the remark this answers is not in the document]
Comment (ldh4) [reply core/src/Kokkos_ExecPolicy.hpp]: Removed `std::is_arithmetic_v<IndexType>` from this condition.

**Comment by dalg24** [comment]
Ignoring unrelated failures (NVC++ segfault, Clang+CUDA and CUDA with generated makefiles with GPU not detected at runtime, and host function called from host device function warning treated as error)

**Comment by dalg24** [comment]
Please add to the change log under bug fix
