### PR TITLE
Ensure valid data in empty UnorderedMap

### LINKED ISSUE #2625: deep_copy empty UnorderedMap segfaults
This code segfaults at the deep_copy() call:
```c++
#include <Kokkos_Core.hpp>
#include <Kokkos_UnorderedMap.hpp>

using ExecutionSpace = Kokkos::DefaultExecutionSpace;

using Key = int;
using Value = int;

int main(int argc, char* argv[]) {
  Kokkos::initialize(argc,argv); {

  using Map = Kokkos::UnorderedMap<Key,Value,ExecutionSpace>;

  Map m{};
  Map n{};
  /* n = Map{m.capacity()}; // this would segfault too*/
  n.rehash(m.capacity());
  Kokkos::deep_copy(n,m);

  } Kokkos::finalize();
}

```
However, it runs fine without the `n.rehash(m.capacity());` line. Both maps' `capacity()` return `0`.

### PR DESCRIPTION
**Pull request by masterleinad**
Fixes #2625.

### CODE REVIEW

**Comment by masterleinad** [comment]
Retest this please.

File: containers/src/Kokkos_UnorderedMap.hpp [hunk 1]
```diff
@@ -295,17 +295,7 @@ class UnorderedMap {
...
-        m_hasher(),
-        m_equal_to(),
-        m_size(),
-        m_available_indexes(),
-        m_hash_lists(),
-        m_next_index(),
-        m_keys(),
-        m_values(),
-        m_scalars() {}
+  UnorderedMap() : UnorderedMap(0) { m_bounded_insert = false; }
```
Comment (dalg24) [inline containers/src/Kokkos_UnorderedMap.hpp]: Please elaborate on why you flipped the `m_bounded_insert` data member and not just delegated to the other constructor.

Comment (masterleinad) [reply containers/src/Kokkos_UnorderedMap.hpp]: To me, this is the only real difference between the constructors. So I am flipping it back to retain the original behavior.

Comment (dalg24) [reply containers/src/Kokkos_UnorderedMap.hpp]: I doubt there was much thought put into that previous version of the default constructor.  My preference would go for giving a default value to the first argument of the other constructor.
Let's see what other think.

Comment (dsunder) [reply containers/src/Kokkos_UnorderedMap.hpp]: Since I wrote UnorderedMap I can verify that we didn't give much thought to the values of a default constructed map, since a default constructed map was designed to be an invalid map (similar to how a default constructed View is invalid).  In general I like this change because having an invalid default map doesn't buy us anything.  However, don't set `m_bounded_insert = false;`.  This will slow the code down greatly if you resize the map instead of assigning a new map to it because every thread will search the entire map to find an empty space before failing (greatly increasing the atomic contention).

Comment (masterleinad) [reply containers/src/Kokkos_UnorderedMap.hpp]: OK, thanks! I will change it accordingly.

**Review by dalg24 — APPROVED** [review]
