### PR TITLE
Disable numeric traits long double epsilon unit test with IBM XL

### LINKED ISSUE #3675: Build and test failures with xl builds: Numeric traits
Following merge of PR #3446  nightly tests with the xl/16.1.1 compiler began failing:

**Serial** (host only build) - test failures:

```bash
01:14:51 1: [ RUN      ] serial.numeric_traits_infinity
01:14:51 1: /home/jenkins/white/workspace/Kokkos_develop_white_xl_1611_serial/kokkos/core/unit_test/TestNumericTraits.hpp:116: Failure
01:14:51 1: Value of: 0
01:14:51 1: Expected: errors
01:14:51 1: Which is: 1
01:14:51 1: [  FAILED  ] serial.numeric_traits_infinity (0 ms)
01:14:51 1: [ RUN      ] serial.numeric_traits_epsilon
01:14:51 1: /home/jenkins/white/workspace/Kokkos_develop_white_xl_1611_serial/kokkos/core/unit_test/TestNumericTraits.hpp:116: Failure
01:14:51 1: Value of: 0
01:14:51 1: Expected: errors
01:14:51 1: Which is: 1
01:14:51 1: [  FAILED  ] serial.numeric_traits_epsilon (0 ms)
```

Reproducer

```bash
module load cmake/3.12.3 ibm/xl/16.1.1 gcc/7.2.0

$KOKKOS_PATH/generate_makefile.bash --with-devices=Serial --arch=Power8,Pascal60 --compiler=xlC --cxxflags="-O3 -Wall -Wunused-parameter -Wshadow -pedantic -Wsign-compare -Wtype-limits -Wuninitialized -isystem /home/projects/ppc64le/gcc/7.2.0/include/c++/7.2.0/powerpc64le-unknown-linux-gnu -qgcc_cpp_stdinc=/home/projects/ppc64le/gcc/7.2.0/include/c++/7.2.0 -qxflag=disable__cplusplusOverride -I/home/projects/ppc64le/gcc/7.2.0/include/c++/7.2.0/powerpc64le-unknown-linux-gnu" --cxxstandard="14"  --kokkos-path=$KOKKOS_PATH --no-examples --with-options=enable_large_mem_tests
```

------

**Cuda_Serial** - compilation error:

```bash
01:20:47 /home/jenkins/white/workspace/Kokkos_develop_white_cuda_101_xl_161_pascal_cuda-serial/kokkos/core/src/Kokkos_NumericTraits.hpp(98): error: a constexpr static data member declaration requires an in-class initializer
01:20:47 
01:20:47 /home/jenkins/white/workspace/Kokkos_develop_white_cuda_101_xl_161_pascal_cuda-serial/kokkos/core/src/Kokkos_NumericTraits.hpp(98): error: data member initializer is not allowed
01:20:47 
01:20:47 2 errors detected in the compilation of "/tmp/tmpxft_000184ce_00000000-6_Kokkos_NumericTraits.cpp1.ii".
```

Reproducer

```bash
module load cmake/3.12.3 cuda/10.1.105 gcc/7.2.0 ibm/xl/16.1.1

$KOKKOS_PATH/generate_makefile.bash --with-devices=Cuda,Serial --arch=Power8,Pascal60 --compiler=$KOKKOS_PATH/bin/nvcc_wrapper --cxxflags="-O3 -Wall -Wunused-parameter -Wshadow -pedantic -Werror -Wsign-compare -Wtype-limits -Wuninitialized -ccbin xlc++ -isystem /home/projects/ppc64le/gcc/7.2.0/include/c++/7.2.0/powerpc64le-unknown-linux-gnu -qgcc_cpp_stdinc=/home/projects/ppc64le/gcc/7.2.0/include/c++/7.2.0 -qxflag=disable__cplusplusOverride -I/home/projects/ppc64le/gcc/7.2.0/include/c++/7.2.0/powerpc64le-unknown-linux-gnu -Wno-unused-function" --cxxstandard="14" --with-cuda --kokkos-path=$KOKKOS_PATH  --no-examples --with-options=enable_large_mem_tests
```

### PR DESCRIPTION
**Pull request by dalg24**
Fix #3675

### CODE REVIEW

**Review by masterleinad — APPROVED** [review]
This is what we agreed upon doing. We of course need to check that it works indeed.

File: core/unit_test/TestNumericTraits.hpp [hunk 1]
```diff
@@ -204,7 +204,9 @@ TEST(TEST_CATEGORY, numeric_traits_infinity) {
 TEST(TEST_CATEGORY, numeric_traits_epsilon) {
   TestNumericTraits<TEST_EXECSPACE, float, Epsilon>();
   TestNumericTraits<TEST_EXECSPACE, double, Epsilon>();
+#ifndef KOKKOS_COMPILER_IBM
```
Comment (Rombur) [inline core/unit_test/TestNumericTraits.hpp:207]: Can you add a comment about which version of IBM compiler does not work so that we can revisit this later.

**Review by Rombur — APPROVED** [review]

**Review by ndellingwood — APPROVED** [review]

File: core/unit_test/TestNumericTraits.hpp (hunk 1 above)
Comment (dalg24) [reply core/unit_test/TestNumericTraits.hpp]: Done
