### PR TITLE
#4126 error on initialize after finalize

### LINKED ISSUE #4126: All backends should error out if initialize called after finalize
Calling `Kokkos::initialize()` after `Kokkos::finalize()` can lead memory corruption and crashes with the `Serial` backend, see https://github.com/lammps/lammps/pull/2470. Some backends like `Cuda` check for this and error out, see https://github.com/kokkos/kokkos/blob/master/core/src/Cuda/Kokkos_Cuda_Instance.cpp#L306, while others like `Serial` do not. It would be very helpful to users if all backends checked for this and consistently errored out.

### PR DESCRIPTION
**Pull request by nmm0**
Closes #4126

### CODE REVIEW

**Comment by nmm0** [comment]
Retest this please

**Review by crtrott — APPROVED** [review]

File: core/src/Kokkos_SYCL.hpp [hunk 1]
```diff
@@ -166,10 +166,11 @@ namespace Impl {
 
 class SYCLSpaceInitializer : public Kokkos::Impl::ExecSpaceInitializerBase {
```
Comment (nliber) [inline core/src/Kokkos_SYCL.hpp:167]: These classes should also be marked as `final`, as that gives a slightly different guarantee than marking all the overridden `virtual` functions as `final` (which should remain, as that is an additional check that the `virtual` function signature is correct).

**Review by nliber — CHANGES_REQUESTED** [review]

**Review by dalg24 — APPROVED** [review]

File: core/src/Kokkos_SYCL.hpp (hunk 1 above)
Comment (dalg24) [reply core/src/Kokkos_SYCL.hpp:167]: What other guarantee else than "no other class would then be able to derive from it"?
In any case this can be addressed elsewhere (I am not convinced we should do anything about it in the first place)

**Review by masterleinad — APPROVED** [review]
Looks OK to me.

File: core/src/Kokkos_SYCL.hpp (hunk 1 above)
Comment (nmm0) [reply core/src/Kokkos_SYCL.hpp:167]: Is there any need for the specific initializers to be able to be derived from? I can add @nliber 's modifications pretty easily. Or is this something that should be voted on

Comment (nliber) [reply core/src/Kokkos_SYCL.hpp:167]: If we are marking things `final`, we should go ahead and mark the whole class as `final` (it's really weird otherwise).  Alternatively (and my slight preference), we can just mark those virtual functions as `override`.

FYI:  The `final` keyword can help with optimizations by compilers that do devirtualization.

**Review by nliber — APPROVED** [review]
