### PR TITLE
Desul atomics enable backends based on configuration

### LINKED ISSUE #5665: Compilation failures in non-Cuda builds using nvcc_wrapper
**Describe the bug**

Compiling Kokkos using nvcc_wrapper without Cuda result in compilation errors as below:

```
23:55:38 /home/jenkins/jenkins-new/workspace/Kokkos_develop_kokkos-dev-2_nvccwrapper_nocuda_gcc830/kokkos/core/src/../../tpls/desul/include/desul/atomics/Fetch_Op_ScopeCaller.hpp(45): error: calling a __host__ function("Test::long_wrapper::operator =") from a __device__ function("desul::Impl::device_atomic_fetch_oper< ::desul::Impl::store_operator< ::Test::long_wrapper, const  ::Test::long_wrapper> ,  ::Test::long_wrapper,  ::desul::MemoryOrderRelease> ") is not allowed
```

**Please also include the following items to support reproducing the bug**
**Reproducer** (kokkos-dev-2):
```bash

source /projects/sems/modulefiles/utils/sems-archive-modules-init.sh
module purge
module load sems-archive-env
module load sems-archive-cuda/11.1 sems-cmake/3.18.4 sems-archive-gcc/8.3.0

cmake -DCMAKE_CXX_COMPILER=$KOKKOS_PATH/bin/nvcc_wrapper -DKokkos_ENABLE_SERIAL=ON -DKokkos_ENABLE_TESTS=ON -DKokkos_ENABLE_EXAMPLES=OFF -DCMAKE_VERBOSE_MAKEFILE=ON -DCMAKE_CXX_EXTENSIONS=OFF -DCMAKE_BUILD_TYPE=RELEASE -DKokkos_ENABLE_DEPRECATION_WARNINGS=OFF -DKokkos_ENABLE_DEPRECATED_CODE_4=OFF $KOKKOS_PATH
```

### PR DESCRIPTION
**Pull request by dalg24**
Fixes #5665
At this time I would like feedback on the updates to the build system, both the generated makefiles and cmake when using our own version of Desul.

### CODE REVIEW

File: tpls/desul/include/desul/atomics/Macros.hpp [hunk 1]
```diff
@@ -31,20 +33,25 @@ SPDX-License-Identifier: (BSD-3-Clause)
...
 
-#if defined(__CUDA_ARCH__) || defined(__HIP_DEVICE_COMPILE__) || \
-    defined(__SYCL_DEVICE_ONLY__)
+#if defined(DESUL_ATOMICS_ENABLE_OPENMP)
+#define DESUL_HAVE_OPENMP_ATOMICS
+#endif
+
+#if (defined(DESUL_ATOMICS_ENABLE_CUDA) && defined(__CUDA_ARCH__)) || \
+    (defined(DESUL_ATOMICS_ENABLE_HIP) && defined(__HIP_DEVICE_COMPILE__)) || \
+    (defined(DESUL_ATOMICS_ENABLE_SYCL) && defined(__SYCL_DEVICE_ONLY__))
```
Comment (dalg24) [inline tpls/desul/include/desul/atomics/Macros.hpp:54]: Just a note to myself that I messed up the format here

File: core/src/Kokkos_Atomics_Desul_Config.hpp [hunk 2]
```diff
@@ -23,10 +23,6 @@ static_assert(false,
 
 #include <Kokkos_Macros.hpp>
 
-#ifdef KOKKOS_ENABLE_OPENMPTARGET
-#define DESUL_HAVE_OPENMP_ATOMICS
-#endif
```
Comment (dalg24) [inline core/src/Kokkos_Atomics_Desul_Config.hpp:28]: `CUDA-11.7-NVCC` build that uses generated makefiles fails
I forgot about non-cmake builds...

File: Makefile.kokkos [hunk 3]
```diff
@@ -1378,19 +1378,72 @@ endif
 KOKKOS_EXTRA_LIBS := ${KOKKOS_LIBS}
 KOKKOS_LIBS := -lkokkos ${KOKKOS_LIBS}
 
+# Generating the <desul/atomics/Config.hpp> header
+DESUL_INTERNAL_CONFIG_TMP=Desul_Config.tmp
+ifeq ($(KOKKOS_INTERNAL_DISABLE_DESUL_ATOMICS), 0)
+  DESUL_CONFIG_HEADER=desul/atomics/Config.hpp
+else
+  DESUL_CONFIG_HEADER=NothingToSeeHereMoveAlong
+endif
```
Comment (masterleinad) [inline Makefile.kokkos:1387]: Any reason not to guard the whole following code block so that you only generate anything if (the bundled) `desul` is used?

File: core/src/CMakeLists.txt [hunk 4]
```diff
@@ -4,6 +4,22 @@ KOKKOS_INCLUDE_DIRECTORIES(
   ${KOKKOS_TOP_BUILD_DIR}
 )
 IF (Kokkos_ENABLE_IMPL_DESUL_ATOMICS AND NOT desul_FOUND)
```
Comment (masterleinad) [inline core/src/CMakeLists.txt:6]: I think we should try to check for compatibility if an external `desul` installation is used. Ideally, the CMake variables used here would also become exported `desul` `CMake` options.

**Review by masterleinad — COMMENTED** [review]
I like the approach of using `#cmakedefine` here. The question would be how to expose this in `desul`'s `CMake` interface (as cached variable, normal variable, user-visible, exported?) but that's more for the corresponding pull request on the `desul` side.

File: Makefile.kokkos (hunk 3 above)
Comment (dalg24) [reply Makefile.kokkos:1387]: Did not want to indent the block and we are about to drop support for disabling Desul atomics

File: core/src/CMakeLists.txt (hunk 4 above)
Comment (dalg24) [reply core/src/CMakeLists.txt:6]: I agree but this is beyond the scope of this PR

Comment (dalg24) [reply core/src/CMakeLists.txt:6]: I updated desul/desul#85 to export `desul_atomics_{CUDA,HIP,SYCL,OPENMP}` variables

File: Makefile.kokkos (hunk 3 above)
Comment (masterleinad) [reply Makefile.kokkos:1387]: I didn't mean to ask about an external `desul` here but only about using non-desul atomics.

**Review by crtrott — APPROVED** [review]

**Review by masterleinad — APPROVED** [review]
Looks OK to me. There really is no point in pulling `desul`'s `CMakeLists.txt` and `desul_atomicsConfig.cmake.in` in here, too.
