### PR TITLE
tests(graph): filesystem not supported by old compilers so skip these tests

### LINKED ISSUE #7416: Nightly job failures, Hip and Cuda with gcc/8.5.0 in the toolchain: linking issues related to std::filesystem
**Describe the bug**

Nightly Hip jobs, with gcc/8.5.0 on the system path, have linkage issue related to std::filesystem:
```
20:59:25 ld.lld: error: undefined symbol: std::filesystem::temp_directory_path[abi:cxx11]()
20:59:25 >>> referenced by TestHIP_InterOp_Graph.cpp
20:59:25 >>>               CMakeFiles/Kokkos_CoreUnitTest_HIPInterOpGraph.dir/hip/TestHIP_InterOp_Graph.cpp.o:((anonymous namespace)::hip_graph_instantiate_and_debug_dot_print_Test::TestBody())
20:59:25 
20:59:25 ld.lld: error: undefined symbol: std::filesystem::status(std::filesystem::__cxx11::path const&)
20:59:25 >>> referenced by TestHIP_InterOp_Graph.cpp
20:59:25 >>>               CMakeFiles/Kokkos_CoreUnitTest_HIPInterOpGraph.dir/hip/TestHIP_InterOp_Graph.cpp.o:((anonymous namespace)::hip_graph_instantiate_and_debug_dot_print_Test::TestBody())
20:59:25 
20:59:25 ld.lld: error: undefined symbol: std::filesystem::file_size(std::filesystem::__cxx11::path const&)
20:59:25 >>> referenced by TestHIP_InterOp_Graph.cpp
20:59:25 >>>               CMakeFiles/Kokkos_CoreUnitTest_HIPInterOpGraph.dir/hip/TestHIP_InterOp_Graph.cpp.o:((anonymous namespace)::hip_graph_instantiate_and_debug_dot_print_Test::TestBody())
20:59:25 
20:59:25 ld.lld: error: undefined symbol: std::filesystem::__cxx11::path::_M_split_cmpts()
20:59:25 >>> referenced by TestHIP_InterOp_Graph.cpp
20:59:25 >>>               CMakeFiles/Kokkos_CoreUnitTest_HIPInterOpGraph.dir/hip/TestHIP_InterOp_Graph.cpp.o:(std::filesystem::__cxx11::path::path<char [14], std::filesystem::__cxx11::path>(char const (&) [14], std::filesystem::__cxx11::path::format))
20:59:25 >>> referenced by TestHIP_InterOp_Graph.cpp
20:59:25 >>>               CMakeFiles/Kokkos_CoreUnitTest_HIPInterOpGraph.dir/hip/TestHIP_InterOp_Graph.cpp.o:(std::filesystem::__cxx11::path::operator/=(std::filesystem::__cxx11::path const&))
20:59:25 
20:59:25 ld.lld: error: undefined symbol: std::filesystem::__cxx11::path::has_root_directory() const
20:59:25 >>> referenced by TestHIP_InterOp_Graph.cpp
20:59:25 >>>               CMakeFiles/Kokkos_CoreUnitTest_HIPInterOpGraph.dir/hip/TestHIP_InterOp_Graph.cpp.o:(std::filesystem::__cxx11::path::operator/=(std::filesystem::__cxx11::path const&))
20:59:25 
20:59:25 ld.lld: error: undefined symbol: std::filesystem::__cxx11::path::has_filename() const
20:59:25 >>> referenced by TestHIP_InterOp_Graph.cpp
20:59:25 >>>               CMakeFiles/Kokkos_CoreUnitTest_HIPInterOpGraph.dir/hip/TestHIP_InterOp_Graph.cpp.o:(std::filesystem::__cxx11::path::operator/=(std::filesystem::__cxx11::path const&))
20:59:25 clang: error: linker command failed with exit code 1 (use -v to see invocation)
20:59:25 make[2]: *** [core/unit_test/CMakeFiles/Kokkos_CoreUnitTest_HIPInterOpGraph.dir/build.make:122: core/unit_test/Kokkos_CoreUnitTest_HIPInterOpGraph] Error 1
```

A couple more notes:

* This issue has not occurred with all jobs using gcc/8, I'm not sure yet why the discrepancy
* Might be related to this note from [cppreference.com](https://en.cppreference.com/w/cpp/filesystem)

> Using this library may require additional compiler/linker options. GNU implementation prior to 9.1 requires linking with -lstdc++fs and LLVM implementation prior to LLVM 9.0 requires linking with -lc++fs. 

This began occurring following merge of these commits:

**Changes**

    Bump actions/cache from 4.0.2 to 4.1.0 ([details](https://jenkins-son.sandia.gov/job/Kokkos_develop_carawaymi210_rocm600_hip_serial/187/changes#efdd419d4588f870edf89f13af2cddb8e145c953) / [githubweb](https://github.com/kokkos/kokkos/commit/efdd419d4588f870edf89f13af2cddb8e145c953))
    Bump github/codeql-action from 3.26.9 to 3.26.11 ([details](https://jenkins-son.sandia.gov/job/Kokkos_develop_carawaymi210_rocm600_hip_serial/187/changes#7ec89289efdebb3332638d0efbb74190151e98e0) / [githubweb](https://github.com/kokkos/kokkos/commit/7ec89289efdebb3332638d0efbb74190151e98e0))
    graph: allow access to native graph object ([details](https://jenkins-son.sandia.gov/job/Kokkos_develop_carawaymi210_rocm600_hip_serial/187/changes#54980770f44beb8799f5deb47fdfb0b827912425) / [githubweb](https://github.com/kokkos/kokkos/commit/54980770f44beb8799f5deb47fdfb0b827912425))
    Use hipMallocAsync when using HIP execution space (#7324) ([details](https://jenkins-son.sandia.gov/job/Kokkos_develop_carawaymi210_rocm600_hip_serial/187/changes#d188dd5440bc883245bb6e4e7512e8c2f3148e3d) / [githubweb](https://github.com/kokkos/kokkos/commit/d188dd5440bc883245bb6e4e7512e8c2f3148e3d))
    Refactor: Remove unnecessary `Mirror*Types` structs (#7339) ([details](https://jenkins-son.sandia.gov/job/Kokkos_develop_carawaymi210_rocm600_hip_serial/187/changes#fdb75ebcc7aa61e7d67379cd161605350ed6f7d4) / [githubweb](https://github.com/kokkos/kokkos/commit/fdb75ebcc7aa61e7d67379cd161605350ed6f7d4))

**Please include the following for a minimal reproducer**

**Reproducer notes** (caraway MI210 queue):
```bash
salloc -N 1 -p MI210

module load cmake rocm/6.0.0

${KOKKOS_PATH}/generate_makefile.bash --with-hip --with-serial --compiler=hipcc --arch=VEGA90A --kokkos-path=${KOKKOS_PATH}

make -j16
```

### PR DESCRIPTION
**Pull request by romintomasetti**
Fixes #7416.

Basically, `gcc` older than `9.1.0` and `LLVM` older than `11` would require additional link flags (that sometimes do not even fix all the undefined references).

Therefore, this PR disables the problematic tests for old host compilers that fall into the above condition.

See https://github.com/kokkos/kokkos/issues/7416#issuecomment-2400691182 for more details.

### CODE REVIEW

File: core/unit_test/cuda/TestCuda_InterOp_Graph.cpp [hunk 1]
```diff
@@ -97,6 +97,10 @@ TEST_F(TEST_CATEGORY_FIXTURE(GraphInterOp), count_nodes) {
 TEST_F(TEST_CATEGORY_FIXTURE(GraphInterOp), debug_dot_print) {
 #if CUDA_VERSION < 11600
   GTEST_SKIP() << "Export a graph to DOT requires Cuda 11.6.";
+#elif KOKKOS_COMPILER_GNU < 910
+  GTEST_SKIP() << "'filesystem' is not fully supported prior to GCC 9.1.0.";
+#elif KOKKOS_COMPILER_CLANG < 1100
+  GTEST_SKIP() << "'filesystem' is not fully supported prior to LLVM 11.";
 #else
```
Comment (masterleinad) [inline core/unit_test/cuda/TestCuda_InterOp_Graph.cpp:104]: This is a compilation failure, not a runtime failure, right?

Comment (romintomasetti) [reply core/unit_test/cuda/TestCuda_InterOp_Graph.cpp:104]: It is a linkage error.

Comment (masterleinad) [reply core/unit_test/cuda/TestCuda_InterOp_Graph.cpp:104]: We normally use `GTEST_SKIP` when we are still testing compiling the test and disable it otherwise fully.

**Review by masterleinad — APPROVED** [review]

**Review by cwpearson — APPROVED** [review]

**Comment by romintomasetti** [comment]
@ndellingwood Could you test this ?

**Comment by ndellingwood** [comment]
@romintomasetti thanks for looking into this, testing now

**Review by ndellingwood — APPROVED** [review]
The change prevents the linkage issues picked up in the hip nightly jobs, thanks @romintomasetti !

**Comment by ndellingwood** [comment]
CI `CUDA-12.2-NVHPC-AS-HOST-COMPILER` job failed with a seg fault during compilation, maybe the machine ran out of memory? The failure should be unrelated to the changes in this PR in any case
```
/var/jenkins/workspace/Kokkos_PR-7418/bin/nvcc_wrapper: line 659: 37222 Segmentation fault      (core dumped) TMPDIR=${temp_dir} $nvcc_depfile_command

make[2]: *** [core/unit_test/CMakeFiles/Kokkos_CoreUnitTest_Cuda1.dir/build.make:986: core/unit_test/CMakeFiles/Kokkos_CoreUnitTest_Cuda1.dir/cuda/TestCuda_Reducers_d.cpp.o] Error 139

make[2]: *** Deleting file 'core/unit_test/CMakeFiles/Kokkos_CoreUnitTest_Cuda1.dir/cuda/TestCuda_Reducers_d.cpp.o'

make[1]: *** [CMakeFiles/Makefile2:1613: core/unit_test/CMakeFiles/Kokkos_CoreUnitTest_Cuda1.dir/all] Error 2

make[1]: *** Waiting for unfinished jobs....
```

**Review by tcclevenger — APPROVED** [review]
Ran into this issue on caraway today. This branch fixes it for me.

File: core/unit_test/cuda/TestCuda_InterOp_Graph.cpp [hunk 2]
```diff
@@ -97,6 +97,10 @@ TEST_F(TEST_CATEGORY_FIXTURE(GraphInterOp), count_nodes) {
 TEST_F(TEST_CATEGORY_FIXTURE(GraphInterOp), debug_dot_print) {
 #if CUDA_VERSION < 11600
   GTEST_SKIP() << "Export a graph to DOT requires Cuda 11.6.";
+#elif KOKKOS_COMPILER_GNU < 910
+  GTEST_SKIP() << "'filesystem' is not fully supported prior to GCC 9.1.0.";
```
Comment (dalg24) [inline core/unit_test/cuda/TestCuda_InterOp_Graph.cpp:101]:
```suggestion
  GTEST_SKIP() << "GNU implementation prior to 9.1 requires linking with '-lstdc++fs'";
```

File: core/unit_test/cuda/TestCuda_InterOp_Graph.cpp [hunk 3]
```diff
@@ -97,6 +97,10 @@ TEST_F(TEST_CATEGORY_FIXTURE(GraphInterOp), count_nodes) {
...
+#elif KOKKOS_COMPILER_CLANG < 1100
+  GTEST_SKIP() << "'filesystem' is not fully supported prior to LLVM 11.";
```
Comment (dalg24) [inline core/unit_test/cuda/TestCuda_InterOp_Graph.cpp:103]:
```suggestion
  GTEST_SKIP() << "LLVM implementation prior to LLVM 9.0 requires linking with '-lc++fs'";
```

**Review by dalg24 — COMMENTED** [review]
(Updating the skip message is optional. You may ignore the suggestions.)

> Ran into this issue on caraway (HIP) today. This branch fixes it for me. Thanks!

I am a bit surprised. What were the associated Clang/hipcc versions associated with it?

**Comment by tcclevenger** [comment]
> I am a bit surprised. What were the associated Clang/hipcc versions associated with it?

The clang version is 16, but I'm guessing it's picking up gcc version 8.5 from the cmake/ctest located in `/projects/x86-64-zen-rocky8/utilities/cmake/3.27.4/gcc/8.5.0/base/4wmpm4r/bin/` folder.

**Comment by dalg24** [comment]
But then I expected `KOKKOS_COMPILER_GNU` would not be defined...

**Comment by tcclevenger** [comment]
Only `KOKKOS_COMPILER_CLANG` is defined (not `KOKKOS_COMPILER_GNU`), but we are picking up the condition 
```
#elif KOKKOS_COMPILER_GNU < 910
  GTEST_SKIP() << "'filesystem' is not fully supported prior to GCC 9.1.0.";
```
Maybe if `!defined(KOKKOS_COMPILER_GNU)`, it evaluates as 0? So this test is always being skipped?

**Comment by tcclevenger** [comment]
Follow up, the reason I was seeing the link fail was I needed to add the flag `-DCMAKE_EXE_LINKER_FLAGS="-lstdc++fs"` to my configuration.
