### PR TITLE
Fix misalignment issues for CUDA and HIP combined reducers

### LINKED ISSUE #8426: Combined reducer fail on Cuda backends with `int16_t` and `int8_t`
When calling a combined reducer with `int16_t` or `int8_t` values for the reducer, the CUDA backend always returns 0 for certain amounts of arguments.

For instance, the following code:
```C++
#include <gtest/gtest.h>
#include <Kokkos_Core.hpp>

template <class T>
void test_func() {
    T ret1, ret2, ret3, ret4, ret5, ret6, ret7, ret8;

    // 2 args
    auto l2 = KOKKOS_LAMBDA(const int i, T& ret1, T& ret2) {
      ret1 = static_cast<T>(1);
    };

    Kokkos::parallel_reduce(Kokkos::RangePolicy(0, 1), l2, ret1, ret2);
    EXPECT_EQ(ret1, 1) << "2 args ";

    // 3 args
    auto l3 = KOKKOS_LAMBDA(const int i, T& ret1, T& ret2, T& ret3) {
      ret1 = static_cast<T>(1);
    };

    Kokkos::parallel_reduce(Kokkos::RangePolicy(0, 1), l3, ret1, ret2, ret3);
    EXPECT_EQ(ret1, 1) << "3 args ";

    // 4 args
    auto l4 = KOKKOS_LAMBDA(const int i, T& ret1, T& ret2, T& ret3, T& ret4) {
      ret1 = static_cast<T>(1);
    };

    Kokkos::parallel_reduce(Kokkos::RangePolicy(0, 1), l4, ret1, ret2, ret3,
                            ret4);
    EXPECT_EQ(ret1, 1) << "4 args ";

    // 5 args
    auto l5 = KOKKOS_LAMBDA(const int i, T& ret1, T& ret2, T& ret3, T& ret4,
                           T& ret5) {
      ret1 = static_cast<T>(1);
    };

    Kokkos::parallel_reduce(Kokkos::RangePolicy(0, 1), l5, ret1, ret2, ret3,
                            ret4, ret5);
    EXPECT_EQ(ret1, 1) << "5 args ";

    // 6 args
    auto l6 = KOKKOS_LAMBDA(const int i, T& ret1, T& ret2, T& ret3, T& ret4,
                           T& ret5, T& ret6) {
      ret1 = static_cast<T>(1);
    };

    Kokkos::parallel_reduce(Kokkos::RangePolicy(0, 1), l6, ret1, ret2, ret3,
                            ret4, ret5, ret6);
    EXPECT_EQ(ret1, 1) << "6 args ";
 
    // 7 args 
    auto l7 = KOKKOS_LAMBDA(const int i, T& ret1, T& ret2, T& ret3, T& ret4,
                           T& ret5, T& ret6, T& ret7) {
      ret1 = static_cast<T>(1);
    };

    Kokkos::parallel_reduce(Kokkos::RangePolicy(0, 1), l7, ret1, ret2, ret3,
                            ret4, ret5, ret6, ret7);
    EXPECT_EQ(ret1, 1) << "7 args ";
 
    // 8 args 
    auto l8 = KOKKOS_LAMBDA(const int i, T& ret1, T& ret2, T& ret3, T& ret4,
                           T& ret5, T& ret6, T& ret7, T& ret8) {
      ret1 = static_cast<T>(1);
    };

    Kokkos::parallel_reduce(Kokkos::RangePolicy(0, 1), l8, ret1, ret2, ret3,
                            ret4, ret5, ret6, ret7, ret8);
    EXPECT_EQ(ret1, 1) << "8 args ";
}

namespace Test {
TEST(defaultdevicetype, development_test) {
  std::cout << "\ndouble:\n";
  test_func<double>();
  std::cout << "\nfloat:\n";
  test_func<float>();
  std::cout << "\nint8_t:\n";
  test_func<int8_t>();
  std::cout << "\nint16_t:\n";
  test_func<int16_t>();
  std::cout << "\nint32_t:\n";
  test_func<int32_t>();
  std::cout << "\nint64:\n";
  test_func<int64_t>();
}
}  // namespace Test
```

Produces:
```
double:

float:

int8_t:
/gpfs/users/gannayp/kokkos/core/unit_test/default/TestDefaultDeviceDevelop.cpp:57: Failure
Expected equality of these values:
  ret1
    Which is: '\0'
  1
5 args 
/gpfs/users/gannayp/kokkos/core/unit_test/default/TestDefaultDeviceDevelop.cpp:67: Failure
Expected equality of these values:
  ret1
    Which is: '\0'
  1
6 args 
/gpfs/users/gannayp/kokkos/core/unit_test/default/TestDefaultDeviceDevelop.cpp:77: Failure
Expected equality of these values:
  ret1
    Which is: '\0'
  1
7 args 

int16_t:
/gpfs/users/gannayp/kokkos/core/unit_test/default/TestDefaultDeviceDevelop.cpp:38: Failure
Expected equality of these values:
  ret1
    Which is: 0
  1
3 args 
/gpfs/users/gannayp/kokkos/core/unit_test/default/TestDefaultDeviceDevelop.cpp:57: Failure
Expected equality of these values:
  ret1
    Which is: 0
  1
5 args 
/gpfs/users/gannayp/kokkos/core/unit_test/default/TestDefaultDeviceDevelop.cpp:77: Failure
Expected equality of these values:
  ret1
    Which is: 0
  1
7 args 

int32_t:

int64:
```

It looks like the combined reducer can't return a value when the size of the combined type is more than 32 bits but not a multiple of 32.

### PR DESCRIPTION
**Pull request by tretre91**
On Cuda and Hip, using a combined reducer with a combination of datatypes giving a `sizeof(CombinedReducerValueImpl)` which is > 4 and not a multiple of 4 leads to wrong results. Additionally, if `sizeof(CombinedReducerValueImpl) > 16` and `alignof(CombinedReducerValueImpl) < 4` we get a misaligned write error.

In the `operator()` of Cuda and Hip `ParallelReduce`, each thread handles a `CombinedReducerValueImpl` which is split in "words" of 1, 2 or 4 bytes chunks depending on `sizeof(CombinedReducerValueImpl)`, if the sizeof is not a multiple of 4, we get the wrong number of words, for example with three `int16_t`, `sizeof(CombinedReducerValueImpl) == 6` which results in `word_count = 6 / 4 = 1`.
https://github.com/kokkos/kokkos/blob/fdc2eabb11ee4d28726ae50efe7424f598c08a93/core/src/Cuda/Kokkos_Cuda_Parallel_Range.hpp#L192-L196

When `sizeof(CombinedReducerValueImpl) > 16`, which is for example the case when reducing nine `int16_t`, a `CombinedReducerValueImpl*` (which has an aligment of 2) is reinterpreted as an `int*`, which leads to a misaligned write error in this call to `in_place_shfl` https://github.com/kokkos/kokkos/blob/f58d70314ce28b4ccff5b078e2187226e48f09b2/core/src/Cuda/Kokkos_Cuda_ReduceScan.hpp#L200

Making sure that `CombinedReducerValueImpl` is aligned on at least `alignof(int)` solves both of these issues, for the second one it is obvious, for the first one if `alignof(CombinedReducerValueImpl) >= 4` then `sizeof(CombinedReducerValueImpl)` has to be a multiple of 4.

I also added tests for reductions of three `int16_t`, nine `int8_t` and nine `int16_t`.

Fixes #8426

### CODE REVIEW

**Review by masterleinad — APPROVED** [review]

File: core/src/impl/Kokkos_Combined_Reducer.hpp [hunk 1]
```diff
@@ -41,12 +42,28 @@ struct CombinedReducerValueItemImpl {
 
 //==============================================================================
 
+// Dummy struct used to get the alignment of CombinedReducerValueImpl.
+template <class IdxSeq, class... ValueTypes>
+struct DummyCombinedReducerValueImpl;
```
Comment (PaulGannay) [inline core/src/impl/Kokkos_Combined_Reducer.hpp]: I don't find the name `DummyCombinedReducerValueImpl` explicit enough, I would prefer if it explained the fact it is use for alignment reason, but I do not have a better alternative to propose.

**Review by PaulGannay — APPROVED** [review]
Looks good, thank you for correcting this bug.

**Comment by dalg24** [comment]
2 questions:

1. Attempting to simplify (Not tested)
Does that do what we want?
```diff
diff --git a/core/src/impl/Kokkos_Combined_Reducer.hpp b/core/src/impl/Kokkos_Combined_Reducer.hpp
index e9381d219..1e2cb8157 100644
--- a/core/src/impl/Kokkos_Combined_Reducer.hpp
+++ b/core/src/impl/Kokkos_Combined_Reducer.hpp
@@ -41,13 +41,15 @@ struct CombinedReducerValueItemImpl {

 //==============================================================================

+struct alignas(int) AlignmentHelper {};
+
 template <class IdxSeq, class... ValueTypes>
 struct CombinedReducerValueImpl;

 template <size_t... Idxs, class... ValueTypes>
 struct CombinedReducerValueImpl<std::integer_sequence<size_t, Idxs...>,
                                 ValueTypes...>
-    : CombinedReducerValueItemImpl<Idxs, ValueTypes>... {
+    : AlignmentHelper, CombinedReducerValueItemImpl<Idxs, ValueTypes>... {
  public:
   KOKKOS_DEFAULTED_FUNCTION
   constexpr CombinedReducerValueImpl() = default;
```

2. Do we want to restrict that alignment fixup to Cuda and HIP?

**Comment by tretre91** [comment]
>     1. Attempting to simplify (Not tested)
>        Does that do what we want?

It does work, I applied those changes.
 
>     2. Do we want to restrict that alignment fixup to Cuda and HIP?

I am in favor of restricting it to Cuda and Hip. Since I added tests, if in the future we end up doing the same things in another backend the tests should fail, indicating that something is wrong.

**Review by crtrott — APPROVED** [review]
