### PR TITLE
Fix multi stream scratch

### LINKED ISSUE #3246: Scratch Allocations in Level 1 will conflict when using multiple streams

### PR DESCRIPTION
**Pull request by crtrott**
This fixes #3246 by making team scratch allocations a per Cuda instance property instead of global.

### CODE REVIEW

File: core/src/Cuda/Kokkos_Cuda_Instance.cpp [hunk 1]
```diff
@@ -653,6 +657,28 @@ Cuda::size_type *CudaInternal::scratch_functor(
...
+  if (m_team_scratch_current_size == 0) {
+    m_team_scratch_current_size = bytes;
+    m_team_scratch_ptr          = Kokkos::kokkos_malloc<Kokkos::CudaSpace>(
+        "CudaSpace::ScratchMemory", m_team_scratch_current_size);
+  }
+  if (bytes > m_team_scratch_current_size) {
+    m_team_scratch_current_size = bytes;
+    Kokkos::kokkos_free<Kokkos::CudaSpace>(m_team_scratch_ptr);
+    m_team_scratch_ptr = Kokkos::kokkos_malloc<Kokkos::CudaSpace>(
+        "CudaSpace::ScratchMemory", m_team_scratch_current_size);
```
Comment (dalg24) [inline core/src/Cuda/Kokkos_Cuda_Instance.cpp:671]: Why did you chose this over `kokkos_realloc`?

File: core/src/Cuda/Kokkos_Cuda_Instance.hpp [hunk 2]
```diff
@@ -117,6 +119,10 @@ class CudaInternal {
   uint32_t* m_scratchConcurrentBitset;
   cudaStream_t m_stream;
 
+  // Team Scratch Level 1 Space
+  mutable int64_t m_team_scratch_current_size;
+  mutable void* m_team_scratch_ptr;
```
Comment (dalg24) [inline core/src/Cuda/Kokkos_Cuda_Instance.hpp:124]: Why did you declare them mutable?

`Cuda:: impl_internal_space_instance` returns a pointer to non-const*.  So I don't think you need it in principle.
https://github.com/kokkos/kokkos/blob/c01580a271257704a50171e6527cd1f36155496e/core/src/Kokkos_Cuda.hpp#L254-L256

*Whether it should is another question 🙄

File: core/unit_test/cuda/TestCuda_TeamScratch.cpp [hunk 3]
```diff
@@ -47,6 +47,91 @@
 
 namespace Test {
 
+namespace Impl {
+
+void cuda_stream_scratch_test_one(
+    int N, int T, int M_base, Kokkos::View<int64_t, Kokkos::CudaSpace> counter,
```
Comment (dalg24) [inline core/unit_test/cuda/TestCuda_TeamScratch.cpp:53]: I would have made it an atomic view to do just `++counter()` below.  You don't have to change.

File: core/src/Cuda/Kokkos_Cuda_Instance.cpp (hunk 1 above)
Comment (crtrott) [reply core/src/Cuda/Kokkos_Cuda_Instance.cpp:671]: yeah we should do kokkos_realloc

File: core/src/Cuda/Kokkos_Cuda_Instance.hpp (hunk 2 above)
Comment (crtrott) [reply core/src/Cuda/Kokkos_Cuda_Instance.hpp:124]: Just talking to Damien: this is interesting problem but maybe a bigger one? We can either get rid of the mutable and leave it a non-const pointer or leave the mutable and make this a const pointer. What is the best pattern here? @nliber

Comment (crtrott) [reply core/src/Cuda/Kokkos_Cuda_Instance.hpp:124]: maybe we leave both of them for now and come back to this later.

**Review by dalg24 — APPROVED** [review]

File: core/unit_test/cuda/TestCuda_TeamScratch.cpp [hunk 4]
```diff
@@ -47,22 +47,121 @@
...
+    });
+  }
+};
+
+void cuda_stream_scratch_test_one(
+    int N, int T, int M_base, Kokkos::View<int64_t, Kokkos::CudaSpace> counter,
+    Kokkos::Cuda cuda, int tid) {
+  int M = M_base + tid * 5;
+  Kokkos::TeamPolicy<Kokkos::Cuda> p(cuda, T, 64);
+  using team_t    = Kokkos::TeamPolicy<Kokkos::Cuda>::member_type;
```
Comment (dalg24) [inline core/unit_test/cuda/TestCuda_TeamScratch.cpp:85]:
```suggestion
```
ClangTidy build complains that it is not use.
All other CUDA builds fail.  There is an illegal memory address somewhere.

File: core/unit_test/cuda/TestCuda_TeamScratch.cpp [hunk 5]
```diff
@@ -47,22 +47,121 @@
...
+    int N, int T, int M_base,
+    Kokkos::View<int64_t, Kokkos::CudaSpace> counter) {
+  int K = 4;
+  cudaStream_t stream[4];
+  Kokkos::Cuda cuda[4];
+  for (int i = 0; i < K; i++) {
+    cudaStreamCreate(&stream[i]);
+    cuda[i] = Kokkos::Cuda(stream[i]);
+  }
+  // Test that growing scratch size in subsequent calls doesn' crash things
```
Comment (Rombur) [inline core/unit_test/cuda/TestCuda_TeamScratch.cpp:106]:
```suggestion
  // Test that growing scratch size in subsequent calls doesn't crash things
```

**Review by Rombur — COMMENTED** [review]
The CUDA 11 tester and clang-tidy still fail. The other CUDA builds are passing.

**Comment by dalg24** [comment]
CUDA-11.0-NVCC-C++17-RDC build [fails](https://cloud.cees.ornl.gov/jenkins-ci/blue/organizations/jenkins/Kokkos/detail/Kokkos/2725/pipeline#step-186-log-836) with
```
terminate called after throwing an instance of 'std::runtime_error'
  what():  Kokkos::Impl::ParallelFor< Cuda > requested too large team size.

**Comment by crtrott** [comment]
OK found the race and fixed it. Its in the caching of the cuda functor attributes.

**Review by DavidPoliakoff — APPROVED** [review]
Address Bruno's comment on your type in your comment and it's good

File: core/src/Cuda/Kokkos_Cuda_KernelLaunch.hpp [hunk 6]
```diff
@@ -296,15 +290,19 @@ struct CudaParallelLaunch<
   }
 
   static cudaFuncAttributes get_cuda_func_attributes() {
-    static cudaFuncAttributes attr;
-    static bool attr_set = false;
-    if (!attr_set) {
+    // Race condition inside of cudaFuncGetAttributes if the same address is
```
Comment (dalg24) [inline core/src/Cuda/Kokkos_Cuda_KernelLaunch.hpp:293]: Should we mark it as a workaround for CUDA 11?  Is that something we are going to report upstream?

Comment (crtrott) [reply core/src/Cuda/Kokkos_Cuda_KernelLaunch.hpp:293]: I don't think its in principle a workaround just for CUDA 11. There is no implementation guarantee for the function, its just bad API design to take pointers to stuff instead of just returning the struct.

File: core/unit_test/cuda/TestCuda_TeamScratch.cpp (hunk 5 above)
Comment (crtrott) [reply core/unit_test/cuda/TestCuda_TeamScratch.cpp:105]: Does somebody else want to unroll all the changes and redo the commits to add the t? I don't have time right now. If nobody else feels the urgent need I will ignore this :-)
