### PR TITLE
SIMD: suppress a uninitialized variable warning

### LINKED ISSUE #6277: SIMD unit test failures on BDW arch (AVX2) with gcc/9.3.0, 10.2.0
**Describe the bug**
The `Kokkos_UnitTest_SIMD` unit tests fail on BDW arch with gcc/9.3.0 and gcc/10.2.0 (other versions of gcc were not available on the system for testing):

**gcc/9.3.0 failure snip**:
```
33: [ RUN      ] simd.host
33: /home/ndellin/kokkos/simd/unit_tests/TestSIMD.cpp:26: Failure
33: Expected equality of these values:
33:   a
33:     Which is: 13
33:   b
33:     Which is: 1
33: /home/ndellin/kokkos/simd/unit_tests/TestSIMD.cpp:26: Failure
33: Expected equality of these values:
33:   a
33:     Which is: 3
33:   b
33:     Which is: 2
33: /home/ndellin/kokkos/simd/unit_tests/TestSIMD.cpp:26: Failure
33: Expected equality of these values:
33:   a
33:     Which is: 2
33:   b
33:     Which is: 1
33: /home/ndellin/kokkos/simd/unit_tests/TestSIMD.cpp:26: Failure
33: Expected equality of these values:
33:   a
33:     Which is: 0
33:   b
33:     Which is: 10
33: /home/ndellin/kokkos/simd/unit_tests/TestSIMD.cpp:26: Failure
33: Expected equality of these values:
33:   a
33:     Which is: 32-byte object <00-00 00-00 00-00 00-00 00-00 00-00 00-00 00-00 00-00 00-00 00-00 00-00 00-00 00-00 00-00 00-00>
33:   b
33:     Which is: 32-byte object <FF-FF FF-FF FF-FF FF-FF FF-FF FF-FF FF-FF FF-FF FF-FF FF-FF FF-FF FF-FF FF-FF FF-FF FF-FF FF-FF>
33: /home/ndellin/kokkos/simd/unit_tests/TestSIMD.cpp:26: Failure
33: Expected equality of these values:
33:   a
33:     Which is: 13
33:   b
33:     Which is: 0
33: /home/ndellin/kokkos/simd/unit_tests/TestSIMD.cpp:26: Failure
33: Expected equality of these values:
33:   a
33:     Which is: 3
33:   b
33:     Which is: 1
33: /home/ndellin/kokkos/simd/unit_tests/TestSIMD.cpp:26: Failure
33: Expected equality of these values:
33:   a
33:     Which is: 0
33:   b
33:     Which is: 10
33: /home/ndellin/kokkos/simd/unit_tests/TestSIMD.cpp:26: Failure
33: Expected equality of these values:
33:   a
33:     Which is: 32-byte object <00-00 00-00 00-00 00-00 00-00 00-00 00-00 00-00 FF-FF FF-FF FF-FF FF-FF 00-00 00-00 00-00 00-00>
33:   b
33:     Which is: 32-byte object <FF-FF FF-FF FF-FF FF-FF FF-FF FF-FF FF-FF FF-FF FF-FF FF-FF FF-FF FF-FF FF-FF FF-FF FF-FF FF-FF>
33: /home/ndellin/kokkos/simd/unit_tests/TestSIMD.cpp:26: Failure
33: Expected equality of these values:
33:   a
33:     Which is: 13
33:   b
33:     Which is: 0
33: /home/ndellin/kokkos/simd/unit_tests/TestSIMD.cpp:26: Failure
33: Expected equality of these values:
33:   a
33:     Which is: 3
33:   b
33:     Which is: 1
33: /home/ndellin/kokkos/simd/unit_tests/TestSIMD.cpp:26: Failure
33: Expected equality of these values:
33:   a
33:     Which is: 32-byte object <00-00 00-00 00-00 00-00 00-00 00-00 00-00 00-00 FF-FF FF-FF FF-FF FF-FF 00-00 00-00 00-00 00-00>
33:   b
33:     Which is: 32-byte object <FF-FF FF-FF FF-FF FF-FF FF-FF FF-FF FF-FF FF-FF FF-FF FF-FF FF-FF FF-FF 00-00 00-00 00-00 00-00>
33: /home/ndellin/kokkos/simd/unit_tests/TestSIMD.cpp:26: Failure
33: Expected equality of these values:
33:   a
33:     Which is: 13
33:   b
33:     Which is: 1
33: /home/ndellin/kokkos/simd/unit_tests/TestSIMD.cpp:26: Failure
33: Expected equality of these values:
33:   a
33:     Which is: 3
33:   b
33:     Which is: 2
33: /home/ndellin/kokkos/simd/unit_tests/TestSIMD.cpp:26: Failure
33: Expected equality of these values:
33:   a
33:     Which is: 2
33:   b
33:     Which is: 1
33: /home/ndellin/kokkos/simd/unit_tests/TestSIMD.cpp:26: Failure
33: Expected equality of these values:
33:   a
33:     Which is: 0
33:   b
33:     Which is: 10
33: /home/ndellin/kokkos/simd/unit_tests/TestSIMD.cpp:26: Failure
33: Expected equality of these values:
33:   a
33:     Which is: 32-byte object <00-00 00-00 00-00 00-00 00-00 00-00 00-00 00-00 00-00 00-00 00-00 00-00 00-00 00-00 00-00 00-00>
33:   b
33:     Which is: 32-byte object <FF-FF FF-FF FF-FF FF-FF FF-FF FF-FF FF-FF FF-FF FF-FF FF-FF FF-FF FF-FF FF-FF FF-FF FF-FF FF-FF>
33: /home/ndellin/kokkos/simd/unit_tests/TestSIMD.cpp:26: Failure
33: Expected equality of these values:
33:   a
33:     Which is: 13
33:   b
33:     Which is: 0
33: /home/ndellin/kokkos/simd/unit_tests/TestSIMD.cpp:26: Failure
33: Expected equality of these values:
33:   a
33:     Which is: 3
33:   b
33:     Which is: 1
33: /home/ndellin/kokkos/simd/unit_tests/TestSIMD.cpp:26: Failure
33: Expected equality of these values:
33:   a
33:     Which is: 0
33:   b
33:     Which is: 10
33: /home/ndellin/kokkos/simd/unit_tests/TestSIMD.cpp:26: Failure
33: Expected equality of these values:
33:   a
33:     Which is: 32-byte object <00-00 00-00 00-00 00-00 00-00 00-00 00-00 00-00 FF-FF FF-FF FF-FF FF-FF 00-00 00-00 00-00 00-00>
33:   b
33:     Which is: 32-byte object <FF-FF FF-FF FF-FF FF-FF FF-FF FF-FF FF-FF FF-FF FF-FF FF-FF FF-FF FF-FF FF-FF FF-FF FF-FF FF-FF>
33: /home/ndellin/kokkos/simd/unit_tests/TestSIMD.cpp:26: Failure
33: Expected equality of these values:
33:   a
33:     Which is: 13
33:   b
33:     Which is: 0
33: /home/ndellin/kokkos/simd/unit_tests/TestSIMD.cpp:26: Failure
33: Expected equality of these values:
33:   a
33:     Which is: 3
33:   b
33:     Which is: 1
33: /home/ndellin/kokkos/simd/unit_tests/TestSIMD.cpp:26: Failure
33: Expected equality of these values:
33:   a
33:     Which is: 32-byte object <00-00 00-00 00-00 00-00 00-00 00-00 00-00 00-00 FF-FF FF-FF FF-FF FF-FF 00-00 00-00 00-00 00-00>
33:   b
33:     Which is: 32-byte object <FF-FF FF-FF FF-FF FF-FF FF-FF FF-FF FF-FF FF-FF FF-FF FF-FF FF-FF FF-FF 00-00 00-00 00-00 00-00>
33: [  FAILED  ] simd.host (1 ms)
33: [ RUN      ] simd.device
33: [       OK ] simd.device (1 ms)
33: [----------] 2 tests from simd (2 ms total)
33: 
33: [----------] Global test environment tear-down
33: [==========] 2 tests from 1 test suite ran. (2 ms total)
33: [  PASSED  ] 1 test.
33: [  FAILED  ] 1 test, listed below:
33: [  FAILED  ] simd.host
33: 
33:  1 FAILED TEST
1/1 Test #33: Kokkos_UnitTest_SIMD .............***Failed  Error regular expression found in output. Regex=[  FAILED  ]  0.01 sec
```

This occurred on a system with Broadwell arch (Intel® Xeon® Processor E5-2698 v4)

I also tested on a system with Skylake arch but setting `Kokkos_ARCH_BDW=ON` (SKX supports avx2) and encountered similar failures

**Please also include the following items to support reproducing the bug**
**Reproducer** (Serial build):
```
module load cmake/3.19 gcc/9.3.0

cmake -DKokkos_ENABLE_OPENMP=ON -DKokkos_ENABLE_SERIAL=ON -DKokkos_ARCH_BDW=ON -DKokkos_ENABLE_TESTS=ON -DKokkos_ENABLE_EXAMPLES=OFF -DCMAKE_VERBOSE_MAKEFILE=ON -DCMAKE_CXX_EXTENSIONS=OFF -DCMAKE_BUILD_TYPE=RELEASE -DKokkos_ENABLE_DEPRECATION_WARNINGS=OFF -DKokkos_ENABLE_DEPRECATED_CODE_4=OFF $KOKKOS_PATH
```

### PR DESCRIPTION
**Pull request by ldh4**
Fixes #6277.

Related to the 4th bullet in #6223.

Added an extra branching operation that suppresses a seemingly spurious uninitialized variable warnings from gcc and included the same comment about this from #6223.

### CODE REVIEW

File: simd/unit_tests/TestSIMD.cpp [hunk 1]
```diff
@@ -192,8 +192,11 @@ void host_check_math_op_one_loader(UnaryOp unary_op, std::size_t n,
     bool const loaded_arg = loader.host_load(args + i, nlanes, arg);
     if (!loaded_arg) continue;
     simd_type expected_result;
-    for (std::size_t lane = 0; lane < nlanes; ++lane) {
-      expected_result[lane] = unary_op.on_host_serial(T(arg[lane]));
+    // gcc 8.4.0 warns if using nlanes as upper bound about first_arg and/or
+    // second_arg being uninitialized
```
Comment (dalg24) [inline simd/unit_tests/TestSIMD.cpp:196]: There is no `first_arg` nor `second_arg`.
Is it meant to be
```suggestion
    // gcc 8.4.0 warns if using nlanes as upper bound about arg
    // being uninitialized
```

**Review by ndellingwood — APPROVED** [review]
Thanks @ldh4 !

This passed for me testing on Solo with BDW arch, as well as testing on Blake (which has SKX) with BDW arch enabled

**Review by masterleinad — APPROVED** [review]

**Comment by dalg24** [comment]
Ignoring
```
4: /var/jenkins/workspace/Kokkos/core/unit_test/TestExecSpacePartitioning.hpp:100: Failure
4: Expected equality of these values:
4:   sum1
4:     Which is: 7642095
4:   sum2
4:     Which is: 0
4: [  FAILED  ] openmptarget.partitioning_by_vector (0 ms)
```
which is clearly unrelated and shows on other PRs.
Will investigate as necessary elsewhere.
