### PR TITLE
#5641: Fix HIP & CUDA MDRange reduce for sizeof(value_type) < sizeof(int)

### LINKED ISSUE #5641: Parallel reducer, `MDRangePolicy` and HIP or CUDA: doesn't work with bool, char, int16_t
**Describe the bug**

It seems that `Kokkos::LAnd<bool>` does not work with `Kokkos::Experimental::HIP` and `Kokkos::MDRangePolicy`.

**Please also include the following items to support reproducing the bug**

* Kokkos release 3.7
* Linux with ROCm 5.3 (vega906)
* code needed to reproduce the bug
   ```c++
   template <typename T, typename execution_space, typename policy_t, typename functor_t>
   T parallel_reducer_LAnd(const policy_t& policy, const functor_t& f)
   {
      T allEqual = 0;
      auto reducer = Kokkos::LAnd<T>(allEqual);
      Kokkos::parallel_reduce(policy,f,reducer);
      execution_space().fence();
      return allEqual;
   }

   TEUCHOS_UNIT_TEST(test,test)
   {
      std::cout << "KOKKOS_VERSION: " << KOKKOS_VERSION << std::endl;

      using execution_space = Kokkos::Experimental::HIP;

      const auto  policy_MD = Kokkos::MDRangePolicy<Kokkos::Rank<2>,execution_space>({0,0},{8,2});
      const auto  policy_RG = Kokkos::  RangePolicy<                execution_space>( 0,    8   );

      const auto res_MD_bool = parallel_reducer_LAnd<bool,execution_space>(policy_MD, KOKKOS_LAMBDA(const size_t, const size_t, bool& res){res = true;});
      const auto res_MD_int  = parallel_reducer_LAnd<int ,execution_space>(policy_MD, KOKKOS_LAMBDA(const size_t, const size_t, int & res){res = 1   ;});

      const auto res_RG_bool = parallel_reducer_LAnd<bool,execution_space>(policy_RG, KOKKOS_LAMBDA(const size_t, bool& res){res = true;});
      const auto res_RG_int  = parallel_reducer_LAnd<int ,execution_space>(policy_RG, KOKKOS_LAMBDA(const size_t, int & res){res = 1   ;});

      TEST_EQUALITY(res_MD_bool,false); // -> I expected true here
      TEST_EQUALITY(res_RG_bool,true);
      TEST_EQUALITY(res_MD_int ,1);
      TEST_EQUALITY(res_RG_int ,1);
   }
   ```
7. please also attach the `KokkosCore_config.h` header file (generated during the build); [KokkosCore_config.hpp.txt](https://github.com/kokkos/kokkos/files/10102708/KokkosCore_config.hpp.txt)

As you can see from the reproducer, using the `Kokkos::LAnd<bool>` with `MDRangePolicy` on HIP seems not to work correctly.

A temporary workaround is to use `int` instead.

Please note that for `OpenMP` and `Cuda` it works fine.

### PR DESCRIPTION
**Pull request by PhilMiller**
Fixes #5641

### CODE REVIEW

**Comment by PhilMiller** [comment]
I'm going to temporarily push a test change to confirm that it fails the HIP build, and then force-push it back.

**Comment by PhilMiller** [comment]
HIP builds with just the assertion but no added test triggering it passed:
https://cloud.cees.ornl.gov/jenkins-ci/blue/organizations/jenkins/Kokkos/detail/Kokkos/11627/pipeline/50#step-231-log-2274

**Comment by PhilMiller** [comment]
The added assertion does trigger with a test modified to call an offending `parallel_reduce`
https://cloud.cees.ornl.gov/jenkins-ci/blue/organizations/jenkins/Kokkos/detail/Kokkos/11630/pipeline#step-65-log-901

However, it also reminds me that the guardrail may be necessary for all possible memory space template arguments of `LAnd`

**Comment by PhilMiller** [comment]
Since I was typo-fixing anyway, I ran ispell over all comments and strings in that file. Everything else is fine.

**Comment by PhilMiller** [comment]
I've only guarded against what's been reported to fail. 

If you can point me at a workable set of modules to test things on kokkos-dev-2 or wherever, I can try it out.

File: core/src/HIP/Kokkos_HIP_Parallel_MDRange.hpp [hunk 1]
```diff
@@ -168,6 +168,18 @@ class ParallelFor<FunctorType, Kokkos::MDRangePolicy<Traits...>, HIP> {
 template <class FunctorType, class ReducerType, class... Traits>
 class ParallelReduce<FunctorType, Kokkos::MDRangePolicy<Traits...>, ReducerType,
                      HIP> {
+  // FIXME HIP #5641
+  static_assert(
+      !std::is_same_v<ReducerType, ::Kokkos::LAnd<bool, ::Kokkos::HostSpace>> &&
```
Comment (Rombur) [inline core/src/HIP/Kokkos_HIP_Parallel_MDRange.hpp:173]: Why `HostSpace`?

**Review by masterleinad — DISMISSED** [review]

**Comment by PhilMiller** [comment]
> Why only for LAnd? I bet all other reductions would fail too for bool? (Sum, BAnd, LOr, etc. )

It looks like `Kokkos::reduction_identity<bool>` only defines `lor()` and `land()`, so none of the others are possible to meaningfully test as such.

That said, I've reproduced the (a?) failure for `LOr` as well, again with `MDRange`. I'm going to guard off any use `value_type == bool` for HIP `MDRange`.

**Comment by PhilMiller** [comment]
I just tested with `char`, `unsigned char`, `signed char`, `int8_t`,  `uint8_t`, `int16_t`, and `uint16_t`, and those all fail as well. Going up to 32 bits passes across a sweep of `MDRange` sizes.

That suggests the bug is in some sort of sizing or alignment.

**Comment by PhilMiller** [comment]
I adapted the changes in #5333 from `TeamPolicy` to `MDRange` and found that they fixed the failing tests across the range of types smaller than `int`.

I'm committing the sloppy mess now because it's late and I want to get it out. I'll make tests for Team reductions and move them to a sensible place and maybe fix them tomorrow.

**Comment by PhilMiller** [comment]
Test passes on Serial but fails on HIP before the fix. Test passes with the fix.

Will clang-format, then this is ready.

**Comment by PhilMiller** [comment]
Lol, once I got nvcc to compile the damn test, it fails on CUDA in the same way! Fixing that, too

File: core/src/Cuda/Kokkos_Cuda_Parallel_MDRange.hpp [hunk 2]
```diff
@@ -212,16 +212,33 @@ class ParallelReduce<CombinedFunctorReducerType,
...
+  // performing the reduction, word_size_type is used again.
+  // For scalars > 4 bytes in size, indexing into shared/global memory relies
+  // on the block and grid dimensions to ensure that we index at the correct
+  // offset rather than at every 4 byte word; such that, when the join is
+  // performed, we have the correct data that was copied over in chunks of 4
+  // bytes.
+  using word_size_type = std::conditional_t<
+      sizeof(value_type) < sizeof(Kokkos::Cuda::size_type),
+      std::conditional_t<sizeof(value_type) == 2, int16_t, int8_t>,
+      Kokkos::Cuda::size_type>;
```
Comment (dalg24) [inline core/src/Cuda/Kokkos_Cuda_Parallel_MDRange.hpp:230]:
```suggestion
      sizeof(value_type) < sizeof(size_type),
      std::conditional_t<sizeof(value_type) == 2, int16_t, int8_t>,
      size_type>;
```

File: core/unit_test/TestMDRangeReduce.hpp [hunk 3]
```diff
@@ -0,0 +1,61 @@
...
+// See https://kokkos.org/LICENSE for license information.
+// SPDX-License-Identifier: Apache-2.0 WITH LLVM-exception
+//
+//@HEADER
+
+#include <gtest/gtest.h>
+
+#include <Kokkos_Core.hpp>
+
+namespace Test {
```
Comment (dalg24) [inline core/unit_test/TestMDRangeReduce.hpp:21]:
```suggestion
namespace {
```

File: core/unit_test/TestMDRangeReduce.hpp [hunk 4]
```diff
@@ -0,0 +1,61 @@
...
+    Kokkos::parallel_reduce(
+        policy_MD, KOKKOS_LAMBDA(const int, const int, T& res) { res = 1; },
+        Kokkos::LAnd<T>(land_MD));
+    EXPECT_EQ(land_MD, 1);
+  }
+}
+
+TEST(TEST_CATEGORY, mdrange_parallel_reduce_primitive_types) {
+  for (int bound = 0; bound < 100; bound++) {
+    for (int k = 0; k < bound; ++k) {
```
Comment (dalg24) [inline core/unit_test/TestMDRangeReduce.hpp:50]: How long does it take?

File: core/unit_test/TestMDRangeReduce.hpp [hunk 5]
```diff
@@ -0,0 +1,61 @@
...
+      MDRangeReduceTester<bool>(bound, k);
+      MDRangeReduceTester<signed char>(bound, k);
+      MDRangeReduceTester<int8_t>(bound, k);
+      MDRangeReduceTester<int16_t>(bound, k);
```
Comment (dalg24) [inline core/unit_test/TestMDRangeReduce.hpp:54]: do we care to test for a user-defined type of size 3?

File: core/unit_test/TestMDRangeReduce.hpp [hunk 6]
```diff
@@ -0,0 +1,61 @@
...
+void MDRangeReduceTester(int bound, int k) {
+  const auto policy_MD = Kokkos::MDRangePolicy<Kokkos::Rank<2>, TEST_EXECSPACE>(
+      {0, 0}, {bound, 2});
+
+  // No explicit fence() calls needed because result is in HostSpace
+  {
+    T lor_MD = 0;
+    Kokkos::parallel_reduce(
+        policy_MD,
+        KOKKOS_LAMBDA(const int i, const int, T& res) { res = res || i == k; },
```
Comment (dalg24) [inline core/unit_test/TestMDRangeReduce.hpp:33]: Might need to guard for LAMBDA support enabled.

File: core/unit_test/TestMDRangeReduce.hpp [hunk 7]
```diff
@@ -0,0 +1,61 @@
...
+namespace Test {
+
+template <typename T>
+void MDRangeReduceTester(int bound, int k) {
+  const auto policy_MD = Kokkos::MDRangePolicy<Kokkos::Rank<2>, TEST_EXECSPACE>(
+      {0, 0}, {bound, 2});
+
+  // No explicit fence() calls needed because result is in HostSpace
+  {
+    T lor_MD = 0;
```
Comment (dalg24) [inline core/unit_test/TestMDRangeReduce.hpp:30]: Why did you go for logical OR and logical AND?  Presumably that bug can show on other somewhat less obscure reductions right?
(Not necessarily asking you to change, just trying to understand if there is a rational)

File: core/unit_test/TestMDRangeReduce.hpp (hunk 5 above)
Comment (e10harvey) [reply core/unit_test/TestMDRangeReduce.hpp:54]: We test this via `reducers_point_t` with a point_t type in TestReducers_d.hpp, if you want to lift that code.

File: core/unit_test/TestMDRangeReduce.hpp (hunk 7 above)
Comment (PhilMiller) [reply core/unit_test/TestMDRangeReduce.hpp:30]: The initial bug report was for reducing `LAnd` over `bool`. That just turned out to be a special case of `size_of(value_type) < sizeof(int)`

File: core/unit_test/TestMDRangeReduce.hpp (hunk 4 above)
Comment (PhilMiller) [reply core/unit_test/TestMDRangeReduce.hpp:50]: a bit under a second

File: core/unit_test/TestMDRangeReduce.hpp (hunk 5 above)
Comment (PhilMiller) [reply core/unit_test/TestMDRangeReduce.hpp:54]: Probably a good idea, but that would require at least some customization of the test. I'm getting really tired of staring at this one at the moment. I already plan to make the same fix for the Team policies, now that it's clearer that it really will be needed

File: core/src/HIP/Kokkos_HIP_Parallel_MDRange.hpp [hunk 8]
```diff
@@ -188,15 +188,32 @@ class ParallelReduce<CombinedFunctorReducerType,
...
   // blockDim.z == 1
 
   const CombinedFunctorReducerType m_functor_reducer;
   const Policy m_policy;  // used for workrange and nwork
   const pointer_type m_result_ptr;
   const bool m_result_ptr_device_accessible;
-  size_type* m_scratch_space;
-  size_type* m_scratch_flags;
+  word_size_type* m_scratch_space;
+  HIP::size_type* m_scratch_flags;
```
[the remark this answers is not in the document]
Comment (PhilMiller) [reply core/src/HIP/Kokkos_HIP_Parallel_MDRange.hpp:216]: How it was written in the `RangePolicy` case. I'm happy to simplify these out.

File: core/unit_test/TestMDRangeReduce.hpp (hunk 6 above)
Comment (PhilMiller) [reply core/unit_test/TestMDRangeReduce.hpp:33]: Earnest question: why is that still optional?

File: core/src/Cuda/Kokkos_Cuda_Parallel_MDRange.hpp [hunk 9]
```diff
@@ -212,16 +212,32 @@ class ParallelReduce<CombinedFunctorReducerType,
...
+  // Within the reduction, the word count is recomputed based on word_size_type
+  // and when calculating indexes into the shared/global memory buffers for
+  // performing the reduction, word_size_type is used again.
+  // For scalars > 4 bytes in size, indexing into shared/global memory relies
+  // on the block and grid dimensions to ensure that we index at the correct
+  // offset rather than at every 4 byte word; such that, when the join is
+  // performed, we have the correct data that was copied over in chunks of 4
+  // bytes.
+  using word_size_type = std::conditional_t<
+      sizeof(value_type) < sizeof(size_type),
```
Comment (dalg24) [inline core/src/Cuda/Kokkos_Cuda_Parallel_MDRange.hpp:228]:
```suggestion
  static_assert(sizeof(size_type) == 4);
  using word_size_type = std::conditional_t<
      sizeof(value_type) < 4,
```

File: core/src/HIP/Kokkos_HIP_Parallel_MDRange.hpp [hunk 10]
```diff
@@ -188,14 +188,30 @@ class ParallelReduce<CombinedFunctorReducerType,
...
+  // Within the reduction, the word count is recomputed based on word_size_type
+  // and when calculating indexes into the shared/global memory buffers for
+  // performing the reduction, word_size_type is used again.
+  // For scalars > 4 bytes in size, indexing into shared/global memory relies
+  // on the block and grid dimensions to ensure that we index at the correct
+  // offset rather than at every 4 byte word; such that, when the join is
+  // performed, we have the correct data that was copied over in chunks of 4
+  // bytes.
+  using word_size_type = std::conditional_t<
+      sizeof(value_type) < sizeof(size_type),
```
Comment (dalg24) [inline core/src/HIP/Kokkos_HIP_Parallel_MDRange.hpp:204]:
```suggestion
  // bytes.
  static_assert(sizeof(size_type) == 4);
  using word_size_type = std::conditional_t<
      sizeof(value_type) < 4,
```

File: core/unit_test/TestMDRangeReduce.hpp (hunk 6 above)
Comment (dalg24) [reply core/unit_test/TestMDRangeReduce.hpp:33]: I think technically if one configure with `-DKokkos_ENABLE_CUDA_LAMBDA=OFF` we do not pass the `-extended-lambda` flag to NVCC

File: core/unit_test/TestMDRangeReduce.hpp [hunk 11]
```diff
@@ -0,0 +1,63 @@
...
+    Kokkos::parallel_reduce(
+        policy_MD,
+        KOKKOS_LAMBDA(const int i, const int, T& res) { res = res || i == k; },
+        Kokkos::LOr<T>(lor_MD));
+    EXPECT_EQ(lor_MD, 1);
```
Comment (dalg24) [inline core/unit_test/TestMDRangeReduce.hpp:35]: Consider putting the type and the arguments value into the stream from the assertion to make failure messages more useful.

File: core/unit_test/TestMDRangeReduce.hpp (hunk 4 above)
Comment (dalg24) [reply core/unit_test/TestMDRangeReduce.hpp:51]: It feels excessive.  Ideally, tests should be as small and fast running as can be while still doing the job.
1 second is actually quite a lot for a single unit test.

File: core/src/Cuda/Kokkos_Cuda_Parallel_MDRange.hpp [hunk 12]
```diff
@@ -342,12 +360,12 @@ class ParallelReduce<CombinedFunctorReducerType,
                        : suggested_blocksize;  // Note: block_size must be less
                                                // than or equal to 512
 
-      m_scratch_space = cuda_internal_scratch_space(
+      m_scratch_space = (word_size_type*)cuda_internal_scratch_space(
           m_policy.space(), m_functor_reducer.get_reducer().value_size() *
                                 block_size /* block_size == max block_count */);
```
Comment (masterleinad) [inline core/src/Cuda/Kokkos_Cuda_Parallel_MDRange.hpp:365]:
```suggestion
      m_scratch_space = reinterpret_cast<word_size_type*>(cuda_internal_scratch_space(
          m_policy.space(), m_functor_reducer.get_reducer().value_size() *
                                block_size /* block_size == max block_count */));
```

File: core/src/Cuda/Kokkos_Cuda_Parallel_MDRange.hpp [hunk 13]
```diff
@@ -342,12 +360,12 @@ class ParallelReduce<CombinedFunctorReducerType,
...
       m_scratch_flags =
           cuda_internal_scratch_flags(m_policy.space(), sizeof(size_type));
-      m_unified_space = cuda_internal_scratch_unified(
+      m_unified_space = (word_size_type*)cuda_internal_scratch_unified(
           m_policy.space(), m_functor_reducer.get_reducer().value_size());
```
Comment (masterleinad) [inline core/src/Cuda/Kokkos_Cuda_Parallel_MDRange.hpp:369]:
```suggestion
      m_unified_space = reinterpret_cast<word_size_type*>(cuda_internal_scratch_unified(
          m_policy.space(), m_functor_reducer.get_reducer().value_size()));
```

File: core/src/HIP/Kokkos_HIP_Parallel_MDRange.hpp [hunk 14]
```diff
@@ -294,7 +313,7 @@ class ParallelReduce<CombinedFunctorReducerType,
                        : suggested_blocksize;  // Note: block_size must be less
                                                // than or equal to 512
 
-      m_scratch_space = hip_internal_scratch_space(
+      m_scratch_space = (word_size_type*)hip_internal_scratch_space(
           m_policy.space(), reducer.value_size() *
                                 block_size /* block_size == max block_count */);
```
Comment (masterleinad) [inline core/src/HIP/Kokkos_HIP_Parallel_MDRange.hpp:318]:
```suggestion
      m_scratch_space = (reinterpret_cast<word_size_type*>(hip_internal_scratch_space(
          m_policy.space(), reducer.value_size() *
                                block_size /* block_size == max block_count */));
```

File: core/unit_test/TestMDRangeReduce.hpp (hunk 6 above)
Comment (masterleinad) [reply core/unit_test/TestMDRangeReduce.hpp:33]: https://github.com/kokkos/kokkos/blob/fc4a9cecfa4d309881847626ebff718bbbe6af8c/cmake/kokkos_arch.cmake#L169-L174

Comment (PhilMiller) [reply core/unit_test/TestMDRangeReduce.hpp:33]: So, it's optional because Nvidia still considered it 'experimental'?

In CUDA 12, it's not experimental anymore:
https://docs.nvidia.com/cuda/cuda-c-programming-guide/index.html
Would we be averse to a PR that deprecates the CMake option, and unconditionally adds the version-appropriate flag and the `#define`?

Is there any benefit to users at this point of being able to *disable* it?

File: core/unit_test/TestMDRangeReduce.hpp (hunk 4 above)
Comment (PhilMiller) [reply core/unit_test/TestMDRangeReduce.hpp:51]: Ok. I'll change it to a smattering of values across a broad range.

**Comment by PhilMiller** [comment]
I'm heading out for a trip over the weekend. I'll do all the remaining cleanup by/on Monday.

**Comment by PhilMiller** [comment]
LOL, OpenMPTarget fails this test too!

File: core/unit_test/TestMDRangeReduce.hpp [hunk 15]
```diff
@@ -0,0 +1,63 @@
...
+//@HEADER
+
+#include <gtest/gtest.h>
+
+#include <Kokkos_Core.hpp>
+
+namespace {
+
+template <typename T>
+void MDRangeReduceTester(int bound, int k) {
```
Comment (PhilMiller) [inline core/unit_test/TestMDRangeReduce.hpp:24]: Lol, `icpc`
```
/__w/kokkos/kokkos/core/unit_test/TestMDRangeReduce.hpp(24): error #869: parameter "bound" was never referenced
  void MDRangeReduceTester(int bound, int k) {
                               ^
```

What the hell do we even do with that? Mark it `[[maybe_unused]]` and pretend that this compiler is not bonkers?

**Comment by PhilMiller** [comment]
Per @rgayatri23 I'm going to skip the test of OpenMPTarget for now.

File: core/unit_test/TestMDRangeReduce.hpp (hunk 6 above)
Comment (masterleinad) [reply core/unit_test/TestMDRangeReduce.hpp:33]: You can bring it up in the developer meeting. 🙂

Comment (PhilMiller) [reply core/unit_test/TestMDRangeReduce.hpp:33]: #5964

File: core/unit_test/TestMDRangeReduce.hpp (hunk 4 above)
Comment (PhilMiller) [reply core/unit_test/TestMDRangeReduce.hpp]: It now runs in less than a millisecond on Serial and Cuda

File: core/unit_test/TestMDRangeReduce.hpp [hunk 16]
```diff
@@ -0,0 +1,66 @@
...
+    EXPECT_EQ(land_MD, 1);
+  }
+}
+
+TEST(TEST_CATEGORY, mdrange_parallel_reduce_primitive_types) {
+#if defined(KOKKOS_ENABLE_OPENMPTARGET)
+  GTEST_SKIP() << "FIXME OPENMPTARGET Tests of MDRange reduce over values "
+                  "smaller than int would fail";
+#elif !defined(KOKKOS_ENABLE_CUDA) || defined(KOKKOS_ENABLE_CUDA_LAMBDA)
+  for (int bound : {0, 1, 7, 32, 65, 70000}) {
```
Comment (PhilMiller) [inline core/unit_test/TestMDRangeReduce.hpp:53]: Grrr, the large value here seems to be long enough to time out a serial debug build.
```suggestion
  for (int bound : {0, 1, 7, 32, 65, 7000}) {
```

**Comment by PhilMiller** [comment]
Rebased on `develop` with Github CI (hopefully) fixed

**Review by Rombur — APPROVED** [review]

File: core/unit_test/TestMDRangeReduce.hpp [hunk 17]
```diff
@@ -0,0 +1,66 @@
...
+        Kokkos::LAnd<T>(land_MD));
+    EXPECT_EQ(land_MD, 1);
+  }
+}
+
+TEST(TEST_CATEGORY, mdrange_parallel_reduce_primitive_types) {
+#if defined(KOKKOS_ENABLE_OPENMPTARGET)
+  GTEST_SKIP() << "FIXME OPENMPTARGET Tests of MDRange reduce over values "
+                  "smaller than int would fail";
+#elif !defined(KOKKOS_ENABLE_CUDA) || defined(KOKKOS_ENABLE_CUDA_LAMBDA)
```
Comment (dalg24) [inline core/unit_test/TestMDRangeReduce.hpp:52]: Prefer GTEST_SKIP if the test does not run

Comment (PhilMiller) [inline core/unit_test/TestMDRangeReduce.hpp:52]:
```suggestion
#elif !defined(KOKKOS_ENABLE_CUDA) || defined(KOKKOS_ENABLE_CUDA_LAMBDA)
  GTEST_SKIP() << "Skipped ENABLE_CUDA_LAMBDA";
#else
```

File: core/unit_test/TestMDRangeReduce.hpp [hunk 18]
```diff
@@ -0,0 +1,68 @@
...
```
Comment (PhilMiller) [inline core/unit_test/TestMDRangeReduce.hpp:52]:
```suggestion
#elif defined(KOKKOS_ENABLE_CUDA) && !defined(KOKKOS_ENABLE_CUDA_LAMBDA)
```
Oops, reversed the condition

**Review by dalg24 — APPROVED** [review]
