### PR TITLE
Ensure OpenMP's partition_space doesn't fail for small concurrency

### LINKED ISSUE #8487: Kokkos_CoreUnitTest_OpenMP aborts when machine has a single CPU
Hello. When trying to build (the Debian package of) kokkos (version 4.5.01) on AWS instances of type m7a.medium or r7a.medium, which incidentally have a single CPU, the build fails with the following error:

```
2: Kokkos::abort: Instance has no resource allocated to it
2: Backtrace:
2: [0x7f385b6daec9] Kokkos::Impl::save_stacktrace()
2: [0x7f385b6ab1e5] Kokkos::Impl::host_abort(char const*)
2: [0x559dadc11919] 
2: [0x559dadc10a31] 
2: [0x7f385b791e67] void testing::internal::HandleExceptionsInMethodIfSupported<testing::Test, void>(testing::Test*, v
oid (testing::Test::*)(), char const*)
2: [0x7f385b77da66] testing::Test::Run()
2: [0x7f385b77dbe5] testing::TestInfo::Run()
2: [0x7f385b77dce9] testing::TestSuite::Run()
2: [0x7f385b787c54] testing::internal::UnitTestImpl::RunAllTests()
2: [0x7f385b7924af] bool testing::internal::HandleExceptionsInMethodIfSupported<testing::internal::UnitTestImpl, bool>(testing::internal::UnitTestImpl*, bool (testing::internal::UnitTestImpl::*)(), char const*)
2: [0x7f385b77de7d] testing::UnitTest::Run()
2: [0x559dada1c946] 
2: [0x7f385b033ca8] 
2: [0x7f385b033d65] __libc_start_main
2: [0x559dada42101] 
 2/47 Test  #2: Kokkos_CoreUnitTest_OpenMP .................................Subprocess aborted***Exception:   0.21 sec
Kokkos::OpenMP::initialize WARNING: OMP_PROC_BIND environment variable not set
  In general, for best performance with OpenMP 4.0 or better set OMP_PROC_BIND=spread and OMP_PLACES=threads
  For best performance with OpenMP 3.1 set OMP_PROC_BIND=true
  For unit testing set OMP_PROC_BIND=false
```

It looks like the test is not ready to be executed on machines with 1 CPU. Is that really the case, or it's a bug in the test? If it's not meant to be executed on machines with 1 CPU, would be possible to enclose the test inside an if statement, so that it's properly skipped? I'm thinking about something like this: (not tested yet)

```
--- kokkos.orig/core/unit_test/CMakeLists.txt
+++ kokkos/core/unit_test/CMakeLists.txt
@@ -700,9 +700,16 @@ if(Kokkos_ENABLE_OPENMP)
   else()
     set(OpenMP_EXTRA_SOURCES)
   endif()
-  kokkos_add_executable_and_test(
-    CoreUnitTest_OpenMP SOURCES UnitTestMainInit.cpp ${OpenMP_SOURCES} ${OpenMP_EXTRA_SOURCES}
-  )
+
+  include(ProcessorCount)
+  ProcessorCount(NCPU)
+
+  if(NCPU GREATER 1)
+    kokkos_add_executable_and_test(
+      CoreUnitTest_OpenMP SOURCES UnitTestMainInit.cpp ${OpenMP_SOURCES} ${OpenMP_EXTRA_SOURCES}
+    )
+  endif()
+
   kokkos_add_executable_and_test(CoreUnitTest_OpenMPInterOp SOURCES UnitTestMain.cpp openmp/TestOpenMP_InterOp.cpp)
 endif()

```

Note: To reproduce the failure, I suggest temporarily modifying GRUB configuration using `GRUB_CMDLINE_LINUX="nr_cpus=1"`.

Thanks.

### PR DESCRIPTION
**Pull request by masterleinad**
Fixes #8487. `partition_space` aborted for `OpenMP` when an integer division for the number of threads by the number of partitions yields 0. This pull request make sure that every instance always at least gets 1 thread.

### CODE REVIEW

**Comment by crtrott** [comment]
I don't see this as the right way. Why should partition space work with serial but not OpenMP if OpenMP has only 1 thread? Can't we just fix the partition space.

**Comment by crtrott** [comment]
I.e. partition space for an openmp instance with 1 thread can just return itself a bunch of times

**Comment by masterleinad** [comment]
> I don't see this as the right way. Why should partition space work with serial but not OpenMP if OpenMP has only 1 thread? Can't we just fix the partition space.

Are these tests still useful if don't have enough concurrency? We have a bunch more places where we are already implementing similar guards.

We can fix partition space but might need a better idea of what we want to do.

> I.e. partition space for an openmp instance with 1 thread can just return itself a bunch of times

What do you want to do when there are say 3 threads and we are asking for 4 execution space instances? Do we just want to make sure the minimum number of threads per execution space is 1?

**Review by dalg24 — APPROVED** [review]

**Comment by crtrott** [comment]
In principle this is fine, but shouldn't this only happen if OMP_NESTED is on? If OMP_NESTED is off you should just get the same instance back multiple times or?

**Comment by masterleinad** [comment]
> In principle this is fine, but shouldn't this only happen if OMP_NESTED is on? If OMP_NESTED is off you should just get the same instance back multiple times or?

After https://github.com/kokkos/kokkos/pull/7417, we check internally that Kokkos parallel regions inside OpenMP parallel regions are only allowed with OMP_NESTED/OMP_MAX_ACTIVE_LEVELS>1. I feel the issue addressed here is somewhat orthogonal, though. We just want to make sure that `partition_space` suceeds independent of the concurrency of the underlying resource. Whether the resulting execution space instances are used within another OpenMP region is a different question (even though that is likely the intent when using `partition_space` with `OpenMP`).

**Review by tcclevenger — APPROVED** [review]

**Comment by masterleinad** [comment]
@crtrott I updated the pull request as disucssed in the developer meeting. Namely
- disallow creating non-default Kokkos::OpenMP instances within OpenMP parallel regions
- return default Kokkos::OpenMP when OMP_NESTED isn't set or inside OpenMP parallel regions

File: core/src/OpenMP/Kokkos_OpenMP_Instance.hpp [hunk 1]
```diff
@@ -57,6 +57,12 @@ class OpenMPInternal {
       : m_pool_size{arg_pool_size}, m_level{omp_get_level()}, m_pool() {
     // guard pushing to all_instances
     {
+#ifndef KOKKOS_ENABLE_DEPRECATED_CODE_4
```
Comment (dalg24) [inline core/src/OpenMP/Kokkos_OpenMP_Instance.hpp:47]: Please briefly speak to this being proposed as deprecated code 4 and not deprecated code 5 (as a reply to this comment)
(Just asking for more information at this time)

Comment (masterleinad) [reply core/src/OpenMP/Kokkos_OpenMP_Instance.hpp:47]: It's consistent with the deprecation in https://github.com/kokkos/kokkos/pull/7417 to make using Kokkos::OpenMP in nested OpenMP regions more manageable/consistent.

Comment (dalg24) [reply core/src/OpenMP/Kokkos_OpenMP_Instance.hpp:47]: OK and the PR you refers to would be first released in 5.0

**Comment by dalg24** [comment]
```
/__w/kokkos/kokkos/core/src/OpenMP/Kokkos_OpenMP_Instance.hpp:174:25: error: narrowing conversion of '(& weights)->std::vector<int>::size()' from 'std::vector<int>::size_type' {aka 'unsigned int'} to 'int' [-Werror=narrowing]
  174 |     return {weights.size(), Kokkos::OpenMP{}};
      |             ~~~~~~~~~~~~^~
