### PR TITLE
Fix a bug when using realloc on views of non-default constructible element types

### LINKED ISSUE #6992: Kokkos::{resize,realloc} do not support views with non-default constructible objects
Using `Kokkos::resize` and `Kokkos::realloc` runs into trouble with non-default constructible types. For example, https://godbolt.org/z/q35MfMfxn.

The issue is stemming from code like this one https://github.com/kokkos/kokkos/blob/e4cc6862c6ba7cd14d7a274660015a62efb62605/core/src/Kokkos_CopyViews.hpp#L3233-L3245 which seems to ignore `WithoutInitializing` part in `deep_copy`.

It is entirely possible I am misusing Kokkos API, and there is a way to make these work.

### PR DESCRIPTION
**Pull request by aprokop**
Fix #6992.

### CODE REVIEW

**Review by masterleinad — COMMENTED** [review]
We need the same fix for `DualView`.
```diff
diff --git a/containers/src/Kokkos_DualView.hpp b/containers/src/Kokkos_DualView.hpp
index e821570a8..cfc4954d0 100644
--- a/containers/src/Kokkos_DualView.hpp
+++ b/containers/src/Kokkos_DualView.hpp
@@ -944,13 +944,13 @@ class DualView : public ViewTraits<DataType, Properties...> {
 
     if (sizeMismatch) {
       ::Kokkos::realloc(arg_prop, d_view, n0, n1, n2, n3, n4, n5, n6, n7);
-      if (alloc_prop_input::initialize) {
+      if constexpr(alloc_prop_input::initialize) {
         h_view = create_mirror_view(typename t_host::memory_space(), d_view);
       } else {
         h_view = create_mirror_view(Kokkos::WithoutInitializing,
                                     typename t_host::memory_space(), d_view);
       }
-    } else if (alloc_prop_input::initialize) {
+    } else if constexpr(alloc_prop_input::initialize) {
       if constexpr (alloc_prop_input::has_execution_space) {
         const auto& exec_space =
             Impl::get_property<Impl::ExecutionSpaceTag>(arg_prop);
@@ -1038,7 +1038,7 @@ class DualView : public ViewTraits<DataType, Properties...> {
       /* Resize on Device */
       if (sizeMismatch) {
         ::Kokkos::resize(properties, d_view, n0, n1, n2, n3, n4, n5, n6, n7);
-        if (alloc_prop_input::initialize) {
+        if constexpr(alloc_prop_input::initialize) {
           h_view = create_mirror_view(typename t_host::memory_space(), d_view);
         } else {
           h_view = create_mirror_view(Kokkos::WithoutInitializing,
@@ -1054,7 +1054,7 @@ class DualView : public ViewTraits<DataType, Properties...> {
       /* Resize on Host */
       if (sizeMismatch) {
         ::Kokkos::resize(properties, h_view, n0, n1, n2, n3, n4, n5, n6, n7);
-        if (alloc_prop_input::initialize) {
+        if constexpr(alloc_prop_input::initialize) {
           d_view = create_mirror_view(typename t_dev::memory_space(), h_view);
 
         } else {
```

**Comment by aprokop** [comment]
`DualView` needs some test refactoring to test for the new `realloc`.

**Review by crtrott — APPROVED** [review]

**Review by masterleinad — APPROVED** [review]

File: core/unit_test/TestResize.hpp [hunk 1]
```diff
@@ -23,6 +23,9 @@ namespace TestViewResize {
 
 struct Default {};
 struct WithoutInitializing {};
+struct NoDefaultConstructor {
+  NoDefaultConstructor(int) {}
+};
```
Comment (dalg24) [inline core/unit_test/TestResize.hpp:28]: Where is that guy used?  Did you forget to commit something?

File: core/unit_test/TestRealloc.hpp [hunk 2]
```diff
@@ -23,6 +23,9 @@ namespace TestViewRealloc {
 
 struct Default {};
 struct WithoutInitializing {};
+struct NoDefaultConstructor {
+  NoDefaultConstructor(int) {}
+};
```
Comment (dalg24) [inline core/unit_test/TestRealloc.hpp:28]: The two guys above are tags and you define something that is meant to be used as a value type in a view.
It is confusing to collocate them.
I suspect you can definite it within the block you added which IMO will make things more readable.

File: core/unit_test/TestRealloc.hpp [hunk 3]
```diff
@@ -51,6 +54,14 @@ void impl_testRealloc() {
     const int* newPointer = view_1d.data();
     EXPECT_EQ(oldPointer, newPointer);
   }
+  // Check #6992 fix (no default initialization in realloc without initializing)
```
Comment (dalg24) [inline core/unit_test/TestRealloc.hpp:57]: It's fine but noting that this test does not need to be instantiated multiple times like all others do.
It wouldn't hurt to add a comment observing how it contrasts with the other blocks.

File: core/src/Kokkos_CopyViews.hpp [hunk 4]
```diff
@@ -3709,7 +3709,7 @@ auto create_mirror_view_and_copy(
                 "not explicitly allow padding!");
 
   // same behavior as deep_copy(src, src)
-  if (!alloc_prop_input::has_execution_space)
+  if constexpr (!alloc_prop_input::has_execution_space)
```
Comment (dalg24) [inline core/src/Kokkos_CopyViews.hpp:3712]: This looks like an unrelated unnecessary change and it will likely conflict with #6955

File: core/unit_test/TestRealloc.hpp (hunk 2 above)
Comment (dalg24) [reply core/unit_test/TestRealloc.hpp:28]: Also I am not sure it is a good idea to have an empty type because that's probably not what you intend to test here.  Please add an int data member.

File: core/unit_test/TestResize.hpp (hunk 1 above)
Comment (aprokop) [reply core/unit_test/TestResize.hpp:28]: Yeah, this is an oversight. I tried testing resize too, but could not trigger it.

Comment (dalg24) [reply core/unit_test/TestResize.hpp:28]: Let's add the test anyway.  More coverage is not going to hurt.

**Review by dalg24 — APPROVED** [review]

File: core/unit_test/TestRealloc.hpp [hunk 5]
```diff
@@ -154,6 +154,19 @@ void testRealloc() {
     impl_testRealloc<DeviceType,
                      WithoutInitializing>();  // without data initialization
   }
+  // Check #6992 fix (no default initialization in realloc without initializing)
+  {
+    struct NoDefaultConstructor {
```
Comment (dalg24) [inline core/unit_test/TestRealloc.hpp:159]: Sorry NVCC did not like my suggestion
```
/var/jenkins/workspace/Kokkos_PR-6993/core/src/Cuda/Kokkos_Cuda_KernelLaunch.hpp(345): error: A type defined inside a __host__ function  ("NoDefaultConstructor") cannot be used in the template argument type of a __global__ function template instantiation
          detected during:
            instantiation of "Kokkos::Impl::cuda_parallel_launch_local_memory" based on template argument <Kokkos::Impl::ParallelFor<Kokkos::Impl::ViewValueFunctor<Kokkos::Device<Kokkos::CudaSpace::execution_space, Kokkos::CudaSpace::memory_space>, NoDefaultConstructor, false>, Kokkos::RangePolicy<Kokkos::CudaSpace::execution_space, Kokkos::IndexType<int64_t>, Kokkos::Impl::ViewValueFunctor<Kokkos::Device<Kokkos::CudaSpace::execution_space, Kokkos::CudaSpace::memory_space>, NoDefaultConstructor, false>::DestroyTag>, Kokkos::CudaSpace::execution_space>> 
(345): here
            instantiation of class "Kokkos::Impl::CudaParallelLaunchKernelFunc<DriverType, Kokkos::LaunchBounds<0U, 0U>, Kokkos::Impl::Experimental::CudaLaunchMechanism::LocalMemory> [with DriverType=Kokkos::Impl::ParallelFor<Kokkos::Impl::ViewValueFunctor<Kokkos::Device<Kokkos::CudaSpace::execution_space, Kokkos::CudaSpace::memory_space>, NoDefaultConstructor, false>, Kokkos::RangePolicy<Kokkos::CudaSpace::execution_space, Kokkos::IndexType<int64_t>, Kokkos::Impl::ViewValueFunctor<Kokkos::Device<Kokkos::CudaSpace::execution_space, Kokkos::CudaSpace::memory_space>, NoDefaultConstructor, false>::DestroyTag>, Kokkos::CudaSpace::execution_space>]"

**Comment by dalg24** [comment]
Ignoring
```
4: [  FAILED  ] 1 test, listed below:
4: [  FAILED  ] openmptarget.exec_space_thread_safety_range_scan
4: 
4:  1 FAILED TEST
 4/49 Test  #4: Kokkos_CoreUnitTest_OpenMPTarget ............***Failed  Error regular expression found in output. Regex=[  FAILED  ]151.03 sec
```
as well as runtime failures in one HIP build and  SYCL timing out
