### PR TITLE
Fix requests for large team scratch sizes

### LINKED ISSUE #4715: shared memory allocation integer overflow
I have a use-case that allocate a quite large shared memory for host only code (not going to be used for Cuda anyway) and I got the following. 

For a testing purpose, I try to allocate 8,000,000 bytes and gdb says that ``m_team_scratch_size = {0, 8000000}``
Then, I tried to allocate shared memory 4,022,364,488 bytes then the debugger says ``m_team_scratch_size = {0, 18446744073436948808}``. I know that it is large shared memory allocation but why do I get some insane number ? The size that I request does not overflow in "size_t" but it looks like that it overflows inside of Kokkos.

### PR DESCRIPTION
**Pull request by masterleinad**
Fixes #4715 by converting a bunch of places to take `size_t` as the type for allocation sizes.

### CODE REVIEW

**Comment by kyungjoo-kim** [comment]
I think that this fix will work fine. The unit test might not fine for all testing platform when the testing platform does not have enough memory as it request very large shared memory which could be amplified by the n_teams. As the test is just for checking that the large number remains as a large number internally in Kokkos (not insane number with overflow), the test can be limited for ``Kokkos::HostSpace::execution_space`` with ``n_team=1``.

File: core/unit_test/TestTeam.hpp [hunk 1]
```diff
@@ -126,6 +126,34 @@ struct TestTeamPolicy {
...
+  struct LargeTeamScratchFunctor {
+    const size_t m_per_team_bytes;
+
+    KOKKOS_FUNCTION void operator()(const team_member &member) const {
+      double *team_shared = static_cast<double *>(
+          member.team_shmem().get_shmem(m_per_team_bytes));
+      if (team_shared == nullptr)
+        Kokkos::abort("Couldn't allocate required size!\n");
+      double *team_shared_1 =
+          static_cast<double *>(member.team_shmem().get_shmem(sizeof(double)));
```
Comment (crtrott) [inline core/unit_test/TestTeam.hpp:138]: this is wrong. team_shmem is by definition level 0.

**Review by crtrott — CHANGES_REQUESTED** [review]

**Comment by masterleinad** [comment]
Retest this please.

File: core/src/Cuda/Kokkos_Cuda_Team.hpp [hunk 2]
```diff
@@ -344,9 +344,10 @@ class CudaTeamMember {
   // Private for the driver
 
   KOKKOS_INLINE_FUNCTION
-  CudaTeamMember(void* shared, const int shared_begin, const int shared_size,
-                 void* scratch_level_1_ptr, const int scratch_level_1_size,
-                 const int arg_league_rank, const int arg_league_size)
+  CudaTeamMember(void* shared, const size_t shared_begin,
+                 const size_t shared_size, void* scratch_level_1_ptr,
+                 const size_t scratch_level_1_size, const int arg_league_rank,
+                 const size_t arg_league_size)
```
Comment (dalg24) [inline core/src/Cuda/Kokkos_Cuda_Team.hpp:350]: why did you change the type of `arg_league_size`?

File: core/src/HIP/Kokkos_HIP_Team.hpp [hunk 3]
```diff
@@ -320,9 +320,10 @@ class HIPTeamMember {
   // Private for the driver
 
   KOKKOS_INLINE_FUNCTION
-  HIPTeamMember(void* shared, const int shared_begin, const int shared_size,
-                void* scratch_level_1_ptr, const int scratch_level_1_size,
-                const int arg_league_rank, const int arg_league_size)
+  HIPTeamMember(void* shared, const size_t shared_begin,
+                const size_t shared_size, void* scratch_level_1_ptr,
+                const size_t scratch_level_1_size, const int arg_league_rank,
+                const size_t arg_league_size)
```
Comment (dalg24) [inline core/src/HIP/Kokkos_HIP_Team.hpp:326]: Same question about changing the type of `arg_league_size`

File: core/src/Kokkos_ExecPolicy.hpp [hunk 4]
```diff
@@ -470,14 +470,14 @@ extract_vector_length(iType, Args...) {
 
 }  // namespace Impl
 
-Impl::PerTeamValue PerTeam(const int& arg);
-Impl::PerThreadValue PerThread(const int& arg);
+Impl::PerTeamValue PerTeam(const size_t& arg);
+Impl::PerThreadValue PerThread(const size_t& arg);
```
Comment (dalg24) [inline core/src/Kokkos_ExecPolicy.hpp:474]: Should we go ahead and fix that by taking the size argument by value?

File: core/src/Cuda/Kokkos_Cuda_Parallel.hpp [hunk 5]
```diff
@@ -254,15 +254,15 @@ class TeamPolicyInternal<Kokkos::Cuda, Properties...>
   inline void impl_set_vector_length(size_t vector_length) {
     m_vector_length = vector_length;
   }
-  inline int scratch_size(int level, int team_size_ = -1) const {
+  inline size_t scratch_size(int level, int team_size_ = -1) const {
```
Comment (dalg24) [inline core/src/Cuda/Kokkos_Cuda_Parallel.hpp:257]: I am tempted to get rid of the inline here and below while we are at it.

File: core/src/impl/Kokkos_HostThreadTeam.hpp [hunk 6]
```diff
@@ -310,8 +308,9 @@ class HostThreadTeamData {
   //   thread_local_size = number bytes for thread local memory
   // Return:
   //   total number of bytes that must be allocated
-  static size_t scratch_size(int pool_reduce_size, int team_reduce_size,
-                             int team_shared_size, int thread_local_size) {
+  static size_t scratch_size(size_t pool_reduce_size, size_t team_reduce_size,
+                             size_t team_shared_size,
+                             size_t thread_local_size) {
```
Comment (dalg24) [inline core/src/impl/Kokkos_HostThreadTeam.hpp:313]: Similar question why changing the type of `thread_local_size`?

File: core/unit_test/TestTeamBasic.hpp [hunk 7]
```diff
@@ -114,6 +114,47 @@ TEST(TEST_CATEGORY, team_reduce_large) {
...
+#ifdef KOKKOS_ENABLE_OPENMPTARGET
+  const size_t per_team_extent = 268435460;
+#else
+  const size_t per_team_extent = 502795560;
+#endif
+
+  const size_t per_team_bytes = per_team_extent * sizeof(double);
+
+#ifdef KOKKOS_ENABLE_OPENMPTARGET
+  Kokkos::TeamPolicy<TEST_EXECSPACE> policy(n_teams, 32);
```
Comment (dalg24) [inline core/unit_test/TestTeamBasic.hpp:147]:
```suggestion
  Kokkos::TeamPolicy<TEST_EXECSPACE> policy(n_teams, std::is_same<TEST_EXECSPACE, Kokkos::Experimental::OpenMPTarget>::value ? 32 : 1);
```

File: core/unit_test/TestTeamBasic.hpp [hunk 8]
```diff
@@ -114,6 +114,47 @@ TEST(TEST_CATEGORY, team_reduce_large) {
...
+
+TEST(TEST_CATEGORY, large_team_scratch_size) {
+  const int level   = 1;
+  const int n_teams = 1;
+
+#ifdef KOKKOS_ENABLE_OPENMPTARGET
+  const size_t per_team_extent = 268435460;
+#else
+  const size_t per_team_extent = 502795560;
+#endif
```
Comment (dalg24) [inline core/unit_test/TestTeamBasic.hpp:142]: How did you pick these magic numbers?

Comment (masterleinad) [reply core/unit_test/TestTeamBasic.hpp:142]: The second pone was in the issue fixed in the pull request, the first one was chosen such that I allocate more than INT_MAX (2^31-1) bytes. I saw some more problems when choosing the larger size for OpenMPTarget (couldn't allocate enough memory) but was able to trigger the expected problems with the smaller size, too.

File: core/src/impl/Kokkos_HostThreadTeam.hpp (hunk 6 above)
Comment (masterleinad) [reply core/src/impl/Kokkos_HostThreadTeam.hpp:313]: Just for consistency. Especially on the host, I would expect `thread_local_size` possibly to be of similar magnitude as `team_shared_size`.

File: core/src/Kokkos_ExecPolicy.hpp (hunk 4 above)
Comment (masterleinad) [reply core/src/Kokkos_ExecPolicy.hpp:474]: I would do it in another pull request throughout the whole repository.

File: core/src/Cuda/Kokkos_Cuda_Team.hpp (hunk 2 above)
Comment (masterleinad) [reply core/src/Cuda/Kokkos_Cuda_Team.hpp:350]: I'll revert that.

File: core/src/Kokkos_ExecPolicy.hpp (hunk 4 above)
Comment (dalg24) [reply core/src/Kokkos_ExecPolicy.hpp:474]: To be clear I am not encouraging such a PR.  I don't even want to think about the amount of noise it will generate.

File: core/unit_test/TestTeamBasic.hpp (hunk 8 above)
Comment (dalg24) [reply core/unit_test/TestTeamBasic.hpp:142]: Please add a comment to that effect

**Review by fnrizzi — APPROVED** [review]

File: core/src/Cuda/Kokkos_Cuda_Parallel.hpp (hunk 5 above)
Comment (dalg24) [reply core/src/Cuda/Kokkos_Cuda_Parallel.hpp]: Please undo these changes, I meant fixing the ones you are editing not all occurrences.
I am not blocking if others want to approve as is.

File: core/src/OpenMP/Kokkos_OpenMP_Parallel.hpp [hunk 9]
```diff
@@ -895,7 +895,7 @@ class ParallelFor<FunctorType, Kokkos::TeamPolicy<Properties...>,
 
     const size_t pool_reduce_size  = 0;  // Never shrinks
     const size_t team_reduce_size  = TEAM_REDUCE_SIZE * m_policy.team_size();
-    const size_t team_shared_size  = m_shmem_size + m_policy.scratch_size(1);
+    const size_t team_shared_size  = m_shmem_size;
```
[the remark this answers is not in the document]
Comment (masterleinad) [reply core/src/OpenMP/Kokkos_OpenMP_Parallel.hpp:898]: `m_shmem_size` already contains `m_policy.scratch_size(1)`,
```
 inline ParallelFor(const FunctorType& arg_functor, const Policy& arg_policy)
      : m_instance(t_openmp_instance),
        m_functor(arg_functor),
        m_policy(arg_policy),
        m_shmem_size(arg_policy.scratch_size(0) + arg_policy.scratch_size(1) +
                     FunctorTeamShmemSize<FunctorType>::value(
                         arg_functor, arg_policy.team_size())) {}
};
```

**Review by crtrott — APPROVED** [review]

**Comment by crtrott** [comment]
Probably the culprit for #5025 , my guess some bug in the OpenMP scratch memory management which does require larger scratch after all.
