### PR TITLE
Fix issue #2410 max_team_size not compiling for reducers with scalar types without +=

### LINKED ISSUE #2410: TeamPolicy with reducers with valuetypes without += broken on CUDA
Reported here:
trilinos/Trilinos#6000

I root caused the issue to our `TeamPolicy::team_size_max` function not taking reducers in addition to the functor and the parallel reduce tag. Hence during the "figure out how many registers this kernel will use" step, it tries to instantiate the kernel as if it were a sum reduction. 
Technically that makes that wrong for any reducer other than sum. But for every reducer which has a native value type (like double) it happens to work, though the register count determination might be slightly off - if so it would result in a runtime dispatch error.

Here is a reproducer:
```c++
#include<Kokkos_Core.hpp>
#include<cmath>

int main(int argc, char* argv[]) {
  Kokkos::initialize(argc,argv);
  {
    using ExecSpace = Kokkos::DefaultExecutionSpace;
    using ReducerType = Kokkos::MinMax<double, ExecSpace>;
    using ReducerValueType = typename ReducerType::value_type;
    using DynamicScheduleType = Kokkos::Schedule<Kokkos::Dynamic>;
    using TeamPolicyType = Kokkos::TeamPolicy<ExecSpace, DynamicScheduleType>;
    using TeamHandleType = typename TeamPolicyType::member_type;

    static constexpr int num_teams = 1000;
    static constexpr int num_threads = 1000;
    ReducerValueType val;
    ReducerType reducer(val);
    Kokkos::parallel_reduce(
      TeamPolicyType(num_teams, Kokkos::AUTO),
      KOKKOS_LAMBDA(const TeamHandleType& team, ReducerValueType& teamVal) {
    }, reducer);
  }
  Kokkos::finalize();
}
```

To fix this: the (non-deprecated) max and recommended team size functions need an option to take in a reducer too. There are two options:

- add an overload `team_size_max(FunctorType,ParallelReduceTag,Reducer)`
- make `ParallelReduceTag` templated on `ReducerType`

I am thinking option 1 is better. 

What needs to happen:
- add a test which exposes this problem: i.e. test ALL reducers with TeamPolicy too
- add that overload
- use it inside the ParallelReduce class to determine max and recommended team size where appropriate

### PR DESCRIPTION
**Pull request by crtrott**
Tests are missing, and I couldn't apply clang format due to limited machines I can access. That said this fixes #2410

### CODE REVIEW

**Comment by crtrott** [comment]
New Reproducer:
```c++
#include<Kokkos_Core.hpp>
#include<cmath>

int main(int argc, char* argv[]) {
  Kokkos::initialize(argc,argv);
  {
    using ExecSpace = Kokkos::DefaultExecutionSpace;
    using ReducerType = Kokkos::MinMax<double, Kokkos::HostSpace>;
    using ReducerValueType = typename ReducerType::value_type;
    using DynamicScheduleType = Kokkos::Schedule<Kokkos::Dynamic>;
    using TeamPolicyType = Kokkos::TeamPolicy<ExecSpace, DynamicScheduleType>;
    using TeamHandleType = typename TeamPolicyType::member_type;

    static constexpr int num_teams = 17;
    static constexpr int num_threads = 16;
    ReducerValueType val;
    ReducerType reducer(val);
    auto f1 = KOKKOS_LAMBDA(const TeamHandleType& team, ReducerValueType& teamVal) {
      printf("Test %i %i\n",(int)team.league_rank(),(int)team.team_rank());
    };
    TeamPolicyType p(num_teams, Kokkos::AUTO);
    printf("Max TeamSize: %i Recommended TeamSize: %i\n",
      p.team_size_max(f1,reducer,Kokkos::ParallelReduceTag()),
      p.team_size_recommended(f1,reducer,Kokkos::ParallelReduceTag()));

    Kokkos::parallel_reduce(p,f1, reducer);
    double sum;
    Kokkos::parallel_reduce(
      TeamPolicyType(num_teams, Kokkos::AUTO),
      KOKKOS_LAMBDA(const TeamHandleType& team, double& teamVal) {
      printf("Test %i %i\n",(int)team.league_rank(),(int)team.team_rank());
      teamVal += 1;
    }, sum);
    printf("Sum: %lf\n",sum);
  }
  Kokkos::finalize();
}
```

**Comment by crtrott** [comment]
Note I also added a version of team_size_recommended which would work for these type of reducers. Doesn't look like that function is called inside our runtime though.

**Comment by crtrott** [comment]
Things to do: 
- run clang-format
- add the new member functions to the non-cuda TeamPolicies
  - these can have trivial implementations: drop the reducer, and call the version without reducer
- add tests for the new member functions of TeamPolicy
- Update documentation.

**Comment by crtrott** [comment]
`team_size_recommended` is in principal tested inside of `TestTeamTeamSize.hpp`. But the new overload is not. `team_size_recommended` is largely a facility for users - not for our internal runtime. But the test of the new overload for reducers should be added.

**Comment by dalg24** [comment]
```diff
--- old
+++ new
@@ -1,18 +1,12 @@
-template <class FunctorType>
-int team_size_max(const FunctorType& f, const ParallelReduceTag&) const {
-  typedef Impl::FunctorAnalysis<Impl::FunctorPatternInterface::REDUCE,
-                                TeamPolicyInternal, FunctorType>
-      functor_analysis_type;
-  typedef typename Impl::ParallelReduceReturnValue<
-      void, typename functor_analysis_type::value_type,
-      FunctorType>::reducer_type reducer_type;
+template <class FunctorType, class ReducerType>
+int team_size_max(const FunctorType& f, const ReducerType& r, const ParallelReduceTag&) const {
   typedef Impl::ParallelReduce<FunctorType, TeamPolicy<Properties...>,
-                               reducer_type>
+                               ReducerType>
```
This makes me say
```C++
template <class FunctorType, class ReducerType>
inline int team_size_max(FunctorType&& f, const ReducerType&,
                  ParallelReduceTag&& tag) const
{
  return team_size_max<ReducerType>(std::forward<FunctorType>(f),
                                    std::forward<ParallelReduceTag>(tag));
}
```

**Comment by crtrott** [comment]
Wow this broke it thoroughly.

File: core/src/Cuda/Kokkos_Cuda_Parallel.hpp [hunk 1]
```diff
@@ -590,6 +509,58 @@ class TeamPolicyInternal<Kokkos::Cuda, Properties...>
     return *this;
   }
 #endif
+
+  template <class FunctorType, class ClosureType>
+  int internal_team_size_max<closure_type>(const FunctorType& f) {
```
Comment (crtrott) [inline core/src/Cuda/Kokkos_Cuda_Parallel.hpp]: remove the `<closure_type>` here and add a `using closure_type=ClosureType` later

File: core/src/Cuda/Kokkos_Cuda_Parallel.hpp [hunk 2]
```diff
@@ -313,27 +252,7 @@ class TeamPolicyInternal<Kokkos::Cuda, Properties...>
...
-            (size_t)thread_scratch_size(0) + sizeof(double) +
-                ((functor_value_traits::StaticValueSize != 0)
-                     ? 0
-                     : functor_value_traits::value_size(f)));
-    // Currently we require Power-of-2 team size for reductions.
-    int p2 = 1;
-    while (p2 <= block_size) p2 *= 2;
-    p2 /= 2;
-    return p2 / vector_length();
+    return team_size_recommeded_impl<closure_type>(f);
```
Comment (crtrott) [inline core/src/Cuda/Kokkos_Cuda_Parallel.hpp]: probably this should be `recommended` with an n ...

Comment (crtrott) [reply core/src/Cuda/Kokkos_Cuda_Parallel.hpp]: also the function later is named: `internal_team_size_recommended` but can we rename them both with "imp" as prefix instead of internal?

**Comment by crtrott** [comment]
The 'internal' is probably fine we use that all over the place. We can discuss whether we should change them all to 'imply'.

**Comment by masterleinad** [comment]
Should we add the reproducer to the test suite?

**Comment by masterleinad** [comment]
>     * Update documentation.

What would need to get updated?` team_size_max` and `team_size_recommended` appear to be documented already in https://github.com/kokkos/kokkos/wiki/Kokkos::TeamPolicy. Anything else you had in mind?

**Comment by masterleinad** [comment]
Retest this please.

File: core/src/Cuda/Kokkos_Cuda_Parallel.hpp [hunk 3]
```diff
@@ -531,6 +509,60 @@ class TeamPolicyInternal<Kokkos::Cuda, Properties...>
...
+                ((functor_value_traits::StaticValueSize != 0)
+                     ? 0
+                     : functor_value_traits::value_size(f)));
+
+    // Currently we require Power-of-2 team size for reductions.
+    int p2 = 1;
+    while (p2 <= block_size) p2 *= 2;
+    p2 /= 2;
+    return p2 / vector_length();
+  }
```
Comment (dhollman) [inline core/src/Cuda/Kokkos_Cuda_Parallel.hpp]: There is **far** to much copy-pasted code in this function. AFAICT literally only line 550 is different. Please restructure to avoid copy-pasta. If there's absolutely no way to do that, please provide a long, detailed comment justifying the copy-paste, detailing *exactly* the differences between the two functions (e.g., *each* and every copied line should be commented with "copied from above because...", and each line where copies from the original can't be avoided should be commented with "copied below because..."), and explaining why there's no way to avoid introducing an extra copy of application logic into the codebase. (Be warned, though, that my bar for approving such things is very high at this point. In my assessment, a large portion of the technical debt in Kokkos currently comes from this kind of thing.)

File: core/src/Cuda/Kokkos_Cuda_Parallel.hpp [hunk 4]
```diff
@@ -531,6 +509,60 @@ class TeamPolicyInternal<Kokkos::Cuda, Properties...>
...
+                                              typename traits::launch_bounds>(
+            space().impl_internal_space_instance(), attr, f,
+            (size_t)vector_length(),
+            (size_t)team_scratch_size(0) + 2 * sizeof(double),
+            (size_t)thread_scratch_size(0) + sizeof(double) +
+                ((functor_value_traits::StaticValueSize != 0)
+                     ? 0
+                     : functor_value_traits::value_size(f)));
+
+    // Currently we require Power-of-2 team size for reductions.
```
Comment (dhollman) [inline core/src/Cuda/Kokkos_Cuda_Parallel.hpp]: Please assert that `block_size > 0`, since that's an implicit assumption in the code below and the reader may not understand that code/think it's buggy if they don't know that

File: core/unit_test/TestTeamTeamSize.hpp [hunk 5]
```diff
@@ -172,4 +172,51 @@ TEST(TEST_CATEGORY, team_policy_max_recommended) {
       max_scratch_size / 2);
 }
 
+template <typename TeamHandleType, typename ReducerValueType>
+struct PrintFunctor1 {
+  KOKKOS_INLINE_FUNCTION void operator()(const TeamHandleType& team,
+                                         ReducerValueType&) const {
+    printf("Test %i %i\n", (int)team.league_rank(), (int)team.team_rank());
```
Comment (dhollman) [inline core/unit_test/TestTeamTeamSize.hpp]: Any reason for C-style casting here? E.g., `int(team.league_rank())` should work fine and not raise the red flags that C-style casts should raise with the reader.

File: core/src/Cuda/Kokkos_Cuda_Parallel.hpp [hunk 6]
```diff
@@ -531,6 +509,60 @@ class TeamPolicyInternal<Kokkos::Cuda, Properties...>
...
+
+  template <class FunctorType, class ClosureType>
+  int internal_team_size_max(const FunctorType& f) const {
+    using closure_type = ClosureType;
+    typedef Impl::FunctorValueTraits<FunctorType, typename traits::work_tag>
+        functor_value_traits;
+
+    cudaFuncAttributes attr =
+        CudaParallelLaunch<closure_type, typename traits::launch_bounds>::
+            get_cuda_func_attributes();
```
[the remark this answers is not in the document]
Comment (mhoemmen) [reply core/src/Cuda/Kokkos_Cuda_Parallel.hpp]: I've been bitten in the past by not checking CUDA errors so I second that.

File: core/src/Cuda/Kokkos_Cuda_Parallel.hpp [hunk 7]
```diff
@@ -186,28 +187,16 @@ class TeamPolicyInternal<Kokkos::Cuda, Properties...>
...
-    while (p2 <= block_size) p2 *= 2;
-    p2 /= 2;
-    return p2 / vector_length();
+  template <class FunctorType, class ReducerType>
+  inline int team_size_max(const FunctorType& f, const ReducerType& r,
+                           const ParallelReduceTag&) const {
+    typedef Impl::ParallelReduce<FunctorType, TeamPolicy<Properties...>,
+                                 ReducerType>
+        closure_type;
+    return internal_team_size_max<FunctorType, closure_type>(f);
```
[the remark this answers is not in the document]
Comment (DavidPoliakoff) [reply core/src/Cuda/Kokkos_Cuda_Parallel.hpp]: I'm going to resolve this so it doesn't get in the way of a review, but it helps to know that this is a design concern with Kokkos. Feel free to unresolve if you think it should change the code

File: core/src/Cuda/Kokkos_Cuda_Parallel.hpp [hunk 8]
```diff
@@ -531,6 +509,60 @@ class TeamPolicyInternal<Kokkos::Cuda, Properties...>
     return *this;
   }
 #endif
+
+  template <class FunctorType, class ClosureType>
+  int internal_team_size_max(const FunctorType& f) const {
```
[the remark this answers is not in the document]
Comment (DavidPoliakoff) [reply core/src/Cuda/Kokkos_Cuda_Parallel.hpp]: I'm doing this, but am curious why it's harmful to specify. If you've got the time, let me know what's up there

File: core/src/Cuda/Kokkos_Cuda_Parallel.hpp (hunk 3 above)
Comment (DavidPoliakoff) [reply core/src/Cuda/Kokkos_Cuda_Parallel.hpp]: I think you're right, and I can refactor this to instead be one function which takes in an argument which could be the different things called on those lines, if that's an acceptable refactoring

**Comment by DavidPoliakoff** [comment]
Folks, I commented a lot on the review, but it looks like @masterleinad is jumping on this one. Ignore my comments

File: core/src/Cuda/Kokkos_Cuda_Parallel.hpp (hunk 8 above)
[the remark this answers is not in the document]
Comment (dhollman) [reply core/src/Cuda/Kokkos_Cuda_Parallel.hpp]: Inadvertent casting, for one thing

[the remark this answers is not in the document]
Comment (dhollman) [reply core/src/Cuda/Kokkos_Cuda_Parallel.hpp]: Basically most of the arguments from the "almost always auto" philosophy apply here. (Conversely, if you're part of the "almost always avoid auto" crowd, which I disagree with, most of those arguments apply against this.)

File: core/src/Cuda/Kokkos_Cuda_Parallel.hpp (hunk 3 above)
Comment (dhollman) [reply core/src/Cuda/Kokkos_Cuda_Parallel.hpp]: Great :-) Exactly what I meant. If it gets too complicated, that's fine, it's just that my bar for "too complicated" is at least that it has to be worth commenting every line that was copied in both places and explaining why

File: core/src/Cuda/Kokkos_Cuda_Parallel.hpp (hunk 6 above)
[the remark this answers is not in the document]
Comment (masterleinad) [reply core/src/Cuda/Kokkos_Cuda_Parallel.hpp]: See #2549.

File: core/unit_test/TestTeamTeamSize.hpp (hunk 5 above)
Comment (dalg24) [reply core/unit_test/TestTeamTeamSize.hpp]: > Any reason for C-style casting here?

Consistency with the rest of the code in the file.  The same goes with the `typedef`s.

Comment (dalg24) [reply core/unit_test/TestTeamTeamSize.hpp]: Anyway we are not going to argue about this.  @dhollman please review the latest changes used by Daniel.

File: core/src/Cuda/Kokkos_Cuda_Parallel.hpp [hunk 9]
```diff
@@ -531,6 +510,49 @@ class TeamPolicyInternal<Kokkos::Cuda, Properties...>
...
+            get_cuda_func_attributes();
+    const int block_size =
+        block_size_callable(space().impl_internal_space_instance(), attr, f,
+                            (size_t)vector_length(),
+                            (size_t)team_scratch_size(0) + 2 * sizeof(double),
+                            (size_t)thread_scratch_size(0) + sizeof(double) +
+                                ((functor_value_traits::StaticValueSize != 0)
+                                     ? 0
+                                     : functor_value_traits::value_size(f)));
+    assert(block_size > 0);
```
Comment (dhollman) [inline core/src/Cuda/Kokkos_Cuda_Parallel.hpp]: `KOKKOS_ASSERT` macro should probably be preferred over the standard one, I think? Not a blocker; we can fix this later if necessary

File: core/src/Cuda/Kokkos_Cuda_Parallel.hpp [hunk 10]
```diff
@@ -531,6 +510,49 @@ class TeamPolicyInternal<Kokkos::Cuda, Properties...>
...
+                                BlockSizeCallable&& block_size_callable) const {
+    using closure_type = ClosureType;
+    using functor_value_traits =
+        Impl::FunctorValueTraits<FunctorType, typename traits::work_tag>;
+
+    cudaFuncAttributes attr =
+        CudaParallelLaunch<closure_type, typename traits::launch_bounds>::
+            get_cuda_func_attributes();
+    const int block_size =
+        block_size_callable(space().impl_internal_space_instance(), attr, f,
```
Comment (dhollman) [inline core/src/Cuda/Kokkos_Cuda_Parallel.hpp]: (pedantic nonsense, please ignore, but in case someone would learn something:) This should *very technically* be `std::forward<BlockSizeCallable>(block_size_callable)(...)` since this is the last use of the forwarding reference `block_size_callable`.  Don't change this here; it's totally fine, but maybe it will help in a future scenario where it would actually matter.

**Comment by masterleinad** [comment]
I am happy to incorporate more improvements here.

**Comment by masterleinad** [comment]
Retest this please.

**Comment by masterleinad** [comment]
Retest this please.

File: core/src/Cuda/Kokkos_Cuda_Parallel.hpp (hunk 6 above)
[the remark this answers is not in the document]
Comment (crtrott) [reply core/src/Cuda/Kokkos_Cuda_Parallel.hpp]: One note for later reference: cudaGetLastError() is not something we should call willy nilly. It incurs a few microseconds latency ...
