### PR TITLE
Extend CEA nightly tests to use C++ 20

### LINKED ISSUE #7779: Build error with Cuda backend and C++ 20 when relocatable device code is enabled
The CEA nightly build using C++ 20 of #7777 has a systematic error when building with the Cuda backend, when the `Kokkos_ENABLE_CUDA_RELOCATABLE_DEVICE_CODE` flag is enabled. See the [CDash report](https://my.cdash.org/build/2824444).

Configuration: `-DKokkos_ENABLE_CUDA=ON -DKokkos_ENABLE_CUDA_RELOCATABLE_DEVICE_CODE=ON -DCMAKE_BUILD_TYPE=Release -DCMAKE_CXX_STANDARD=20 -DCMAKE_COMPILE_WARNING_AS_ERROR=ON -DKokkos_ENABLE_COMPILER_WARNINGS=ON -DKokkos_ENABLE_TESTS=ON`

Environment:

- GCC 11.4.0;
- NVCC 12.2;
- CMake 3.22; and
- OS: Ubuntu 22.04.

Errors:

```
[core/src/impl/Kokkos_SimpleTaskScheduler.hpp:420](https://github.com/kokkos/kokkos//blob/9f2db8e9c5c724ace8b1c27120996281ff12cffd/core/src/impl/Kokkos_SimpleTaskScheduler.hpp#L420):21: error: template constraint failure for 'template<class _Range>  requires  range<_Range> using range_reference_t = std::iter_reference_t<decltype (std::ranges::__cust_access::__begin(declval<_Container&>()))>'
[core/src/impl/Kokkos_SimpleTaskScheduler.hpp:420](https://github.com/kokkos/kokkos//blob/9f2db8e9c5c724ace8b1c27120996281ff12cffd/core/src/impl/Kokkos_SimpleTaskScheduler.hpp#L420):21: error: template constraint failure for 'template<class _Range>  requires  range<_Range> using range_reference_t = std::iter_reference_t<decltype (std::ranges::__cust_access::__begin(declval<_Container&>()))>'
[core/src/impl/Kokkos_SimpleTaskScheduler.hpp:420](https://github.com/kokkos/kokkos//blob/9f2db8e9c5c724ace8b1c27120996281ff12cffd/core/src/impl/Kokkos_SimpleTaskScheduler.hpp#L420):21: error: template constraint failure for 'template<class _Range>  requires  range<_Range> using range_reference_t = std::iter_reference_t<decltype (std::ranges::__cust_access::__begin(declval<_Container&>()))>'
```

https://github.com/kokkos/kokkos/blob/9f2db8e9c5c724ace8b1c27120996281ff12cffd/core/src/impl/Kokkos_SimpleTaskScheduler.hpp#L420-L424

### PR DESCRIPTION
**Pull request by pzehner**
This PR aims to add cases with the C++ 20 standard enabled for CEA nightly tests.

It is the following of #7704 and #7762.

The PR adds a guard to a call to `std::is_base_of` when C++ 20 is enabled, with NVCC ≤ 12.5, which was failing otherwise.

Fixes #7779.

Progress:

- [x] Add configuration;
- [x] Prevent to use for pull requests and reenable Nightly mode.

Outcomes of the new cases:

- Cuda-A100-GCC/11.2.0-Cuda/12.2.1-Static-CUDA_CONSTEXPR-CUDA_RELOCATABLE_DEVICE_CODE-C++20-Release:
  - [Workflow](https://github.com/kokkos/kokkos/actions/runs/13464265055/job/37626497211?pr=7777);
  - [Dashboard](https://my.cdash.org/build/2830180);
- Cuda-A100-UVM-GCC/11.2.0-Cuda/12.2.1-Static-CUDA_CONSTEXPR-CUDA_RELOCATABLE_DEVICE_CODE-C++20-Release:
  - [Workflow](https://github.com/kokkos/kokkos/actions/runs/13464265055/job/37626497528?pr=7777);
  - [Dashboard](https://my.cdash.org/build/2830193);
- Cuda-V100-GCC/11.2.0-Cuda/12.2.1-Static-CUDA_CONSTEXPR-CUDA_RELOCATABLE_DEVICE_CODE-C++20-Release:
  - [Workflow](https://github.com/kokkos/kokkos/actions/runs/13464265055/job/37626497869?pr=7777);
  - [Dashboard](https://my.cdash.org/build/2830212);
- Cuda-V100-UVM-GCC/11.2.0-Cuda/12.2.1-Static-CUDA_CONSTEXPR-CUDA_RELOCATABLE_DEVICE_CODE-C++20-Release:
  - [Workflow](https://github.com/kokkos/kokkos/actions/runs/13464265055/job/37626498164?pr=7777);
  - [Dashboard](https://my.cdash.org/build/2830229).

As for #7704, there is an error during the Update step, which is due to the branch of this PR belonging to a fork. As for the cited PR, this will fade away when merged.

<details>
<summary>Details on the error with C++20 and NVCC</summary>

Builds with C++20 are all failing with the following errors:

```
[core/src/impl/Kokkos_SimpleTaskScheduler.hpp:420](https://github.com/kokkos/kokkos//blob/9f2db8e9c5c724ace8b1c27120996281ff12cffd/core/src/impl/Kokkos_SimpleTaskScheduler.hpp#L420):21: error: template constraint failure for 'template<class _Range>  requires  range<_Range> using range_reference_t = std::iter_reference_t<decltype (std::ranges::__cust_access::__begin(declval<_Container&>()))>'
[core/src/impl/Kokkos_SimpleTaskScheduler.hpp:420](https://github.com/kokkos/kokkos//blob/9f2db8e9c5c724ace8b1c27120996281ff12cffd/core/src/impl/Kokkos_SimpleTaskScheduler.hpp#L420):21: error: template constraint failure for 'template<class _Range>  requires  range<_Range> using range_reference_t = std::iter_reference_t<decltype (std::ranges::__cust_access::__begin(declval<_Container&>()))>'
[core/src/impl/Kokkos_SimpleTaskScheduler.hpp:420](https://github.com/kokkos/kokkos//blob/9f2db8e9c5c724ace8b1c27120996281ff12cffd/core/src/impl/Kokkos_SimpleTaskScheduler.hpp#L420):21: error: template constraint failure for 'template<class _Range>  requires  range<_Range> using range_reference_t = std::iter_reference_t<decltype (std::ranges::__cust_access::__begin(declval<_Container&>()))>'
```

https://github.com/kokkos/kokkos/blob/9f2db8e9c5c724ace8b1c27120996281ff12cffd/core/src/impl/Kokkos_SimpleTaskScheduler.hpp#L420-L424

Fixed within the PR.

</details>

### CODE REVIEW

**Review by JBludau — APPROVED** [review]
looks good to me

**Comment by pzehner** [comment]
Crap, I made a mistake in the C++ 20 identification macro...

**Review by JBludau — APPROVED** [review]

File: core/src/impl/Kokkos_SimpleTaskScheduler.hpp [hunk 1]
```diff
@@ -417,11 +417,19 @@ class SimpleTaskScheduler
     static_assert(is_future<generated_type>::value,
                   "when_all function must return a Kokkos future (an instance "
                   "of Kokkos::BasicFuture)");
+
+    // see #7779
+    // There are issues with the implementation of std::is_base_of in NVCC
+    // <= 12.5 for C++ 20
+#if __cplusplus < 202002L || !defined(__CUDACC__) || \
+    __CUDACC_VER_MAJOR__ > 12 ||                     \
+    __CUDACC_VER_MAJOR__ == 12 && __CUDACC_VER_MINOR__ >= 5
```
Comment (masterleinad) [inline core/src/impl/Kokkos_SimpleTaskScheduler.hpp:426]:
```suggestion
    (__CUDACC_VER_MAJOR__ == 12 && __CUDACC_VER_MINOR__ >= 5)
```

Comment (dalg24) [inline core/src/impl/Kokkos_SimpleTaskScheduler.hpp:426]:
```C++
#if !defined(KOKKOS_ENABLE_CXX17) &&  \
  (!defined(KOKKOS_COMPILER_NVCC) || KOKKOS_COMPILER_NVCC >= 1250)
```
(not sure about `__CUDACC__`)

**Review by dalg24 — CHANGES_REQUESTED** [review]

File: core/src/impl/Kokkos_SimpleTaskScheduler.hpp (hunk 1 above)
Comment (pzehner) [reply core/src/impl/Kokkos_SimpleTaskScheduler.hpp:426]: Oh, I didn't think about using the Kokkos macros.

Here, you restrict the code to not be built for C++ 17, but there is no issue for this version of the standard, so I would do:

```cpp
#if defined(KOKKOS_ENABLE_CXX17) || !defined(KOKKOS_COMPILER_NVCC) || \
  KOKKOS_COMPILER_NVCC >= 1250
```

Comment (pzehner) [reply core/src/impl/Kokkos_SimpleTaskScheduler.hpp]: I'm confused. So you mean that macro guards always discard C++ 17?

Comment (cedricchevalier19) [reply core/src/impl/Kokkos_SimpleTaskScheduler.hpp]: I agree with @dalg24 that his writing is clearer in term of testing C++ version and then on the second line NVCC specifics.

**Review by masterleinad — APPROVED** [review]

**Review by dalg24 — APPROVED** [review]
