### PR TITLE
Fix adjacent difference

### LINKED ISSUE #6890: adjacent_difference should not allow running with source being the same as destination
Right now, it is possible to run
```c++
Kokkos::Experimental::adjacent_difference(space, view, view);
```
According to the [standard](https://eel.is/c++draft/numeric.ops#adjacent.difference-8), it should not be possible.
```
For the overloads with an ExecutionPolicy, the ranges [first, last)
and [result, result + (last - first)) shall not overlap.
```

Affects all Kokkos versions I tried.

### PR DESCRIPTION
**Pull request by yasahi-hpc**
Resolves #6890

This PR aims at adding assertion in `adjacent_difference` to disallow the overlapping of source and destination. 
`expect_no_overlap` is newly added which is enabled in debug mode only. In the debug mode, it checks
```C++
// KOKKOS_EXPECTS(first < s_first && s_last < last); // previous implementation
KOKKOS_EXPECTS(first > s_last1 || last < s_first1); // current implementation
```

It disallows the case 0 but still allows cases 1 and 2.
1. Case 1 can be disabled if `decltype(begin(const_a))` is constructible from `decltype(begin(a))`. 
2. In order to suppress Case 2, O (n) of comparisons may be needed.

```C++
// Case 0 No longer allowed
Kokkos::View<double*> a("A",N0);
auto res1 = KE::adjacent_difference("label", exespace(), a, a, args...);

// Case 1 still allowed
Kokkos::View<const double*> const_a(a);
auto res2 = KE::adjacent_difference("label", exespace(), const_a, a, args...);

// Case 2 still allowed (element b (1, 1) overlaps)
Kokkos::View<double**> b("B",N0, N1);
auto sub_b0 = Kokkos::subview(b, 0, Kokkos::pair<int, int>(1, 5) );
auto sub_b1 = Kokkos::subview(b, Kokkos::pair<int, int>(0, 4), 1 );
auto res3 = KE::adjacent_difference("label", exespace(), sub_b0, sub_b1, args...);
```

### CODE REVIEW

File: algorithms/src/std_algorithms/impl/Kokkos_Constraints.hpp [hunk 1]
```diff
@@ -215,6 +215,23 @@ KOKKOS_INLINE_FUNCTION void expect_valid_range(IteratorType first,
...
+// Check if iterators are overlapped
+//
+template <typename IteratorType1, typename IteratorType2>
+KOKKOS_INLINE_FUNCTION void expect_no_overlap(IteratorType1 first,
+                                              IteratorType1 last,
+                                              IteratorType2 s_first,
+                                              IteratorType2 s_last) {
+  if constexpr (std::is_constructible_v<IteratorType2, IteratorType1>) {
+    IteratorType1 s_first1(s_first), s_last1(s_last);
+    KOKKOS_EXPECTS(first < s_first1 && s_last1 < last);
```
Comment (jbigot) [inline algorithms/src/std_algorithms/impl/Kokkos_Constraints.hpp:228]: don't you want to check instead:
```
( first > s_last1 ) || ( last < s_first1 )
```
?

Comment (yasahi-hpc) [reply algorithms/src/std_algorithms/impl/Kokkos_Constraints.hpp]: That is better. I fixed accordingly

File: algorithms/src/std_algorithms/impl/Kokkos_Constraints.hpp [hunk 2]
```diff
@@ -215,6 +215,28 @@ KOKKOS_INLINE_FUNCTION void expect_valid_range(IteratorType first,
...
+// Check if iterators are overlapped
+//
+template <typename IteratorType1, typename IteratorType2>
+KOKKOS_INLINE_FUNCTION void expect_no_overlap(IteratorType1 first,
+                                              IteratorType1 last,
+                                              IteratorType2 s_first,
+                                              IteratorType2 s_last) {
+  if constexpr (std::is_constructible_v<IteratorType2, IteratorType1>) {
+    IteratorType1 s_first1(s_first), s_last1(s_last);
+    KOKKOS_EXPECTS(first > s_last1 || last < s_last1);
```
Comment (masterleinad) [inline algorithms/src/std_algorithms/impl/Kokkos_Constraints.hpp:228]:
```suggestion
    KOKKOS_EXPECTS(first > s_last1 || last < s_first1);
```

File: algorithms/src/std_algorithms/impl/Kokkos_Constraints.hpp [hunk 3]
```diff
@@ -215,6 +215,28 @@ KOKKOS_INLINE_FUNCTION void expect_valid_range(IteratorType first,
...
 }
 
+//
+// Check if iterators are overlapped
+//
+template <typename IteratorType1, typename IteratorType2>
+KOKKOS_INLINE_FUNCTION void expect_no_overlap(IteratorType1 first,
+                                              IteratorType1 last,
+                                              IteratorType2 s_first,
+                                              IteratorType2 s_last) {
```
Comment (masterleinad) [inline algorithms/src/std_algorithms/impl/Kokkos_Constraints.hpp:225]:
```suggestion
KOKKOS_INLINE_FUNCTION void expect_no_overlap([[maybe_unused]] IteratorType1 first,
                                              [[maybe_unused]] IteratorType1 last,
                                              [[maybe_unused]] IteratorType2 s_first,
                                              [[maybe_unused]] IteratorType2 s_last) {
```

File: algorithms/src/std_algorithms/impl/Kokkos_Constraints.hpp (hunk 2 above)
Comment (masterleinad) [reply algorithms/src/std_algorithms/impl/Kokkos_Constraints.hpp:228]: I was imagining a scenario where you could have iterators of the same type with the same stride but different starting pointers so that they don't overlap. For example, the location in memory would be alternating between the first iterator and the second iterator.

Comment (masterleinad) [reply algorithms/src/std_algorithms/impl/Kokkos_Constraints.hpp:228]: I would only try to detect overlapping memory for 
- View types with stride 1
- raw pointers
- std::contiguous_iterators

**Comment by crtrott** [comment]
Not sure what the cases are, but I guess the thing this would now "wrongly" complain about is two layout stride views with offset 1 between them and stride 2? Do we care?

**Comment by crtrott** [comment]
otherwise looks good.

**Comment by yasahi-hpc** [comment]
That is true. We can create some valid (non-overlapping) cases with layout stride views, which do not satisfy this check. If there is a way to check that in a reasonable cost (say O (1)), it is certainly preferable to add that test. Maybe we can do some integer problem?

**Comment by yasahi-hpc** [comment]
So, it now suppresses "maybe overlapping" cases for safety.

**Comment by masterleinad** [comment]
> That is true. We can create some valid (non-overlapping) cases with layout stride views, which do not satisfy this check. If there is a way to check that in a reasonable cost (say O (1)), it is certainly preferable to add that test. Maybe we can do some integer problem?

See https://github.com/kokkos/kokkos/pull/6922#discussion_r1555806423. I would just test specific types.

File: algorithms/src/std_algorithms/impl/Kokkos_Constraints.hpp (hunk 2 above)
Comment (jbigot) [reply algorithms/src/std_algorithms/impl/Kokkos_Constraints.hpp]: I think you can check for all `Kokkos::view::iterator` in case the referenced view is the same, even with non unit stride. This would case the most common case, wouldn't it?

Comment (yasahi-hpc) [reply algorithms/src/std_algorithms/impl/Kokkos_Constraints.hpp]: We need to add a method to `Kokkos::iterator` to compare internal views?

Comment (yasahi-hpc) [reply algorithms/src/std_algorithms/impl/Kokkos_Constraints.hpp]: That is nice. So the check would be something like this? (assuming the View access operator returns a reference)

```C++
auto next_first = first;
auto stride  = &*(++next_first) - &*first;
if constexpr (std::is_constructible_v<IteratorType2, IteratorType1>) {
  IteratorType1 s_first1(s_first), s_last1(s_last);
  auto first_diff = &*(first) - &*(s_first1);
  bool is_no_overlap = first_diff % stride;
  KOKKOS_EXPECTS(first > s_last1 || last < s_first1 || is_no_overlap);
}
```

**Comment by masterleinad** [comment]
You'll have to rebase on top of `develop`.

File: algorithms/src/std_algorithms/impl/Kokkos_AdjacentDifference.hpp [hunk 4]
```diff
@@ -82,9 +82,17 @@ OutputIteratorType adjacent_difference_exespace_impl(
...
   }
 
-  // run
+  // ranges shall not overlap
   const auto num_elements =
       Kokkos::Experimental::distance(first_from, last_from);
+  auto last_dest = first_dest + num_elements;
+  // Iterators must be accessed from Execution space
+  ::Kokkos::parallel_for(
+      "Check", RangePolicy<ExecutionSpace>(ex, 0, 1), KOKKOS_LAMBDA(int) {
```
Comment (masterleinad) [inline algorithms/src/std_algorithms/impl/Kokkos_AdjacentDifference.hpp:91]:
```suggestion
      "Kokkos::adjacent_difference::check_no_overlap", RangePolicy<ExecutionSpace>(ex, 0, 1), KOKKOS_LAMBDA(int) {
```

File: algorithms/src/std_algorithms/impl/Kokkos_AdjacentDifference.hpp [hunk 5]
```diff
@@ -82,9 +82,17 @@ OutputIteratorType adjacent_difference_exespace_impl(
     return first_dest;
   }
 
-  // run
+  // ranges shall not overlap
```
Comment (masterleinad) [inline algorithms/src/std_algorithms/impl/Kokkos_AdjacentDifference.hpp:85]:
```suggestion
  // check for overlapping iterators
```

File: algorithms/src/std_algorithms/impl/Kokkos_AdjacentDifference.hpp [hunk 6]
```diff
@@ -82,9 +82,17 @@ OutputIteratorType adjacent_difference_exespace_impl(
...
   const auto num_elements =
       Kokkos::Experimental::distance(first_from, last_from);
+  auto last_dest = first_dest + num_elements;
+  // Iterators must be accessed from Execution space
+  ::Kokkos::parallel_for(
+      "Check", RangePolicy<ExecutionSpace>(ex, 0, 1), KOKKOS_LAMBDA(int) {
+        Impl::expect_no_overlap(first_from, last_from, first_dest, last_dest);
+      });
```
Comment (masterleinad) [inline algorithms/src/std_algorithms/impl/Kokkos_AdjacentDifference.hpp:93]:
```suggestion
#ifdef KOKKOS_ENABLE_DEBUG
  ::Kokkos::parallel_for(
      "Check", RangePolicy<ExecutionSpace>(ex, 0, 1), KOKKOS_LAMBDA(int) {
        Impl::expect_no_overlap(first_from, last_from, first_dest, last_dest);
      });
#endif
```
so we don't have to always pay for the launch overhead for another kernel.

File: algorithms/src/std_algorithms/impl/Kokkos_Constraints.hpp [hunk 7]
```diff
@@ -215,6 +230,37 @@ KOKKOS_INLINE_FUNCTION void expect_valid_range(IteratorType first,
...
+KOKKOS_INLINE_FUNCTION void expect_no_overlap(
+    [[maybe_unused]] IteratorType1 first, [[maybe_unused]] IteratorType1 last,
+    [[maybe_unused]] IteratorType2 s_first,
+    [[maybe_unused]] IteratorType2 s_last) {
+  if constexpr (is_kokkos_iterator_v<IteratorType1> &&
+                is_kokkos_iterator_v<IteratorType2>) {
+    if constexpr (std::is_constructible_v<IteratorType2, IteratorType1>) {
+      IteratorType2 first2(first), last2(last);
+      IteratorType2 next_first2           = first2;
+      ptrdiff_t stride                    = &*(++next_first2) - &*first2;
```
Comment (masterleinad) [inline algorithms/src/std_algorithms/impl/Kokkos_Constraints.hpp:246]: Instead, we could avoid executing this in the correct space if we allow to retrieve the View from the iterator.

File: algorithms/src/std_algorithms/impl/Kokkos_AdjacentDifference.hpp (hunk 6 above)
Comment (yasahi-hpc) [reply algorithms/src/std_algorithms/impl/Kokkos_AdjacentDifference.hpp]: That is true. I also add this guard to the team level, since this check performs some computations

File: algorithms/src/std_algorithms/impl/Kokkos_AdjacentDifference.hpp (hunk 4 above)
Comment (yasahi-hpc) [reply algorithms/src/std_algorithms/impl/Kokkos_AdjacentDifference.hpp]: Sure

**Comment by dalg24** [comment]
Current failures are clearly unrelated (previous OpenACC issue, OpenMPTarget compile error that is resolved in develop, and other timeouts)

File: algorithms/src/std_algorithms/impl/Kokkos_RandomAccessIterator.hpp [hunk 8]
```diff
@@ -184,6 +184,13 @@ class RandomAccessIterator< ::Kokkos::View<DataType, Args...> > {
   KOKKOS_FUNCTION
   reference operator*() const { return m_view(m_current_index); }
 
+  KOKKOS_FUNCTION
+  auto view() const {
```
Comment (dalg24) [inline algorithms/src/std_algorithms/impl/Kokkos_RandomAccessIterator.hpp:188]: This is a bad name.  One could expect it returns `m_view`.

**Review by dalg24 — CHANGES_REQUESTED** [review]
Tests are missing

**Comment by yasahi-hpc** [comment]
> Tests are missing

Sure. I will add tests for `expect_no_overlap`.

File: algorithms/src/std_algorithms/impl/Kokkos_RandomAccessIterator.hpp (hunk 8 above)
Comment (yasahi-hpc) [reply algorithms/src/std_algorithms/impl/Kokkos_RandomAccessIterator.hpp:188]: Do you have some recommendation? 
Maybe better to suppress this method and do a check with`operator*()` alone?

Comment (masterleinad) [reply algorithms/src/std_algorithms/impl/Kokkos_RandomAccessIterator.hpp:188]: You could keep it returning `m_view` and only use it here for obtaining the stride.

Comment (yasahi-hpc) [reply algorithms/src/std_algorithms/impl/Kokkos_RandomAccessIterator.hpp]: Sure. I have updated accordingly.

File: algorithms/src/std_algorithms/impl/Kokkos_Constraints.hpp [hunk 9]
```diff
@@ -215,6 +230,40 @@ KOKKOS_INLINE_FUNCTION void expect_valid_range(IteratorType first,
...
 }
 
+//
+// Check if kokkos iterators are overlapping
+//
+template <typename IteratorType1, typename IteratorType2>
+KOKKOS_INLINE_FUNCTION void expect_no_overlap(
+    [[maybe_unused]] IteratorType1 first, [[maybe_unused]] IteratorType1 last,
+    [[maybe_unused]] IteratorType2 s_first,
+    [[maybe_unused]] IteratorType2 s_last) {
```
Comment (dalg24) [inline algorithms/src/std_algorithms/impl/Kokkos_Constraints.hpp:240]: Do you mean to take `s_last` as argument rather than computing it with something like `advance(s_first, distance(first, last))`?

File: algorithms/unit_tests/TestStdAlgorithmsConstraints.cpp [hunk 10]
```diff
@@ -81,5 +81,122 @@ TEST(std_algorithms, is_admissible_to_std_algorithms) {
...
+      "std-algo-test-2d-contiguous-view-strided", layout2d};
+  auto sub_strided_view_1d_0 = Kokkos::subview(strided_view_2d, 0, Kokkos::ALL);
+  auto sub_strided_view_1d_1 = Kokkos::subview(strided_view_2d, 1, Kokkos::ALL);
+  auto sub_first_st0 = KE::begin(sub_strided_view_1d_0);  // 0, 6, 12, ...
+  auto sub_last_st0  = sub_first_st0 + sub_strided_view_1d_0.extent(0);
+  auto sub_first_st1 = KE::begin(sub_strided_view_1d_1);  // 1, 7, 13, ...
+  auto sub_last_st1  = sub_first_st1 + sub_strided_view_1d_1.extent(0);
+
+  KE::Impl::expect_no_overlap(sub_first_st0, sub_last_st0, sub_first_st1,
+                              sub_last_st1);
```
Comment (dalg24) [inline algorithms/unit_tests/TestStdAlgorithmsConstraints.cpp:196]: The non-overlapping case could be run even when the preconditions are not checked.
You could wrapt the check in `TEST_NO_THROW()`.
That way you don't need the dummy passing assertion below.

File: algorithms/unit_tests/TestStdAlgorithmsConstraints.cpp [hunk 11]
```diff
@@ -81,5 +81,122 @@ TEST(std_algorithms, is_admissible_to_std_algorithms) {
...
+  [[maybe_unused]] dyn_view_1d_t dynamic_view_1d{
+      "std-algo-test-1d-contiguous-view-dynamic", extent0};
+
+  using strided_view_1d_t = Kokkos::View<value_type*, Kokkos::LayoutStride>;
+  Kokkos::LayoutStride layout1d{extent0, 2};
+  [[maybe_unused]] strided_view_1d_t strided_view_1d{
+      "std-algo-test-1d-strided-view", layout1d};
+
+#if !defined(NDEBUG) || defined(KOKKOS_ENFORCE_CONTRACTS) || \
+    defined(KOKKOS_ENABLE_DEBUG)
```
Comment (dalg24) [inline algorithms/unit_tests/TestStdAlgorithmsConstraints.cpp:107]: I suspect that guard is not right.
You guarded the precondition check with `#ifdef KOKKOS_ENABLE_DEBUG` so it probably should be something like
```suggestion
#if defined(KOKKOS_ENABLE_DEBUG) && !defined(NDEBUG)
```

File: algorithms/src/std_algorithms/impl/Kokkos_Constraints.hpp (hunk 9 above)
Comment (yasahi-hpc) [reply algorithms/src/std_algorithms/impl/Kokkos_Constraints.hpp:240]: That is true. We no longer need `s_last`. I will fix that.

File: algorithms/unit_tests/TestStdAlgorithmsConstraints.cpp (hunk 10 above)
Comment (yasahi-hpc) [reply algorithms/unit_tests/TestStdAlgorithmsConstraints.cpp:196]: For these cases, checks are made to confirm no-overlapping. 
Sure, I will wrap them with `TEST_NO_THROW` and remove the last `EXPECT_TRUE(true)`

File: algorithms/unit_tests/TestStdAlgorithmsConstraints.cpp [hunk 12]
```diff
@@ -81,5 +81,114 @@ TEST(std_algorithms, is_admissible_to_std_algorithms) {
...
+  using dyn_view_1d_t = Kokkos::View<value_type*>;
+  [[maybe_unused]] dyn_view_1d_t dynamic_view_1d{
+      "std-algo-test-1d-contiguous-view-dynamic", extent0};
+
+  using strided_view_1d_t = Kokkos::View<value_type*, Kokkos::LayoutStride>;
+  Kokkos::LayoutStride layout1d{extent0, 2};
+  strided_view_1d_t strided_view_1d{"std-algo-test-1d-strided-view", layout1d};
+
+// Overlapping because iterators are identical
+#if defined(KOKKOS_ENABLE_DEBUG) && !defined(NDEBUG)
```
[the remark this answers is not in the document]
Comment (yasahi-hpc) [reply algorithms/unit_tests/TestStdAlgorithmsConstraints.cpp:106]: I will do that way after this one. Sorry for inconvenience.

[the remark this answers is not in the document]
Comment (yasahi-hpc) [reply algorithms/unit_tests/TestStdAlgorithmsConstraints.cpp]: @dalg24 Fixed accordingly. Also made a minor fix for comments

**Review by masterleinad — APPROVED** [review]

**Comment by dalg24** [comment]
Ignoring the `CUDA-11.6-NVCC-DEBUG` that is running really slowly.

**Comment by ndellingwood** [comment]
Should this have a bug fix entry to the 4.4 changelog? Looks like a fixes an issue from 4.3 (or earlier)?

**Comment by dalg24** [comment]
> Should this have a bug fix entry to the 4.4 changelog? Looks like a fixes an issue from 4.3 (or earlier)?

It's not a bug fix, it improves the QOI, diagnose a precondition violation in debug mode. Yuuichi please mention this as a general enhancement.

**Comment by yasahi-hpc** [comment]
Done

> Should this have a bug fix entry to the 4.4 changelog? Looks like a fixes an issue from 4.3 (or earlier)?

At first I thought it was a bug, but in the end, it is recognized as an improvement as Damien said. (See #6890 for discussion)
