### PR TITLE
Fix and test with -fsanitize=undefined in GitHub CI

### LINKED ISSUE #7086: Undefined Behavior sanitizer reports problems
Enabling the `Serial` and `OpenMP` backend in a build using `-fsanitize=undefined` with `clang-18.1.5` reports
```
/tmp/kokkos/containers/unit_tests/TestVector.hpp:210:36: runtime error: signed integer overflow: 18647684 * -6116 cannot be represented in type 'int'
/tmp/kokkos/core/src/../../tpls/desul/include/desul/atomics/Lock_Based_Fetch_Op_Host.hpp:37:18: runtime error: load of value 4, which is not a valid value for type 'bool'
/tmp/kokkos/core/src/../../tpls/desul/include/desul/atomics/Operator_Function_Objects.hpp:132:17: runtime error: left shift of negative value -5
/tmp/kokkos/core/src/Kokkos_ScratchSpace.hpp:151:45: runtime error: subtraction of unsigned offset from 0x000000002840 overflowed to 0x000000002c40
/tmp/kokkos/core/src/OpenMP/Kokkos_OpenMP_Task.hpp:338:13: runtime error: call to function Kokkos::Impl::Task<Kokkos::BasicTaskScheduler<Kokkos::OpenMP, Kokkos::Impl::TaskQueue<Kokkos::OpenMP, Kokkos::HostSpace>>, void, TestTaskScheduler::TestTaskTeam<Kokkos::BasicTaskScheduler<Kokkos::OpenMP, Kokkos::Impl::TaskQueue<Kokkos::OpenMP, Kokkos::HostSpace>>>>::apply(Kokkos::Impl::TaskBase*, void*) through pointer to incorrect function type 'void (*)(Kokkos::Impl::TaskBase *, void *)'
/tmp/kokkos/core/src/impl/Kokkos_HostThreadTeam.hpp:109:54: runtime error: applying non-zero offset 9216 to null pointer
/tmp/kokkos/core/src/impl/Kokkos_HostThreadTeam.hpp:134:47: runtime error: applying non-zero offset 9216 to null pointer
/tmp/kokkos/core/src/impl/Kokkos_HostThreadTeam.hpp:274:27: runtime error: applying non-zero offset 10304 to null pointer
/tmp/kokkos/core/src/impl/Kokkos_Profiling.cpp:295:5: runtime error: call to function kokkosp_allocate_data through pointer to incorrect function type 'void (*)(Kokkos_Profiling_SpaceHandle, const char *, const void *, unsigned long long)'
/tmp/kokkos/core/src/impl/Kokkos_Profiling.cpp:295:5: runtime error: call to function kokkosp_begin_deep_copy through pointer to incorrect function type 'void (*)(Kokkos_Profiling_SpaceHandle, const char *, const void *, Kokkos_Profiling_SpaceHandle, const char *, const void *, unsigned long long)'
/tmp/kokkos/core/src/impl/Kokkos_SharedAlloc.cpp:268:5: runtime error: call to function void Kokkos::Impl::(anonymous namespace)::deallocate<Kokkos::HostSpace, Kokkos::Impl::ViewValueFunctor<Kokkos::Device<Kokkos::OpenMP, Kokkos::HostSpace>, double, true>>(Kokkos::Impl::SharedAllocationRecord<void, void>*) through pointer to incorrect function type 'void (*)(Kokkos::Impl::SharedAllocationRecord<void, void> *)'
/tmp/kokkos/core/src/impl/Kokkos_SharedAlloc.cpp:268:5: runtime error: call to function void Kokkos::Impl::(anonymous namespace)::deallocate<Kokkos::HostSpace, Kokkos::Impl::ViewValueFunctor<Kokkos::Device<Kokkos::OpenMP, Kokkos::HostSpace>, int, true>>(Kokkos::Impl::SharedAllocationRecord<void, void>*) through pointer to incorrect function type 'void (*)(Kokkos::Impl::SharedAllocationRecord<void, void> *)'
/tmp/kokkos/core/src/impl/Kokkos_SharedAlloc.cpp:268:5: runtime error: call to function void Kokkos::Impl::(anonymous namespace)::deallocate<Kokkos::HostSpace, Kokkos::Impl::ViewValueFunctor<Kokkos::Device<Kokkos::Serial, Kokkos::HostSpace>, Kokkos::complex<float>, false>>(Kokkos::Impl::SharedAllocationRecord<void, void>*) through pointer to incorrect function type 'void (*)(Kokkos::Impl::SharedAllocationRecord<void, void> *)'
/tmp/kokkos/core/src/impl/Kokkos_SharedAlloc.cpp:268:5: runtime error: call to function void Kokkos::Impl::(anonymous namespace)::deallocate<Kokkos::HostSpace, Kokkos::Impl::ViewValueFunctor<Kokkos::Device<Kokkos::Serial, Kokkos::HostSpace>, int, true>>(Kokkos::Impl::SharedAllocationRecord<void, void>*) through pointer to incorrect function type 'void (*)(Kokkos::Impl::SharedAllocationRecord<void, void> *)'
/tmp/kokkos/core/unit_test/TestAtomicOperations.hpp:245:16: runtime error: left shift of negative value -5
/tmp/kokkos/simd/src/Kokkos_SIMD_Scalar.hpp:176:29: runtime error: left shift of negative value -1
/tmp/kokkos/simd/unit_tests/include/SIMDTesting_Ops.hpp:206:14: runtime error: left shift of negative value -1
/tmp/kokkos/simd/unit_tests/include/SIMDTesting_Ops.hpp:210:14: runtime error: left shift of negative value -1
```
(stripping information for which test these belong to and only reporting unique errors).

### PR DESCRIPTION
**Pull request by masterleinad**
Fixes #7086. The respective `desul` changes are in desul/desul#128.

- Fix signed overflow in tests
- Make sure to use C-linkage for profiling C-interface
- Prefer inline over anonymous namespace in Kokkos_SharedAlloc.hpp
- Don't test left shift for negative values 
- Fix using uninitialized memory in generic HOST_OR_DEVICE##_atomic_store
- avoid offsetting nullptr
- fix bug in atomic_max/min tests

### CODE REVIEW

File: simd/unit_tests/include/TestSIMD_ShiftOps.hpp [hunk 1]
```diff
@@ -131,8 +131,6 @@ inline void host_check_shift_ops() {
         for (std::size_t i = 0; i < width; ++i) test_vals[i] *= -1;
         host_check_shift_op_all_loaders<Abi>(shift_right(), test_vals, shift_by,
                                              num_cases);
-        host_check_shift_op_all_loaders<Abi>(shift_left(), test_vals, shift_by,
-                                             num_cases);
```
Comment (crtrott) [inline simd/unit_tests/include/TestSIMD_ShiftOps.hpp:135]: What is up with this?

Comment (masterleinad) [reply simd/unit_tests/include/TestSIMD_ShiftOps.hpp:135]: Left-shifting negative values is undefined behavior.

Comment (crtrott) [reply simd/unit_tests/include/TestSIMD_ShiftOps.hpp:135]: yeah makes sense just looked it up myself.

**Comment by crtrott** [comment]
Is this ready for review, I glanced over it and I think I am good with it.

**Comment by masterleinad** [comment]
> Is this ready for review, I glanced over it and I think I am good with it.

We just need the `desul` pull request to be merged. At the moment, the comments are slightly different.

File: containers/unit_tests/TestVector.hpp [hunk 2]
```diff
@@ -207,6 +207,7 @@ struct test_vector_combinations {
     Scalar test3 = 0;
     for (unsigned int i = 0; i < a.size(); i++) test3 += a[i];
 
+    std::cout << test1 << ' ' << test2 << ' ' << test3 << '\n';
```
Comment (masterleinad) [inline containers/unit_tests/TestVector.hpp:210]:
```suggestion
```

File: containers/unit_tests/TestVector.hpp [hunk 3]
```diff
@@ -233,7 +234,7 @@ void test_vector_allocate(unsigned int size) {
 TEST(TEST_CATEGORY, vector_combination) {
   test_vector_allocate<int, TEST_EXECSPACE>(10);
   test_vector_combinations<int, TEST_EXECSPACE>(10);
-  test_vector_combinations<int, TEST_EXECSPACE>(3057);
+  test_vector_combinations<long, TEST_EXECSPACE>(3057);
```
Comment (crtrott) [inline containers/unit_tests/TestVector.hpp:237]:
```suggestion
  test_vector_combinations<long long int, TEST_EXECSPACE>(3057);
```

Since on Windows long could be 32 bit

**Review by crtrott — APPROVED** [review]

**Comment by crtrott** [comment]
The desul version was merged.

**Review by Rombur — APPROVED** [review]

File: .github/workflows/continuous-integration-workflow.yml [hunk 4]
```diff
@@ -39,7 +39,8 @@ jobs:
             backend: 'OPENMP'
           - distro: 'ubuntu:intel'
             cxx: 'icpx'
-            cxx_extra_flags: '-fp-model=precise -Wno-pass-failed'
+            cxx_extra_flags: '-fp-model=precise -Wno-pass-failed -fsanitize=address,undefined -fno-sanitize=function -fno-sanitize-recover=all'
```
Comment (dalg24) [inline .github/workflows/continuous-integration-workflow.yml:42]: What are these `-fno-sanitize=function -fno-sanitize-recover=all` flags?

File: containers/unit_tests/TestVector.hpp [hunk 5]
```diff
@@ -233,7 +233,7 @@ void test_vector_allocate(unsigned int size) {
 TEST(TEST_CATEGORY, vector_combination) {
   test_vector_allocate<int, TEST_EXECSPACE>(10);
   test_vector_combinations<int, TEST_EXECSPACE>(10);
-  test_vector_combinations<int, TEST_EXECSPACE>(3057);
+  test_vector_combinations<long long int, TEST_EXECSPACE>(3057);
```
Comment (dalg24) [inline containers/unit_tests/TestVector.hpp:236]: Why was that change needed?

File: core/perf_test/test_atomic.cpp [hunk 6]
```diff
@@ -390,12 +390,11 @@ static void Test_Atomic(benchmark::State& state) {
 
 static constexpr int LOOP = 100'000;
 
-BENCHMARK(Test_Atomic<int>)->Arg(LOOP)->Iterations(10);
+BENCHMARK(Test_Atomic<int>)->Arg(30'000)->Iterations(10);
```
Comment (dalg24) [inline core/perf_test/test_atomic.cpp:393]: What was the issue when using `LOOP`?

File: core/src/impl/Kokkos_SharedAlloc.hpp [hunk 7]
```diff
@@ -385,11 +385,9 @@ SharedAllocationRecord<void, void>
   template class Kokkos::Impl::HostInaccessibleSharedAllocationRecordCommon<           \
       MEMORY_SPACE>
 
-namespace {
-
 /* Taking the address of this function so make sure it is unique */
 template <class MemorySpace, class DestroyFunctor>
-void deallocate(SharedAllocationRecord<void, void>* record_ptr) {
+inline void deallocate(SharedAllocationRecord<void, void>* record_ptr) {
```
Comment (dalg24) [inline core/src/impl/Kokkos_SharedAlloc.hpp:390]: Any idea why we had the anonymous namespace?
The `inline` specifier is not necessary here.  (Not blocking but I would like to understand the change)

**Review by dalg24 — DISMISSED** [review]
Many unrelated changes and I can't understand all at this time

File: .github/workflows/continuous-integration-workflow.yml (hunk 4 above)
Comment (masterleinad) [reply .github/workflows/continuous-integration-workflow.yml:42]: We get more warnings when checking function signatures, mostly due to our tools interface since C- and C++- function pointers are technically different types. This pull request fixes a bunch of them but I didn't see a way to address all of them and rather decided to disable this particular check. By default the undefined behavior sanitizer doesn't error out but just warns. `-fno-sanitize-recover=all` makes sure that we actually error out.

File: core/src/impl/Kokkos_SharedAlloc.hpp (hunk 7 above)
Comment (masterleinad) [reply core/src/impl/Kokkos_SharedAlloc.hpp:390]: I left the `inline` here to signal intent that we only want one symbol generated (since we are later taking the address of this function). I don't know why an `anonymous` namespace was used instead (generating one symbol per compilation unit). The `function` sanitizer complained here.

Comment (dalg24) [reply core/src/impl/Kokkos_SharedAlloc.hpp:390]: but you disabled the "function" diagnostic in the end so why do we want this resolved here?

Comment (masterleinad) [reply core/src/impl/Kokkos_SharedAlloc.hpp:390]: This was one fix I could make (even if we won't diagnose it again with the current set of checks).

File: core/perf_test/test_atomic.cpp (hunk 6 above)
Comment (masterleinad) [reply core/perf_test/test_atomic.cpp:393]:
```
23: /tmp/kokkos/core/perf_test/test_atomic.cpp:309:12: runtime error: signed integer overflow: 2147450880 + 65536 cannot be represented in type 'int'
23: SUMMARY: UndefinedBehaviorSanitizer: undefined-behavior /tmp/kokkos/core/perf_test/test_atomic.cpp:309:12 
```
