### PR TITLE
fix incorrect offset in cuda parallel scan for < 4 byte types

### LINKED ISSUE #5545: Cuda Parallel Scan has incorrect offset for types smaller than `size_type`
**Describe the bug**
https://github.com/kokkos/kokkos/blob/0fb8b8ab8bd01cfc7dd27da37f20deb0904afe30/core/src/Cuda/Kokkos_Cuda_Parallel_Range.hpp#L542-L544

This value is 0 if the size of `value_type` is < 4 bytes (`sizeof(size_type)`)

This is the underlying cause for https://github.com/kokkos/kokkos/issues/5513 and partially fixes the issue

### PR DESCRIPTION
**Pull request by nmm0**
Fixes #5545

### CODE REVIEW

**Comment by nmm0** [comment]
@cwsmith this should solve the issue though there is additional work to be done in ensuring the correct type is used for the internal parallel scan when using `Kokkos::Experimental::inclusive_scan"

File: core/src/Cuda/Kokkos_Cuda_Parallel_Range.hpp [hunk 1]
```diff
@@ -1026,7 +1061,8 @@ class ParallelScanWithTotal<FunctorType, Kokkos::RangePolicy<Traits...>,
         if (!m_result_ptr_device_accessible)
           DeepCopy<HostSpace, CudaSpace, Cuda>(
               m_policy.space(), m_result_ptr,
-              m_scratch_space + (grid_x - 1) * size / sizeof(int), size);
```
Comment (nmm0) [inline core/src/Cuda/Kokkos_Cuda_Parallel_Range.hpp:1029]: I don't actually know where `int` came from in the original, but `sizeof(word_size_type)` is important here otherwise the result will be incorrect

**Review by PhilMiller — COMMENTED** [review]
Does any corresponding change need to be done for HIP?

**Comment by nmm0** [comment]
> Does any corresponding change need to be done for HIP?

From looking at the code it certainly appears so -- in fact the logic bug (size < `HIP::size_type`) appears to also be present in HIP's reduce

File: core/src/Cuda/Kokkos_Cuda_Parallel_Range.hpp [hunk 2]
```diff
@@ -463,8 +463,24 @@ class ParallelScan<FunctorType, Kokkos::RangePolicy<Traits...>, Kokkos::Cuda> {
...
+  // word_size_type is used to determine the word count, shared memory buffer
+  // size, and global memory buffer size before the scan is performed.
+  // Within the reduction, the word count is recomputed based on word_size_type
+  // and when calculating indexes into the shared/global memory buffers for
+  // performing the reduction, word_size_type is used again.
+  // For scalars > 4 bytes in size, indexing into shared/global memory relies
+  // on the block and grid dimensions to ensure that we index at the correct
+  // offset rather than at every 4 byte word; such that, when the join is
+  // performed, we have the correct data that was copied over in chunks of 4
+  // bytes.
```
Comment (masterleinad) [inline core/src/Cuda/Kokkos_Cuda_Parallel_Range.hpp:479]:
```suggestion
  // Conditionally set word_size_type to int16_t or int8_t if value_type is
  // smaller than int32_t (Kokkos::Cuda::size_type)
  // word_size_type is used to determine the word count, shared memory buffer
  // size, and global memory buffer size before the scan is performed.
  // Within the scan, the word count is recomputed based on word_size_type
  // and when calculating indexes into the shared/global memory buffers for
  // performing the scan, word_size_type is used again.
  // For scalars > 4 bytes in size, indexing into shared/global memory relies
  // on the block and grid dimensions to ensure that we index at the correct
  // offset rather than at every 4 byte word; such that, when the join is
  // performed, we have the correct data that was copied over in chunks of 4
  // bytes.
```

File: core/src/Cuda/Kokkos_Cuda_Parallel_Range.hpp [hunk 3]
```diff
@@ -754,7 +772,22 @@ class ParallelScanWithTotal<FunctorType, Kokkos::RangePolicy<Traits...>,
...
+  // word_size_type is used to determine the word count, shared memory buffer
+  // size, and global memory buffer size before the reduction is performed.
+  // Within the reduction, the word count is recomputed based on word_size_type
+  // and when calculating indexes into the shared/global memory buffers for
+  // performing the reduction, word_size_type is used again.
+  // For scalars > 4 bytes in size, indexing into shared/global memory relies
+  // on the block and grid dimensions to ensure that we index at the correct
+  // offset rather than at every 4 byte word; such that, when the join is
+  // performed, we have the correct data that was copied over in chunks of 4
+  // bytes.
```
Comment (masterleinad) [inline core/src/Cuda/Kokkos_Cuda_Parallel_Range.hpp:786]:
```suggestion
  // Conditionally set word_size_type to int16_t or int8_t if value_type is
  // smaller than int32_t (Kokkos::Cuda::size_type)
  // word_size_type is used to determine the word count, shared memory buffer
  // size, and global memory buffer size before the scan is performed.
  // Within the scan, the word count is recomputed based on word_size_type
  // and when calculating indexes into the shared/global memory buffers for
  // performing the scan, word_size_type is used again.
  // For scalars > 4 bytes in size, indexing into shared/global memory relies
  // on the block and grid dimensions to ensure that we index at the correct
  // offset rather than at every 4 byte word; such that, when the join is
  // performed, we have the correct data that was copied over in chunks of 4
  // bytes.
```

**Comment by masterleinad** [comment]
I think we should make the same changes for `HIP`.

**Comment by nmm0** [comment]
> I think we should make the same changes for `HIP`.

Filed https://github.com/kokkos/kokkos/issues/5556

**Comment by crtrott** [comment]
Yeah lets get the HIP thing fixed here too, since the test doesn't pass anyway.

File: core/unit_test/TestScan.hpp [hunk 4]
```diff
@@ -170,11 +170,108 @@ struct TestScan {
...
+      if (update != static_cast<value_type>(i)) {
+        int fail = errors()++;
+
+        // Limit the amount of output
+        if (fail < 20) {
+          KOKKOS_IMPL_DO_NOT_USE_PRINTF(
+              "TestSmallSizeTypeScan(%d) = %ld != %ld\n", i,
+              static_cast<long>(update), static_cast<long>(i));
+        }
+      }
```
Comment (dalg24) [inline core/unit_test/TestScan.hpp:214]: Do not mix computation and verification.  Launch another kernel for that.

File: core/unit_test/TestScan.hpp [hunk 5]
```diff
@@ -170,11 +170,108 @@ struct TestScan {
...
+  TestSmallSizeTypeScan<TEST_EXECSPACE, std::int8_t>(5, false);
+  TestSmallSizeTypeScan<TEST_EXECSPACE, std::int8_t>(100, false);
+  TestSmallSizeTypeScan<TEST_EXECSPACE, std::int8_t>(
+      std::numeric_limits<std::int8_t>::max(), false);
+  TestSmallSizeTypeScan<TEST_EXECSPACE, std::int16_t>(0, false);
+  TestSmallSizeTypeScan<TEST_EXECSPACE, std::int16_t>(5, false);
+  TestSmallSizeTypeScan<TEST_EXECSPACE, std::int16_t>(10000, false);
+  TestSmallSizeTypeScan<TEST_EXECSPACE, std::int16_t>(
+      std::numeric_limits<std::int16_t>::max(), false);
+  TEST_EXECSPACE().fence();
```
Comment (dalg24) [inline core/unit_test/TestScan.hpp:262]: Why fence?

**Review by dalg24 — CHANGES_REQUESTED** [review]
Please beef up the description of the PR and relate it to #4156

File: core/unit_test/TestScan.hpp (hunk 5 above)
Comment (nmm0) [reply core/unit_test/TestScan.hpp:262]: That's what the existing test does, I tried to copy it as closely as possible. I can remove both fences though

File: core/unit_test/TestScan.hpp (hunk 4 above)
Comment (nmm0) [reply core/unit_test/TestScan.hpp:214]: Similarly, should I remove from the existing test?

**Comment by Rombur** [comment]
I have a patch that fixes the problem with HIP. How should we proceed?

**Comment by dalg24** [comment]
Please go ahead and push to this PR

File: core/src/HIP/Kokkos_HIP_ReduceScan.hpp [hunk 6]
```diff
@@ -390,13 +391,12 @@ __device__ void hip_intra_block_reduce_scan(
  *  Global reduce result is in the last threads' 'shared_data' location.
  */
 
-template <bool DoScan, class FunctorType>
+template <bool DoScan, class FunctorType, typename SizeType>
```
Comment (dalg24) [inline core/src/HIP/Kokkos_HIP_ReduceScan.hpp:394]: Do not mix `class` and `typename`.  Pick your poison.

File: core/unit_test/TestScan.hpp [hunk 7]
```diff
@@ -170,11 +170,108 @@ struct TestScan {
...
+    check_error(res, N, use_total);
+  }
+
+  KOKKOS_INLINE_FUNCTION
+  void operator()(int i, value_type& update, bool final) const {
+    const auto val = x(i);
+    if (final) {
+      x(i) = update;
+
+      // We should have a nice count from 0 to 1...
```
Comment (masterleinad) [inline core/unit_test/TestScan.hpp:204]:
```suggestion
      // We should have a nice count from 0 to N
```
?

File: core/unit_test/TestScan.hpp [hunk 8]
```diff
@@ -170,11 +170,108 @@ struct TestScan {
...
+              static_cast<long>(update), static_cast<long>(i));
+        }
+      }
+    }
+    update += val;
+  }
+
+  KOKKOS_INLINE_FUNCTION
+  void init(value_type& update) const { update = 0; }
+
```
Comment (masterleinad) [inline core/unit_test/TestScan.hpp:221]:
```suggestion
```

File: core/unit_test/TestScan.hpp [hunk 9]
```diff
@@ -170,11 +170,108 @@ struct TestScan {
...
   TestScan<TEST_EXECSPACE>::test_range(1, 1000);
   TestScan<TEST_EXECSPACE>(0);
   TestScan<TEST_EXECSPACE>(100000);
   TestScan<TEST_EXECSPACE>(10000000);
   TEST_EXECSPACE().fence();
 }
-}  // namespace Test
+
+TEST(TEST_CATEGORY, small_size_scan) {
+  TestSmallSizeTypeScan<TEST_EXECSPACE, std::int8_t>(0, false);
```
Comment (masterleinad) [inline core/unit_test/TestScan.hpp:252]: It's not intuitive to me to understand what the second parameter could do just by seeing these lines. Would you mind introducing another named variable to make this clear?

File: core/src/Cuda/Kokkos_Cuda_Parallel_Range.hpp [hunk 10]
```diff
@@ -463,8 +463,24 @@ class ParallelScan<FunctorType, Kokkos::RangePolicy<Traits...>, Kokkos::Cuda> {
  public:
   using pointer_type   = typename Analysis::pointer_type;
   using reference_type = typename Analysis::reference_type;
+  using value_type     = typename Analysis::value_type;
   using functor_type   = FunctorType;
-  using size_type      = Cuda::size_type;
```
Comment (dalg24) [inline core/src/Cuda/Kokkos_Cuda_Parallel_Range.hpp:467]: Nitpick: I would have kept that guy and not update the definitions of `m_scratch_flags` and `m_final` below.
Same comment in `ParallelScanWithTotal`.

File: core/unit_test/TestScan.hpp [hunk 11]
```diff
@@ -169,12 +170,31 @@ struct TestScan {
...
-  TestScan<TEST_EXECSPACE>::test_range(1, 1000);
-  TestScan<TEST_EXECSPACE>(0);
-  TestScan<TEST_EXECSPACE>(100000);
-  TestScan<TEST_EXECSPACE>(10000000);
+  constexpr auto imbalance_size = 1000;
+  TestScan<TEST_EXECSPACE, int64_t, imbalance_size>::test_range(1, 1000);
+  TestScan<TEST_EXECSPACE, int64_t, imbalance_size>(0);
+  TestScan<TEST_EXECSPACE, int64_t, imbalance_size>(100000);
+  TestScan<TEST_EXECSPACE, int64_t, imbalance_size>(10000000);
+  TEST_EXECSPACE().fence();
```
Comment (dalg24) [inline core/unit_test/TestScan.hpp:181]: Please drop these fences.  They are pointless.

**Review by dalg24 — APPROVED** [review]

File: core/unit_test/TestScan.hpp [hunk 12]
```diff
@@ -45,20 +45,21 @@
...
   Kokkos::View<int, Device, Kokkos::MemoryTraits<Kokkos::Atomic> > errors;
 
   KOKKOS_INLINE_FUNCTION
   void operator()(const int iwork, value_type& update,
                   const bool final_pass) const {
-    const value_type n         = iwork + 1;
-    const value_type imbalance = ((1000 <= n) && (0 == n % 1000)) ? 1000 : 0;
+    const value_type n = iwork + 1;
+    const value_type imbalance =
+        ((ImbalanceSz <= n) && (0 == n % ImbalanceSz)) ? ImbalanceSz : 0;
```
Comment (dalg24) [inline core/unit_test/TestScan.hpp:62]: HPX builds fails with
```
In file included from /home/runner/work/kokkos/kokkos/kokkos/build/core/unit_test/hpx/TestHPX_Scan.cpp:2:
[88](https://github.com/kokkos/kokkos/actions/runs/3341905420/jobs/5533579527#step:9:89)
/home/runner/work/kokkos/kokkos/kokkos/core/unit_test/TestScan.hpp:62:23: error: comparison of integers of different signs: 'unsigned long' and 'const (anonymous namespace)::TestScan<Kokkos::Experimental::HPX, long, 1000>::value_type' (aka 'const long') [-Werror,-Wsign-compare]
[89](https://github.com/kokkos/kokkos/actions/runs/3341905420/jobs/5533579527#step:9:90)
        ((ImbalanceSz <= n) && (0 == n % ImbalanceSz)) ? ImbalanceSz : 0;
[90](https://github.com/kokkos/kokkos/actions/runs/3341905420/jobs/5533579527#step:9:91)
          ~~~~~~~~~~~ ^  ~

File: core/unit_test/TestScan.hpp (hunk 9 above)
Comment (nmm0) [reply core/unit_test/TestScan.hpp]: removed this value, but did similarly with the new ImbalanceSz param

File: core/unit_test/TestScan.hpp (hunk 7 above)
Comment (nmm0) [reply core/unit_test/TestScan.hpp]: was removed when I combined the testing harasses

File: core/unit_test/TestScan.hpp (hunk 11 above)
Comment (nmm0) [reply core/unit_test/TestScan.hpp]: done

File: core/unit_test/TestScan.hpp [hunk 13]
```diff
@@ -45,20 +45,21 @@
...
   Kokkos::View<int, Device, Kokkos::MemoryTraits<Kokkos::Atomic> > errors;
 
   KOKKOS_INLINE_FUNCTION
   void operator()(const int iwork, value_type& update,
                   const bool final_pass) const {
-    const value_type n         = iwork + 1;
-    const value_type imbalance = ((1000 <= n) && (0 == n % 1000)) ? 1000 : 0;
+    const value_type n = iwork + 1;
+    const value_type imbalance =
+        ((ImbalanceSz <= n) && (value_type(0) == n % ImbalanceSz)) ? ImbalanceSz : value_type(0);
```
Comment (dalg24) [inline core/unit_test/TestScan.hpp:62]:
```suggestion
        ((ImbalanceSz <= n) && (value_type(0) == n % ImbalanceSz))
            ? ImbalanceSz
            : value_type(0);
```

**Comment by dalg24** [comment]
The HPX build is now passing.  On the ORNL Jenkins CI server, there is one (likely unrelated) CUDA timing-based failure which I am willing to ignore.
We need one more approval though.

**Review by masterleinad — APPROVED** [review]

File: core/src/Cuda/Kokkos_Cuda_Parallel_Range.hpp (hunk 10 above)
Comment (dalg24) [reply core/src/Cuda/Kokkos_Cuda_Parallel_Range.hpp:467]: I went ahead and applied the suggestion to reduce the diff and be consistent with the HIP backend

**Review by masterleinad — APPROVED** [review]
Still looks good to me.

File: core/src/Cuda/Kokkos_Cuda_Parallel_Range.hpp [hunk 14]
```diff
@@ -987,10 +1021,11 @@ class ParallelScanWithTotal<FunctorType, Kokkos::RangePolicy<Traits...>,
...
 
-      m_scratch_space = cuda_internal_scratch_space(
-          m_policy.space(), Analysis::value_size(m_functor) * grid_x);
-      m_scratch_flags =
-          cuda_internal_scratch_flags(m_policy.space(), sizeof(size_type) * 1);
+      m_scratch_space =
+          reinterpret_cast<word_size_type*>(cuda_internal_scratch_space(
+              m_policy.space(), Analysis::value_size(m_functor) * grid_x));
+      m_scratch_flags = cuda_internal_scratch_flags(
+          m_policy.space(), sizeof(Cuda::size_type) * 1);
```
Comment (ldh4) [inline core/src/Cuda/Kokkos_Cuda_Parallel_Range.hpp:1028]:
```suggestion
      m_scratch_flags =
          cuda_internal_scratch_flags(m_policy.space(), sizeof(size_type) * 1);
```

This change seems unnecessary. Doesn't change anything functionally, but I suggest reverting back to using `sizeof(size_type)` here to keep it consistent with other `[backend]_internal_scratch_flags` calls.

**Review by ldh4 — APPROVED** [review]
Looks good to me. Just nitpicking on one thing.

File: core/src/Cuda/Kokkos_Cuda_Parallel_Range.hpp (hunk 14 above)
Comment (dalg24) [reply core/src/Cuda/Kokkos_Cuda_Parallel_Range.hpp:1028]: Agreed.  I missed that one.  Will revert.
