### PR TITLE
Fix max scratch size calculation for level 0 of CUDA and HIP

### LINKED ISSUE #1811: Figure out the maximal number of elements in a shared memory view
I get the "Kokkos::Impl::ParallelFor< Cuda > insufficient shared memory" runtime error when trying to use TeamPolicy::scratch_size_max(0) / sizeof(int) to calculate the maximal number of element in a shared view. This is an example:
```
#include <Kokkos_Core.hpp>
#include <Kokkos_DualView.hpp>
using ExecutionSpace = Kokkos::DefaultExecutionSpace;
using namespace std;

template < class DualView >
void syncToHost(DualView&& data) {
  using MemorySpace = typename std::decay_t<DualView>::memory_space;
  using HostMirrorSpace = typename std::decay_t<DualView>::host_mirror_space;
  std::forward<DualView>(data).template modify<MemorySpace>();
  std::forward<DualView>(data).template sync<HostMirrorSpace>();
}

template < class DualView >
void syncToDevice(DualView&& data) {
  using MemorySpace = typename std::decay_t<DualView>::memory_space;
  using HostMirrorSpace = typename std::decay_t<DualView>::host_mirror_space;
  std::forward<DualView>(data).template modify<HostMirrorSpace>();
  std::forward<DualView>(data).template sync<MemorySpace>();
}

template < class T, class E >
struct F {
  using TeamPolicy = Kokkos::TeamPolicy<E>;
  using Team = typename TeamPolicy::member_type;
  using SharedSpace = typename E::scratch_memory_space;
  using UnmanagedTraits = Kokkos::MemoryTraits<Kokkos::Unmanaged>;
  using SharedView = Kokkos::View<T*,SharedSpace,UnmanagedTraits>;

  Kokkos::DualView<std::size_t,E> N_;

  F() : N_("N") 
  {
    N_.h_view() = TeamPolicy::scratch_size_max(0) / sizeof(T);
    syncToDevice(N_);
    printf("N = %10lu\n",N_.h_view());
  };

  KOKKOS_INLINE_FUNCTION 
  void operator()(const Team& team) const {
    SharedView a(team.team_scratch(0),N_.d_view());
    Kokkos::parallel_for(Kokkos::TeamThreadRange(team,a.extent(0)),
      [&](const int& i){
        a(i) = i;
      });
  }

  std::size_t shmemSize() const {
    return SharedView::shmem_size(N_.h_view());
  }

};


int main(int argc, char* argv[]) {
  Kokkos::initialize(argc,argv); {

  const std::size_t nTeams = 10;
  using Functor = F<int,ExecutionSpace>;
  using Policy = Functor::TeamPolicy;
  using Team = Functor::Team;
  Functor f{};
  printf("shmemSize = %10lu\n",f.shmemSize());
  const std::size_t teamSize = Policy(nTeams,Kokkos::AUTO).
    team_size_max(f,Kokkos::ParallelForTag{});
  auto policy = Policy(nTeams,teamSize).
    set_scratch_size(0,Kokkos::PerTeam(f.shmemSize())); 
  Kokkos::parallel_for(policy,f); 

  } Kokkos::finalize();
}
```

### PR DESCRIPTION
**Pull request by crtrott**
This takes a bit better into account the internal shared memory teams are using by default. It does not take into account static shared memory which teams may use for certain types of team level reductions. The amount of shared memory there depends on the `value_type` and thus can't be taken into account without handing over the functor. 

It does otherwise fix #1811

### CODE REVIEW

File: core/src/Cuda/Kokkos_Cuda_Parallel_Team.hpp [hunk 1]
```diff
@@ -47,6 +47,12 @@ extern bool show_warnings() noexcept;
 
 namespace Impl {
 
+// Cuda Teams use (team_size + 2)*sizeof(double) shared memory for team
+// reductions they also use one in64_t static shared memory for a shared ID
```
Comment (PhilMiller) [inline core/src/Cuda/Kokkos_Cuda_Parallel_Team.hpp:51]: int64_t

File: core/src/Cuda/Kokkos_Cuda_Parallel_Team.hpp [hunk 2]
```diff
@@ -47,6 +47,12 @@ extern bool show_warnings() noexcept;
...
+// Furthermore, they use additional scratch memory in some reduction scenarios,
+// which depend on the size of the value_type and is NOT captured here.
+constexpr size_t cuda_team_max_reserved_shared_mem = (1024 + 2) * 8 + 8;
```
Comment (PhilMiller) [inline core/src/Cuda/Kokkos_Cuda_Parallel_Team.hpp:54]: Why not use the `sizeof` expressions shown in the comments?

**Comment by PhilMiller** [comment]
This maybe leaves the question of whether we should provide a version that takes the functor for the case where it matters, and make sure the documentation points users to that.

File: core/src/Cuda/Kokkos_Cuda_Parallel_Team.hpp (hunk 2 above)
Comment (crtrott) [reply core/src/Cuda/Kokkos_Cuda_Parallel_Team.hpp:54]: Yeah I guess I could do that.

File: core/src/Cuda/Kokkos_Cuda_Parallel_Team.hpp [hunk 3]
```diff
@@ -47,6 +47,13 @@ extern bool show_warnings() noexcept;
 
 namespace Impl {
 
+// Cuda Teams use (team_size + 2)*sizeof(double) shared memory for team
+// reductions they also use one int64_t static shared memory for a shared ID
```
Comment (PhilMiller) [inline core/src/Cuda/Kokkos_Cuda_Parallel_Team.hpp:51]:
```suggestion
// reductions. They also use one int64_t in static shared memory for a shared ID.
```

File: core/src/Cuda/Kokkos_Cuda_Parallel_Team.hpp [hunk 4]
```diff
@@ -47,6 +47,13 @@ extern bool show_warnings() noexcept;
...
+// Furthermore, they use additional scratch memory in some reduction scenarios,
```
Comment (PhilMiller) [inline core/src/Cuda/Kokkos_Cuda_Parallel_Team.hpp:52]: Scans as well as reductions?

File: core/src/HIP/Kokkos_HIP_Parallel_Team.hpp [hunk 5]
```diff
@@ -30,6 +30,13 @@
 namespace Kokkos {
 namespace Impl {
 
+// HIP Teams use (team_size + 2)*sizeof(double) shared memory for team
+// reductions they also use one int64_t static shared memory for a shared ID
```
Comment (PhilMiller) [inline core/src/HIP/Kokkos_HIP_Parallel_Team.hpp:34]:
```suggestion
// reductions. They also use one int64_t in static shared memory for a shared ID.
```

File: core/src/Cuda/Kokkos_Cuda_Parallel_Team.hpp (hunk 4 above)
Comment (crtrott) [reply core/src/Cuda/Kokkos_Cuda_Parallel_Team.hpp:52]: yeah generally when I say "reduction scenarios" I imply scans too, since they are basically doing reductions too.

File: core/src/Cuda/Kokkos_Cuda_Parallel_Team.hpp [hunk 6]
```diff
@@ -47,6 +47,14 @@ extern bool show_warnings() noexcept;
 
 namespace Impl {
 
+// Cuda Teams use (team_size + 2)*sizeof(double) shared memory for team
+// reductions. They also use one int64_t in static shared memory for a shared
+// ID. Furthermore, they use additional scratch memory in some reduction
+// scenarios, which depend on the size of the value_type and is NOT captured
+// here.
+constexpr size_t cuda_team_max_reserved_shared_mem =
+    (1024 + 2) * sizeof(double) + sizeof(int64_t);
```
Comment (dalg24) [inline core/src/Cuda/Kokkos_Cuda_Parallel_Team.hpp:56]: Why declare it at namespace scope?   Keep the scope minimal, move it to `TeamPolicyInternal<Cuda>:: scratch_size_max()`

File: core/src/Cuda/Kokkos_Cuda_Parallel_Team.hpp [hunk 7]
```diff
@@ -198,12 +206,13 @@ class TeamPolicyInternal<Kokkos::Cuda, Properties...>
   }
 
   inline static int scratch_size_max(int level) {
-    return (
-        level == 0 ? 1024 * 40 :  // 48kB is the max for CUDA, but we need some
-                                  // for team_member.reduce etc.
-            20 * 1024 *
-                1024);  // arbitrarily setting this to 20MB, for a Volta V100
-                        // that would give us about 3.2GB for 2 teams per SM
+    size_t max_shmem = Cuda().cuda_device_prop().sharedMemPerBlock;
```
Comment (dalg24) [inline core/src/Cuda/Kokkos_Cuda_Parallel_Team.hpp:209]: Presumably you have access to an exec space from the policy so don't use a default-constructed one.

File: core/src/Cuda/Kokkos_Cuda_Parallel_Team.hpp [hunk 8]
```diff
@@ -198,12 +206,13 @@ class TeamPolicyInternal<Kokkos::Cuda, Properties...>
...
+    return (level == 0
+                ? max_shmem - cuda_team_max_reserved_shared_mem
+                :
+                // arbitrarily setting level 1 scratch limit to 20MB, for a
+                // Volta V100 that would give us about 3.2GB for 2 teams per SM
+                20 * 1024 * 1024);
```
Comment (dalg24) [inline core/src/Cuda/Kokkos_Cuda_Parallel_Team.hpp:215]: Consider turning this guy into a local variable too.

**Comment by PhilMiller** [comment]
(Your HIP commit message got truncated)

**Review by dalg24 — CHANGES_REQUESTED** [review]

File: core/src/Cuda/Kokkos_Cuda_Parallel_Team.hpp (hunk 7 above)
Comment (dalg24) [reply core/src/Cuda/Kokkos_Cuda_Parallel_Team.hpp:209]: Ah it is a static member function :/

File: core/src/Cuda/Kokkos_Cuda_Parallel_Team.hpp [hunk 9]
```diff
@@ -47,6 +47,14 @@ extern bool show_warnings() noexcept;
 
 namespace Impl {
 
+// Cuda Teams use (team_size + 2)*sizeof(double) shared memory for team
+// reductions. They also use one int64_t in static shared memory for a shared
+// ID. Furthermore, they use additional scratch memory in some reduction
+// scenarios, which depend on the size of the value_type and is NOT captured
+// here.
+constexpr size_t cuda_team_max_reserved_shared_mem =
```
Comment (PhilMiller) [inline core/src/Cuda/Kokkos_Cuda_Parallel_Team.hpp:55]: Why is there `max` in this name? It's a minimum reservation, isn't it?

Comment (crtrott) [reply core/src/Cuda/Kokkos_Cuda_Parallel_Team.hpp]: no, its the max you might get because the actual calculation is: `(team_size+2)*sizeof(double)+sizeof(int64_t)`

Comment (crtrott) [reply core/src/Cuda/Kokkos_Cuda_Parallel_Team.hpp]: and max team size if 1024

File: core/src/Cuda/Kokkos_Cuda_Parallel_Team.hpp [hunk 10]
```diff
@@ -198,12 +198,21 @@ class TeamPolicyInternal<Kokkos::Cuda, Properties...>
...
-        level == 0 ? 1024 * 40 :  // 48kB is the max for CUDA, but we need some
-                                  // for team_member.reduce etc.
-            20 * 1024 *
-                1024);  // arbitrarily setting this to 20MB, for a Volta V100
-                        // that would give us about 3.2GB for 2 teams per SM
+    // Cuda Teams use (team_size + 2)*sizeof(double) shared memory for team
+    // reductions. They also use one int64_t in static shared memory for a
+    // shared ID. Furthermore, they use additional scratch memory in some
+    // reduction scenarios, which depend on the size of the value_type and is
+    // NOT captured here.
```
Comment (PhilMiller) [inline core/src/Cuda/Kokkos_Cuda_Parallel_Team.hpp:205]: Again, please add something in the spirit of this comment as a comment on `Kokkos::TeamPolicy::scratch_size_max` so callers of the public API have an indication that other things may eat into this value.

File: core/src/Cuda/Kokkos_Cuda_Parallel_Team.hpp (hunk 9 above)
Comment (PhilMiller) [reply core/src/Cuda/Kokkos_Cuda_Parallel_Team.hpp]: Ah, ok. Is there a `int max_team_size = 1024` somewhere? If not, could you make one, and use that by name, rather than the magic constant that I had to ask about?

**Comment by PhilMiller** [comment]
This may also address #3498

File: core/src/Cuda/Kokkos_Cuda_Parallel_Team.hpp (hunk 9 above)
Comment (crtrott) [reply core/src/Cuda/Kokkos_Cuda_Parallel_Team.hpp]: there isn't a constexpr one, and technically that might not be correct.  In some ways that number is more prone to misinterpretation or misuse than the `reserved_shared_mem`. Essentially, in most cases the max team size will be smaller than that due to stuff like register constraints. Misuse or misunderstanding what a "max_team_size" variable means is very likely to be much more harmful than misunderstanding what cuda_team_max_reserved_shared_mem means. The latter would simply mean you are underestimating a bit how much shared memory you could theoretically use per block, the max_team_size misuse could mean all kinds of problems since it will almost always be wrong.

File: core/src/Cuda/Kokkos_Cuda_Parallel_Team.hpp (hunk 10 above)
Comment (crtrott) [reply core/src/Cuda/Kokkos_Cuda_Parallel_Team.hpp:205]: Note that the (admittedly stupid) way this works: this IS the public function, because TeamPolicy inherits from this guy. Turns out there is no scratch_size_max inside the Kokkos_ExecPolicy.hpp ...

Comment (crtrott) [reply core/src/Cuda/Kokkos_Cuda_Parallel_Team.hpp:205]: Oh and the prototype for TeamPolicyInternal in that header is unused, because everything real happens in partial specializations ...

Comment (crtrott) [reply core/src/Cuda/Kokkos_Cuda_Parallel_Team.hpp:205]: that said: working on a PR for the documentation

File: core/src/Cuda/Kokkos_Cuda_Parallel_Team.hpp (hunk 8 above)
Comment (crtrott) [reply core/src/Cuda/Kokkos_Cuda_Parallel_Team.hpp:215]: not sure that its worth it.

File: core/src/Cuda/Kokkos_Cuda_Parallel_Team.hpp (hunk 9 above)
Comment (PhilMiller) [reply core/src/Cuda/Kokkos_Cuda_Parallel_Team.hpp]: Even if it were just a variable local to this function, it would be an improvement. Perhaps `int max_possible_team_size`? `int theoretical_max_team_size`? `int team_size_upper_bound`?

File: core/src/Cuda/Kokkos_Cuda_Parallel_Team.hpp (hunk 10 above)
Comment (crtrott) [reply core/src/Cuda/Kokkos_Cuda_Parallel_Team.hpp:205]: https://github.com/kokkos/kokkos-core-wiki/pull/234

File: core/src/Cuda/Kokkos_Cuda_Parallel_Team.hpp (hunk 9 above)
Comment (crtrott) [reply core/src/Cuda/Kokkos_Cuda_Parallel_Team.hpp]: done

File: core/src/Cuda/Kokkos_Cuda_Parallel_Team.hpp (hunk 8 above)
Comment (crtrott) [reply core/src/Cuda/Kokkos_Cuda_Parallel_Team.hpp]: anyway done

**Review by PhilMiller — APPROVED** [review]

File: core/src/Cuda/Kokkos_Cuda_Parallel_Team.hpp [hunk 11]
```diff
@@ -198,12 +198,21 @@ class TeamPolicyInternal<Kokkos::Cuda, Properties...>
   }
 
   inline static int scratch_size_max(int level) {
-    return (
-        level == 0 ? 1024 * 40 :  // 48kB is the max for CUDA, but we need some
-                                  // for team_member.reduce etc.
-            20 * 1024 *
-                1024);  // arbitrarily setting this to 20MB, for a Volta V100
-                        // that would give us about 3.2GB for 2 teams per SM
+    // Cuda Teams use (team_size + 2)*sizeof(double) shared memory for team
```
Comment (dalg24) [inline core/src/Cuda/Kokkos_Cuda_Parallel_Team.hpp:201]: I assume the `sizeof(double)` here is our saying "let the value type for the reduction be double"?

Comment (crtrott) [reply core/src/Cuda/Kokkos_Cuda_Parallel_Team.hpp:201]: No, it actually doesn't I had there an 8 before because we actually say sizeof(double) in the code, but if you happen to do reductions with value_types larger than that they are done in stages.

Comment (crtrott) [reply core/src/Cuda/Kokkos_Cuda_Parallel_Team.hpp:201]: But I think its not a great idea to write the entire explanation of how our reductions work in the description of one variable.

Comment (dalg24) [reply core/src/Cuda/Kokkos_Cuda_Parallel_Team.hpp:201]: OK

**Review by Rombur — APPROVED** [review]

**Review by dalg24 — APPROVED** [review]
