### PR TITLE
Fix view_subview_constructor_layout_compatibility

### LINKED ISSUE #8245: Nightly test failures, cuda/11.2.2 w/ boundscheck enabled
**Describe the bug**

Nightly Cuda builds (cuda/11.2.2) with bounds checking began failing in the `cuda_uvm_DeathTest.view_subview_constructor_layout_compatibility` subtest after recently merged commits

**Error snips**:
`cuda_uvm_DeathTest.view_subview_constructor_layout_compatibility`
```
07:46:11 [ RUN      ] cuda_uvm_DeathTest.view_subview_constructor_layout_compatibility
07:46:11 Kokkos::subview bounds error ( 1 < 1 , Kokkos::ALL )
07:46:11 Backtrace:
07:46:11 [0x10e1d574] 
07:46:11 [0x10df5308] 
07:46:11 [0x1034ab50] 
07:46:11 [0x1034c8d0] 
07:46:11 [0x10dae020] 
07:46:11 [0x10df33ac] 
07:46:11 [0x10de02d0] 
07:46:11 [0x10de0790] 
07:46:11 [0x10de10a8] 
07:46:11 [0x10de3d94] 
07:46:11 [0x10de4430] 
07:46:11 [0x1000d3d8] 
07:46:11 [0x200002529f5c] 
07:46:11 [0x20000252a0f4] __libc_start_main
```

`serial_DeathTest.view_subview_constructor_layout_compatibility`
```
07:34:46 [ RUN      ] serial_DeathTest.view_subview_constructor_layout_compatibility
07:34:46 Kokkos::subview bounds error ( 1 < 1 , Kokkos::ALL )
07:34:46 Backtrace:
07:34:46 [0x10b42d64] 
07:34:46 [0x10b1a9a8] 
07:34:46 [0x10229800] 
07:34:46 [0x1022bee0] 
07:34:46 [0x10ad36c0] 
07:34:46 [0x10b18a4c] 
07:34:46 [0x10b05970] 
07:34:46 [0x10b05e30] 
07:34:46 [0x10b06748] 
07:34:46 [0x10b09434] 
07:34:46 [0x10b09ad0] 
07:34:46 [0x1000cd38] 
07:34:46 [0x200002529f5c] 
07:34:46 [0x20000252a0f4] __libc_start_main
```

The test failure began following merge of these commits:

**Changes**

    Merge pull request #8210 from tcclevenger/fix_subview_constructor ([details](https://jenkins-son.sandia.gov/job/Kokkos_develop_weaver_cuda_serial_cuda1122_gcc830_volta-boundscheck/946/changes#c28ad497e03189ff578fd28bff535a235ab703a1) / [githubweb](https://github.com/kokkos/kokkos/commit/c28ad497e03189ff578fd28bff535a235ab703a1))
    Disable mdspan-based view for CUDA 12.9 (#8169) ([details](https://jenkins-son.sandia.gov/job/Kokkos_develop_weaver_cuda_serial_cuda1122_gcc830_volta-boundscheck/946/changes#167cbc0b9579d15d97be124c643b664b067537ac) / [githubweb](https://github.com/kokkos/kokkos/commit/167cbc0b9579d15d97be124c643b664b067537ac))
    Fix a segfault with GCC 12 (#8223) ([details](https://jenkins-son.sandia.gov/job/Kokkos_develop_weaver_cuda_serial_cuda1122_gcc830_volta-boundscheck/946/changes#11cf8c13e12a95f2a5b4d8f8f195b3e10aa43f9b) / [githubweb](https://github.com/kokkos/kokkos/commit/11cf8c13e12a95f2a5b4d8f8f195b3e10aa43f9b))
    Remove BUILD.md in favor of the documentation website (#8242) ([details](https://jenkins-son.sandia.gov/job/Kokkos_develop_weaver_cuda_serial_cuda1122_gcc830_volta-boundscheck/946/changes#b22f613c3f856c0300dcf16f80b495d89ab1fcff) / [githubweb](https://github.com/kokkos/kokkos/commit/b22f613c3f856c0300dcf16f80b495d89ab1fcff))

**Please include the following for a minimal reproducer**

**Reproducer notes** (weaver testbed, rhel8 queue):
```bash

# Grab an interactive node
bsub -Is -n 1 -q rhel8 -gpu "num=1" bash

# Environment
source /etc/profile.d/modules.sh
source /projects/ppc64le-pwr9-rhel8/legacy-env.sh
module load cuda/11.2.2/gcc/8.3.1 cmake/3.23.1

export KOKKOS_PATH=<path-to-repo>

# Configure
cmake -DCMAKE_CXX_COMPILER=$KOKKOS_PATH/bin/nvcc_wrapper -DKokkos_ENABLE_SERIAL=ON -DKokkos_ENABLE_CUDA=ON -DKokkos_ARCH_POWER9=ON -DKokkos_ARCH_VOLTA70=ON -DKokkos_ENABLE_TESTS=ON -DKokkos_ENABLE_EXAMPLES=OFF -DKokkos_ENABLE_CUDA_LAMBDA=ON -DCMAKE_VERBOSE_MAKEFILE=ON -DCMAKE_CXX_EXTENSIONS=OFF -DCMAKE_CXX_STANDARD=17 -DCMAKE_BUILD_TYPE=RELEASE -DKokkos_ENABLE_DEBUG_BOUNDS_CHECK=ON -DKokkos_ENABLE_DEPRECATION_WARNINGS=OFF -DKokkos_ENABLE_DEPRECATED_CODE_4=OFF $KOKKOS_PATH

# Build
make -j16

# Tests
ctest -R Kokkos_CoreUnitTest_Serial2
ctest -R Kokkos_CoreUnitTest_Cuda2
```

### PR DESCRIPTION
**Pull request by masterleinad**
Fixes #8245. The first extent is 1 so we can only request index 0 when creating a subview.

### CODE REVIEW

**Comment by JBludau** [comment]
how did this not fail before?

File: core/unit_test/TestSubView_c15.hpp [hunk 1]
```diff
@@ -50,9 +50,9 @@ TEST(TEST_CATEGORY_DEATH, view_subview_constructor_layout_compatibility) {
   {
     // Using subview dims (1, ALL), but the first dimension is stride 1. Any
```
Comment (dalg24) [inline core/unit_test/TestSubView_c15.hpp]: Consider updating that comment as well.

**Review by dalg24 — COMMENTED** [review]
We need to clarify whether/why that was not caught earlier by our testing harness

**Comment by masterleinad** [comment]
> We need to clarify whether/why that was not caught earlier by our testing harness

https://cloud1.cees.ornl.gov/jenkins-ci/job/Kokkos/job/PR-8210/13/pipeline-overview/?selected-node=288 shows the issue and we merged ignoring it.

**Review by dalg24 — APPROVED** [review]

**Review by ndellingwood — APPROVED** [review]

**Review by tcclevenger — APPROVED** [review]
