### PR TITLE
Fix #6336: capturing `this` implicitly is deprecated in C++20

### LINKED ISSUE #6336: Nightly GCC13 fails in TestStdAlgorithmsTeamAdjacentFind
@fnrizzi Can you take a look. The error message is [here](https://cloud.cees.ornl.gov/jenkins-ci/blue/organizations/jenkins/Kokkos-nightly/detail/Kokkos-nightly/446/pipeline)

### PR DESCRIPTION
**Pull request by fnrizzi**
implicit capture of 'this' via '[=]' is deprecated in C++20 , so making it explicit anyway.

### CODE REVIEW

**Comment by fnrizzi** [comment]
retest this please

**Review by Rombur — APPROVED** [review]

File: algorithms/unit_tests/TestStdAlgorithmsTeamAdjacentFind.cpp [hunk 1]
```diff
@@ -55,7 +55,7 @@ struct TestFunctorA {
       case 0: {
         const auto it = KE::adjacent_find(member, KE::cbegin(myRowViewFrom),
                                           KE::cend(myRowViewFrom));
-        Kokkos::single(Kokkos::PerTeam(member), [=]() {
+        Kokkos::single(Kokkos::PerTeam(member), [=, this]() {
```
Comment (masterleinad) [inline algorithms/unit_tests/TestStdAlgorithmsTeamAdjacentFind.cpp:58]: Don't you want
```suggestion
        Kokkos::single(Kokkos::PerTeam(member), [=, *this]() {
```
here and below instead?

Comment (masterleinad) [reply algorithms/unit_tests/TestStdAlgorithmsTeamAdjacentFind.cpp:58]: The `this` pointer points to host data so I find it at the very least confusing to use `this` instead of `*this` here.

Comment (Rombur) [reply algorithms/unit_tests/TestStdAlgorithmsTeamAdjacentFind.cpp:58]: Windows is not happy with `this` anyway.

Comment (fnrizzi) [reply algorithms/unit_tests/TestStdAlgorithmsTeamAdjacentFind.cpp:58]: yes both right, i will fix it

**Review by masterleinad — APPROVED** [review]

**Review by crtrott — APPROVED** [review]

File: algorithms/unit_tests/TestStdAlgorithmsTeamAdjacentFind.cpp [hunk 2]
```diff
@@ -55,7 +55,7 @@ struct TestFunctorA {
       case 0: {
         const auto it = KE::adjacent_find(member, KE::cbegin(myRowViewFrom),
                                           KE::cend(myRowViewFrom));
-        Kokkos::single(Kokkos::PerTeam(member), [=]() {
+        Kokkos::single(Kokkos::PerTeam(member), [=, *this]() {
```
Comment (nliber) [inline algorithms/unit_tests/TestStdAlgorithmsTeamAdjacentFind.cpp:58]: `[=]` and `[=, *this]` are not equivalent.

`[=]` and `[=, this]` are equivalent, as `[=]` effectively captured the object by reference.

**Review by nliber — CHANGES_REQUESTED** [review]

File: algorithms/unit_tests/TestStdAlgorithmsTeamAdjacentFind.cpp (hunk 2 above)
Comment (fnrizzi) [reply algorithms/unit_tests/TestStdAlgorithmsTeamAdjacentFind.cpp:58]: Yes but I think what we want is *this because _this_ points to the host object and because of https://github.com/kokkos/kokkos/issues/695

Comment (PhilMiller) [reply algorithms/unit_tests/TestStdAlgorithmsTeamAdjacentFind.cpp:58]: Per @nmm0 [here](https://github.com/DARMA-tasking/vt/issues/925#issuecomment-1259849888), it's possible to end up with warnings coming from compilers passed `-std=c++17` about restating defaults with an explicit capture clause. I don't recall how that got resolved there, but Nic might.

Comment (PhilMiller) [reply algorithms/unit_tests/TestStdAlgorithmsTeamAdjacentFind.cpp:58]: Also, isn't one of those the expansion of `KOKKOS_CLASS_LAMBDA`, modulo `__host__ __device__` annotations?

Comment (fnrizzi) [reply algorithms/unit_tests/TestStdAlgorithmsTeamAdjacentFind.cpp:58]: Not sure if the Kokkos macros changes based on the standard. 
But I think solving the warning can be done via ifdeffing it, however we need to resolve if we want to use *this or this. 
I was going off the wiki (see [here](https://kokkos.github.io/kokkos-core-wiki/ProgrammingGuide/HierarchicalParallelism.html#restricting-execution-to-a-single-executor)) but then Daniel's comments made me realize this is not totally correct

Comment (masterleinad) [reply algorithms/unit_tests/TestStdAlgorithmsTeamAdjacentFind.cpp:58]: Since this uses an explicit functor, rather than a lambda, we copy the whole class to the device anyway and it should be OK to just use `[=, this]` (but this raises warnings for C++17 with some compilers and we have seen problems in particular with MSVC). If changing the functor to a lambda, I could see that using `[=, this]` is problematic and I was preferring `[=, *this]` for consistency (and portability in that case). Ultimately, this is just a test, and copying any of the class members is cheap anyway.

Comment (crtrott) [reply algorithms/unit_tests/TestStdAlgorithmsTeamAdjacentFind.cpp:58]: Technically in this place it doesn't matter: It must be correct with [=, *this] but if it is it's ok to just capture via [&] because it's a nested lambda. Since this is all tests I don't have a preference and I am happy to go with [=, *this] which is the closest to what the test intended.
