### PR TITLE
Fix using View without corresponding mdspan-type

### LINKED ISSUE #7135: Uninstantiable conversion to mdspan in Trilinos build with clang
```
FAILED: packages/sacado/test/UnitTests/CMakeFiles/Sacado_FadKokkosAtomicTests_Serial.dir/Fad_KokkosAtomicTests_Serial.cpp.o
/projects/x86-64-icelake-rocky8/compilers/llvm/15.0.7/gcc/8.5.0/base/i7ryam5/bin/clang++ -DKOKKOS_DEPENDENCE -I/home/ndellin/trilinos/Trilinos/Build/Blake-serial-llvm1507 -I/home/ndellin/trilinos/Trilinos/packages/sacado/test/utils -I/home/ndellin/trilinos/Trilinos/Build/Blake-serial-llvm1507/packages/sacado/src -I/home/ndellin/trilinos/Trilinos/packages/sacado/src -I/home/ndellin/trilinos/Trilinos/packages/sacado/src/new_design -I/home/ndellin/trilinos/Trilinos/packages/sacado/src/template -I/home/ndellin/trilinos/Trilinos/packages/sacado/src/parameter -I/home/ndellin/trilinos/Trilinos/packages/sacado/src/mpl -I/home/ndellin/trilinos/Trilinos/Build/Blake-serial-llvm1507/kokkos/core/src -I/home/ndellin/trilinos/Trilinos/kokkos/core/src -I/home/ndellin/trilinos/Trilinos/Build/Blake-serial-llvm1507/kokkos -I/home/ndellin/trilinos/Trilinos/kokkos/core/src/../../tpls/desul/include -I/home/ndellin/trilinos/Trilinos/kokkos/core/src/../../tpls/mdspan/include -I/home/ndellin/trilinos/Trilinos/Build/Blake-serial-llvm1507/kokkos/containers/src -I/home/ndellin/trilinos/Trilinos/kokkos/containers/src -I/home/ndellin/trilinos/Trilinos/Build/Blake-serial-llvm1507/kokkos/algorithms/src -I/home/ndellin/trilinos/Trilinos/kokkos/algorithms/src -I/home/ndellin/trilinos/Trilinos/Build/Blake-serial-llvm1507/kokkos/simd/src -I/home/ndellin/trilinos/Trilinos/kokkos/simd/src -I/home/ndellin/trilinos/Trilinos/Build/Blake-serial-llvm1507/packages/teuchos/core/src -I/home/ndellin/trilinos/Trilinos/packages/teuchos/core/src -I/home/ndellin/trilinos/Trilinos/packages/teuchos/numerics/src -I/home/ndellin/trilinos/Trilinos/packages/teuchos/comm/src -I/home/ndellin/trilinos/Trilinos/packages/teuchos/parameterlist/src -I/home/ndellin/trilinos/Trilinos/Build/Blake-serial-llvm1507/packages/teuchos/parameterlist/src -I/home/ndellin/trilinos/Trilinos/packages/teuchos/parser/src -I/home/ndellin/trilinos/Trilinos/Build/Blake-serial-llvm1507/packages/teuchos/kokkoscomm/src -I/home/ndellin/trilinos/Trilinos/packages/teuchos/kokkoscomm/src -I/home/ndellin/trilinos/Trilinos/Build/Blake-serial-llvm1507/packages/teuchos/kokkoscompat/src -I/home/ndellin/trilinos/Trilinos/packages/teuchos/kokkoscompat/src -isystem /projects/x86-64-icelake-rocky8/tpls/openblas/0.3.20/clang/15.0.7/base/3as4mmu/include -g -fPIC -g -std=c++17 -march=skylake-avx512 -mtune=skylake-avx512 -MD -MT packages/sacado/test/UnitTests/CMakeFiles/Sacado_FadKokkosAtomicTests_Serial.dir/Fad_KokkosAtomicTests_Serial.cpp.o -MF packages/sacado/test/UnitTests/CMakeFiles/Sacado_FadKokkosAtomicTests_Serial.dir/Fad_KokkosAtomicTests_Serial.cpp.o.d -o packages/sacado/test/UnitTests/CMakeFiles/Sacado_FadKokkosAtomicTests_Serial.dir/Fad_KokkosAtomicTests_Serial.cpp.o -c /home/ndellin/trilinos/Trilinos/packages/sacado/test/UnitTests/Fad_KokkosAtomicTests_Serial.cpp
In file included from /home/ndellin/trilinos/Trilinos/packages/sacado/test/UnitTests/Fad_KokkosAtomicTests_Serial.cpp:29:
In file included from /home/ndellin/trilinos/Trilinos/packages/teuchos/core/src/Teuchos_UnitTestHarness.hpp:51:
In file included from /home/ndellin/trilinos/Trilinos/packages/teuchos/core/src/Teuchos_UnitTestBase.hpp:51:
In file included from /home/ndellin/trilinos/Trilinos/packages/teuchos/core/src/Teuchos_Describable.hpp:45:
In file included from /home/ndellin/trilinos/Trilinos/packages/teuchos/core/src/Teuchos_VerbosityLevel.hpp:51:
In file included from /home/ndellin/trilinos/Trilinos/packages/teuchos/core/src/Teuchos_Assert.hpp:46:
In file included from /home/ndellin/trilinos/Trilinos/packages/teuchos/core/src/Teuchos_TestForException.hpp:49:
In file included from /home/ndellin/trilinos/Trilinos/packages/teuchos/core/src/Teuchos_TypeNameTraits.hpp:65:
In file included from /home/ndellin/trilinos/Trilinos/packages/teuchos/core/src/Teuchos_ConfigDefs.hpp:85:
In file included from /usr/lib/gcc/x86_64-redhat-linux/8/../../../../include/c++/8/string:40:
In file included from /usr/lib/gcc/x86_64-redhat-linux/8/../../../../include/c++/8/bits/char_traits.h:39:
In file included from /usr/lib/gcc/x86_64-redhat-linux/8/../../../../include/c++/8/bits/stl_algobase.h:64:
In file included from /usr/lib/gcc/x86_64-redhat-linux/8/../../../../include/c++/8/bits/stl_pair.h:59:
In file included from /usr/lib/gcc/x86_64-redhat-linux/8/../../../../include/c++/8/bits/move.h:55:
/usr/lib/gcc/x86_64-redhat-linux/8/../../../../include/c++/8/type_traits:1000:56: error: incomplete type 'Kokkos::Impl::UnsupportedKokkosArrayLayout' used in type trait expression
      : public __bool_constant<__is_assignable(_Tp, _Up)>
                                                       ^
/usr/lib/gcc/x86_64-redhat-linux/8/../../../../include/c++/8/type_traits:2799:43: note: in instantiation of template class 'std::is_assignable<Kokkos::mdspan<double, Kokkos::extents<unsigned long, 18446744073709551615, 18446744073709551615>, Kokkos::Experimental::layout_left_padded<18446744073709551615>, Kokkos::Impl::SpaceAwareAccessor<Kokkos::HostSpace, Kokkos::default_accessor<double>>>, Kokkos::Impl::UnsupportedKokkosArrayLayout>' requested here
  inline constexpr bool is_assignable_v = is_assignable<_Tp, _Up>::value;
                                          ^
/home/ndellin/trilinos/Trilinos/kokkos/core/src/Kokkos_View.hpp:1744:46: note: in instantiation of variable template specialization 'std::is_assignable_v<Kokkos::mdspan<double, Kokkos::extents<unsigned long, 18446744073709551615, 18446744073709551615>, Kokkos::Experimental::layout_left_padded<18446744073709551615>, Kokkos::Impl::SpaceAwareAccessor<Kokkos::HostSpace, Kokkos::default_accessor<double>>>, Kokkos::Impl::UnsupportedKokkosArrayLayout>' requested here
            typename = std::enable_if_t<std::is_assignable_v<
                                             ^
/home/ndellin/trilinos/Trilinos/kokkos/core/src/Kokkos_View.hpp:1748:36: note: in instantiation of default argument for 'operator mdspan<type-parameter-0-0, type-parameter-0-1, type-parameter-0-2, type-parameter-0-3><double, Kokkos::extents<unsigned long, 18446744073709551615, 18446744073709551615>, Kokkos::Experimental::layout_left_padded<18446744073709551615>, Kokkos::Impl::SpaceAwareAccessor<Kokkos::HostSpace, Kokkos::default_accessor<double>>>' required here
  KOKKOS_INLINE_FUNCTION constexpr operator mdspan<
                                   ^~~~~~~~~~~~~~~~
/home/ndellin/trilinos/Trilinos/packages/sacado/src/KokkosExp_View_Fad.hpp:408:67: note: while substituting deduced template arguments into function template 'operator mdspan<type-parameter-0-0, type-parameter-0-1, type-parameter-0-2, type-parameter-0-3>' [with OtherElementType = double, OtherExtents = Kokkos::extents<unsigned long, 18446744073709551615, 18446744073709551615>, OtherLayoutPolicy = Kokkos::Experimental::layout_left_padded<18446744073709551615>, OtherAccessor = Kokkos::Impl::SpaceAwareAccessor<Kokkos::HostSpace, Kokkos::default_accessor<double>>, $4 = (no value)]
  typename PODViewDeepCopyType< View<DT,DP...> >::type dst_array( dst );
                                                                  ^
/home/ndellin/trilinos/Trilinos/packages/sacado/src/KokkosExp_View_Fad.hpp:408:56: note: while substituting deduced template arguments into function template 'View' [with U = (no value)]
  typename PODViewDeepCopyType< View<DT,DP...> >::type dst_array( dst );
                                                       ^
/home/ndellin/trilinos/Trilinos/packages/sacado/src/KokkosExp_View_Fad.hpp:435:11: note: in instantiation of function template specialization 'Kokkos::deep_copy<Kokkos::Serial, Sacado::Fad::Exp::GeneralFad<Sacado::Fad::Exp::StaticFixedStorage<double, 5>> *, Kokkos::LayoutContiguous<Kokkos::LayoutLeft, 1>, Kokkos::Serial, Sacado::Fad::Exp::GeneralFad<Sacado::Fad::Exp::StaticFixedStorage<double, 5>> *, Kokkos::LayoutContiguous<Kokkos::LayoutLeft, 1>, Kokkos::Device<Kokkos::Serial, Kokkos::HostSpace>, Kokkos::Experimental::EmptyViewHooks>' requested here
  Kokkos::deep_copy(exec_space(), dst, src);
          ^
/home/ndellin/trilinos/Trilinos/packages/sacado/test/UnitTests/Fad_KokkosAtomicTests.hpp:286:11: note: in instantiation of function template specialization 'Kokkos::deep_copy<Sacado::Fad::Exp::GeneralFad<Sacado::Fad::Exp::StaticFixedStorage<double, 5>> *, Kokkos::LayoutContiguous<Kokkos::LayoutLeft, 1>, Kokkos::Serial, Sacado::Fad::Exp::GeneralFad<Sacado::Fad::Exp::StaticFixedStorage<double, 5>> *, Kokkos::LayoutContiguous<Kokkos::LayoutLeft, 1>, Kokkos::Device<Kokkos::Serial, Kokkos::HostSpace>, Kokkos::Experimental::EmptyViewHooks>' requested here
  Kokkos::deep_copy(v, h_v);
          ^
/home/ndellin/trilinos/Trilinos/packages/sacado/test/UnitTests/Fad_KokkosAtomicTests.hpp:324:13: note: in instantiation of function template specialization 'testAtomic<Sacado::Fad::Exp::GeneralFad<Sacado::Fad::Exp::StaticFixedStorage<double, 5>>, Kokkos::LayoutContiguous<Kokkos::LayoutLeft, 1>, Kokkos::Serial, true, AddTag>' requested here
  success = testAtomic<FadType, Layout, Device, true>(AddTag(), out);
            ^
/home/ndellin/trilinos/Trilinos/kokkos/core/src/Kokkos_View.hpp:379:8: note: forward declaration of 'Kokkos::Impl::UnsupportedKokkosArrayLayout'
struct UnsupportedKokkosArrayLayout;
       ^
In file included from /home/ndellin/trilinos/Trilinos/packages/sacado/test/UnitTests/Fad_KokkosAtomicTests_Serial.cpp:29:
In file included from /home/ndellin/trilinos/Trilinos/packages/teuchos/core/src/Teuchos_UnitTestHarness.hpp:51:
In file included from /home/ndellin/trilinos/Trilinos/packages/teuchos/core/src/Teuchos_UnitTestBase.hpp:51:
In file included from /home/ndellin/trilinos/Trilinos/packages/teuchos/core/src/Teuchos_Describable.hpp:45:
In file included from /home/ndellin/trilinos/Trilinos/packages/teuchos/core/src/Teuchos_VerbosityLevel.hpp:51:
In file included from /home/ndellin/trilinos/Trilinos/packages/teuchos/core/src/Teuchos_Assert.hpp:46:
In file included from /home/ndellin/trilinos/Trilinos/packages/teuchos/core/src/Teuchos_TestForException.hpp:49:
In file included from /home/ndellin/trilinos/Trilinos/packages/teuchos/core/src/Teuchos_TypeNameTraits.hpp:65:
In file included from /home/ndellin/trilinos/Trilinos/packages/teuchos/core/src/Teuchos_ConfigDefs.hpp:85:
In file included from /usr/lib/gcc/x86_64-redhat-linux/8/../../../../include/c++/8/string:40:
In file included from /usr/lib/gcc/x86_64-redhat-linux/8/../../../../include/c++/8/bits/char_traits.h:39:
In file included from /usr/lib/gcc/x86_64-redhat-linux/8/../../../../include/c++/8/bits/stl_algobase.h:64:
In file included from /usr/lib/gcc/x86_64-redhat-linux/8/../../../../include/c++/8/bits/stl_pair.h:59:
In file included from /usr/lib/gcc/x86_64-redhat-linux/8/../../../../include/c++/8/bits/move.h:55:
/usr/lib/gcc/x86_64-redhat-linux/8/../../../../include/c++/8/type_traits:1000:56: error: incomplete type 'Kokkos::Impl::UnsupportedKokkosArrayLayout' used in type trait expression
      : public __bool_constant<__is_assignable(_Tp, _Up)>
... # repeat of the above
```

_Originally posted by @ndellingwood in https://github.com/kokkos/kokkos/issues/7126#issuecomment-2223501140_

### PR DESCRIPTION
**Pull request by masterleinad**
Fixes #7135. For some reason, the conversion operator only gets instantiated with clang++ when compiling Sacado.
There is no corresponding `mdspan`-type and so the instantiation fails. We have to use SFINAE with `std::conditional_t` to short-circuit the existing SFINAE guard.

We could think about crafting a test if testing with Trilinos is not good enough.

### CODE REVIEW

File: core/src/Kokkos_View.hpp [hunk 1]
```diff
@@ -1741,10 +1741,13 @@ class View : public ViewTraits<DataType, Properties...> {
...
-                mdspan<OtherElementType, OtherExtents, OtherLayoutPolicy,
-                       OtherAccessor>,
-                typename Impl::MDSpanViewTraits<traits>::mdspan_type>>>
+            class Dummy = typename Impl::MDSpanViewTraits<traits>::mdspan_type,
+            typename    = std::enable_if_t<std::conditional_t<
+                std::is_same_v<Impl::UnsupportedKokkosArrayLayout, Dummy>,
+                std::false_type,
+                std::is_assignable<mdspan<OtherElementType, OtherExtents,
+                                          OtherLayoutPolicy, OtherAccessor>,
+                                   Dummy>>::value>>
```
Comment (nmm0) [inline core/src/Kokkos_View.hpp:1750]:
```suggestion
            class ImplNaturalMDSpanType = typename Impl::MDSpanViewTraits<traits>::mdspan_type,
            typename    = std::enable_if_t<std::conditional_t<
                std::is_same_v<Impl::UnsupportedKokkosArrayLayout, ImplNaturalMDSpanType>,
                std::false_type,
                std::is_assignable<mdspan<OtherElementType, OtherExtents,
                                          OtherLayoutPolicy, OtherAccessor>,
                                   ImplNaturalMDSpanType>>::value>>
```

This might be a bit clearer what it's doing since it's more specific

**Review by nmm0 — APPROVED** [review]
Thanks for fixing this!

**Review by nliber — APPROVED** [review]

**Comment by masterleinad** [comment]
Rebased after CI fixes in other pull requests (no changes here).

**Comment by masterleinad** [comment]
Retest this please.
