### PR TITLE
[4.0.0] Changes to resolve ICE with intel/19

### LINKED ISSUE #5290: Trilinos compilation errors, Intel Classic Compilers (19,2021.3) + OMP: internal compiler error 101003_1112 with Sacado, Intrepid2 unit tests
**Describe the bug**
Building Trilinos with intel/19 and the OpenMP backend results in ICE in the Sacado unit test `Trilinos/packages/sacado/test/UnitTests/Fad_Fad_KokkosTests_OpenMP.cpp`

```
[ 28%] Building CXX object packages/sacado/test/UnitTests/CMakeFiles/Sacado_FadFadKokkosTests_OpenMP.dir/Fad_Fad_KokkosTests_OpenMP.cpp.o
cd /ascldap/users/ndellin/trilinos/Trilinos/Build/ATDM-Blake-intel19-omp-sacado/packages/sacado/test/UnitTests && /ascldap/users/projects/x86-64-skylake/openmpi/4.0.1/intel/19.3.199/bin/mpicxx  -I/ascldap/users/ndellin/trilinos/Trilinos/Build/ATDM-Blake-intel19-omp-sacado -I/ascldap/users/ndellin/trilinos/Trilinos/packages/sacado/test/utils -I/ascldap/users/ndellin/trilinos/Trilinos/Build/ATDM-Blake-intel19-omp-sacado/packages/sacado/src -I/ascldap/users/ndellin/trilinos/Trilinos/packages/sacado/src -I/ascldap/users/ndellin/trilinos/Trilinos/packages/sacado/src/new_design -I/ascldap/users/ndellin/trilinos/Trilinos/packages/sacado/src/template -I/ascldap/users/ndellin/trilinos/Trilinos/packages/sacado/src/parameter -I/ascldap/users/ndellin/trilinos/Trilinos/packages/sacado/src/mpl -I/ascldap/users/ndellin/trilinos/Trilinos/Build/ATDM-Blake-intel19-omp-sacado/packages/teuchos/kokkoscomm/src -I/ascldap/users/ndellin/trilinos/Trilinos/packages/teuchos/kokkoscomm/src -I/ascldap/users/ndellin/trilinos/Trilinos/Build/ATDM-Blake-intel19-omp-sacado/packages/teuchos/kokkoscompat/src -I/ascldap/users/ndellin/trilinos/Trilinos/packages/teuchos/kokkoscompat/src -I/ascldap/users/ndellin/trilinos/Trilinos/packages/teuchos/parameterlist/src -I/ascldap/users/ndellin/trilinos/Trilinos/packages/teuchos/parser/src -I/ascldap/users/ndellin/trilinos/Trilinos/Build/ATDM-Blake-intel19-omp-sacado/packages/teuchos/core/src -I/ascldap/users/ndellin/trilinos/Trilinos/packages/teuchos/core/src -I/ascldap/users/ndellin/trilinos/Trilinos/Build/ATDM-Blake-intel19-omp-sacado/kokkos/core/src -I/ascldap/users/ndellin/trilinos/Trilinos/kokkos/core/src -I/ascldap/users/ndellin/trilinos/Trilinos/Build/ATDM-Blake-intel19-omp-sacado/kokkos -I/ascldap/users/ndellin/trilinos/Trilinos/kokkos/core/src/../../tpls/desul/include -I/ascldap/users/projects/x86-64-skylake/boost/1.65.1/intel/19.3.199/include -I/ascldap/users/ndellin/trilinos/Trilinos/packages/teuchos/comm/src -I/ascldap/users/ndellin/trilinos/Trilinos/packages/teuchos/numerics/src -I/ascldap/users/ndellin/trilinos/Trilinos/Build/ATDM-Blake-intel19-omp-sacado/kokkos/containers/src -I/ascldap/users/ndellin/trilinos/Trilinos/kokkos/containers/src -g -fopenmp -xCORE-AVX512  -O3 -DNDEBUG -std=c++14 -o CMakeFiles/Sacado_FadFadKokkosTests_OpenMP.dir/Fad_Fad_KokkosTests_OpenMP.cpp.o -c /ascldap/users/ndellin/trilinos/Trilinos/packages/sacado/test/UnitTests/Fad_Fad_KokkosTests_OpenMP.cpp
make[2]: Leaving directory '/home/ndellin/trilinos/Trilinos/Build/ATDM-Blake-intel19-omp-sacado'
...
": internal error: 101003_1112

compilation aborted for /ascldap/users/ndellin/trilinos/Trilinos/packages/sacado/test/UnitTests/Fad_Fad_KokkosTests_OpenMP.cpp (code 4)
make[2]: *** [packages/sacado/test/UnitTests/CMakeFiles/Sacado_FadFadKokkosTests_OpenMP.dir/build.make:81: packages/sacado/test/UnitTests/CMakeFiles/Sacado_FadFadKokkosTests_OpenMP.dir/Fad_Fad_KokkosTests_OpenMP.cpp.o] Error 4
make[2]: Leaving directory '/home/ndellin/trilinos/Trilinos/Build/ATDM-Blake-intel19-omp-sacado'
make[1]: *** [CMakeFiles/Makefile2:8572: packages/sacado/test/UnitTests/CMakeFiles/Sacado_FadFadKokkosTests_OpenMP.dir/all] Error 2
make[1]: *** Waiting for unfinished jobs....
```

I backtracked on kokkos merge commits and found this fails with acb34347ac67dc55c5255c1f7dac39af47e11b5f PR #5148 

Due to incompatibilities introduced (and resolved) between that commit and votd develop, some older shas are needed to reproduce with the issue:
kokkos/kokkos@acb34347ac67dc55c5255c1f7dac39af47e11b5f
kokkos/kokkos-kernels@42b60092741f9bceaf47c941df61527d66e2d932
trilinos/Trilinos@40898fa793500ecdf019017e1064127c82bee930 (kokkos-promotion branch)

**Please also include the following items to support reproducing the bug**
Reproducer (blake testbed, SKX arch):
```bash
# Repos
git clone -b kokkos-promotion https://github.com/trilinos/Trilinos.git
  cd Trilinos; git checkout 40898fa793500ecdf019017e1064127c82bee930; cd -
git clone -b develop kokkos
  cd kokkos; git checkout acb34347ac67dc55c5255c1f7dac39af47e11b5f; cd -
git clone -b develop kokkos-kernels
  cd kokkos-kernels; git checkout 42b60092741f9bceaf47c941df61527d66e2d932; cd -

# Symbolic link to your kokkos and kokkos-kernels repos in Trilinos source directory for source override
cd Trilinos
ln -s <path-to-your-repo>/kokkos kokkos
ln -s <path-to-your-repo>/kokkos-kernels kokkos-kernels

cd $HOME
mkdir -p build
cd build

# Env and Configure
module load devpack/20190329/openmpi/4.0.1/intel/19.3.199
module swap cmake/3.12.3 cmake/3.19.3
export OMP_NUM_THREADS=8

export ARCH_C_FLAG="-xCORE-AVX512 -mkl"
export BLAS_LIBRARIES="-mkl;${MKLROOT}/lib/intel64/libmkl_intel_lp64.a;${MKLROOT}/lib/intel64/libmkl_intel_thread.a;${MKLROOT}/lib/intel64/libmkl_core.a"
export LAPACK_LIBRARIES=${BLAS_LIBRARIES}

TESTS=ON
EXAMPLES=ON
SHARED=ON

CUDA=OFF
OPENMP=ON
PTHREAD=OFF
SERIAL=ON

COMPLEX=ON

ENABLE_SHYLU="ON"
if [ ${PTHREAD} == "ON" ]
then
  EXTRA_ARGS="$EXTRA_ARGS -DPhalanx_KOKKOS_DEVICE_TYPE="THREAD""
fi

# Configure

cmake \
-DCMAKE_INSTALL_PREFIX="${TRILINOS_INSTALL_DIR}" \
-DCMAKE_CXX_STANDARD="14" \
-D Trilinos_ENABLE_COMPLEX_DOUBLE=${COMPLEX} \
\
-D Kokkos_ARCH_SKX=ON \
-D CMAKE_CXX_FLAGS="-g" \
-D CMAKE_C_FLAGS="${ARCH_C_FLAG} -g" \
-D CMAKE_Fortran_FLAGS="${ARCH_C_FLAG} -g" \
-D CMAKE_EXE_LINKER_FLAGS="${ARCH_C_FLAG}" \
-D CMAKE_Fortran_COMPILER="mpif77" \
-D HAVE_CXX_PRAGMA_WEAK:BOOL=OFF \
-D CMAKE_AR:FILEPATH=/usr/bin/ar \
-D CMAKE_STRIP:FILEPATH=/usr/bin/strip \
-D CMAKE_RANLIB:FILEPATH=/usr/bin/ranlib \
-D Trilinos_ENABLE_EXPLICIT_INSTANTIATION:BOOL=ON \
-D Trilinos_ENABLE_DEBUG:BOOL=OFF \
\
-D Trilinos_ENABLE_INSTALL_CMAKE_CONFIG_FILES:BOOL=ON \
-D CMAKE_BUILD_TYPE:STRING=RELEASE \
-D CMAKE_VERBOSE_MAKEFILE:BOOL=OFF \
-D CMAKE_SKIP_RULE_DEPENDENCY=ON \
-D Trilinos_ENABLE_CHECKED_STL:BOOL=OFF \
-D Trilinos_ENABLE_ALL_PACKAGES:BOOL=OFF \
-D Trilinos_ENABLE_ALL_OPTIONAL_PACKAGES:BOOL=OFF \
-D BUILD_SHARED_LIBS:BOOL=${SHARED} \
-D DART_TESTING_TIMEOUT:STRING=500 \
-D Trilinos_WARNINGS_AS_ERRORS_FLAGS:STRING="" \
\
-D Trilinos_ENABLE_OpenMP=${OPENMP} \
-D TPL_ENABLE_CUDA=${CUDA} \
-D TPL_ENABLE_MPI=ON \
  -D MPI_EXEC_POST_NUMPROCS_FLAGS:STRING="-bind-to;socket;-map-by;socket" \
-D TPL_ENABLE_BinUtils=OFF \
-D TPL_ENABLE_SuperLU=OFF \
  -D TPL_SuperLU_LIBRARIES:STRING="${SUPERLU_ROOT}/lib/libsuperlu.a" \
  -D TPL_SuperLU_INCLUDE_DIRS:STRING="${SUPERLU_ROOT}/include" \
-D TPL_ENABLE_BLAS=ON \
  -D TPL_BLAS_LIBRARIES:PATH="${BLAS_LIBRARIES}" \
-D TPL_ENABLE_LAPACK=ON \
  -D TPL_LAPACK_LIBRARIES:PATH="${LAPACK_LIBRARIES}" \
-D TPL_ENABLE_Boost=ON \
   -D Boost_INCLUDE_DIRS:PATH="${BOOST_ROOT}/include" \
   -D Boost_LIBRARY_DIRS:PATH="${BOOST_ROOT}/lib" \
-D TPL_ENABLE_BoostLib=ON \
   -D BoostLib_INCLUDE_DIRS:PATH="${BOOST_ROOT}/include" \
   -D BoostLib_LIBRARY_DIRS:PATH="${BOOST_ROOT}/lib" \
-D TPL_ENABLE_Netcdf=ON \
  -D Netcdf_INCLUDE_DIRS:PATH="${NETCDF_ROOT}/include" \
  -D Netcdf_LIBRARY_DIRS:PATH="${NETCDF_ROOT}/lib" \
  -D TPL_Netcdf_LIBRARIES:PATH="${NETCDF_ROOT}/lib/libnetcdf.a;${HDF5_ROOT}/lib/libhdf5_hl.a;${HDF5_ROOT}/lib/libhdf5.a;${ZLIB_ROOT}/lib/libz.a;${PNETCDF_ROOT}/lib/libpnetcdf.a" \
  -D TPL_Netcdf_PARALLEL:BOOL=ON \
-D TPL_ENABLE_HDF5=ON \
  -D HDF5_INCLUDE_DIRS:PATH="${HDF5_ROOT}/include" \
  -D TPL_HDF5_LIBRARIES:PATH="${HDF5_ROOT}/lib/libhdf5_hl.a;${HDF5_ROOT}/lib/libhdf5.a;${ZLIB_ROOT}/lib/libz.a" \
-D TPL_ENABLE_Zlib=ON \
  -D Zlib_INCLUDE_DIRS:PATH="${ZLIB_ROOT}/include" \
  -D TPL_Zlib_LIBRARIES:PATH="${ZLIB_ROOT}/lib/libz.a" \
-D TPL_ENABLE_DLlib=ON \
\
\
-D Trilinos_ENABLE_Kokkos=ON \
  -D Kokkos_ENABLE_SERIAL=${SERIAL} \
  -D Kokkos_ENABLE_PTHREAD=${PTHREAD} \
  -D Kokkos_ENABLE_OPENMP=${OPENMP} \
  -D Kokkos_ENABLE_CUDA=${CUDA} \
  -D Kokkos_ENABLE_CUDA_LAMBDA=${CUDA} \
  -D Kokkos_ENABLE_TESTS:BOOL=${TESTS} \
-D Trilinos_ENABLE_KokkosKernels=ON \
  -D KokkosKernels_ENABLE_TESTS:BOOL=${TESTS} \
-D Trilinos_ENABLE_Sacado=ON \
  -D Sacado_ENABLE_UNINIT:BOOL=ON \
  -D Sacado_ENABLE_TESTS:BOOL=${TESTS} \
  -D Sacado_ENABLE_EXAMPLES:BOOL=${EXAMPLES} \
-D Trilinos_ENABLE_Tpetra=ON \
  -D Tpetra_INST_SERIAL:BOOL=${SERIAL} \
  -D Tpetra_INST_OPENMP:BOOL=${OPENMP} \
  -D Tpetra_INST_PTHREAD:BOOL=${PTHREAD} \
  -D Tpetra_INST_CUDA:BOOL=${CUDA} \
  -D Tpetra_ENABLE_TESTS:BOOL=${TESTS} \
  -D Tpetra_ENABLE_EXAMPLES:BOOL=${EXAMPLES} \
-D Trilinos_ENABLE_Intrepid2=ON \
  -D Intrepid2_ENABLE_UNINIT:BOOL=ON \
 -DKokkos_SOURCE_DIR_OVERRIDE:STRING=kokkos \
 -DKokkosKernels_SOURCE_DIR_OVERRIDE:STRING=kokkos-kernels \
$TRILINOS_DIR
```

Lots of the TPL stuff is boiler plate for enabling other Trilinos packages, the key TPLs needed are and MPI implemenation and MKL
The intel compiler from the module devpack lists as:
```
bash-4.2$ icpc --version
icpc (ICC) 19.0.3.199 20190206
Copyright (C) 1985-2019 Intel Corporation.  All rights reserved.
```

### PR DESCRIPTION
**Pull request by ndellingwood**
Changes to remove duplicate copies of policy and functor in ParallelFor specialization of MDRangePolicy Resolves internal compiler errors occurring with intel/19.0.5 OpenMP builds

Fixes #5290

Co-authored-by: Christian Trott <crtrott@sandia.gov>

### CODE REVIEW

**Comment by ndellingwood** [comment]
This PR is result of a debugging session with @crtrott
Addresses occurrence of ICE with intel/19.0.5 with OpenMP builds of Trilinos and BDW arch

@crtrott pointed out similar changes may be needed for ParallelReduce

After reviews of this PR are satisfied I'll open up matching PR's to develop and release-candidate-3.7.02

**Comment by ndellingwood** [comment]
Confirming that changes in this PR resulted in successful compilation of Sacado with intel/19.0.5, OpenMP backend, and BDW arch

**Comment by crtrott** [comment]
This change does go in the same direction as the previous fix here: #5671
Specifically it removed duplicate copies of the execution space instance, execution policy and functor - and thus indirectly removes copies of the execution space instance. In this case the creation of `iterate_type` did create new copies of the policy and the functor, which are already stored in the ParallelFor class. We now simply create one instance of that `iterate_type` which contains the policy and functor, and remove the explicit members for both from `ParallelFor`. We also sidestep an implicit creation of the default instance of OpenMP in the OpenMP::in_parallel call, by passing the actual instance into it.

**Comment by masterleinad** [comment]
Looks like there is a problem with `KokkosCore_UnitTest_OpenMPGraph`.

**Review by Rombur — APPROVED** [review]

**Comment by ndellingwood** [comment]
The ICE issues, and related modifications in this PR, apply similarly to intel/2021.3
Attempts to resolve the failures with the OpenMP Graph tests are unsuccessful so far, as they result in the return of ICE showing up in Sacado unit tests in builds of Trilinos

**Comment by crtrott** [comment]
I reopened this PR after fixing the other backends etc. and make the iterate_tile thing safe (i.e. store actual copies of functor and policy). That on its own did not fix the ICE in Sacado. But combined with disabling the nested OpenMP support code path it did. The latter change on its own also did not allow Sacado to compile - so you need both the new iterate_tile interface approach and commenting out the nested OpenMP support.

File: core/src/OpenMP/Kokkos_OpenMP_Parallel.hpp [hunk 1]
```diff
@@ -210,18 +207,19 @@ class ParallelFor<FunctorType, Kokkos::MDRangePolicy<Traits...>,
...
   inline void execute() const {
-    if (execute_in_serial()) {
-      ParallelFor::exec_range(m_mdr_policy, m_functor, 0,
-                              m_mdr_policy.m_num_tiles);
+#ifndef KOKKOS_COMPILER_INTEL
+    if (execute_in_serial(m_iter.m_rp.space())) {
+      exec_range(0, m_iter.m_rp.m_num_tiles);
       return;
     }
+#endif
```
Comment (ndellingwood) [inline core/src/OpenMP/Kokkos_OpenMP_Parallel.hpp:222]: Should this `#endif` be moved up before line 221? It looks to me like the braces are not matched within the guards

**Review by ndellingwood — COMMENTED** [review]
@crtrott aside from the `#endif` and mismatch of braces (unless I'm misreading) this looks good, thanks for all the effort on this!

File: core/src/OpenMP/Kokkos_OpenMP_Parallel.hpp (hunk 1 above)
Comment (PhilMiller) [reply core/src/OpenMP/Kokkos_OpenMP_Parallel.hpp:222]: I think you're misreading the diff, because Github is formatting it inconveniently. The entire block `if (foo) { bar }` is enclosed in the `#ifdef / #endif`

**Comment by PhilMiller** [comment]
@crtrott Since (as I understand) this partially moves the code in a desirable direction anyway, could you please rebase and rewrite the commits to separate and clarify the intended improvements from the purely Intel-workaround bits? Basically, I think it would be easier to review now, and easier to revisit later, if one could look at the succession of ultimately merged commits as standalone increments of progress, and then an eventually revertable workaround.

**Comment by PhilMiller** [comment]
Possibly even separate the improvement into one PR, and the workaround in another, but I wouldn't consider that necessary as long as the individual commit messages provide sufficient documentation.

**Comment by PhilMiller** [comment]
Also, the HPX build failure is directly tied to the substance of this change, so that needs to get fixed.

**Comment by PhilMiller** [comment]
Also, for documentation's sake, reproducing the failure requires icpc arguments that have all of
* `-fopenmp`
* `-O2` or greater (maybe `-O1` fails as well, could go back to check)
* an architecture flag that enables AVX2 vectorization (e.g. `-march=native`, `-mAVX2`, etc)

**Comment by crtrott** [comment]
The changes are all necessary to do the fix. I mean the only thing you could separate out is the ifdef around the "execute in serial" part. But that on its own does NOT fix the issue.

File: core/src/impl/KokkosExp_Host_IterateTile.hpp [hunk 2]
```diff
@@ -2324,15 +2321,10 @@ struct HostIterateTile<RP, Functor, Tag, ValueType,
                                         // 'array-ness' [], only
                                         // underlying type remains
 
-  inline HostIterateTile(
-      RP const& rp, Functor const& func,
-      value_type* v)  // v should be an array; treat as pointer for
-                      // compatibility since size is not known nor needed here
-      : m_rp(rp)      // Cuda 7.0 does not like braces...
+  inline HostIterateTile(RP const& rp, Functor const& func)
+      : m_rp(rp)  // Cuda 7.0 does not like braces...
```
Comment (PhilMiller) [inline core/src/impl/KokkosExp_Host_IterateTile.hpp:2325]: It's a silly thing, but we really don't care about Cuda 7 anymore

**Review by PhilMiller — APPROVED** [review]

File: core/src/impl/KokkosExp_Host_IterateTile.hpp (hunk 2 above)
Comment (crtrott) [reply core/src/impl/KokkosExp_Host_IterateTile.hpp:2325]: Yeah but I didn't want to do unrelated changed.

**Comment by crtrott** [comment]
Was only fixing HPX after Phils approval

**Comment by ndellingwood** [comment]
I can't approve I guess since I submitted the initial PR, can someone else approve?

**Review by dalg24 — APPROVED** [review]
