### PR TITLE
Fix warnigns for clang/cuda on Kepler

### LINKED ISSUE #2884: clang/7+cuda/9 build -Werror-unused parameter error in nightly test
Sample error:

```
18:48:10 /home/jenkins/slave/workspace/Kokkos_develop_kokkos-dev_clang_701_cuda_92/kokkos/core/src/impl/Kokkos_Atomic_Load.hpp:123:8: error: unused parameter 'ptr' [-Werror,-Wunused-parameter]
18:48:10     T* ptr, typename std::enable_if<!(sizeof(T) == 1 || sizeof(T) == 2 ||
18:48:10        ^
18:48:10 1 error generated when compiling for sm_35.
```

Sample reproducer:
```
   #   Load modules:
         module load sems-env sems-cmake/3.12.2 kokkos-env kokkos-hwloc/1.10.1/base sems-clang/7.0.1 sems-cuda/9.2
 
   #   Use generate_makefile line below to call cmake which generates makefile for this build:
         /home/jenkins/slave/workspace/Kokkos_develop_kokkos-dev_clang_701_cuda_92/kokkos/generate_makefile.bash --with-devices=Cuda,OpenMP --arch=Kepler35 --compiler=/projects/sems/install/rhel6-x86_64/sems/compiler/clang/7.0.1/base/bin/clang++ --cxxflags="-O3 -Wall -Wunused-parameter -Wshadow -pedantic -Werror -Wsign-compare -Wtype-limits -Wuninitialized " --cxxstandard="11" --ldflags="" --with-cuda=/projects/sems/install/rhel6-x86_64/sems/compiler/cuda/9.2/base --kokkos-path=/home/jenkins/slave/workspace/Kokkos_develop_kokkos-dev_clang_701_cuda_92/kokkos --no-examples 
```

### PR DESCRIPTION
**Pull request by crtrott**
One of the unused parameter issues was probably a real bug in atomics
for atomic_load of larger than 64bit on Volta. Apparently not used anywhere
(otherwise it would have shown since the return value was always defaulted
scalar type)

Fixes #2884

### CODE REVIEW

File: core/src/impl/Kokkos_Atomic_Load.hpp [hunk 1]
```diff
@@ -125,8 +125,7 @@ __device__ __inline__ T _relaxed_atomic_load_impl(
                                     void const**>::type = nullptr) {
   T rv{};
   // TODO remove a copy operation here?
-  Kokkos::Impl::atomic_oper_fetch(NoOpOper<T>{}, &rv, rv);
-  return rv;
+  return Kokkos::Impl::atomic_oper_fetch(NoOpOper<T>{}, ptr, rv);
```
Comment (dalg24) [inline core/src/impl/Kokkos_Atomic_Load.hpp]: There was no point on declaring `rv` in the first place, you could pass `*ptr` instead.

Comment (crtrott) [reply core/src/impl/Kokkos_Atomic_Load.hpp]: not sure if that does an unneccessary read?

Comment (dalg24) [reply core/src/impl/Kokkos_Atomic_Load.hpp]: I would expect the compiler would inline the apply and see it is not used.
Anyway I am not asking you to change.
