### PR TITLE
Switch to using functors in sort_by_key_via_sort

### LINKED ISSUE #7036: sort_by_key fails to compile with host execution space in cuda build
`Kokkos::Experimental::sort_by_key` fails to compile when using the host execution space with `Kokkos_ENABLE_CUDA=ON` build.

Reproducer:
```
  using ExecutionSpace = Kokkos::DefaultHostExecutionSpace;

  Kokkos::View<int *, ExecutionSpace> keys("keys", 0); 
  Kokkos::View<float *, ExecutionSpace> values("values", 0); 

  ASSERT_NO_THROW(
      Kokkos::Experimental::sort_by_key(ExecutionSpace(), keys, values));
```

Error output (gcc 12.2.0 + cuda 12.0):
```
/kokkos/algorithms/src/sorting/./impl/Kokkos_SortByKeyImpl.hpp:210:578: error: no matches converting function 'sort_by_key_via_sort' to type 'void (*)(const class Kokkos::Serial&, const class Kokkos::View<int*, Kokkos::Serial>&, const class Kokkos::View<float*, Kokkos::Serial>&)'
  210 |   Kokkos::parallel_for(
      |                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  ^
  211 |       "Kokkos::sort_by_key_via_sort::iota",
      |       ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                       
  212 |       Kokkos::RangePolicy<ExecutionSpace>(exec, 0, n),
      |       ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            
  213 |       KOKKOS_LAMBDA(int i) { permute(i) = i; });
      |       ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
                                                                                                                                                                                                                                                                
/kokkos/kokkos/algorithms/src/sorting/./impl/Kokkos_SortByKeyImpl.hpp:195:1: note: candidate is: 'template<class ExecutionSpace, class KeysDataType, class ... KeysProperties, class ValuesDataType, class ... ValuesProperties, class ... MaybeComparator> void Kokkos::Impl::sort_by_key_via_sort(const ExecutionSpace&, const Kokkos::View<T, Args ...>&, const Kokkos::View<ST, SP ...>&, MaybeComparator&& ...)'
  195 | void sort_by_key_via_sort(
      | ^~~~~~~~~~~~~~~~~~~~
```

It seems that this only fail to compile for gcc+cuda. Clang+cuda builds fine, and this also fine for HIP and SYCL build.

### PR DESCRIPTION
**Pull request by aprokop**
Fix #7036.

For some reason, nvcc has trouble getting the address of a function with variadic template arguments. Could reproduce with nvcc/11.5 and gcc/9.3.0. I switched to using functors instead.

If anyone has a better idea/more knowledge, it would be welcome.

Drive-by change: fix a label in `iota` that was copied from ArborX.

### CODE REVIEW

**Review by masterleinad — APPROVED** [review]
Fine with me.

File: algorithms/src/sorting/impl/Kokkos_SortByKeyImpl.hpp [hunk 1]
```diff
@@ -189,6 +189,21 @@ void applyPermutation(const ExecutionSpace& space,
       KOKKOS_LAMBDA(int i) { view(i) = view_copy(permutation(i)); });
 }
 
+// Use functors as nvcc errors out on trying to get the address of a function
```
Comment (nliber) [inline algorithms/src/sorting/impl/Kokkos_SortByKeyImpl.hpp:192]: I think this comment should mention this is an issue specifically with lambdas inside a variadic function under nvcc. As the comment reads now, making it a lambda should fix things, yet that is the original problem.

(Other than that, I'm fine with this.)

**Review by nliber — CHANGES_REQUESTED** [review]

File: algorithms/src/sorting/impl/Kokkos_SortByKeyImpl.hpp (hunk 1 above)
Comment (aprokop) [reply algorithms/src/sorting/impl/Kokkos_SortByKeyImpl.hpp:192]: I'm not sure how to properly describe it, though. Lambdas seem to work with nvcc when the execution space is also on the device. It's only when the stuff is on the host that it becomes a problem. So, I don't quite know the full extent of the problem. How would you formulate the comment?

File: algorithms/unit_tests/TestSortByKey.hpp [hunk 2]
```diff
@@ -87,6 +87,18 @@ TEST(TEST_CATEGORY, SortByKeyEmptyView) {
...
+// Test #7036
+TEST(TEST_CATEGORY, SortByKeyEmptyViewHost) {
+  using ExecutionSpace = Kokkos::DefaultHostExecutionSpace;
+
+  // does not matter if we use int or something else
+  Kokkos::View<int *, ExecutionSpace> keys("keys", 0);
+  Kokkos::View<float *, ExecutionSpace> values("values", 0);
+
+  ASSERT_NO_THROW(
+      Kokkos::Experimental::sort_by_key(ExecutionSpace(), keys, values));
```
Comment (dalg24) [inline algorithms/unit_tests/TestSortByKey.hpp:99]: I don't quite understand what in that test being added triggers the issue but had no coverage before.
Please explain.

Comment (aprokop) [reply algorithms/unit_tests/TestSortByKey.hpp:99]: Using the `DefaultHostExecutionSpace` instead of `DefaultExecutionSpace` triggers the issue.

File: algorithms/src/sorting/impl/Kokkos_SortByKeyImpl.hpp (hunk 1 above)
Comment (aprokop) [reply algorithms/src/sorting/impl/Kokkos_SortByKeyImpl.hpp]: @nliber I updated the comment.

**Review by crtrott — APPROVED** [review]

**Comment by crtrott** [comment]
Restarted the Windows CUDA build don't see why it would have failed here.

**Comment by crtrott** [comment]
Yeah likely, just checked its using make 3.29.

**Comment by crtrott** [comment]
#7062 does have a passing CUDA/Windows build

**Comment by crtrott** [comment]
Hm but #7061 did pass too.

**Comment by masterleinad** [comment]
The error is
```
C:\Program Files\NVIDIA GPU Computing
  Toolkit\CUDA\v12.1\include\crt/host_config.h(153): fatal error C1189:
  #error: -- unsupported Microsoft Visual Studio version! Only the versions
  between 2017 and 2022 (inclusive) are supported! The nvcc flag
  '-allow-unsupported-compiler' can be used to override this version check;
  however, using an unsupported host compiler may cause compilation failure
  or incorrect run time execution.  Use at your own risk.
  [D:\a\kokkos\kokkos\build\CMakeFiles\3.29.3\CompilerIdCUDA\CompilerIdCUDA.vcxproj]
```
so we might just need to use a newer CUDA version (assuming that the MSVC version changed silently).

**Comment by aprokop** [comment]
> so we might just need to use a newer CUDA version (assuming that the MSVC version changed silently).

It still does not explain why other MSVC builds passed at the same time. I don't see what is different about this PR compared to others.

**Review by nliber — APPROVED** [review]

File: algorithms/unit_tests/TestSortByKey.hpp (hunk 2 above)
Comment (ldh4) [reply algorithms/unit_tests/TestSortByKey.hpp:99]: This is something I was also confused about as I was reporting the issue #7036.

I expected that the original test https://github.com/kokkos/kokkos/blob/63f05204d0eaeec83e25f87eeb8025a188683f92/algorithms/unit_tests/TestSortByKey.hpp#L79-L88
would be catching this issue by having `TEST_EXECSPACE` defined as `Kokkos::Serial` even when cuda is enabled. (based on including `Test{Space}_Category.hpp` files in kokkos core/unit_test). But clearly, the need for this additional test in this PR shows otherwise.

I wonder if the tests are set up differently in kokkos algorithms.

**Review by ldh4 — APPROVED** [review]

**Comment by ndellingwood** [comment]
Should this have an entry added to Bug Fixes in the 4.4 changelog issue (assuming the issue pre-dated 4.3)?

**Comment by masterleinad** [comment]
> Should this have an entry added to Bug Fixes in the 4.4 changelog issue (assuming the issue pre-dated 4.3)?

Added one.
