### PR TITLE
Specify device type everywhere in Kokkos_Random.hpp

### LINKED ISSUE #4723: Nightly Trilinos build error with Cuda: Recent change incompatible with Intrepid2
Nightly Cuda builds of Trilinos with Intrepid2 began failing after merge of PR #4675, sample output:

```
FAILED: packages/intrepid2/unit-test/Discretization/Basis/HGRAD_TRI_Cn_FEM/Cuda/CMakeFiles/Intrepid2_unit-test_Discretization_Basis_HGRAD_TRI_Cn_FEM_Cuda_Test_02.dir/test_02.cpp.o
/projects/sems/install/rhel7-x86_64/sems/compiler/gcc/7.2.0/openmpi/4.0.2/bin/mpicxx   -I. -I../../packages/intrepid2/unit-test/Discretization/Basis/HGRAD_TRI_Cn_FEM -Ipackages/intrepid2/src -I../../packages/intrepid2/src/Cell -I../../packages/intrepid2/src/Discretization/Basis -I../../packages/intrepid2/src/Discretization/FunctionSpaceTools -I../../packages/intrepid2/src/Discretization/Integration -I../../packages/intrepid2/src/Orientation -I../../packages/intrepid2/src/Projection -I../../packages/intrepid2/src/Shared -I../../packages/intrepid2/src -Ipackages/shards/src -I../../packages/shards/src -Ipackages/sacado/src -I../../packages/sacado/src -I../../packages/sacado/src/new_design -I../../packages/sacado/src/template -I../../packages/sacado/src/parameter -I../../packages/sacado/src/mpl -Ipackages/teuchos/kokkoscomm/src -I../../packages/teuchos/kokkoscomm/src -Ipackages/teuchos/kokkoscompat/src -I../../packages/teuchos/kokkoscompat/src -I../../packages/teuchos/parameterlist/src -I../../packages/teuchos/parser/src -Ipackages/teuchos/core/src -I../../packages/teuchos/core/src -Ikokkos/core/src -I../../kokkos/core/src -Ikokkos -I/projects/sems/install/rhel7-x86_64/sems/tpl/boost/1.59.0/gcc/7.2.0/base/include -I../../packages/teuchos/comm/src -I../../packages/teuchos/numerics/src -Ikokkos-kernels/src -I../../kokkos-kernels/src -I../../kokkos-kernels/src/impl -Ikokkos-kernels/src/impl -I../../kokkos-kernels/src/impl/tpls -I../../kokkos-kernels/src/blas -I../../kokkos-kernels/src/blas/impl -I../../kokkos-kernels/src/sparse -I../../kokkos-kernels/src/sparse/impl -I../../kokkos-kernels/src/graph -I../../kokkos-kernels/src/graph/impl -I../../kokkos-kernels/src/batched -I../../kokkos-kernels/src/batched/dense -I../../kokkos-kernels/src/batched/dense/impl -I../../kokkos-kernels/src/batched/sparse -I../../kokkos-kernels/src/batched/sparse/impl -I../../kokkos-kernels/src/common -Ikokkos/algorithms/src -I../../kokkos/algorithms/src -Ikokkos/containers/src -I../../kokkos/containers/src -expt-extended-lambda -arch=sm_70  -O3 -DNDEBUG -fPIE   -std=c++14 -MD -MT packages/intrepid2/unit-test/Discretization/Basis/HGRAD_TRI_Cn_FEM/Cuda/CMakeFiles/Intrepid2_unit-test_Discretization_Basis_HGRAD_TRI_Cn_FEM_Cuda_Test_02.dir/test_02.cpp.o -MF packages/intrepid2/unit-test/Discretization/Basis/HGRAD_TRI_Cn_FEM/Cuda/CMakeFiles/Intrepid2_unit-test_Discretization_Basis_HGRAD_TRI_Cn_FEM_Cuda_Test_02.dir/test_02.cpp.o.d -o packages/intrepid2/unit-test/Discretization/Basis/HGRAD_TRI_Cn_FEM/Cuda/CMakeFiles/Intrepid2_unit-test_Discretization_Basis_HGRAD_TRI_Cn_FEM_Cuda_Test_02.dir/test_02.cpp.o -c ../../packages/intrepid2/unit-test/Discretization/Basis/HGRAD_TRI_Cn_FEM/Cuda/test_02.cpp
../../kokkos/core/src/Kokkos_View.hpp(1437): error: static assertion failed with "Incompatible View copy construction"
          detected during:
            instantiation of "Kokkos::View<DataType, Properties...>::View(const Kokkos::View<RT, RP...> &, std::enable_if<Kokkos::Impl::ViewMapping<Kokkos::View<DataType, Properties...>::traits, Kokkos::View<RT, RP...>::traits, Kokkos::ViewTraits<DataType, Properties...>::specialize>::is_assignable_data_type, void>::type *) [with DataType=int **, Properties=<Kokkos::Cuda>, RT=Intrepid2::ordinal_type **, RP=<Kokkos::Device<Kokkos::CudaSpace::execution_space, Kokkos::CudaSpace::memory_space>>]"
../../kokkos/algorithms/src/Kokkos_Random.hpp(967): here
            instantiation of "Kokkos::Random_XorShift64<DeviceType> Kokkos::Random_XorShift64_Pool<DeviceType>::get_state() const [with DeviceType=Kokkos::Device<Kokkos::CudaSpace::execution_space, Kokkos::CudaSpace::memory_space>]"
../../kokkos/algorithms/src/Kokkos_Random.hpp(1295): here
            instantiation of "void Kokkos::Impl::fill_random_functor_range<ViewType, RandomPool, loops, 2, IndexType>::operator()(IndexType) const [with ViewType=Kokkos::View<double **, Kokkos::Device<Kokkos::CudaSpace::execution_space, Kokkos::CudaSpace::memory_space>>, RandomPool=Kokkos::Random_XorShift64_Pool<Kokkos::Device<Kokkos::CudaSpace::execution_space, Kokkos::CudaSpace::memory_space>>, loops=128, IndexType=int64_t]"
../../kokkos/core/src/Cuda/Kokkos_Cuda_Parallel.hpp(465): here
            instantiation of "std::enable_if<std::is_same<TagType, void>::value, void>::type Kokkos::Impl::ParallelFor<FunctorType, Kokkos::RangePolicy<Traits...>, Kokkos::Cuda>::exec_range<TagType>(Kokkos::Impl::ParallelFor<FunctorType, Kokkos::RangePolicy<Traits...>, Kokkos::Cuda>::Member) const [with FunctorType=Kokkos::Impl::fill_random_functor_range<Kokkos::View<double **, Kokkos::Device<Kokkos::CudaSpace::execution_space, Kokkos::CudaSpace::memory_space>>, Kokkos::Random_XorShift64_Pool<Kokkos::Device<Kokkos::CudaSpace::execution_space, Kokkos::CudaSpace::memory_space>>, 128, 2, int64_t>, Traits=<Kokkos::CudaSpace::execution_space>, TagType=Kokkos::Impl::WorkTagTrait::base_traits::work_tag]"
../../kokkos/core/src/Cuda/Kokkos_Cuda_Parallel.hpp(489): here
            instantiation of "void Kokkos::Impl::ParallelFor<FunctorType, Kokkos::RangePolicy<Traits...>, Kokkos::Cuda>::operator()() const [with FunctorType=Kokkos::Impl::fill_random_functor_range<Kokkos::View<double **, Kokkos::Device<Kokkos::CudaSpace::execution_space, Kokkos::CudaSpace::memory_space>>, Kokkos::Random_XorShift64_Pool<Kokkos::Device<Kokkos::CudaSpace::execution_space, Kokkos::CudaSpace::memory_space>>, 128, 2, int64_t>, Traits=<Kokkos::CudaSpace::execution_space>]"
../../kokkos/core/src/Cuda/Kokkos_Cuda_KernelLaunch.hpp(121): here
            [ 3 instantiation contexts not shown ]
            instantiation of "void Kokkos::Impl::ParallelFor<FunctorType, Kokkos::RangePolicy<Traits...>, Kokkos::Cuda>::execute() const [with FunctorType=Kokkos::Impl::fill_random_functor_range<Kokkos::View<double **, Kokkos::Device<Kokkos::CudaSpace::execution_space, Kokkos::CudaSpace::memory_space>>, Kokkos::Random_XorShift64_Pool<Kokkos::Device<Kokkos::CudaSpace::execution_space, Kokkos::CudaSpace::memory_space>>, 128, 2, int64_t>, Traits=<Kokkos::CudaSpace::execution_space>]"
../../kokkos/core/src/Kokkos_Parallel.hpp(192): here
            instantiation of "void Kokkos::parallel_for(size_t, const FunctorType &, const std::__cxx11::string &) [with FunctorType=Kokkos::Impl::fill_random_functor_range<Kokkos::View<double **, Kokkos::Device<Kokkos::CudaSpace::execution_space, Kokkos::CudaSpace::memory_space>>, Kokkos::Random_XorShift64_Pool<Kokkos::Device<Kokkos::CudaSpace::execution_space, Kokkos::CudaSpace::memory_space>>, 128, 2, int64_t>]"
../../kokkos/core/src/Kokkos_Parallel.hpp(200): here
            instantiation of "void Kokkos::parallel_for(const std::__cxx11::string &, const ExecPolicy &, const FunctorType &) [with ExecPolicy=long, FunctorType=Kokkos::Impl::fill_random_functor_range<Kokkos::View<double **, Kokkos::Device<Kokkos::CudaSpace::execution_space, Kokkos::CudaSpace::memory_space>>, Kokkos::Random_XorShift64_Pool<Kokkos::Device<Kokkos::CudaSpace::execution_space, Kokkos::CudaSpace::memory_space>>, 128, 2, int64_t>]"
../../kokkos/algorithms/src/Kokkos_Random.hpp(1784): here
            instantiation of "void Kokkos::fill_random(ViewType, RandomPool, ViewType::const_value_type) [with ViewType=Kokkos::View<double **, Kokkos::Device<Kokkos::CudaSpace::execution_space, Kokkos::CudaSpace::memory_space>>, RandomPool=Kokkos::Random_XorShift64_Pool<Kokkos::Device<Kokkos::CudaSpace::execution_space, Kokkos::CudaSpace::memory_space>>, IndexType=int64_t]"
../../packages/intrepid2/unit-test/Discretization/Basis/HGRAD_TRI_Cn_FEM/test_02.hpp(88): here
            instantiation of "int Intrepid2::Test::HGRAD_TRI_Cn_FEM_Test02<OutValueType,PointValueType,DeviceType>(__nv_bool) [with OutValueType=double, PointValueType=double, DeviceType=Kokkos::Device<Kokkos::CudaSpace::execution_space, Kokkos::CudaSpace::memory_space>]"

```

**Reproducer instructions**:
kokkos/kokkos@2d2087f7fd486ebdb27637eba52b1a3acd7eb933 
kokkos/kokkos-kernels@bcc505d321da561889285184a085220da8920515 
trilinos/Trilinos@ca382dbdb180a8a54c553d6677635091344184a4  (kokkos-promotion branch)

To build Trilinos with kokkos and/or kokkos-kernels develop branches using source override of the Trilinos packages, follow these instructions: https://github.com/kokkos/kokkos/wiki/Compiling#building-trilinos-with-kokkos-develop-branch

```
# Weaver env
export ATDM_CONFIG_REGISTER_CUSTOM_CONFIG_DIR=$TRILINOS_DIR/cmake/std/atdm/contributed/weaver
source $TRILINOS_DIR/cmake/std/atdm/load-env.sh weaver-cuda-10.1-opt
export ATDM_CONFIG_USE_NINJA=OFF
export OMPI_CXX=$KOKKOS_PATH/bin/nvcc_wrapper

# Configuration
cmake \
  -DTrilinos_CONFIGURE_OPTIONS_FILE:STRING=cmake/std/atdm/ATDMDevEnv.cmake  \
  -DCMAKE_INSTALL_PREFIX="${PWD}/install" \
  -DTrilinos_ENABLE_TESTS=OFF \
  -DTrilinos_ENABLE_Kokkos=ON \
  -DTrilinos_ENABLE_KokkosKernels=ON \
  -DTrilinos_ENABLE_Intrepid2=ON \
  -DIntrepid2_ENABLE_TESTS=ON \
  -DCMAKE_CXX_STANDARD=14 \
  -DKokkos_SOURCE_DIR_OVERRIDE:STRING=kokkos \
  -DKokkosKernels_SOURCE_DIR_OVERRIDE:STRING=kokkos-kernels \
$TRILINOS_DIR
```

Alternatively, kokkos-dev-2 can be used to reproduce with these environment changes:
```
export ATDM_CONFIG_REGISTER_CUSTOM_CONFIG_DIR=$TRILINOS_DIR/cmake/std/atdm/contributed/kokkos-dev-2
source ~/Trilinos/cmake/std/atdm/load-env.sh kokkos-dev-2-cuda-opt
module swap sems-archive-cmake/3.12.2 sems-archive-cmake/3.17.1
```

I confirmed the configure above successfully builds with kokkos/kokkos@2f5a088c72872c5a5ed27c08e61e2bc13644ace9, sha prior to merge of #4675

@kyungjoo-kim can you investigate or give feedback regarding the Intrepid2 errors posted above and how they relate to the changes in #4675?

### PR DESCRIPTION
**Pull request by masterleinad**
Fixes #4723 by using the device type everywhere (and making sure that we really use a device type even if `DeviceType` is not).

### CODE REVIEW

File: algorithms/src/Kokkos_Random.hpp [hunk 1]
```diff
@@ -685,9 +688,9 @@ struct Random_UniqueIndex<Kokkos::Experimental::HIP> {
 #endif
 
 #ifdef KOKKOS_ENABLE_SYCL
-template <>
-struct Random_UniqueIndex<Kokkos::Experimental::SYCL> {
-  using locks_view_type = View<int**, Kokkos::Experimental::SYCL>;
+template <class MemorySpace>
+struct Random_UniqueIndex<Kokkos::Experimental::SYCL, MemorySpace> {
+  using locks_view_type = View<int**, Kokkos::Experimental::SYCL, MemorySpave>;
```
Comment (PhilMiller) [inline algorithms/src/Kokkos_Random.hpp:693]:
```suggestion
  using locks_view_type = View<int**, Kokkos::Experimental::SYCL, MemorySpace>;
```

**Comment by ndellingwood** [comment]
@masterleinad this resolved the Intrepid2 compilation issue

File: algorithms/src/Kokkos_Random.hpp [hunk 2]
```diff
@@ -629,9 +630,10 @@ struct Random_UniqueIndex {
 };
 
 #ifdef KOKKOS_ENABLE_CUDA
-template <>
-struct Random_UniqueIndex<Kokkos::Cuda> {
-  using locks_view_type = View<int**, Kokkos::Cuda>;
+template <class MemorySpace>
+struct Random_UniqueIndex<Kokkos::Cuda, MemorySpace> {
```
Comment (dalg24) [inline algorithms/src/Kokkos_Random.hpp:634]:
```suggestion
template <class MemorySpace>
struct Random_UniqueIndex<Kokkos::Device<Kokkos::Cuda, MemorySpace>> {
```

File: algorithms/src/Kokkos_Random.hpp [hunk 3]
```diff
@@ -617,9 +617,10 @@ struct Random_XorShift1024_UseCArrayState<Kokkos::Experimental::OpenMPTarget>
     : std::false_type {};
 #endif
 
-template <class ExecutionSpace>
+template <class ExecutionSpace, class MemorySpace>
 struct Random_UniqueIndex {
```
Comment (dalg24) [inline algorithms/src/Kokkos_Random.hpp:621]: Template it on the device type

**Review by dalg24 — CHANGES_REQUESTED** [review]

File: algorithms/src/Kokkos_Random.hpp (hunk 3 above)
Comment (masterleinad) [reply algorithms/src/Kokkos_Random.hpp:621]: See [`c7fbcb7` (#4724)](https://github.com/kokkos/kokkos/pull/4724/commits/c7fbcb79cfbad0406200ab7fa89159f11edd8573).

File: algorithms/src/Kokkos_Random.hpp [hunk 4]
```diff
@@ -887,18 +896,20 @@ class Random_XorShift64 {
...
+  using locks_type      = View<int**, device_type>;
+  using state_data_type = View<uint64_t**, device_type>;
   locks_type locks_;
   state_data_type state_;
   int num_states_;
   int padding_;
 
  public:
   using generator_type = Random_XorShift64<DeviceType>;
-  using device_type    = DeviceType;
```
Comment (dalg24) [inline algorithms/src/Kokkos_Random.hpp:901]: Undo.  It bloats the diff and makes us interleave public and private members with no obvious improvement.

File: algorithms/src/Kokkos_Random.hpp [hunk 5]
```diff
@@ -1151,8 +1164,6 @@ class Random_XorShift1024_Pool {
  public:
   using generator_type = Random_XorShift1024<DeviceType>;
 
-  using device_type = DeviceType;
-
```
Comment (dalg24) [inline algorithms/src/Kokkos_Random.hpp:1155]: Undo this too

**Review by dalg24 — DISMISSED** [review]

File: algorithms/src/Kokkos_Random.hpp (hunk 4 above)
Comment (masterleinad) [reply algorithms/src/Kokkos_Random.hpp:901]: The improvement is that we are sure that `device_type` is a device type in fact.

Comment (dalg24) [reply algorithms/src/Kokkos_Random.hpp:901]: Oh you are right I missed that

**Review by crtrott — APPROVED** [review]

**Review by dalg24 — APPROVED** [review]
