### PR TITLE
Do not specify alignment attribute with MSVC

### LINKED ISSUE #8409: Kokkos core build issues on Windows
**Describe the bug**

Xyce is encountering a compile-time error trying to build the Trilinos development branch on Windows using Intel oneAPI (Version 2022.1.0) compiler with VS2022 (version 17.4.2).  

- When the preprocessor definition for _WIN32 is set, the definition of KOKKOS_IMPL_ALIGN_PTR is incorrect; align_value is not a valid __declspec option, it should be align.  (Kokkos_Macros.hpp)
- The KOKKOS_IMPL_ALIGN_PTR is also applied incorrectly in the typedef. The align attribute should be in front of the type it applies to.  (Kokkos_ViewMapping.hpp)

We have provided a patch (below) for those files that fixes the issue on Xyce Windows development and test machine.

**Please include the following for a minimal reproducer**

1. Compilers (with versions):  Intel oneAPI (Version 2022.1.0) compiler with VS2022 (version 17.4.2)
2. Kokkos release or commit used (i.e., the sha1 number):  
3. Platform, architecture and backend:  Windows
4. CMake configure command  

[windows_cmake.txt](https://github.com/user-attachments/files/22176361/windows_cmake.txt)

5. Output from CMake configure command 

[build_cmake.txt](https://github.com/user-attachments/files/22176621/build_cmake.txt)

6. Minimum, complete code needed to reproduce the bug:  The compile-time errors occurred while building Trilinos.
7. Command line needed to reproduce the bug:  (see above)
8. `KokkosCore_config.h` header file (generated during the build)
9. Please provide any additional relevant error logs
[0001-Fix-definitions-for-Windows-compiler-compatibility.patch](https://github.com/user-attachments/files/22141815/0001-Fix-definitions-for-Windows-compiler-compatibility.patch)

### PR DESCRIPTION
**Pull request by dalg24**
On behalf of @jdschic

Fix #8409

### CODE REVIEW

File: core/src/Kokkos_Macros.hpp [hunk 1]
```diff
@@ -131,6 +131,11 @@
 
 #if defined(__INTEL_LLVM_COMPILER)
 #define KOKKOS_COMPILER_INTEL_LLVM __INTEL_LLVM_COMPILER
+#if defined(_MSC_VER)
+// Check this after Intel and Clang because those define _MSC_VER for
+// compatibility
+#define KOKKOS_COMPILER_MSVC _MSC_VER
+#endif
```
Comment (dalg24) [inline core/src/Kokkos_Macros.hpp]: Hmmmm I expect this will fail https://github.com/kokkos/kokkos/blob/b1e5aa7e9e21e5f32863e4e5311ee7f4069009e3/core/unit_test/TestCompilerMacros.cpp#L20-L29

Did you try w/o that change?

Comment (crtrott) [reply core/src/Kokkos_Macros.hpp]: Yeah we definitely don't want to of these defined.

Comment (dalg24) [reply core/src/Kokkos_Macros.hpp]: I reverted that hunk.  @jdschic please confirm that this PR still resolves the issue your reported.

Comment (crtrott) [reply core/src/Kokkos_Macros.hpp]: I think the problem is that he is trying to use Intel compiler on windows and it behaves in some instances like MSVC including defining the MSVC macro?

**Comment by dalg24** [comment]
Ping @hkthorn

**Comment by hkthorn** [comment]
@dalg24  Working with Xyce developer to review PR.  However, the issue report is lacking context for the KOKKOS_COMPILER_MSVC change, which I will add.

**Comment by hkthorn** [comment]
The Xyce team submitted a ticket to Intel’s Developer Products Support team for additional information on the use of the align_value attribute with their OneAPI C++ compiler. Here is part of the response received:
```
Currently "__declspec(align_value(x))" isn't supported on Windows platform. I will open a request to update the description in the compiler documentation.
```
So, we recommend using an empty string definition for the KOKKOS_IMPL_ALIGN_PTR macro on Windows systems. The attached patch file includes the recommended change. Instead of explicitly defining this macro for Windows systems, Windows compilers should use the fall-through value (empty string).
[kokkos_fix_pointer_align_on_windows.patch](https://github.com/user-attachments/files/22471110/kokkos_fix_pointer_align_on_windows.patch)

File: core/src/Kokkos_Macros.hpp [hunk 2]
```diff
@@ -200,7 +200,7 @@
 
 #ifndef KOKKOS_IMPL_ALIGN_PTR
 #if defined(_WIN32)
-#define KOKKOS_IMPL_ALIGN_PTR(size) __declspec(align_value(size))
+#define KOKKOS_IMPL_ALIGN_PTR(size)
```
Comment (masterleinad) [inline core/src/Kokkos_Macros.hpp:203]: I'd like to understand why we have never seen an issue here. https://godbolt.org/z/E5hnecejE shows that we should see a compiler error immediately.
Of course, the code paths possibly affected are only for the legacy View implementations.

Comment (dalg24) [reply core/src/Kokkos_Macros.hpp:203]: My best guess is that we don't have coverage for the `Aligned` memory trait

Comment (crtrott) [reply core/src/Kokkos_Macros.hpp:203]: No this is a misunderstanding. I think the problem is only with Intel compiler used on windows.

**Review by crtrott — CHANGES_REQUESTED** [review]
I believe the reported issue is only for using intel compiler on windows not msvc.

**Comment by crtrott** [comment]
I believe the macro guard should be changed to either
```
#if defined(_WIN32) && !defined(KOKKOS_COMPILER_INTEL_LLVM)
```
or
```
#if defined(KOKKOS_COMPILER_MSVC)
```

File: core/src/Kokkos_Macros.hpp (hunk 2 above)
Comment (masterleinad) [reply core/src/Kokkos_Macros.hpp:203]: No https://godbolt.org/z/E5hnecejE uses MSVC

**Comment by dalg24** [comment]
Please take this PR over

File: core/src/Kokkos_Macros.hpp (hunk 2 above)
Comment (masterleinad) [reply core/src/Kokkos_Macros.hpp:203]: > My best guess is that we don't have coverage for the Aligned memory trait

https://github.com/kokkos/kokkos/blob/6a79ad9512b315c4ae500d74cf769cdcef7edbc0/core/unit_test/TestViewSubview.hpp#L2110-L2186 is supposed to check building with all memory traits.

**Review by crtrott — APPROVED** [review]
OK fine, not sure what happened here in the first place. In principle there is a declspec(align) but it goes into a different position with MSVC.
