### PR TITLE
Replace calls to kokkos_malloc/free with HostSpace::[de]allocate during the initialization and destruction of Threads backend

### LINKED ISSUE #7944: Incorrect call to kokkos_malloc while initializing the Threads backend
This bug has come to light while running the CI checks for PR [7676](https://github.com/kokkos/kokkos/pull/7676). In this PR, we are checking if memory management functions (`kokkos_malloc`, `kokkos_realloc`, `kokkos_free`) are called properly. i.e., after `Kokkos::initialize()` and before `Kokkos::finalize()`. Otherwise, the plan is to abort with a suitable error message (e.g., `Kokkos ERROR: attempting to perform C-style memory management via kokkos_malloc() **before** Kokkos::initialize() was called` etc).

In the CI checks, there are four groups of tests based on the C++ threads backend. This backend can be enabled via the CMake keyword: `Kokkos_ENABLE_THREADS`. We are observing that there are several failed tests in all four of them. It is the same set of tests for [clang++](https://github.com/kokkos/kokkos/actions/runs/13772306621/job/39770658261?pr=7676), [g++](https://github.com/kokkos/kokkos/actions/runs/13772306621/job/39770660140?pr=7676) and [arm64](https://github.com/kokkos/kokkos/actions/runs/13772306621/job/39770660140?pr=7676). [osx-x64](https://github.com/kokkos/kokkos/actions/runs/13772306621/job/39770653592?pr=7676) fails a smaller subset of the same tests.

All the failures are due to the new check that is being introduced in PR 7676: Abort with the message `Kokkos ERROR: attempting to perform C-style memory management via kokkos_malloc() **before** Kokkos::initialize() was called`).

Through these failed tests it has come to light that `kokkos_malloc` is currently being called while initializing the Threads backend (via `Kokkos::initialize()`).

Here is one way to obtain the call stack of `Kokkos::initialize()` with the Threads backend. The following snippet of code, was compiled and run with the implementation of Kokkos in PR 7676 for the Threads backend:
```
#include <Kokkos_Core.hpp>

int main() {
  Kokkos::initialize();
}
```
The relevant part of the backtrace in gdb is:
```
#8  0x00005555555a3dad in Kokkos::kokkos_malloc<Kokkos::HostSpace> (arg_alloc_label="Kokkos::thread_scratch", arg_alloc_size=2048) at .../core/src/Kokkos_Core.hpp:171
#9  0x00005555555a23fc in Kokkos::Impl::ThreadsInternal::first_touch_allocate_thread_private_scratch (exec=...) at .../core/src/Threads/Kokkos_Threads_Instance.cpp:369
#10 0x00005555555a22fe in Kokkos::Impl::ThreadsInternal::execute_resize_scratch_in_serial () at .../core/src/Threads/Kokkos_Threads_Instance.cpp:344
#11 0x00005555555a25c8 in Kokkos::Impl::ThreadsInternal::resize_scratch (reduce_size=1024, thread_size=1024) at .../core/src/Threads/Kokkos_Threads_Instance.cpp:405
#12 0x00005555555a2e44 in Kokkos::Impl::ThreadsInternal::initialize (thread_count_arg=-1) at .../core/src/Threads/Kokkos_Threads_Instance.cpp:579
#13 0x00005555555a3788 in Kokkos::Threads::impl_initialize (settings=...) at .../core/src/Threads/Kokkos_Threads_Instance.hpp:560
#14 0x00005555555a4ede in Kokkos::Impl::ExecSpaceDerived<Kokkos::Threads>::initialize (this=0x555555655ee0, settings=...) at .../core/src/impl/Kokkos_ExecSpaceManager.hpp:127
#15 0x000055555555ee41 in Kokkos::Impl::ExecSpaceManager::initialize_spaces (this=0x5555555e1900 <Kokkos::Impl::ExecSpaceManager::get_instance()::space_initializer>, settings=...) at .../core/src/impl/Kokkos_Core.cpp:231
#16 0x000055555556083b in (anonymous namespace)::initialize_backends (settings=...) at .../core/src/impl/Kokkos_Core.cpp:453
#17 0x00005555555627cb in (anonymous namespace)::initialize_internal (settings=...) at .../core/src/impl/Kokkos_Core.cpp:797
#18 0x0000555555563bc6 in Kokkos::initialize (settings=...) at .../core/src/impl/Kokkos_Core.cpp:1075
#19 0x000055555555c73d in main ()
```
Note: Unnecessary path information has been replaced by `...` for clarity. This backtrace was obtained after the abort that happens in PR 7676, when `kokkos_malloc` is improperly called. However, the same call stack is what is expected while calling `Kokkos::initialize` using a current version of Kokkos with the Threads backend. The abort caused by PR 7676 was used as a hack to get the call stack.

The call to `kokkos_malloc` should be replaced by a memory allocation function that is native to the Threads backend. An approach based on `std::malloc` may do the needful. The initialization of other backends are based on memory allocation functions that are native to those backends (e.g., there is this `allocate` function for `Kokkos::HIPSpace`).

### PR DESCRIPTION
**Pull request by science-enthusiast**
Fixes [7944](https://github.com/kokkos/kokkos/issues/7944).

Since [7676](https://github.com/kokkos/kokkos/pull/7676) C-sytle memory management functions (kokkos_malloc, kokkos_realloc, kokkos_free) can be called only inside an active Kokkos execution environment.

The changes concern `core/src/Threads/Kokkos_Threads_Instance.cpp`.
In the Threads backend, `kokkos_malloc` (and potentially `kokkos_free`) are currently called during the initialization of the Threads backend. Refer the functions `resize_scratch`, `execute_resize_scratch_in_serial` and `first_touch_allocate_thread_private_scratch`.
`kokkos_free` is also called in the destructor of `ThreadsInternal`.

`allocate` and `deallocate` from `core/src/Kokkos_HostSpace.hpp` and `core/src/impl/Kokkos_HostSpace.cpp` could substitute for `kokkos_malloc` and `kokkos_free` to allocate and deallocate the scratch space.

As a result of these changes, the checks and tests that were so far disabled for the Threads backend have been enabled.

### CODE REVIEW

File: core/src/Threads/Kokkos_Threads_Instance.cpp [hunk 1]
```diff
@@ -358,8 +362,11 @@ void ThreadsInternal::first_touch_allocate_thread_private_scratch(
   if (s_threads_process.m_scratch_thread_end) {
     // Allocate tracked memory:
     {
-      exec.m_scratch = Kokkos::kokkos_malloc<Kokkos::HostSpace>(
-          "Kokkos::thread_scratch", s_threads_process.m_scratch_thread_end);
+      using MemorySpace = typename Kokkos::HostSpace::memory_space;
+      exec.m_scratch =
+          Impl::SharedAllocationRecord<MemorySpace>::allocate_tracked(
+              MemorySpace(), "Kokkos::thread_scratch",
+              s_threads_process.m_scratch_thread_end);
```
Comment (dalg24) [inline core/src/Threads/Kokkos_Threads_Instance.cpp]: Any good reason to use `Impl::SharedAllocationRecord` here?
Could we store the scratch memory buffer as something like `std::unique_ptr<std::byte[]>`?

Comment (dalg24) [reply core/src/Threads/Kokkos_Threads_Instance.cpp]: Another option would be to look at what other backends do.
HIP and Cuda seem to go through `mem_space.allocate(...)`

**Review by dalg24 — COMMENTED** [review]
We don't want to spread direct uses of `Impl::SharedAllocationRecord` throughout the code base because that would get in the way of future refactors.

File: core/src/Threads/Kokkos_Threads_Instance.cpp (hunk 1 above)
Comment (science-enthusiast) [reply core/src/Threads/Kokkos_Threads_Instance.cpp]: I used `Impl::SharedAllocationRecord` here, thinking it was good enough for Host memory space. I have noted your point about how it gets in the way for future refactors.

I did notice `allocate` for `Kokkos::HIPSpace` and `allocate` for HostSpace in `core/src/Kokkos_HostSpace.hpp` and `core/src/impl/Kokkos_HostSpace.cpp`.

I will improve my PR.

**Comment by crtrott** [comment]
Remember to think about first touch behavior!

**Comment by science-enthusiast** [comment]
Squashed and force pushed the modifications for this commit because the feedback was given at the very beginning of the PR.

**Review by dalg24 — APPROVED** [review]
Please update the PR title line to reflect that we go through HostSpace::[de]allocate()

**Review by masterleinad — APPROVED** [review]
