### PR TITLE
Fix allocating large Views

### LINKED ISSUE #4906: Kokkos::View segfault when using runtime dimensions of 8x16 or 8x32
We found that accessing a `Kokkos::View` created with runtime dimensions of 8 produces a segfault when its dimensions are 16 or 32.

But when the view was allocated in compile time dimensions or combination of compile time and runtime dimensions, this segfault is not produced.

Here's a reproducer:
```
TEST(TEST_CATEGORY, quicktest) {
  constexpr int dim = 16;
  int idx = dim - 1;
  using ViewType = typename Kokkos::View<int********, Kokkos::DefaultExecutionSpace>;
  ViewType v(Kokkos::view_alloc("v", Kokkos::WithoutInitializing), dim, dim, dim, dim, dim, dim, dim, dim);

  Kokkos::parallel_for(1,
    KOKKOS_LAMBDA(const int&) {
      auto& lhs = v(idx, idx, idx, idx, idx, idx, idx, idx);
      lhs = 0;  // This is where it segfaults
    }
  );
}
```

* Segfault seems to happen when lhs reference is invalid as seen when running in gdb
* Usage of Kokkos::WithoutInitializing does not affect whether this segfaults or not
* Seems to segfault starting from `v(0,0,0,0,4,12,14,0)`
* This was using a serial only build and GCC 11.1.0

@nliber

### PR DESCRIPTION
**Pull request by masterleinad**
Fixes #4906. For `Kokkos::Views` with dynamic View greater or equal to 3, we use unsigned int as `type` for storing the dynamic rank. Hence, we need to explicitly cast to `size_t` in some places where we multiply the ranks and return `size_t`.
Still needs the test.

### CODE REVIEW

**Comment by fnrizzi** [comment]
@masterleinad is this ready or still draft?

**Comment by masterleinad** [comment]
> @masterleinad is this ready or still draft? ah i see, the test is missing

I just need to add a test and make sure it works on all backends. Otherwise, it's ready from my side.

**Comment by MikolajZuzek** [comment]
Hi @masterleinad!
Do you think [`operator()` in `ViewOffset`](https://github.com/kokkos/kokkos/blob/78befdea64c77a59f2cd273039aef1681098c98b/core/src/impl/Kokkos_ViewMapping.hpp#L885-L970) could also be affected and should have `size_type` casts in index multiplication ?

**Comment by masterleinad** [comment]
> Do you think [`operator()` in `ViewOffset`](https://github.com/kokkos/kokkos/blob/78befdea64c77a59f2cd273039aef1681098c98b/core/src/impl/Kokkos_ViewMapping.hpp#L885-L970) could also be affected and should have `size_type` casts in index multiplication ?

It's probably a good idea.

**Comment by PhilMiller** [comment]
Should this potentially get cherry picked for 3.6 as well?

**Comment by PhilMiller** [comment]
In operator() and other spots with nested expressions, I think the casts may need to be applied pretty much ubiquitously, since otherwise subexpressions may overflow before reaching the cast

**Comment by masterleinad** [comment]
> In operator() and other spots with nested expressions, I think the casts may need to be applied pretty much ubiquitously, since otherwise subexpressions may overflow before reaching the cast

Thinking about it, we should discuss this. I'm pretty sure that the type for the variables was chosen here due to performance implications which might matter more for View access than calling `span()` or the like. In the end, this is something that can be worked around in user code by providing the indices as `size_t`.

**Comment by masterleinad** [comment]
I marked this as ready for review and would consider making the discussion about the call operator separate.

**Review by crtrott — APPROVED** [review]

File: core/src/impl/Kokkos_ViewMapping.hpp [hunk 1]
```diff
@@ -2064,7 +2065,7 @@ struct ViewOffset<
         m_stride(
             Padding<TrivialScalarSize>::
                 stride(/* 2 <= rank */
-                       m_dim.N1 *
```
Comment (PhilMiller) [inline core/src/impl/Kokkos_ViewMapping.hpp:2067]: If you do this cast instead on `m_dim.N7`, the 'common type' of each ternary operator expression will be `size_type`, and that will bubble up through the whole expression. Doing it up here seems to assume that any potential overflow doesn't happen until the arithmetic reaches the first dimension.

Comment (masterleinad) [reply core/src/impl/Kokkos_ViewMapping.hpp:2067]: Good point.

Comment (masterleinad) [reply core/src/impl/Kokkos_ViewMapping.hpp:2067]: 043aadd7ca525aaeadc909a12e11879784a3246b

File: core/unit_test/TestViewAPI_e.hpp [hunk 2]
```diff
@@ -240,6 +240,32 @@ struct TestViewOverloadResolution {
...
 }
+
+template <typename MemorySpace>
+struct TestViewAllocationLargeRank {
+  using ViewType = Kokkos::View<char********, MemorySpace>;
+
+  KOKKOS_FUNCTION void operator()(int) const {
+    size_t idx = v.extent(0) - 1;
+    auto& lhs  = v(idx, idx, idx, idx, idx, idx, idx, idx);
+    lhs        = 0;  // This is where it segfaulted
```
Comment (PhilMiller) [inline core/unit_test/TestViewAPI_e.hpp:251]: Could this assign a non-zero value `foo`, and then assert on the host that `v.access(idx, ...) == foo`? As written, this is a weak smoke-test that the particular case doesn't happen to crash in our CI environments

**Review by PhilMiller — APPROVED** [review]
Up to you whether to make the test more demanding.

**Review by nliber — APPROVED** [review]
