### PR TITLE
[ready] algorithm: fix for error #4423

### LINKED ISSUE #4423: Nightly tests build failures with std algorithms: cuda/11.0+gcc/9.2 with c++17
Some nightly tests began failing following merge of #4315 with support for C++ algorithms.
The cuda/11.0+gcc/9.2 with c++17 build fails to compile with errors of type:

```
21:21:39 nvcc error   : 'cicc' died due to signal 11 (Invalid memory reference)
21:21:39 nvcc error   : 'cicc' core dumped
21:21:39 make[2]: *** [algorithms/unit_tests/CMakeFiles/KokkosAlgorithms_UnitTest.dir/TestStdAlgorithmsSearch_n.cpp.o] Error 139
```

**Reproducer (Cuda_Serial, kokkos-dev-2)**:
```
module load sems-env sems-cmake/3.17.1 cuda/11.0 sems-gcc/9.2.0

$KOKKOS_PATH/generate_makefile.bash --with-devices=Cuda,Serial --arch=SNB,Volta70 --compiler=$KOKKOS_PATH/bin/nvcc_wrapper --cxxflags="-O3 -Wall -Wunused-parameter -Wshadow -pedantic -Werror -Wsign-compare -Wtype-limits -Wuninitialized " --cxxstandard="17"--kokkos-path=$KOKKOS_PATH --with-options=disable_deprecated_code --with-cuda-options=enable_lambda  --no-examples
```

@cz4rs @fnrizzi are you able to take a look?

### PR DESCRIPTION
**Pull request by fnrizzi**
This fixes #4423

Original error:
```
nvcc error   : 'cicc' died due to signal 11 (Invalid memory reference)
```

Apparently, it did not like creating a vector and pushing back. So I am allocating the vector with the right size and subscripting it as needed.

### CODE REVIEW

**Review by masterleinad — APPROVED** [review]

File: algorithms/unit_tests/TestStdAlgorithmsSearch_n.cpp [hunk 1]
```diff
@@ -261,45 +261,45 @@ void run_single_scenario(const InfoType& scenario_info, std::size_t count,
...
-  scenarios.push_back(std::make_tuple("medium-c", 21103u, "random"));
-  scenarios.push_back(std::make_tuple("medium-d", 21103u, "right"));
-  scenarios.push_back(std::make_tuple("medium-e", 21103u, "left_and_1567"));
-  scenarios.push_back(std::make_tuple("medium-f", 21103u, "11133_and_right"));
-
-  scenarios.push_back(std::make_tuple("large-a", 101333u, "none"));
-  scenarios.push_back(std::make_tuple("large-b", 101333u, "left"));
-  scenarios.push_back(std::make_tuple("large-c", 101333u, "random"));
-  scenarios.push_back(std::make_tuple("large-d", 101333u, "right"));
+  std::vector<scenario_t> scenarios(31);
```
Comment (nliber) [inline algorithms/unit_tests/TestStdAlgorithmsSearch_n.cpp:264]: I know it is just a test (so not on a critical path), but why not something simple like:

```
scenarios_t senarios[] = {
  {"empty", 0u, "none"},
  {"one-element-a", 1u, "none"},
  // ...
};

```

This works because:
The size is known at compile time, so an array is preferred.
`make_tuple` is only needed for deduction, which isn't needed in this case as you know the exact type of the tuple.
`tuple` will work fine with brace initialization syntax.

**Review by nliber — CHANGES_REQUESTED** [review]

**Comment by ndellingwood** [comment]
The changes here allowed successful completion of the previously failing build from #4423, thanks!

File: algorithms/unit_tests/TestStdAlgorithmsSearch_n.cpp (hunk 1 above)
Comment (fnrizzi) [reply algorithms/unit_tests/TestStdAlgorithmsSearch_n.cpp:264]: @nliber thanks, i can make those changes!

Comment (fnrizzi) [reply algorithms/unit_tests/TestStdAlgorithmsSearch_n.cpp]: @nliber change made!

Comment (fnrizzi) [reply algorithms/unit_tests/TestStdAlgorithmsSearch_n.cpp:264]: changed it back after discussing with @nliber

**Review by nliber — APPROVED** [review]
