### PR TITLE
Switch to `find_last_of` to parse key value pairs in benchmarks

### LINKED ISSUE #8241: `Kokkos::print_configuration` and `KokkosBenchmark::add_kokkos_configuration` aren't happy together
## Observation

I'm seeing:
```bash
Failed to add custom context "Kokkos" as it already exists with value ":HIP[ 0 ] gcnArch gfx906:sramecc+:xnack- : Selected"
```

I think it comes from
https://github.com/kokkos/kokkos/blob/6adc7a05882064db2e70f0cd8503d901d51a1819/core/perf_test/Benchmark_Context.cpp#L41-L58
that parses
https://github.com/kokkos/kokkos/blob/6adc7a05882064db2e70f0cd8503d901d51a1819/core/src/HIP/Kokkos_HIP.cpp#L176-L181

It probably originates from https://github.com/kokkos/kokkos/pull/7673 (@JBludau).

## A way to fix it

`KokkosBenchmark::add_kokkos_configuration` should probably work with a `std::map<std::string, std::string>`. And so should probably `Kokkos::print_configuration`. Because the configuration seems to almost always be a `<config key> : <config value>`. Explicitly working with a map (or a more advanced JSON-like structure) would make the `Kokkos` configuration more structured.

### PR DESCRIPTION
**Pull request by JBludau**
Fixes https://github.com/kokkos/kokkos/issues/8241.
This is the quickest attempt of a fix by splitting the parsed line at the last `:` instead of the first. This only requires that the last `:` is the one delimiting key and value.

Currently we do not promise a parsable output in our `print_configuration`. We can discuss if we want to do that.
Sine `benchmark::AddCustomContext` does not error out for invalid arguments, but just prints a message our CI did not catch it. So to catch errors in the context we would need our own error detection for which we would want a parsable output of `print_configuration`

### CODE REVIEW

File: core/perf_test/Benchmark_Context.cpp [hunk 1]
```diff
@@ -45,7 +45,7 @@ void add_kokkos_configuration(bool verbose) {
   // Iterate over lines returned from kokkos and extract key:value pairs
   std::stringstream ss{msg.str()};
   for (std::string line; std::getline(ss, line, '\n');) {
-    auto found = line.find_first_of(':');
+    auto found = line.find_last_of(':');
```
Comment (romintomasetti) [inline core/perf_test/Benchmark_Context.cpp:48]: Did you check that the context is still meaningful ? (*i.e.* it solves the problem - the warning disappeared (?) - but also does not break previously OKish context)

Comment (JBludau) [reply core/perf_test/Benchmark_Context.cpp:48]:
```    "load_avg": [25.56,29.94,28.7],
    "library_build_type": "release",
    "APU or dGPU": "APU",
    "Architecture capable of accessing system allocated memory": "1",
    "CPU architecture": "none",
    "Default Device": "HIP",
    "GIT_BRANCH": "fix_benchmark_parsing",
    "GIT_CLEAN_STATUS": "CLEAN",
    "GIT_COMMIT_DATE": "2025-07-11T16:30:33-04:00",
    "GIT_COMMIT_DESCRIPTION": "switch to last of for separating the strings",
    "GIT_COMMIT_HASH": "596991861",
    "GPU architecture": "none",
    "Is Large Bar": "1",
    "KOKKOS_COMPILER_CLANG": "1900",
    "KOKKOS_ENABLE_ASM": "no",
    "KOKKOS_ENABLE_CXX17": "yes",
    "KOKKOS_ENABLE_CXX20": "no",
    "KOKKOS_ENABLE_CXX23": "no",
    "KOKKOS_ENABLE_CXX26": "no",
    "KOKKOS_ENABLE_DEBUG_BOUNDS_CHECK": "no",
    "KOKKOS_ENABLE_HIP": "yes",
    "KOKKOS_ENABLE_HIP_RELOCATABLE_DEVICE_CODE": "no",
    "KOKKOS_ENABLE_HWLOC": "no",
    "KOKKOS_ENABLE_LIBDL": "yes",
    "KOKKOS_ENABLE_PRAGMA_IVDEP": "no",
    "KOKKOS_ENABLE_PRAGMA_LOOPCOUNT": "no",
    "KOKKOS_ENABLE_PRAGMA_UNROLL": "no",
    "KOKKOS_ENABLE_PRAGMA_VECTOR": "no",
    "KOKKOS_ENABLE_SERIAL": "yes",
    "Kernel reports HMM module via `CONFIG_HMM_MIRROR=y` in `/boot/config`": "yes",
    "Kokkos Version": "4.6.99",
    "Kokkos::HIP[ 0 ] gcnArch gfx942:sramecc+:xnack-": "Selected",
    "Kokkos::HIP[ 1 ] gcnArch gfx942:sramecc+": "xnack-",
    "Kokkos::HIP[ 2 ] gcnArch gfx942:sramecc+": "xnack-",
    "Kokkos::HIP[ 3 ] gcnArch gfx942:sramecc+": "xnack-",
    "Shared Memory per Block": "64 KiB",
    "Supports Managed Memory": "1",
    "System allows accessing system allocated memory on GPU": "0",
    "Total Global Memory": "94.08 GiB",
    "Wavefront Size": "64",
    "XNACK environment variable set": "no",
    "macro  KOKKOS_ENABLE_HIP": "defined",
    "macro KOKKOS_ENABLE_IMPL_HIP_MALLOC_ASYNC": "yes",
    "macro KOKKOS_ENABLE_ROCTHRUST": "defined",
    "platform": "64bit"

Comment (JBludau) [reply core/perf_test/Benchmark_Context.cpp:48]: I added a `Not selected` for GPUs that we don't use. Together with using `last_of` it should be a usable fix for now

Comment (romintomasetti) [reply core/perf_test/Benchmark_Context.cpp:48]: What does it look like with your "Not selected" for a multi-GPU?

Comment (JBludau) [reply core/perf_test/Benchmark_Context.cpp:48]: Come on Romin, just use your imagination:
```
    "KOKKOS_COMPILER_CLANG": "1900",
    "KOKKOS_ENABLE_ASM": "no",
    "KOKKOS_ENABLE_CXX17": "yes",
    "KOKKOS_ENABLE_CXX20": "no",
    "KOKKOS_ENABLE_CXX23": "no",
    "KOKKOS_ENABLE_CXX26": "no",
    "KOKKOS_ENABLE_DEBUG_BOUNDS_CHECK": "no",
    "KOKKOS_ENABLE_HIP": "yes",
    "KOKKOS_ENABLE_HIP_RELOCATABLE_DEVICE_CODE": "no",
    "KOKKOS_ENABLE_HWLOC": "no",
    "KOKKOS_ENABLE_LIBDL": "yes",
    "KOKKOS_ENABLE_PRAGMA_IVDEP": "no",
    "KOKKOS_ENABLE_PRAGMA_LOOPCOUNT": "no",
    "KOKKOS_ENABLE_PRAGMA_UNROLL": "no",
    "KOKKOS_ENABLE_PRAGMA_VECTOR": "no",
    "KOKKOS_ENABLE_SERIAL": "yes",
    "Kernel reports HMM module via `CONFIG_HMM_MIRROR=y` in `/boot/config`": "yes",
    "Kokkos Version": "4.6.99",
    "Kokkos::HIP[ 0 ] gcnArch gfx942:sramecc+:xnack-": "Selected",
    "Kokkos::HIP[ 1 ] gcnArch gfx942:sramecc+:xnack-": "Not Selected",
    "Kokkos::HIP[ 2 ] gcnArch gfx942:sramecc+:xnack-": "Not Selected",
    "Kokkos::HIP[ 3 ] gcnArch gfx942:sramecc+:xnack-": "Not Selected",
    "Shared Memory per Block": "64 KiB",
    "Supports Managed Memory": "1",
    "System allows accessing system allocated memory on GPU": "0",
    "Total Global Memory": "94.08 GiB",
    "Wavefront Size": "64",
    "XNACK environment variable set": "no",
    "macro  KOKKOS_ENABLE_HIP": "defined",
    "macro KOKKOS_ENABLE_IMPL_HIP_MALLOC_ASYNC": "yes",
    "macro KOKKOS_ENABLE_ROCTHRUST": "defined",
    "platform": "64bit"

Comment (romintomasetti) [reply core/perf_test/Benchmark_Context.cpp:48]: That’s exactly what I had in mind 😉 (I'm currently on vacation, so imagination is all I’ve got for now 🤯)

Please correct me if I’m wrong, but it looks like the "print configuration" uses the default execution space instance?

If that’s the case, then the reason GPU 0 appears as "selected" is simply because it’s the one used by the default execution space — meaning that only one GPU will ever be shown as "selected", regardless of how many are visible?

If so, I wonder if "selected" is the most accurate term.

Maybe labeling GPUs as either "visible" or "default" would be clearer? With only one GPU marked as the default.

Does this make sense?

Comment (JBludau) [reply core/perf_test/Benchmark_Context.cpp:48]: You are right and I am for revising that. But I think it is reasonable to move that into an issue for the next pr. This one is focused on making our benchmarks have usable context instead of a warning. 

I created https://github.com/kokkos/kokkos/issues/8281

**Review by crtrott — APPROVED** [review]

**Review by ldh4 — APPROVED** [review]

**Review by tretre91 — COMMENTED** [review]
The lines for the values of `CUDA_VERSION` and `HIP_VERSION` are discarded, as there is no colon (for example `macro  HIP_VERSION = 60140093 = version 6.1.40093`)

**Comment by JBludau** [comment]
> The lines for the values of `CUDA_VERSION` and `HIP_VERSION` are discarded, as there is no colon (for example `macro HIP_VERSION = 60140093 = version 6.1.40093`)

yeah, you are right. I will add a :

**Review by tretre91 — APPROVED** [review]
