### PR TITLE
Fix create_mirror_view_and_copy() for const data type

### LINKED ISSUE #2932: c8aee0d8 (#2911) makes create_mirror_view_and_copy() trigger a static_assert about copying to const
Before revision c8aee0d8, if view v has a const value type, it was allowed to do:
```
auto v_host = Kokkos::create_mirror_view_and_copy(Kokkos::HostSpace(), v);
```
But after, this code causes a static_assert to fail:
```
/ascldap/users/bmkelle/KK_FixSpgemmColor/kokkos-kernels/unit_test/graph/Test_Graph_graph_color_distance2.hpp:420:1:   required from here
/home/bmkelle/KK_FixSpgemmColor/ompBuild/kokkos-install/include/Kokkos_CopyViews.hpp:1756:72: error: static assertion failed: deep_copy requires non-const destination type
 1756 |                              typename dst_type::non_const_value_type>::value,
      |                                                                        ^~~~~
/home/bmkelle/KK_FixSpgemmColor/ompBuild/kokkos-install/include/Kokkos_CopyViews.hpp:1932:21: error: invalid conversion from ‘const void*’ to ‘void*’ [-fpermissive]
 1932 |       Kokkos::Impl::DeepCopy<dst_memory_space, src_memory_space>(
      |                     ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
      |                     |
      |                     const void*
 1933 |           dst.data(), src.data(), nbytes);
      |           ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
```

### PR DESCRIPTION
**Pull request by dalg24**
Fix #2932

### CODE REVIEW

File: core/src/Kokkos_CopyViews.hpp [hunk 1]
```diff
@@ -3560,8 +3560,7 @@ create_mirror_view_and_copy(
         Impl::MirrorViewType<Space, T, P...>::is_same_memspace>::type* =
         nullptr) {
   (void)name;
-  // Inherit fencing behavior of deep_copy
-  deep_copy(src, src);
+  fence();  // same behavior as deep_copy(src, src)
```
Comment (masterleinad) [inline core/src/Kokkos_CopyViews.hpp:3563]:
```suggestion
  Kokkos::fence();  // same behavior as deep_copy(src, src)
```
since this is what we do everywhere else. Is it necessary to fence all execution spaces here or do you want `space.fence()` here?

Comment (dalg24) [reply core/src/Kokkos_CopyViews.hpp:3563]: `Space` can be a memory space

File: core/unit_test/TestViewAPI.hpp [hunk 2]
```diff
@@ -841,6 +841,24 @@ struct TestViewMirror {
...
+  }
+
+  static void test_mirror_copy_const_data_type() {
+    using ExecutionSpace = typename DeviceType::execution_space;
+    int const N          = 100;
+    Kokkos::View<int *, ExecutionSpace> v("v", N);
+    Kokkos::deep_copy(v, 255);
+    auto v_m1 = Kokkos::create_mirror_view_and_copy(
+        Kokkos::DefaultHostExecutionSpace(), view_const_cast(v));
+    ASSERT_TRUE(run_check(v_m1, 255));
```
Comment (dalg24) [inline core/unit_test/TestViewAPI.hpp:856]: I moved it from `core/unit_test/TestViewCopy.hpp` and of course `run_check()` is not defined there
