### PR TITLE
SYCL: Fix Windows build issues

### LINKED ISSUE #9034: Windows + SYCL build fails (`__assert_fail` undeclared, `sycl::nan` ambiguous)
## Describe the bug

When configuring Kokkos with SYCL on Windows using Intel oneAPI `icx`, the build fails with 2 errors. 

1. `use of undeclared identifier '__assert_fail'` in `SYCL/Kokkos_SYCL_Abort.hpp`
2. `call to 'nan' is ambiguous` in `Kokkos_MathematicalFunctions.hpp` at `sycl::nan(0ul)`

I've attached the full output to this issue. See point 9.

### 1) Compilers (with versions)
- C/C++ compiler: Intel oneAPI DPC++/C++ Compiler `icx` Version: `2025.3.2` 

### 2) Kokkos release or commit used (sha1)
- tested 5.1.0 and 5.0.0

### 3) Platform, architecture and backend
Platform - Windows 11 Pro, Version 25H2 (OS Build 26200.8037)
Architecture - x64
backend - SYCL

### 4) CMake configure command
cmake -B build_dir_sycl -G Ninja -DCMAKE_CXX_COMPILER=icx -DKokkos_ENABLE_SYCL=ON -DKokkos_ARCH_INTEL_GEN=ON

### 5) Output from CMake configure command
```
C:\Users\WilliamSati\source\repos\kokkos-tutorials\Exercises\02\Solution>cmake -B build_dir_sycl -G Ninja -DCMAKE_CXX_COMPILER=icx -DKokkos_ENABLE_SYCL=ON -DKokkos_ARCH_INTEL_GEN=ON
-- Could NOT find Kokkos (missing: Kokkos_DIR)
-- Setting default Kokkos CXX standard to 20
-- Kokkos version: 5.0.0
-- The project name is: Kokkos
-- Using internal gtest for testing
-- Kokkos is configured for CMake languages CXX compilation (using IntelLLVM version 2025.3.2)
-- Using -Qstd:c++20 for C++20 extensions as feature
-- Built-in Execution Spaces:
--     Device Parallel: Kokkos::SYCL
--     Host Parallel: NoTypeDefined
--       Host Serial: SERIAL
--
-- Architectures:
--  INTEL_GEN
-- Using bundled desul_atomics copy (desul/desul@79f928075837ffb5d302aae188e0ec7b7a79ae94)
-- Performing Test KOKKOS_LINK_OPTIONS_CHECK
-- Performing Test KOKKOS_LINK_OPTIONS_CHECK - Success
-- Performing Test KOKKOS_COMPILE_OPTIONS_CHECK
-- Performing Test KOKKOS_COMPILE_OPTIONS_CHECK - Success
-- Using bundled mdspan copy (kokkos/mdspan@537053f83150f1b6f7528c1d961866d8628abc2e)
-- Kokkos Backends: SERIAL;SYCL
-- Configuring done (33.9s)
-- Generating done (0.4s)
-- Build files have been written to: C:/Users/WilliamSati/source/repos/kokkos-tutorials/Exercises/02/Solution/build_dir_sycl
```
### 6) Minimum, complete code needed to reproduce the bug

The failure occurs while compiling Kokkos core itself, so a minimal executable is enough:

```cpp
#include <Kokkos_Core.hpp>

int main(int argc, char* argv[]) {
  Kokkos::initialize(argc, argv);
  Kokkos::finalize();
  return 0;
}
```

### 7) Command line needed to reproduce the bug

in cmd:
```
rmdir /s /q build_dir_sycl
"C:\Program Files (x86)\Intel\oneAPI\setvars.bat"
cmake -B build_dir_sycl -G Ninja -DCMAKE_CXX_COMPILER=icx -DKokkos_ENABLE_SYCL=ON -DKokkos_ARCH_INTEL_GEN=ON
cmake --build build_dir_sycl
```

### 8) `KokkosCore_config.h` header file (generated during build)

[kokkoscore_config.txt](https://github.com/user-attachments/files/26448844/kokkoscore_config.txt)

### 9) Additional relevant error logs
full build output attached

[output.txt](https://github.com/user-attachments/files/26448774/output.txt)

### PR DESCRIPTION
**Pull request by masterleinad**
Fixes https://github.com/kokkos/kokkos/issues/9034.

### CODE REVIEW

File: core/src/SYCL/Kokkos_SYCL_Abort.hpp [hunk 1]
```diff
@@ -14,11 +14,16 @@ namespace Impl {
 inline void sycl_abort(char const* msg) {
 #ifdef NDEBUG
   Kokkos::printf("Aborting with message %s.\n", msg);
+#else
+// FIXME_WINDOWS __assert_fail isn't defined
+#ifdef _MSC_VER
+  (void)msg;
```
Comment (janciesko) [inline core/src/SYCL/Kokkos_SYCL_Abort.hpp]: We probably still want to abort here?


```suggestion
  (void)msg;
  abort();
```

Comment (masterleinad) [reply core/src/SYCL/Kokkos_SYCL_Abort.hpp]: `abort` isn't defined in device code.

**Review by ndellingwood — APPROVED** [review]

**Comment by ndellingwood** [comment]
Jenkins OPENACC-NVHPC-CUDA-12.2 build [failed](https://cloud1.cees.ornl.gov/jenkins-ci/job/Kokkos/job/PR-9043/1/stages/?selected-node=186) due to `Disk quota exceeded`, unrelated to PR changes:
```
stderr: error: copy-fd: write returned: Disk quota exceeded
fatal: cannot copy '/usr/share/git-core/templates/description' to '/var/jenkins/workspace/Kokkos/PR-9043/.git/description': Disk quota exceeded
	at PluginClassLoader for git-client//org.jenkinsci.plugins.gitclient.CliGitAPIImpl.launchCommandIn(CliGitAPIImpl.java:2848)
	at PluginClassLoader for git-client//org.jenkinsci.plugins.gitclient.CliGitAPIImpl.launchCommandIn(CliGitAPIImpl.java:2773)
	at PluginClassLoader for git-client//org.jenkinsci.plugins.gitclient.CliGitAPIImpl.launchCommandIn(CliGitAPIImpl.java:2768)
	at PluginClassLoader for git-client//org.jenkinsci.plugins.gitclient.CliGitAPIImpl.launchCommand(CliGitAPIImpl.java:2055)
	at PluginClassLoader for git-client//org.jenkinsci.plugins.gitclient.CliGitAPIImpl$5.execute(CliGitAPIImpl.java:1080)
	... 12 more
ERROR: Error cloning remote repo 'origin'
```

[SNL_HPX_GCC_15_1_1](https://github.com/kokkos/kokkos/actions/runs/24040541821/job/70110892474?pr=9043#logs) failure addressed in https://github.com/kokkos/kokkos/pull/9044 (unrelated to changes in this PR)

File: core/src/Kokkos_MathematicalFunctions.hpp [hunk 2]
```diff
@@ -529,8 +530,12 @@ KOKKOS_INLINE_FUNCTION double nan(char const* arg) { return ::nan(arg); }
 // sycl::nan does not follow the C/C++ standard library and takes an unsigned
 // integer as argument.  The current implementation does not attempt to convert
 // the character string arg into the quiet NaN value.
-KOKKOS_INLINE_FUNCTION float nanf(char const*) { return sycl::nan(0u); }
-KOKKOS_INLINE_FUNCTION double nan(char const*) { return sycl::nan(0ul); }
+KOKKOS_INLINE_FUNCTION float nanf(char const*) {
+  return sycl::nan(std::uint32_t(0));
+}
+KOKKOS_INLINE_FUNCTION double nan(char const*) {
+  return sycl::nan(std::uint64_t(0));
```
Comment (dalg24) [inline core/src/Kokkos_MathematicalFunctions.hpp:537]: I don't understand how any of these changes would help when looking at the SYCL spec.
https://github.khronos.org/SYCL_Reference/iface/math-functions.html#sycl-nan
What am I missing?

Comment (tretre91) [reply core/src/Kokkos_MathematicalFunctions.hpp:537]: They do use `std::uint16/32/64_t` in the spec https://registry.khronos.org/SYCL/specs/sycl-2020/html/sycl-2020.html#api:nan, otherwise the current implementation would compile fine.

On windows `unsigned long` is 32 bits and `std::uint32_t` is defined as `unsigned int`, so both the `sycl::nan(std::uint32_t)` and `sycl::nan(std::uin64_t)` overloads are considered by the compiler for `sycl::nan(unsigned long)`

File: core/src/SYCL/Kokkos_SYCL_Abort.hpp (hunk 1 above)
Comment (tretre91) [reply core/src/SYCL/Kokkos_SYCL_Abort.hpp]: Maybe we can still do a print even though there is no abort?

File: core/src/Kokkos_MathematicalFunctions.hpp (hunk 2 above)
Comment (dalg24) [reply core/src/Kokkos_MathematicalFunctions.hpp:537]: Thanks for the reference.
So we could also just pass `0ull` as for the function returning `double`, right?
Anyway I am not requesting change.  Up to Daniel whether to change.

File: core/src/SYCL/Kokkos_SYCL_Abort.hpp (hunk 1 above)
Comment (dalg24) [inline core/src/SYCL/Kokkos_SYCL_Abort.hpp]:
```suggestion
// FIXME_WINDOWS __assert_fail isn't defined
#if defined(NDEBUG) || defined(_MSC_VER)
  Kokkos::printf("Aborting with message %s.\n", msg);
```

File: core/src/SYCL/Kokkos_SYCL_Abort.hpp [hunk 3]
```diff
@@ -12,13 +12,15 @@ namespace Kokkos {
...
-#ifdef NDEBUG
+// FIXME_WINDOWS __assert_fail isn't defined
+#if defined(NDEBUG) || defined(_MSC_VER)
   Kokkos::printf("Aborting with message %s.\n", msg);
 #else
   // Choosing "" here causes problems but a single whitespace character works.
   const char* empty = " ";
   __assert_fail(msg, empty, 0, empty);
 #endif
+#endif
```
Comment (dalg24) [inline core/src/SYCL/Kokkos_SYCL_Abort.hpp]:
```suggestion
```

**Review by dalg24 — APPROVED** [review]

**Review by tretre91 — APPROVED** [review]

**Review by JBludau — COMMENTED** [review]
~The issue seems to state that this does not fix the problem~
After talking to @dalg24 this seems to be the correct way forward to fix the issue
