### PR TITLE
simd: Fix compile failures when ranges are not available

### LINKED ISSUE #9039: simd: Compile failures with clang/appleclang 14 and `<ranges>`
Reported here https://kokkosteam.slack.com/archives/C5BGU5NDQ/p1775139837796809

Using Kokkos 5.1 with appleclang 14 or clang 14 (with `-stdlib=libc++`) leads to compile failures because the libc++ that comes with these versions of clang has an incomplete support for `<ranges>`, some concepts and functions from `<ranges>` are used in Kokkos SIMD since 5.1.

There is no failure when using `-stdlib=libstdc++`, see https://godbolt.org/z/aEYTYqndh.

Building with the tests enabled or compiling a simple executable instantiating a simd class should reproduce the compile failure
```cpp
#include <Kokkos_SIMD.hpp>

using type_real = float;

int main() {
  constexpr int simd_size = Kokkos::Experimental::simd<type_real>::size();

  std::cout << "SIMD size: " << simd_size << std::endl;
}
```
This gives the following error
<details>

```
[ 50%] Building CXX object CMakeFiles/test.dir/main.cpp.o
In file included from /var/tmp/bug_simd_appleclang/test_kokkos/main.cpp:2:
In file included from /var/tmp/bug_simd_appleclang/kokkos/install/include/Kokkos_SIMD.hpp:8:
/var/tmp/bug_simd_appleclang/kokkos/install/include/Kokkos_SIMD_Scalar.hpp:521:45: error: no type named 'contiguous_range' in namespace 'std::ranges'
template <Impl::SimdVecType V, std::ranges::contiguous_range R,
                               ~~~~~~~~~~~~~^
/var/tmp/bug_simd_appleclang/kokkos/install/include/Kokkos_SIMD_Scalar.hpp:523:25: error: no member named 'sized_range' in namespace 'std::ranges'
  requires std::ranges::sized_range<R> &&
           ~~~~~~~~~~~~~^
In file included from /var/tmp/bug_simd_appleclang/test_kokkos/main.cpp:2:
In file included from /var/tmp/bug_simd_appleclang/kokkos/install/include/Kokkos_SIMD.hpp:44:
/var/tmp/bug_simd_appleclang/kokkos/install/include/Kokkos_SIMD_NEON.hpp:736:1: error: no type named 'contiguous_range' in namespace 'std::ranges'
KOKKOS_SIMD_IMPL_MEMORY_PERMUTE_UNCHECKED_GATHER_FROM(
^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
/var/tmp/bug_simd_appleclang/kokkos/install/include/impl/Kokkos_SIMD_Impl_Macros.hpp:21:3: note: expanded from macro 'KOKKOS_SIMD_IMPL_MEMORY_PERMUTE_UNCHECKED_GATHER_FROM'
  KOKKOS_SIMD_IMPL_MEMORY_PERMUTE_GATHER_FROM(unchecked, DATA_TYPE, ABI_TYPE, \
  ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
/var/tmp/bug_simd_appleclang/kokkos/install/include/impl/Kokkos_SIMD_Impl_Macros.hpp:9:47: note: expanded from macro 'KOKKOS_SIMD_IMPL_MEMORY_PERMUTE_GATHER_FROM'
  template <Impl::SimdVecType V, std::ranges::contiguous_range R,         \
                                 ~~~~~~~~~~~~~^
In file included from /var/tmp/bug_simd_appleclang/test_kokkos/main.cpp:2:
In file included from /var/tmp/bug_simd_appleclang/kokkos/install/include/Kokkos_SIMD.hpp:44:
/var/tmp/bug_simd_appleclang/kokkos/install/include/Kokkos_SIMD_NEON.hpp:736:1: error: no member named 'sized_range' in namespace 'std::ranges'
KOKKOS_SIMD_IMPL_MEMORY_PERMUTE_UNCHECKED_GATHER_FROM(
^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
/var/tmp/bug_simd_appleclang/kokkos/install/include/impl/Kokkos_SIMD_Impl_Macros.hpp:21:3: note: expanded from macro 'KOKKOS_SIMD_IMPL_MEMORY_PERMUTE_UNCHECKED_GATHER_FROM'
  KOKKOS_SIMD_IMPL_MEMORY_PERMUTE_GATHER_FROM(unchecked, DATA_TYPE, ABI_TYPE, \
  ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
/var/tmp/bug_simd_appleclang/kokkos/install/include/impl/Kokkos_SIMD_Impl_Macros.hpp:11:27: note: expanded from macro 'KOKKOS_SIMD_IMPL_MEMORY_PERMUTE_GATHER_FROM'
    requires std::ranges::sized_range<R> &&                               \
             ~~~~~~~~~~~~~^
In file included from /var/tmp/bug_simd_appleclang/test_kokkos/main.cpp:2:
In file included from /var/tmp/bug_simd_appleclang/kokkos/install/include/Kokkos_SIMD.hpp:44:
/var/tmp/bug_simd_appleclang/kokkos/install/include/Kokkos_SIMD_NEON.hpp:928:77: error: implicit instantiation of undefined template 'Kokkos::Experimental::basic_simd<float, Kokkos::Experimental::simd_abi::neon_fixed_size<2>>'
Experimental::basic_simd<float, Experimental::simd_abi::neon_fixed_size<2>> abs(
                                                                            ^
/var/tmp/bug_simd_appleclang/kokkos/install/include/Kokkos_SIMD_Common.hpp:35:7: note: template is declared here
class basic_simd;
      ^
In file included from /var/tmp/bug_simd_appleclang/test_kokkos/main.cpp:2:
In file included from /var/tmp/bug_simd_appleclang/kokkos/install/include/Kokkos_SIMD.hpp:44:
/var/tmp/bug_simd_appleclang/kokkos/install/include/Kokkos_SIMD_NEON.hpp:933:16: error: cannot convert 'const Experimental::basic_simd<float, Experimental::simd_abi::neon_fixed_size<2>>' to 'float32x2_t' (vector of 2 'float32_t' values) without a conversion operator
      vabs_f32(static_cast<float32x2_t>(a)));
               ^~~~~~~~~~~~~~~~~~~~~~~~~~~
/var/tmp/bug_simd_appleclang/kokkos/install/include/Kokkos_SIMD_NEON.hpp:938:1: error: implicit instantiation of undefined template 'Kokkos::Experimental::basic_simd<float, Kokkos::Experimental::simd_abi::neon_fixed_size<2>>'
floor(Experimental::basic_simd<
^
/var/tmp/bug_simd_appleclang/kokkos/install/include/Kokkos_SIMD_Common.hpp:35:7: note: template is declared here
class basic_simd;
      ^
In file included from /var/tmp/bug_simd_appleclang/test_kokkos/main.cpp:2:
In file included from /var/tmp/bug_simd_appleclang/kokkos/install/include/Kokkos_SIMD.hpp:44:
/var/tmp/bug_simd_appleclang/kokkos/install/include/Kokkos_SIMD_NEON.hpp:942:17: error: cannot convert 'const Experimental::basic_simd<float, Experimental::simd_abi::neon_fixed_size<2>>' to 'float32x2_t' (vector of 2 'float32_t' values) without a conversion operator
      vrndm_f32(static_cast<float32x2_t>(a)));
                ^~~~~~~~~~~~~~~~~~~~~~~~~~~
/var/tmp/bug_simd_appleclang/kokkos/install/include/Kokkos_SIMD_NEON.hpp:947:1: error: implicit instantiation of undefined template 'Kokkos::Experimental::basic_simd<float, Kokkos::Experimental::simd_abi::neon_fixed_size<2>>'
ceil(Experimental::basic_simd<
^
/var/tmp/bug_simd_appleclang/kokkos/install/include/Kokkos_SIMD_Common.hpp:35:7: note: template is declared here
class basic_simd;
      ^
In file included from /var/tmp/bug_simd_appleclang/test_kokkos/main.cpp:2:
In file included from /var/tmp/bug_simd_appleclang/kokkos/install/include/Kokkos_SIMD.hpp:44:
/var/tmp/bug_simd_appleclang/kokkos/install/include/Kokkos_SIMD_NEON.hpp:951:17: error: cannot convert 'const Experimental::basic_simd<float, Experimental::simd_abi::neon_fixed_size<2>>' to 'float32x2_t' (vector of 2 'float32_t' values) without a conversion operator
      vrndp_f32(static_cast<float32x2_t>(a)));
                ^~~~~~~~~~~~~~~~~~~~~~~~~~~
/var/tmp/bug_simd_appleclang/kokkos/install/include/Kokkos_SIMD_NEON.hpp:956:1: error: implicit instantiation of undefined template 'Kokkos::Experimental::basic_simd<float, Kokkos::Experimental::simd_abi::neon_fixed_size<2>>'
round(Experimental::basic_simd<
^
/var/tmp/bug_simd_appleclang/kokkos/install/include/Kokkos_SIMD_Common.hpp:35:7: note: template is declared here
class basic_simd;
      ^
In file included from /var/tmp/bug_simd_appleclang/test_kokkos/main.cpp:2:
In file included from /var/tmp/bug_simd_appleclang/kokkos/install/include/Kokkos_SIMD.hpp:44:
/var/tmp/bug_simd_appleclang/kokkos/install/include/Kokkos_SIMD_NEON.hpp:960:17: error: cannot convert 'const Experimental::basic_simd<float, Experimental::simd_abi::neon_fixed_size<2>>' to 'float32x2_t' (vector of 2 'float32_t' values) without a conversion operator
      vrndx_f32(static_cast<float32x2_t>(a)));
                ^~~~~~~~~~~~~~~~~~~~~~~~~~~
/var/tmp/bug_simd_appleclang/kokkos/install/include/Kokkos_SIMD_NEON.hpp:965:1: error: implicit instantiation of undefined template 'Kokkos::Experimental::basic_simd<float, Kokkos::Experimental::simd_abi::neon_fixed_size<2>>'
trunc(Experimental::basic_simd<
^
/var/tmp/bug_simd_appleclang/kokkos/install/include/Kokkos_SIMD_Common.hpp:35:7: note: template is declared here
class basic_simd;
      ^
In file included from /var/tmp/bug_simd_appleclang/test_kokkos/main.cpp:2:
In file included from /var/tmp/bug_simd_appleclang/kokkos/install/include/Kokkos_SIMD.hpp:44:
/var/tmp/bug_simd_appleclang/kokkos/install/include/Kokkos_SIMD_NEON.hpp:969:16: error: cannot convert 'const Experimental::basic_simd<float, Experimental::simd_abi::neon_fixed_size<2>>' to 'float32x2_t' (vector of 2 'float32_t' values) without a conversion operator
      vrnd_f32(static_cast<float32x2_t>(a)));
               ^~~~~~~~~~~~~~~~~~~~~~~~~~~
/var/tmp/bug_simd_appleclang/kokkos/install/include/Kokkos_SIMD_NEON.hpp:974:1: error: implicit instantiation of undefined template 'Kokkos::Experimental::basic_simd<float, Kokkos::Experimental::simd_abi::neon_fixed_size<2>>'
copysign(Experimental::basic_simd<
^
/var/tmp/bug_simd_appleclang/kokkos/install/include/Kokkos_SIMD_Common.hpp:35:7: note: template is declared here
class basic_simd;
      ^
In file included from /var/tmp/bug_simd_appleclang/test_kokkos/main.cpp:2:
In file included from /var/tmp/bug_simd_appleclang/kokkos/install/include/Kokkos_SIMD.hpp:44:
/var/tmp/bug_simd_appleclang/kokkos/install/include/Kokkos_SIMD_NEON.hpp:982:32: error: cannot convert 'Experimental::basic_simd<double, Experimental::simd_abi::neon_fixed_size<2>>' to 'float32x2_t' (vector of 2 'float32_t' values) without a conversion operator
          vreinterpret_u32_f32(static_cast<float32x2_t>(abs(a))),
                               ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
/var/tmp/bug_simd_appleclang/kokkos/install/include/Kokkos_SIMD_NEON.hpp:984:41: error: cannot convert 'const Experimental::basic_simd<float, Experimental::simd_abi::neon_fixed_size<2>>' to 'float32x2_t' (vector of 2 'float32_t' values) without a conversion operator
                   vreinterpret_u32_f32(static_cast<float32x2_t>(b))))));
                                        ^~~~~~~~~~~~~~~~~~~~~~~~~~~
/var/tmp/bug_simd_appleclang/kokkos/install/include/Kokkos_SIMD_NEON.hpp:989:1: error: implicit instantiation of undefined template 'Kokkos::Experimental::basic_simd<float, Kokkos::Experimental::simd_abi::neon_fixed_size<2>>'
sqrt(Experimental::basic_simd<
^
/var/tmp/bug_simd_appleclang/kokkos/install/include/Kokkos_SIMD_Common.hpp:35:7: note: template is declared here
class basic_simd;
      ^
In file included from /var/tmp/bug_simd_appleclang/test_kokkos/main.cpp:2:
In file included from /var/tmp/bug_simd_appleclang/kokkos/install/include/Kokkos_SIMD.hpp:44:
/var/tmp/bug_simd_appleclang/kokkos/install/include/Kokkos_SIMD_NEON.hpp:993:17: error: cannot convert 'const Experimental::basic_simd<float, Experimental::simd_abi::neon_fixed_size<2>>' to 'float32x2_t' (vector of 2 'float32_t' values) without a conversion operator
      vsqrt_f32(static_cast<float32x2_t>(a)));
                ^~~~~~~~~~~~~~~~~~~~~~~~~~~
fatal error: too many errors emitted, stopping now [-ferror-limit=]
20 errors generated.
gmake[2]: *** [CMakeFiles/test.dir/build.make:76 : CMakeFiles/test.dir/main.cpp.o] Erreur 1
gmake[1]: *** [CMakeFiles/Makefile2:83 : CMakeFiles/test.dir/all] Erreur 2
gmake: *** [Makefile:91 : all] Erreur 2
```

</details>

### PR DESCRIPTION
**Pull request by tretre91**
This PR adds a new macro `KOKKOS_IMPL_COMPILER_SUPPORTS_CXX20_RANGES` which is defined when the standard library used to compile Kokkos has full support for C++20 ranges. The detection relies on the feature test macro `__cpp_lib_ranges` being >= 201911L, currently the macro is made available by the `<version>` header, I noticed that we either include this or `<ciso646>` (which doesn't define feature test macros), but I'm going with the assumption that if the stdlib doesn't have `<version>` it doesn't have `<ranges>` either.
https://github.com/kokkos/kokkos/blob/10106632c6cda0c327629500e0fbabbad6372c78/core/src/Kokkos_Macros.hpp#L46-L50
In my testing this matches the minimal stdlib versions reported here https://en.cppreference.com/w/cpp/compiler_support.html#C.2B.2B20_library_features ("The One Ranges Proposal" and "Input range adaptors"), except for MSVC where 19.29 should support ranges but `_cpp_lib_ranges` is defined starting from 19.32.

The PR also introduces a `Kokkos::Experimental::Impl::Ranges` namespace in `Kokkos_SIMD_RangesCtorSupport.hpp` providing `contiguous_range`, `sized_range`, `range_value_t` and `data` (what we currently use in Kokkos SIMD). They are either aliases to the `std::ranges` versions or fallback implementations depending on whether `KOKKOS_IMPL_COMPILER_SUPPORTS_CXX20_RANGES` is defined.
All occurrences of `std::ranges::...` in the implementation have been replaced with `Impl::Ranges::...`

I tested locally that this solves the compile failures with libc++ < 16 and appleclang < 15, but we might want to add a CI configuration which results in `KOKKOS_IMPL_COMPILER_SUPPORTS_CXX20_RANGES` not being defined.

Fixes #9039

### CODE REVIEW

File: core/src/Kokkos_Macros.hpp [hunk 1]
```diff
@@ -611,4 +611,9 @@
 #define KOKKOS_IMPL_EXPORT
 #endif
 
+// Some of the compiler versions we support don't fully support C++20 ranges
+#if defined(__cpp_lib_ranges) && (__cpp_lib_ranges >= 201911L)
+#define KOKKOS_IMPL_COMPILER_SUPPORTS_CXX20_RANGES
+#endif
```
Comment (dalg24) [inline core/src/Kokkos_Macros.hpp]: Please move it to `impl/Kokkos_SIMD_Ranges.hpp‎`.

File: simd/src/impl/Kokkos_SIMD_Ranges.hpp [hunk 2]
```diff
@@ -0,0 +1,91 @@
...
+// clause as an alternative.
+template <class R>
+concept range = []() {
+  using std::begin;
+  using std::end;
+  return requires(R& r) {
+    begin(r);
+    end(r);
+  };
+}();
```
Comment (dalg24) [inline simd/src/impl/Kokkos_SIMD_Ranges.hpp]: Why are we bringing up ADL?
```suggestion
template <class R>
concept range = requires(R& r) {
    Ranges::begin(r);
    Ranges::end(r);
};
```
https://eel.is/c++draft/ranges#range.range

File: core/src/Kokkos_Macros.hpp [hunk 3]
```diff
@@ -611,4 +611,9 @@
 #define KOKKOS_IMPL_EXPORT
 #endif
 
+// Some of the compiler versions we support don't fully support C++20 ranges
```
Comment (Adrien-Tab) [inline core/src/Kokkos_Macros.hpp]: Maybe add a `FIXME` for when all compilers fully support ranges ?

**Comment by crtrott** [comment]
OK I have been thinking about this for a bit. While I dislike implementing Range light, this isn't really that. Its the kind of minimal concept to allow taking the arguments we need to be able to take. Just like 50 lines of real code, and not very complicated one at that. So I think I am ok with this.

File: simd/src/impl/Kokkos_SIMD_Ranges.hpp [hunk 4]
```diff
@@ -0,0 +1,91 @@
...
+using std::ranges::sized_range;
+}  // namespace Kokkos::Experimental::Impl::Ranges
+#else
+#include <iterator>
+
+namespace Kokkos::Experimental::Impl::Ranges {
+
+// We use this namespace to make sure that what's exposed only corresponds to
+// what is exposed in the non-fallback branch
+namespace impl {
```
Comment (crtrott) [inline simd/src/impl/Kokkos_SIMD_Ranges.hpp]:
```suggestion
namespace {
```

Doesn't this work? So we don't have `Impl::Ranges::impl`

File: simd/src/impl/Kokkos_SIMD_Ranges.hpp [hunk 5]
```diff
@@ -0,0 +1,91 @@
...
+template <class R>
+concept contiguous_range =
+    impl::range<R> &&
+#if defined(__cpp_lib_concepts) && (__cpp_lib_concepts >= 202002L)
+    std::contiguous_iterator<impl::iterator_t<R> > && requires(R& r) {
+      {
+        data(r)
+      } -> std::same_as<std::add_pointer_t<impl::range_reference_t<R> > >;
+    };
+#else
```
Comment (crtrott) [inline simd/src/impl/Kokkos_SIMD_Ranges.hpp]:
```suggestion
```

Not sure, but how about we nuke this branch. In the end all of this is only used anyway if Ranges is not implemented. So how many compiler versions are there where cpp_lib_concepts >= 202002L but ranges isn't there?

**Review by crtrott — CHANGES_REQUESTED** [review]
Two suggested changes. Not sure about the second one in particular.

File: core/src/Kokkos_Macros.hpp (hunk 1 above)
Comment (ldh4) [inline core/src/Kokkos_Macros.hpp]: I was imagining that we'd check this upfront during the cmake configuration with `check_source_compiles` and define a flag there (and maybe also a warning message about falling back to kokkos implementation of a subset of ranges).

File: simd/src/impl/Kokkos_SIMD_RangesCtorSupport.hpp
Comment (ldh4) [inline simd/src/impl/Kokkos_SIMD_RangesCtorSupport.hpp:1]: Even though `std::ranges` is currently only used in Kokkos simd, should this fallback file be limited to kokkos simd?

Comment (tretre91) [reply simd/src/impl/Kokkos_SIMD_RangesCtorSupport.hpp:1]: I'm assuming that if this is needed somewhere else in the code in the future, we will be able to move this out of simd without too much issue

File: simd/src/impl/Kokkos_SIMD_Ranges.hpp (hunk 4 above)
Comment (tretre91) [reply simd/src/impl/Kokkos_SIMD_Ranges.hpp]: It does work yes, fixed it

File: simd/src/impl/Kokkos_SIMD_Ranges.hpp (hunk 5 above)
Comment (tretre91) [reply simd/src/impl/Kokkos_SIMD_Ranges.hpp]: I removed it, as the most important constraint for us is actually the `{ data(r) } -> std::same_as<std::add_pointer_t<range_reference_t<R>>>`. For standard containers only the contiguous ones satisfy this constraint.

I also added a few more constraints in the other branch (as well as checking the type of the expresions)

File: core/src/Kokkos_Macros.hpp (hunk 1 above)
Comment (tretre91) [reply core/src/Kokkos_Macros.hpp]: Were you thinking about a check with a real source file importing and using things from ranges or a dummy file which `#error`s out if `__cpp_lib_ranges` doesn't have the right value?

I would also be in favor of having a configure-time warning.

Comment (ldh4) [reply core/src/Kokkos_Macros.hpp]: I was thinking of something like what we already do to check for neon/sve availability in `kokkos_arch.cmake`
https://github.com/kokkos/kokkos/blob/46fefe08776adf3cce345d0739b5645adc83d3fb/cmake/kokkos_arch.cmake#L288-L298
We'd include `<ranges>` and see if some basic cases like `using std::ranges::contiguous_range;` compiles.

File: simd/src/impl/Kokkos_SIMD_RangesCtorSupport.hpp
Comment (ldh4) [reply simd/src/impl/Kokkos_SIMD_RangesCtorSupport.hpp:1]: Sounds fair.

File: simd/src/impl/Kokkos_SIMD_Ranges.hpp [hunk 6]
```diff
@@ -0,0 +1,95 @@
...
+using std::ranges::data;
+using std::ranges::range_value_t;
+using std::ranges::sized_range;
+}  // namespace Kokkos::Experimental::Impl::Ranges
+#else
+#include <iterator>
+
+namespace Kokkos::Experimental::Impl::Ranges {
+
+namespace {
```
Comment (dalg24) [inline simd/src/impl/Kokkos_SIMD_Ranges.hpp]: Why are we opening the anonymous namespace here?

File: simd/src/impl/Kokkos_SIMD_RangesCtorSupport.hpp [hunk 7]
```diff
@@ -0,0 +1,95 @@
+// SPDX-License-Identifier: Apache-2.0 WITH LLVM-exception
+// SPDX-FileCopyrightText: Copyright Contributors to the Kokkos project
+
+#ifndef KOKKOS_SIMD_RANGES_HPP
+#define KOKKOS_SIMD_RANGES_HPP
+
+#include <Kokkos_Macros.hpp>
+
+// FIXME: Some of the compiler versions we support are compatible with standard
+// library implementations which don't fully support C++20 ranges
```
Comment (dalg24) [inline simd/src/impl/Kokkos_SIMD_RangesCtorSupport.hpp]: Please write down the compiler/toolchain versions this workaround is for

File: simd/src/impl/Kokkos_SIMD_Ranges.hpp (hunk 6 above)
Comment (tretre91) [reply simd/src/impl/Kokkos_SIMD_Ranges.hpp]: My intent was to expose the same things in the "ranges are available" and "ranges are not available" branches, so that we don't accidentally use things from this anonymous namespace in the simd implementations and end up with compile errors when in the other branch

I'd be ok removing it, as it would be very unlikely that one of the devs uses a toolchain which doesn't support ranges, and the CI would catch this kind of error anyway

Comment (dalg24) [reply simd/src/impl/Kokkos_SIMD_Ranges.hpp]: >  so that we don't accidentally use things from this anonymous namespace in the simd implementations and end up with compile errors when in the other branch

It does not prevent us to accidentally use these symbols.  It makes them unique in all translation units.

File: simd/src/impl/Kokkos_SIMD_Ranges.hpp (hunk 4 above)
Comment (crtrott) [reply simd/src/impl/Kokkos_SIMD_Ranges.hpp]: I guess I was wrong about this being better.

**Comment by crtrott** [comment]
I implemented the changes discussed during the meeting today.

**Review by crtrott — APPROVED** [review]

**Comment by crtrott** [comment]
Rerunning SNL CI, otherwise looks good.

**Review by ldh4 — APPROVED** [review]
