### PR TITLE
Fix bug in kokkosp profiling section utility

### LINKED ISSUE #4316: Kokkos::Profiling::ProfilingSection should not be copyable
https://github.com/kokkos/kokkos/blob/2fc10503681d8968bf80c209b9e50839afabbd0d/core/src/Kokkos_Profiling_ProfileSection.hpp#L77-L81

### PR DESCRIPTION
**Pull request by dalg24**
Fix #4316

### CODE REVIEW

File: core/unit_test/tools/TestProfilingSection.cpp [hunk 1]
```diff
@@ -0,0 +1,129 @@
...
+      kokkosp_test_stop_section);
+
+  ASSERT_TRUE(kokkosp_test_section_vector.empty());
+
+  {
+    Kokkos::Profiling::ProfilingSection profile_1("one");
+    ASSERT_EQ(kokkosp_test_section_vector.size(), 1);
+    ASSERT_EQ(kokkosp_test_section_vector[0], Section("one", 0, 0, 0));
+
+    // NOTE: In its current design, ProfileSection is a wrapper manages the
```
Comment (masterleinad) [inline core/unit_test/tools/TestProfilingSection.cpp:91]:
```suggestion
    // NOTE: In its current design, ProfileSection is a wrapper that manages the
```

**Review by masterleinad — COMMENTED** [review]
Other than the typo this looks good to me.

**Review by DavidPoliakoff — APPROVED** [review]
I think this is appropriate. If it turns out somebody used the buggy behavior, I'll work with them

File: core/unit_test/tools/TestProfilingSection.cpp [hunk 2]
```diff
@@ -0,0 +1,143 @@
...
+    os << "( " << s.name << ", " << s.start_call_cnt << ", " << s.stop_call_cnt
+       << ", " << s.is_destroyed << " )";
+    return os;
+  }
+  friend bool operator==(Section const& l, Section const& r) {
+    return (l.name == r.name) && (l.start_call_cnt == r.start_call_cnt) &&
+           (l.stop_call_cnt == r.stop_call_cnt) &&
+           (l.is_destroyed == r.is_destroyed);
+  }
+};
```
Comment (dalg24) [inline core/unit_test/tools/TestProfilingSection.cpp:65]: @masterleinad I changed this because tuple comparison in google test wasn't great
```
../core/unit_test/tools/TestProfilingSection.cpp:114: Failure
Value of: Section("two", 1, 0, 2)
  Actual: 48-byte object <02-00 00-00 00-00 00-00 01-00 00-00 00-00 00-00 B0-98 FF-FF FF-7F 00-00 03-00 00-00 00-00 00-00 74-77 6F-00 00-00 00-00 18-22 55-00 00-00 00-00>
Expected: kokkosp_test_section_vector[1]
Which is: 48-byte object <01-00 00-00 00-00 00-00 01-00 00-00 00-00 00-00 20-FE 55-00 00-00 00-00 03-00 00-00 00-00 00-00 74-77 6F-00 00-00 00-00 00-00 00-00 00-00 00-00>
```
VS now
```
./core/unit_test/tools/TestProfilingSection.cpp:128: Failure
Value of: (Section{"two", 1, 1, 1})
  Actual: ( two, 1, 1, 1 )
Expected: kokkosp_test_section_vector[1]
Which is: ( two, 1, 0, 1 )

File: core/unit_test/tools/TestProfilingSection.cpp (hunk 1 above)
Comment (dalg24) [reply core/unit_test/tools/TestProfilingSection.cpp]: Done

File: core/unit_test/tools/TestProfilingSection.cpp [hunk 3]
```diff
@@ -0,0 +1,143 @@
...
+  ++kokkosp_test_section_vector[id].stop_call_cnt;
+}
+
+void kokkosp_test_destroy_section(std::uint32_t id) {
+  ++kokkosp_test_section_vector[id].is_destroyed;
+}
+
+}  // namespace
+
+TEST(defaultdevicetype, profiling_section) {
```
Comment (dalg24) [inline core/unit_test/tools/TestProfilingSection.cpp:88]: @DavidPoliakoff I did that for consistency but I'd like to change to
```diff
diff --git a/core/unit_test/tools/TestProfilingSection.cpp b/core/unit_test/tools/TestProfilingSection.cpp
index 167b29704..bae69b80d 100644
--- a/core/unit_test/tools/TestProfilingSection.cpp
+++ b/core/unit_test/tools/TestProfilingSection.cpp
@@ -85,7 +85,7 @@ void kokkosp_test_destroy_section(std::uint32_t id) {

 }  // namespace

-TEST(defaultdevicetype, profiling_section) {
+TEST(kokkosp, profiling_section) {
   Kokkos::Profiling::Experimental::set_create_profile_section_callback(
       kokkosp_test_create_section);
   Kokkos::Profiling::Experimental::set_destroy_profile_section_callback(
```
For reference, `KokkosCore_UnitTest_KokkosP --gtest_list_tests` currently yields
```
defaultdevicetype.
  test_named_instance_fence
  test_unnamed_instance_fence
  test_named_global_fence
  test_unnamed_global_fence
  test_multiple_default_instances
  test_kernel_sequence
  profiling_section

File: core/unit_test/tools/TestProfilingSection.cpp [hunk 4]
```diff
@@ -0,0 +1,143 @@
...
+#include <Kokkos_Profiling_ProfileSection.hpp>
+
+#include <gtest/gtest.h>
+
+namespace {
+struct Section {
+  std::string name;
+  int start_call_cnt;
+  int stop_call_cnt;
+  int is_destroyed;
```
Comment (masterleinad) [inline core/unit_test/tools/TestProfilingSection.cpp:54]: I would rather call this `destruction_cnt` but I think it doesn't matter much for a test.

**Review by masterleinad — APPROVED** [review]
