### PR TITLE
Skip bessel function tests known to fail on Intel GPUs

### LINKED ISSUE #6396: SYCL sycl.mathspecialfunc_cbesselj1y1 subtest failure with intel/2023.1.0 on Intel Ponte Vecchio
**Describe the bug**
The `sycl.mathspecialfunc_cbesselj1y1` subtest failed for me with an initial test on a newer system (tested with kokkos@7e299b4e25c42528e105379c3aa9a318056545ba) on Intel Ponte Vecchio with the following output:

```
[ RUN      ] sycl.mathspecialfunc_cbesselj1y1
/home/ndellin/kokkos/core/unit_test/TestMathematicalSpecialFunctions.hpp:914: Failure
Expected equality of these values:
  h_ref_cby1(0)
    Which is: (-inf,0)
  h_cby1(0)
    Which is: (-inf,1233.15)
/home/ndellin/kokkos/core/unit_test/TestMathematicalSpecialFunctions.hpp:917: Failure
Expected: (Kokkos::abs(h_cby1(i) - h_ref_cby1(i))) <= (Kokkos::abs(h_ref_cby1(i)) * 1e-13), actual: 424.078 vs 1.47619e-13
/home/ndellin/kokkos/core/unit_test/TestMathematicalSpecialFunctions.hpp:917: Failure
Expected: (Kokkos::abs(h_cby1(i) - h_ref_cby1(i))) <= (Kokkos::abs(h_ref_cby1(i)) * 1e-13), actual: 424.078 vs 1.47619e-13
/home/ndellin/kokkos/core/unit_test/TestMathematicalSpecialFunctions.hpp:917: Failure
....
```

**Please also include the following items to support reproducing the bug**
**Reproducer**:
* Note that I disabled onedpl (the spack install on the system was a bit older and triggered compilation errors)
```bash
module load cmake intel-oneapi-compilers/2023.1.0

$KOKKOS_PATH/generate_makefile.bash --with-sycl --arch=INTEL_PVC --compiler=/projects/x86-64-icelake-rocky8/compilers/intel-oneapi-compilers/2023.1.0/gcc/8.5.0/base/6g2jkiv/compiler/2023.1.0/linux/bin-llvm/clang++ --cxxflags="-fp-model=precise" --cmake-flags=-DKokkos_ENABLE_ONEDPL=OFF

```

I'm testing on a newer system and I am relatively inexperienced with the Intel GPUs and SYCL backend, please let me know if this is self-inflicted user-configure error

Edit: updated reproducer instructions to current flag usage (-fp-model=precise)

### PR DESCRIPTION
**Pull request by masterleinad**
Fixes #6396, supersedes #6416.
We have reported these test failures to Intel.

### CODE REVIEW

File: core/unit_test/TestMathematicalSpecialFunctions.hpp [hunk 1]
```diff
@@ -1207,9 +1207,16 @@ struct TestComplexBesselI0K0Function {
     }
 
     EXPECT_EQ(h_ref_cbk0(0), h_cbk0(0));
-    for (int i = 1; i < N; i++) {
+    int upper_limit = N;
+    // FIXME_SYCL Failing for Intel GPUs
+#if defined(KOKKOS_ENABLE_SYCL) && defined(KOKKOS_ARCH_INTEL_GPU)
+    if (std::is_same_v<TEST_EXECSPACE, Kokkos::Experimental::SYCL>)
+      upper_limit = 19;
```
Comment (fnrizzi) [inline core/unit_test/TestMathematicalSpecialFunctions.hpp:1214]: why 19?

File: core/unit_test/TestMathematicalSpecialFunctions.hpp [hunk 2]
```diff
@@ -1449,9 +1456,16 @@ struct TestComplexBesselI1K1Function {
     }
 
     EXPECT_EQ(h_ref_cbk1(0), h_cbk1(0));
-    for (int i = 1; i < N; i++) {
+    int upper_limit = N;
+    // FIXME_SYCL Failing for Intel GPUs
+#if defined(KOKKOS_ENABLE_SYCL) && defined(KOKKOS_ARCH_INTEL_GPU)
+    if (std::is_same_v<TEST_EXECSPACE, Kokkos::Experimental::SYCL>)
+      upper_limit = 8;
```
Comment (fnrizzi) [inline core/unit_test/TestMathematicalSpecialFunctions.hpp:1463]: similar comment as above

File: core/unit_test/TestMathematicalSpecialFunctions.hpp [hunk 3]
```diff
@@ -1892,9 +1912,16 @@ struct TestComplexBesselH2Function {
     }
 
     EXPECT_EQ(h_ref_ch21(0), h_ch21(0));
-    for (int i = 1; i < N; i++) {
+    int upper_limit = N;
+    // FIXME_SYCL Failing for Intel GPUs
+#if defined(KOKKOS_ENABLE_SYCL) && defined(KOKKOS_ARCH_INTEL_GPU)
+    if (std::is_same_v<TEST_EXECSPACE, Kokkos::Experimental::SYCL>)
+      upper_limit = 17;
```
Comment (fnrizzi) [inline core/unit_test/TestMathematicalSpecialFunctions.hpp:1919]: similar comment as above

File: core/unit_test/TestMathematicalSpecialFunctions.hpp (hunk 1 above)
Comment (masterleinad) [reply core/unit_test/TestMathematicalSpecialFunctions.hpp:1214]: Yes, I picked the first failing test.

Comment (fnrizzi) [reply core/unit_test/TestMathematicalSpecialFunctions.hpp:1214]: can you pleas just add a comment to explain that?

**Review by fnrizzi — APPROVED** [review]
provided a comment is added to explain the magic upper limit number

**Comment by fnrizzi** [comment]
thanks @masterleinad !

**Review by Rombur — APPROVED** [review]

**Comment by dalg24** [comment]
@masterleinad please confirm you were able to reproduce these failures on ALCF systems

**Comment by masterleinad** [comment]
> @masterleinad please confirm you were able to reproduce these failures on ALCF systems

Yes, we reported the failures there to Intel and they confirmed that it's a code generation issue. A workaround is forcing smaller subgroup sizes or lower optimization flags.

**Comment by crtrott** [comment]
Retest this please.

**Comment by crtrott** [comment]
System test failures, but I trust that this works.
