### PR TITLE
Fix C++20 KOKKOS_LAMBDA deprecation warning

### LINKED ISSUE #2454: C++20 deprecation warnings about KOKKOS_LAMBDA
This appears to be an implementation issue with `Kokkos_Macros.hpp`. The CMake configuration and config header seem to be correct?

````
/Users/jjwilke/Programs/kokkos/seplibs/core/src/Kokkos_Macros.hpp:208:23: warning: implicit capture of 'this' via '[=]' is deprecated in C++20 [-Wdeprecated]
  208 | #define KOKKOS_LAMBDA [=]

/Users/jjwilke/Programs/kokkos/seplibs/core/unit_test/TestRange.hpp:320:11: note: in expansion of macro 'KOKKOS_LAMBDA'
  320 |           KOKKOS_LAMBDA(const int &i, int &lsum) {
````

### PR DESCRIPTION
**Pull request by masterleinad**
Fixes #2454. `KOKKOS_CLASS_LAMBDA` should be used instead of `KOKKOS_LAMBDA` in places where `this` is implicitly captured. Unfortunately, we can only do this for `C++17` and later. To be able to write code that both avoids this warning for C++17 and later and still works for C++14 and below, this pull requests defines `KOKKOS_CLASS_LAMBDA` the same as `KOKKOS_LAMBDA` as this is the closest we can (easily) get.

### CODE REVIEW

File: core/unit_test/TestRange.hpp [hunk 1]
```diff
@@ -256,7 +256,7 @@ struct TestRange {
       Kokkos::View<int *, ExecSpace> a("A", N);
 
       Kokkos::parallel_for(
-          policy_t(0, N), KOKKOS_LAMBDA(const int &i) {
+          policy_t(0, N), KOKKOS_CLASS_LAMBDA(const int &i) {
             for (int k = 0; k < (i < N / 2 ? 1 : 10000); k++) {
               a(i)++;
```
Comment (dalg24) [inline core/unit_test/TestRange.hpp]: This won't work pre C++17.  You need to do something like
```C++
auto that = *this;
Kokkos::parallel_for(policy_t(0, N), KOKKOS_LAMBDA(int i) {
  ...
  that.a(i)++;
  ...
});
```

**Review by dalg24 — CHANGES_REQUESTED** [review]

**Review by dalg24 — APPROVED** [review]

**Comment by crtrott** [comment]
Uhm: I don't think this is ok. This obfuscates the issue that people are not allowed to capture the this pointer ever inside of a dispatch operation, because it violates Kokkos semantics.

**Comment by dalg24** [comment]
Proposed alternative fix is 8f66f19
