### PR TITLE
Avoid forcing matching execution spaces in BinSort constructor and sort()

### LINKED ISSUE #4891: Static assertion failure due to mismatch of execution policy and functor execution space
I have the following routine, which implements `sort_pairs()` using `kokkos::BinSort`:
```
template < typename EXEC, typename KEY_TYPE, typename VAL_TYPE >
inline void sort_pairs( KEY_TYPE* keys, VAL_TYPE* vals, index_t N )
{
  using kokkos_execspace = typename execution_space< EXEC >::kokkos_execspace;
  using kokkos_memspace  = typename execution_space< EXEC >::kokkos_memspace;
  using RangePolicy = typename execution_space< EXEC >::loop_policy;

  using KeyViewType = Kokkos::View< KEY_TYPE*, kokkos_memspace >;
  using ValViewType = Kokkos::View< VAL_TYPE*, kokkos_memspace >;
  KeyViewType keys_view( keys, N );
  ValViewType vals_view( vals, N );

  using minmax_t = Kokkos::MinMaxScalar<typename KeyViewType::non_const_value_type>;
  minmax_t result;
  Kokkos::MinMax<typename KeyViewType::non_const_value_type> reducer(result);
  Kokkos::parallel_reduce(
    "MinMaxReduce"
  , RangePolicy(0,N)
  , KOKKOS_LAMBDA(const index_t& idx, minmax_t& minmax)
    {
      const KEY_TYPE key = keys[ idx ];
      if ( key < minmax.min_val) minmax.min_val = key;
      if ( key > minmax.max_val) minmax.max_val = key;
    }
  , reducer );

  const index_t max_bins = static_cast< index_t >(0.5 * N);
  using CompType = Kokkos::BinOp1D<KeyViewType>;
  CompType comparator( max_bins, result.min_val, result.max_val );
  Kokkos::BinSort<KeyViewType, CompType> Sorter( keys_view, comparator, true );
  Sorter.create_permute_vector( kokkos_execspace() );
  Sorter.sort( kokkos_execspace(), keys_view );
  Sorter.sort( kokkos_execspace(), vals_view );

  kokkos_execspace().fence();
}
```

The code works with `Kokkos::Serial`, however, when I enable `Kokkos::OpenMP`, I get the following static assert failure:
```
kokkos/core/src/impl/Kokkos_FunctorAnalysis.hpp:119:71: error: static assertion failed: Execution Policy and Functor execution space must match
  119 |   static_assert(!policy_has_space::value || !functor_has_space::value ||
      |                 ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^~
  120 |                     std::is_same<typename policy_has_space::type,
      |                     ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~      
  121 |                                  typename functor_has_space::type>::value,
      |                                  ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
```

The stopgap solution provided by @crtrott on a corresponding discussion on Slack is to define `KeyViewType` as follows:
```
using KeyViewType = Kokkos::View< KEY_TYPE*, Kokkos::Device<kokkos_execspace, kokkos_memspace> >;
```

However, it would be nice if that can be handled inside Kokkos instead, if possible.

### PR DESCRIPTION
**Pull request by masterleinad**
Fixes #4891. Having an `execution_space` alias forces that to be considered when executing functors. This is not what we want.
This pull requests just renames `execution_space` to `exec_space`.

### CODE REVIEW

**Review by janciesko — APPROVED** [review]

File: algorithms/src/Kokkos_Sort.hpp [hunk 1]
```diff
@@ -248,13 +248,13 @@ class BinSort {
...
+      : BinSort(exec_space{}, keys_, bin_op_, sort_within_bins_) {}
 
   //----------------------------------------
   // Create the permutation vector, the bin_offset array and the bin_count
   // array. Can be called again if keys changed
-  template <class ExecutionSpace = execution_space>
-  void create_permute_vector(const ExecutionSpace& exec = execution_space{}) {
+  template <class ExecutionSpace = exec_space>
+  void create_permute_vector(const ExecutionSpace& exec = exec_space{}) {
     const size_t len = range_end - range_begin;
```
Comment (crtrott) [inline algorithms/src/Kokkos_Sort.hpp:258]: can we make a check here that (i.e. static_assert) that ExecutionSpace can access the memory space of the view?

**Review by crtrott — CHANGES_REQUESTED** [review]

File: algorithms/src/Kokkos_Sort.hpp (hunk 1 above)
Comment (masterleinad) [reply algorithms/src/Kokkos_Sort.hpp:269]: [`c8e2702` (#4919)](https://github.com/kokkos/kokkos/pull/4919/commits/c8e27021125244434b3ef5d4ad2d67ac89bb4cd4)

**Review by dalg24 — CHANGES_REQUESTED** [review]

**Review by dalg24 — APPROVED** [review]

**Review by crtrott — APPROVED** [review]
