### PR TITLE
Fix support for `Kokkos::Array` of const-qualified element type

### LINKED ISSUE #6960: Nightly Trilinos failure: kokkos_swap update breakage
**Describe the bug**

Nightly Trilinos build (clang/15, serial backend so far) is failing to compile following merge of #6943 
The error pops up mixed in with kokkos-kernels/ode unit test output, but I did a grep search in kokkos-kernels and did not see usage of `kokkos_swap`...

```
17:42:17 In file included from /home/jenkins/blake-new/workspace/KokkosEco_Trilinos_Blake_LLVM1507_Serial_debug/Trilinos/kokkos-kernels/ode/unit_test/backends/Test_Serial_ODE.cpp:19:
17:42:17 In file included from /home/jenkins/blake-new/workspace/KokkosEco_Trilinos_Blake_LLVM1507_Serial_debug/Trilinos/kokkos-kernels/test_common/Test_Serial.hpp:20:
17:42:17 In file included from /home/jenkins/blake-new/workspace/KokkosEco_Trilinos_Blake_LLVM1507_Serial_debug/Trilinos/kokkos/core/src/Kokkos_Core.hpp:45:
17:42:17 In file included from /home/jenkins/blake-new/workspace/KokkosEco_Trilinos_Blake_LLVM1507_Serial_debug/Build/kokkos/KokkosCore_Config_DeclareBackend.hpp:22:
17:42:17 In file included from /home/jenkins/blake-new/workspace/KokkosEco_Trilinos_Blake_LLVM1507_Serial_debug/Trilinos/kokkos/core/src/decl/Kokkos_Declare_SERIAL.hpp:21:
17:42:17 In file included from /home/jenkins/blake-new/workspace/KokkosEco_Trilinos_Blake_LLVM1507_Serial_debug/Trilinos/kokkos/core/src/Serial/Kokkos_Serial.hpp:37:
17:42:17 In file included from /home/jenkins/blake-new/workspace/KokkosEco_Trilinos_Blake_LLVM1507_Serial_debug/Trilinos/kokkos/core/src/Kokkos_TaskScheduler.hpp:34:
17:42:17 In file included from /home/jenkins/blake-new/workspace/KokkosEco_Trilinos_Blake_LLVM1507_Serial_debug/Trilinos/kokkos/core/src/Kokkos_MemoryPool.hpp:26:
17:42:17 In file included from /home/jenkins/blake-new/workspace/KokkosEco_Trilinos_Blake_LLVM1507_Serial_debug/Trilinos/kokkos/core/src/Kokkos_Parallel.hpp:31:
17:42:17 In file included from /home/jenkins/blake-new/workspace/KokkosEco_Trilinos_Blake_LLVM1507_Serial_debug/Trilinos/kokkos/core/src/Kokkos_View.hpp:42:
17:42:17 In file included from /home/jenkins/blake-new/workspace/KokkosEco_Trilinos_Blake_LLVM1507_Serial_debug/Trilinos/kokkos/core/src/Kokkos_MinMax.hpp:21:
17:42:17 In file included from /home/jenkins/blake-new/workspace/KokkosEco_Trilinos_Blake_LLVM1507_Serial_debug/Trilinos/kokkos/core/src/Kokkos_Pair.hpp:31:
17:42:17 /home/jenkins/blake-new/workspace/KokkosEco_Trilinos_Blake_LLVM1507_Serial_debug/Trilinos/kokkos/core/src/Kokkos_Swap.hpp:43:19: error: no matching function for call to 'kokkos_swap'
17:42:17   static decltype(kokkos_swap(std::declval<T&>(), std::declval<T&>()))
17:42:17                   ^~~~~~~~~~~
17:42:17 /home/jenkins/blake-new/workspace/KokkosEco_Trilinos_Blake_LLVM1507_Serial_debug/Trilinos/kokkos/core/src/Kokkos_Array.hpp:138:13: note: in instantiation of template class 'Kokkos::Impl::is_swappable<const double>' requested here
17:42:17       Impl::is_swappable<T>::value>
17:42:17             ^
17:42:17 /home/jenkins/blake-new/workspace/KokkosEco_Trilinos_Blake_LLVM1507_Serial_debug/Trilinos/kokkos-kernels/ode/impl/KokkosODE_BDF_impl.hpp:313:40: note: in instantiation of template class 'Kokkos::Array<const double, 6>' requested here
17:42:17   const Kokkos::Array<const double, 6> alpha{
17:42:17                                        ^
17:42:17 /home/jenkins/blake-new/workspace/KokkosEco_Trilinos_Blake_LLVM1507_Serial_debug/Trilinos/kokkos/core/src/Kokkos_Swap.hpp:31:1: note: candidate template ignored: requirement 'std::is_move_assignable_v<const double>' was not satisfied [with T = const double]
17:42:17 kokkos_swap(T& a, T& b) noexcept(std::is_nothrow_move_constructible_v<T>&&
```

**Please include the following for a minimal reproducer**

**Reproducer configuration** (blake):
```
git clone -b develop https://github.com/trilinos/Trilinos.git
TRILINOS_DIR=$PWD/Trilinos
git clone -b develop https://github.com/kokkos/kokkos.git
KOKKOS_DIR=$PWD/kokkos
git clone -b develop https://github.com/kokkos/kokkos-kernels.git
KOKKOSKERNELS_DIR=$PWD/kokkos-kernels

cd $TRILINOS_DIR
ln -s ${KOKKOS_DIR}/kokkos kokkos
ln -s ${KOKKOSKERNELS_DIR}/kokkos-kernels kokkos-kernels
cd -

module load cmake llvm openblas/0.3.23

cmake \
  -D CMAKE_INSTALL_PREFIX="${TRILINOS_INSTALL_DIR}" \
  -D CMAKE_CXX_COMPILER="`which clang++`" \
  -D CMAKE_C_COMPILER="`which clang`" \
  -D CMAKE_Fortran_COMPILER="`which gfortran`" \
  -D CMAKE_CXX_FLAGS="-g -fPIC" \
  -D CMAKE_C_FLAGS="-g -fPIC" \
  -D CMAKE_Fortran_FLAGS="-g -fPIC" \
  -D CMAKE_BUILD_TYPE:STRING=DEBUG \
  -D BUILD_SHARED_LIBS:BOOL=OFF \
  -DTPL_ENABLE_MPI=OFF \
  -DTPL_ENABLE_BLAS:BOOL=ON \
   -DBLAS_LIBRARY_DIRS:FILEPATH=${OPENBLAS_ROOT}/lib \
   -DBLAS_LIBRARY_NAMES:STRING="openblas" \
  -DTPL_ENABLE_LAPACK:BOOL=ON \
   -DLAPACK_INCLUDE_DIRS:FILEPATH=${OPENBLAS_ROOT}/include \
   -DLAPACK_LIBRARY_DIRS:FILEPATH=${OPENBLAS_ROOT}/lib \
   -DLAPACK_LIBRARY_NAMES:STRING="openblas" \
  -DTrilinos_ENABLE_ALL_PACKAGES=OFF \
  -DTrilinos_ENABLE_ALL_OPTIONAL_PACKAGES=OFF \
  -DTrilinos_ENABLE_TESTS=ON \
  -DTrilinos_MUST_FIND_ALL_TPL_LIBS=TRUE \
  -DTrilinos_ENABLE_COMPLEX=ON \
  -DTrilinos_ENABLE_OpenMP=OFF \
  -DTrilinos_ENABLE_Kokkos=ON \
  -D Kokkos_ENABLE_SERIAL=ON \
   -D Kokkos_ENABLE_TESTS=ON \
  -D Kokkos_ARCH_SKX=ON \
  -DTrilinos_ENABLE_KokkosKernels=ON \
   -D KokkosKernels_ENABLE_TESTS=ON \
  -DTrilinos_ENABLE_Tpetra=ON \
   -D Tpetra_ENABLE_TESTS=ON \
  -DTrilinos_ENABLE_Sacado=ON \
   -D Sacado_ENABLE_TESTS=ON \
  -DTrilinos_ENABLE_Stokhos=ON \
   -D Stokhos_ENABLE_TESTS=ON \
  -DTrilinos_ENABLE_Intrepid2=ON \
   -D Intrepid2_ENABLE_TESTS=ON \
  -DTrilinos_ENABLE_Adelus=ON \
   -D Adelus_ENABLE_TESTS:BOOL=ON \
  -DTrilinos_ENABLE_Compadre=ON \
   -D Compadre_ENABLE_TESTS=ON \
  -DTrilinos_ENABLE_Panzer=ON \
   -D Panzer_ENABLE_TESTS=ON \
  -DTrilinos_ENABLE_Amesos2=ON \
   -D Amesos2_ENABLE_TESTS=ON \
  -DTrilinos_ENABLE_Zoltan2=ON \
   -D Zoltan2_ENABLE_TESTS=ON \
  -DTrilinos_ENABLE_Teuchos=ON \
   -D Teuchos_ENABLE_TESTS=ON \
  -DTrilinos_ENABLE_Ifpack2=ON \
   -D Ifpack2_ENABLE_TESTS=ON \
\
  -DTPL_ENABLE_Matio=OFF \
\
-DKokkos_SOURCE_DIR_OVERRIDE:STRING=kokkos \
-DKokkosKernels_SOURCE_DIR_OVERRIDE:STRING=kokkos-kernels \
$TRILINOS_DIR
```

### PR DESCRIPTION
**Pull request by dalg24**
Fix #6960 
Poorly-crafted constraint on the `kokkos_swap` hidden friend in #6943 inadvertently broke use of Kokkos arrays of const-qualified element type.

In the process had to come up with a workaround in the definition of the `Impl::is_nothrow_swappable_v` variable template for NVCC pre 11.4

### CODE REVIEW

**Review by masterleinad — DISMISSED** [review]

**Review by ndellingwood — APPROVED** [review]
Thanks for fast fix and adding the test!

**Comment by ndellingwood** [comment]
The `Stage 'HIP-ROCm-5.2'` job failed, looks unrelated to this PR (maybe the system is out of memory?):

```
test 1

      Start  1: Kokkos_CoreUnitTest_OpenMP

1: Test command: /var/jenkins/workspace/Kokkos_PR-6962/build/core/unit_test/Kokkos_CoreUnitTest_OpenMP

1: Test timeout computed to be: 1500

1: terminate called after throwing an instance of 'std::runtime_error'

1:   what():  Desul::Error: init_lock_arrays_hip: post malloc error(hipErrorOutOfMemory): hipErrorOutOfMemory

 1/53 Test  #1: Kokkos_CoreUnitTest_OpenMP ..................Child aborted***Exception:   0.78 sec
...
```

**Comment by dalg24** [comment]
There is a legit compile error in the CUDA-11.0-NVCC-RDC build
```
/var/jenkins/workspace/Kokkos_PR-6962/core/unit_test/TestArray.cpp(54): warning: calling a constexpr __host__ function("size") from a __host__ __device__ function("is_equal") is not allowed. The experimental flag '--expt-relaxed-constexpr' can be used to allow this.
          detected during instantiation of "__nv_bool <unnamed>::is_equal(const L &, const R &) [with L=Kokkos::Array<int, 5UL, void>, R=Kokkos::Array<int, 5UL, void>]" 
(70): here

/var/jenkins/workspace/Kokkos_PR-6962/core/unit_test/TestArray.cpp(54): warning: calling a constexpr __host__ function("size") from a __host__ __device__ function("is_equal") is not allowed. The experimental flag '--expt-relaxed-constexpr' can be used to allow this.
          detected during instantiation of "__nv_bool <unnamed>::is_equal(const L &, const R &) [with L=Kokkos::Array<int, 5UL, void>, R=Kokkos::Array<int, 5UL, void>]" 
(70): here

/var/jenkins/workspace/Kokkos_PR-6962/core/unit_test/TestArray.cpp(56): warning: calling a constexpr __host__ function("size") from a __host__ __device__ function("is_equal") is not allowed. The experimental flag '--expt-relaxed-constexpr' can be used to allow this.
          detected during instantiation of "__nv_bool <unnamed>::is_equal(const L &, const R &) [with L=Kokkos::Array<int, 5UL, void>, R=Kokkos::Array<int, 5UL, void>]" 
(70): here

/var/jenkins/workspace/Kokkos_PR-6962/install/include/Kokkos_Swap.hpp(54): error: no instance of overloaded function "Kokkos::kokkos_swap" matches the argument list
            argument types are: (const int, const int)
          detected during:
            instantiation of "const __nv_bool Kokkos::Impl::is_nothrow_swappable_v [with T=const int]" 
/var/jenkins/workspace/Kokkos_PR-6962/install/include/Kokkos_Array.hpp(141): here
            instantiation of class "Kokkos::Array<T, N, Proxy> [with T=const int, N=1UL, Proxy=void]" 
/var/jenkins/workspace/Kokkos_PR-6962/core/unit_test/TestArray.cpp(124): here

1 error detected in the compilation of "/var/jenkins/workspace/Kokkos_PR-6962/core/unit_test/TestArray.cpp".
core/unit_test/CMakeFiles/Kokkos_CoreTestCompileOnly.dir/build.make:95: recipe for target 'core/unit_test/CMakeFiles/Kokkos_CoreTestCompileOnly.dir/TestArray.cpp.o' failed
make[2]: *** [core/unit_test/CMakeFiles/Kokkos_CoreTestCompileOnly.dir/TestArray.cpp.o] Error 1
make[2]: *** Waiting for unfinished jobs....

**Comment by dalg24** [comment]
In case someone wants to try a different workaround https://godbolt.org/z/z1EoPrjWT

**Comment by dalg24** [comment]
> > In case someone wants to try a different workaround [godbolt.org/z/z1EoPrjWT](https://godbolt.org/z/z1EoPrjWT)
> 
> ```c++
> template <class T>
> inline constexpr bool is_nothrow_swappable_v = noexcept(kokkos_swap(std::declval<std::remove_const_t<T>&>(), std::declval<std::remove_const_t<T>&>()));
> ```
> 
> (adding `std::remove_const_t`) also seems to fix it.

Stripping the const-qualifier is just wrong.  `const-qualified` types are **not** swappable.

**Comment by masterleinad** [comment]
> Stripping the const-qualifier is just wrong. `const-qualified` types are **not** swappable.

Right, so you can combine it with `is_swappable<T>::value` to give
```C++
template <class T>
inline constexpr bool is_nothrow_swappable_v = is_swappable<T>::value && noexcept(kokkos_swap(std::declval<std::remove_const_t<T>&>(), std::declval<std::remove_const_t<T>&>()));
```
as a workaround. In general, I would prefer not to have multiple versions of the check depending on the compiler and the compiler version.

**Comment by dalg24** [comment]
How about
```C++
#if defined(KOKKOS_COMPILER_NVCC) && (KOKKOS_COMPILER_NVCC < 1140)
template <class T>
inline constexpr bool is_nothrow_swappable_v =
    is_swappable<T>::value&& noexcept(
        kokkos_swap(std::declval<std::remove_const_t<T>&>(),
                    std::declval<std::remove_const_t<T>&>()));
#else
template <class T>
inline constexpr bool is_nothrow_swappable_v =
    noexcept(kokkos_swap(std::declval<T&>(), std::declval<T&>()));
#endif
```
I agree with reducing duplication of code but I am not comfortable with the workaround version unconditionally.

File: core/src/Kokkos_Swap.hpp [hunk 1]
```diff
@@ -37,6 +37,26 @@ kokkos_swap(T& a, T& b) noexcept(std::is_nothrow_move_constructible_v<T>&&
...
+struct is_swappable {
+  template <class U>
+  static decltype(kokkos_swap(std::declval<T&>(), std::declval<T&>()))
+  test_swap(int) noexcept(noexcept(kokkos_swap(std::declval<T&>(),
+                                               std::declval<T&>())));
+  struct Nope {};  // test_swap must return a complete type for the definition
+                   // of nothrow below
+  template <class U>
+  static Nope test_swap(long);
+  static constexpr bool value =
```
Comment (crtrott) [inline core/src/Kokkos_Swap.hpp:52]:
```suggestion
  // will prefer the overload of test_swap taking int, if it is valid
  static constexpr bool value =
```

**Review by crtrott — CHANGES_REQUESTED** [review]
Might be worthwhile to add a comment how this works (i.e. because you pass 0 which is an int, it will prefer the first overload if it's not SFINAEd away.) I made a suggestion.

**Comment by masterleinad** [comment]
> How about [...]

Sure, I'm fine with that.

**Review by masterleinad — APPROVED** [review]

File: core/src/Kokkos_Swap.hpp (hunk 1 above)
Comment (dalg24) [reply core/src/Kokkos_Swap.hpp]: N/A since I withdrew that code

**Review by crtrott — APPROVED** [review]

**Comment by crtrott** [comment]
Retest this please

**Comment by masterleinad** [comment]
This doesn't pass the indentation check.

File: core/src/Kokkos_Swap.hpp [hunk 2]
```diff
@@ -40,18 +40,27 @@ namespace Impl {
 template <class T>
 struct is_swappable {
   template <class U>
-  static decltype(kokkos_swap(std::declval<T&>(), std::declval<T&>()))
+  KOKKOS_FUNCTION static decltype(kokkos_swap(std::declval<T&>(),
```
Comment (dalg24) [inline core/src/Kokkos_Swap.hpp:43]: Why did you add host device annotations?  What is this resolving and why is it part of this PR?

Comment (crtrott) [reply core/src/Kokkos_Swap.hpp:43]: Misreading of warning message which incidentally has warnings in Test_Array line 54, while both that file is changed and a change in line 54 of Kokkos_Swap.hpp occurred. I think the markup should be there, but this particular use of non-marked up function (decltype of function inside an expression to define a constexpr variable) is accepted by both clang and NVCC. However using decltype directly inside a device function is not:

https://godbolt.org/z/1vd36Tr9E

Comment (crtrott) [reply core/src/Kokkos_Swap.hpp:43]: So feel free to revert.
