### PR TITLE
simd: use floating point comparison for float types

### LINKED ISSUE #7686: Nightly test failures, intel 2021.3, 2023.2 icpc compilers, simd.host_math_ops
**Describe the bug**

Nightly builds with intel 2021.3 and 2023.2 icpc are failing in the `simd.host_math_ops` subtest:
```
17:41:07 [ RUN      ] simd.host_math_ops
...
17:41:07 /home/jenkins/blake-new/workspace/Kokkos_develop_blake_intel_2023_2_0-icpc_openmp_serial_cpp17/kokkos/simd/unit_tests/include/SIMDTesting_Utilities.hpp:29: Failure
17:41:07 Expected equality of these values:
17:41:07   a
17:41:07     Which is: 1-byte object <5E>
17:41:07   b
17:41:07     Which is: 1-byte object <FF>
...
```

@ldh4 can you investigate? This is began after merge #7678 which resolved some compilation issues

**Please include the following for a minimal reproducer**

**Reproducer notes** (blake testbed):
```bash
source /projects/x86-64-icelake-rocky8/spack-config/blake-setup-user-module-env.sh
module load intel-oneapi-compilers/2023.2.0 intel-oneapi-dpl/2022.2.0 intel-oneapi-tbb/2021.10.0 cmake git

$KOKKOS_PATH/generate_makefile.bash --with-openmp --with-serial --compiler=icpc --cxxstandard=17 --cxxflags="-Wall" --arch=SKX

make -j16

ctest -R Kokkos_UnitTest_SIMD 
```

### PR DESCRIPTION
**Pull request by ldh4**
Fixes #7686 

It seems that even with `-fp-model precise`, `SVML` intrinsics (such as `_mm_cbrt_pd`) introduce precision errors when built with icc/icpc.

Converted the unit test to use floating point comparison for floating point values.

### CODE REVIEW

**Review by masterleinad — APPROVED** [review]
Also see https://github.com/kokkos/kokkos/pull/6581/files#diff-8fc72fc8625ab19640d621aef4a330d19cd98b302017fc4f549beb0432057476 for a similar approach when using `icpx`.

**Comment by ldh4** [comment]
Retest this please.

File: simd/unit_tests/include/SIMDTesting_Utilities.hpp [hunk 1]
```diff
@@ -53,12 +59,14 @@ inline void host_check_equality(
   }
   using mask_type =
       typename Kokkos::Experimental::basic_simd<T, Abi>::mask_type;
-  if constexpr (std::is_same_v<Abi, Kokkos::Experimental::simd_abi::scalar>) {
-    mask_type mask(KOKKOS_LAMBDA(std::size_t i) { return (i < nlanes); });
-    checker.equality((expected_result == computed_result) && mask, mask);
-  } else {
-    mask_type mask([=](std::size_t i) { return (i < nlanes); });
-    checker.equality((expected_result == computed_result) && mask, mask);
+  if constexpr (std::is_integral_v<T>) {
```
Comment (Rombur) [inline simd/unit_tests/include/SIMDTesting_Utilities.hpp:62]: Why do you restrict the test to integral type? The PR description only mentions the change in `equality()`.

Comment (ldh4) [reply simd/unit_tests/include/SIMDTesting_Utilities.hpp]: It's because of `expected_result == computed_result`. The expression fails for floating point types with icpc, because the simd equality operators aren't set up to check with tolerances.
But this restriction should be limited to icpc builds. Fixed.

**Review by Rombur — APPROVED** [review]

**Comment by crtrott** [comment]
The failures are unrelated. MI300 large allocation host pinned memory test timed out and on PVC the init/finalize test timed out.
