### PR TITLE
Fix TestThreadVectorMDRangeParallelReduce

### LINKED ISSUE #6720: Nightly test failure, SYCL backend on PVC: multiple ThreadVectorMDRangeParallelReduce unit sub-test failures
**Describe the bug**

Nightly SYCL builds on PVC arch are failing the `ThreadVectorMDRangeParallelReduce` unit test:
```
03:40:34 [ RUN      ] sycl.ThreadVectorMDRangeParallelReduce
03:40:34 /home/jenkins/blake-new/workspace/Kokkos_develop_blake_sycl_pv_oneapi_2023_1_0/kokkos/core/unit_test/TestTeamMDRange.hpp:1445: Failure
03:40:34 Expected equality of these values:
03:40:34   finalSum
03:40:34     Which is: 75435360
03:40:34   expectedSum
03:40:34     Which is: 2357355
03:40:34 /home/jenkins/blake-new/workspace/Kokkos_develop_blake_sycl_pv_oneapi_2023_1_0/kokkos/core/unit_test/TestTeamMDRange.hpp:1445: Failure
03:40:34 Expected equality of these values:
03:40:34   finalSum
03:40:34     Which is: 75435360
03:40:34   expectedSum
03:40:34     Which is: 2357355
03:40:34 /home/jenkins/blake-new/workspace/Kokkos_develop_blake_sycl_pv_oneapi_2023_1_0/kokkos/core/unit_test/TestTeamMDRange.hpp:1509: Failure
03:40:34 Expected equality of these values:
03:40:34   finalSum
03:40:34     Which is: 15409474080
03:40:34   expectedSum
03:40:34     Which is: 481546065
03:40:34 /home/jenkins/blake-new/workspace/Kokkos_develop_blake_sycl_pv_oneapi_2023_1_0/kokkos/core/unit_test/TestTeamMDRange.hpp:1509: Failure
03:40:34 Expected equality of these values:
03:40:34   finalSum
03:40:34     Which is: 15409474080
03:40:34   expectedSum
03:40:34     Which is: 481546065
03:40:34 /home/jenkins/blake-new/workspace/Kokkos_develop_blake_sycl_pv_oneapi_2023_1_0/kokkos/core/unit_test/TestTeamMDRange.hpp:1574: Failure
03:40:34 Expected equality of these values:
03:40:34   finalSum
03:40:34     Which is: 5821864208160
03:40:34   expectedSum
03:40:34     Which is: 181933256505
03:40:34 /home/jenkins/blake-new/workspace/Kokkos_develop_blake_sycl_pv_oneapi_2023_1_0/kokkos/core/unit_test/TestTeamMDRange.hpp:1574: Failure
03:40:34 Expected equality of these values:
03:40:34   finalSum
03:40:34     Which is: 5821864208160
03:40:34   expectedSum
03:40:34     Which is: 181933256505
03:40:34 /home/jenkins/blake-new/workspace/Kokkos_develop_blake_sycl_pv_oneapi_2023_1_0/kokkos/core/unit_test/TestTeamMDRange.hpp:1644: Failure
03:40:34 Expected equality of these values:
03:40:34   finalSum
03:40:34     Which is: 28840320
03:40:34   expectedSum
03:40:34     Which is: 901260
03:40:34 /home/jenkins/blake-new/workspace/Kokkos_develop_blake_sycl_pv_oneapi_2023_1_0/kokkos/core/unit_test/TestTeamMDRange.hpp:1644: Failure
03:40:34 Expected equality of these values:
03:40:34   finalSum
03:40:34     Which is: 28840320
03:40:34   expectedSum
03:40:34     Which is: 901260
03:40:34 /home/jenkins/blake-new/workspace/Kokkos_develop_blake_sycl_pv_oneapi_2023_1_0/kokkos/core/unit_test/TestTeamMDRange.hpp:1718: Failure
03:40:34 Expected equality of these values:
03:40:34   finalSum
03:40:34     Which is: 1077321600
03:40:34   expectedSum
03:40:34     Which is: 33666300
03:40:34 /home/jenkins/blake-new/workspace/Kokkos_develop_blake_sycl_pv_oneapi_2023_1_0/kokkos/core/unit_test/TestTeamMDRange.hpp:1718: Failure
03:40:34 Expected equality of these values:
03:40:34   finalSum
03:40:34     Which is: 1077321600
03:40:34   expectedSum
03:40:34     Which is: 33666300
03:40:34 [  FAILED  ] sycl.ThreadVectorMDRangeParallelReduce (16 ms)
```

The failures began following merge of commits below, likely #6511 is the culprit

**Changes**:
fill_random without exceution space instance should fence ([details](https://jenkins-son.sandia.gov/job/Kokkos_develop_blake_sycl_pv_oneapi_2023_1_0/142/changes#391daefd51480fcf674d4c891e9296c1eb8e0e55) / [githubweb](https://github.com/kokkos/kokkos/commit/391daefd51480fcf674d4c891e9296c1eb8e0e55))
    add tests ([details](https://jenkins-son.sandia.gov/job/Kokkos_develop_blake_sycl_pv_oneapi_2023_1_0/142/changes#67340103852ddcc11cd67695cb6520934d1c333a) / [githubweb](https://github.com/kokkos/kokkos/commit/67340103852ddcc11cd67695cb6520934d1c333a))
    Provide new public headers `<Kokkos_Clamp.hpp>` and `<Kokkos_MinMax.hpp>` (#6687) ([details](https://jenkins-son.sandia.gov/job/Kokkos_develop_blake_sycl_pv_oneapi_2023_1_0/142/changes#89ba3fbae8ab2ae2dbfd30eef05c3bac387630a5) / [githubweb](https://github.com/kokkos/kokkos/commit/89ba3fbae8ab2ae2dbfd30eef05c3bac387630a5))
    Fix TeamThreadMDRange parallel_reduce (#6511) ([details](https://jenkins-son.sandia.gov/job/Kokkos_develop_blake_sycl_pv_oneapi_2023_1_0/142/changes#ee5cbfc25c81b9efc5b2a4abd82d9a9d5d3d07bd) / [githubweb](https://github.com/kokkos/kokkos/commit/ee5cbfc25c81b9efc5b2a4abd82d9a9d5d3d07bd))
    add tests for in-place `inclusive_scan` (#6682) ([details](https://jenkins-son.sandia.gov/job/Kokkos_develop_blake_sycl_pv_oneapi_2023_1_0/142/changes#36da6cca7fb4b4b7082f0ec91b4e388578787e8f) / [githubweb](https://github.com/kokkos/kokkos/commit/36da6cca7fb4b4b7082f0ec91b4e388578787e8f))

**Please include the following for a minimal reproducer**

**Reproducer** (blake, PV queue):
```bash
salloc -N 1 -p PV

module load cmake intel-oneapi-compilers/2023.1.0 intel-oneapi-dpl/2022.1.0 git

$KOKKOS_PATH/generate_makefile.bash --with-sycl --arch=INTEL_PVC --compiler=icpx --cxxflags="-fp-model=precise" --cmake-flags=-DKokkos_ENABLE_ONEDPL=OFF

make -j

ctest -R Kokkos_CoreUnitTest_SYCL2A
```

### PR DESCRIPTION
**Pull request by masterleinad**
Fixes #6720. We only want to add the contribution once per thread.
Updating `teamSum` within a `parallel_for` `TeamThreadRange` should lead to race conditions anyway. I'm surprised that we didn't see problems with other backends.

### CODE REVIEW

File: core/unit_test/TestTeamMDRange.hpp [hunk 1]
```diff
@@ -1432,8 +1432,8 @@ struct TestThreadVectorMDRangeParallelReduce : public TestTeamMDParallelReduce {
                   vectorSum += v(leagueRank, i, j, k);
                 },
                 threadSum);
-
-            teamSum += threadSum;
+            Kokkos::single(Kokkos::PerThread(team),
+                           [&]() { teamSum += threadSum; });
```
Comment (crtrott) [inline core/unit_test/TestTeamMDRange.hpp:1436]: Just add to leagueSum in the single. There is really zero value to the teamSum temporary.

**Review by crtrott — CHANGES_REQUESTED** [review]

File: core/unit_test/TestTeamMDRange.hpp (hunk 1 above)
Comment (masterleinad) [reply core/unit_test/TestTeamMDRange.hpp]: I agree. Addressed in 2c9b873.

**Review by crtrott — APPROVED** [review]

**Review by dalg24 — COMMENTED** [review]
Sounds like the tests need to be adjusted/augemented

**Review by dalg24 — APPROVED** [review]
