### PR TITLE
Only use __atomic_max_fetch with floating point types from LLVM 22.1 on

### LINKED ISSUE #8716: ICE using Clang atomic min/max GCC-style builtins
Just a quick heads up: Clang (or more precisely LLVM) currently results in ICE (internal compiler error) when compiling these builtins.

The ICE is present in upstream x86-64 clang versions 21.1.0 - 17.0.1, thus, a quick fix may be to enable these with `(__clang_major__ >= 22)` instead of `(__clang_major__ >= 17)`.

The ICE is triggered by the Clang’s AtomicExpr lowering path for the GCC-style atomic min/max builtins when used with floating-point types (under HIP mode when compiling Kokkos, but attaching a simpler non-HIP reproducer below).

For integer types, the lowering involves forming an ICmp and select to implement min/max atomically. For floating types, the path should use FP compares or atomicrmw fmax/fmin patterns. The ICE suggests the lowering incorrectly forms an integer ICmp over a float operand, triggering ICmpInst’s type assertion.

As a quick check, patching this out using a non-existent Clang version 99 as in `(__clang_major__ >= 99)` instead of `(__clang_major__ >= 17)` allows to compile without ICE even with an older version of Clang (21):
https://github.com/kokkos/kokkos/blob/feec7d3aa457e71c10b280b821f9fec385fd3626/tpls/desul/include/desul/atomics/Fetch_Op_GCC.hpp#L59C5-L59C28

---

Simple repro:

```sh
$ cat repro.cpp
```

```cpp
// Repro: Clang 17-21 ICE in EmitAtomicExpr on floating max
// Compile with: clang -c repro.cpp

extern "C" double test_atomic_max(double* p) {
  // Based on GCC-style builtin used by Desul
  // Memory order: __ATOMIC_SEQ_CST (or Relaxed) — try both to show it’s order-agnostic
  return __atomic_max_fetch(p, 3.5, __ATOMIC_SEQ_CST);
}

extern "C" float test_atomic_max_f(float* p) {
  return __atomic_max_fetch(p, 1.25f, __ATOMIC_SEQ_CST);
}
```

Present in upstream x86-64 clang versions 21.1.0 - 17.0.1 (assertions)
- clang version 21.1.0 (https://github.com/llvm/llvm-project.git 3623fe661ae35c6c80ac221f14d85be76aa870f1)
- clang version 17.0.1 (https://github.com/llvm/llvm-project.git e19b7dc36bc047b9eb72078d034596be766da350)

Compiler Explorer link: https://clang.godbolt.org/z/YWf53hGK6
ICE:
```
clang++: /root/llvm-project/llvm/include/llvm/IR/Instructions.h:1184: void llvm::ICmpInst::AssertOK(): Assertion `(getOperand(0)->getType()->isIntOrIntVectorTy() || getOperand(0)->getType()->isPtrOrPtrVectorTy()) && "Invalid operand types for ICmp instruction"' failed.
```

ICE no longer present in upstream trunk as of clang version 22.0.0git (https://github.Com/llvm/llvm-project.Git
2f71e606c96c6b1a534b829fc10ff2d3ef497688):
Https://clang.godbolt.org/z/ecwpbjebr

Cf. the 2025-10-13 commit:
[Clang] Add support for fp when using min_fetch/max_fetch atomics (#160330)
https://github.com/llvm/llvm-project/commit/34c7cf07507841a8e6480dcaad88c6a4dfa40e4b
https://github.com/llvm/llvm-project/pull/160330

_Originally posted by @MattPD in https://github.com/kokkos/kokkos/issues/8507#issuecomment-3598595087_

### PR DESCRIPTION
**Pull request by masterleinad**
Fixes https://github.com/kokkos/kokkos/issues/8716. Corresponds to https://github.com/desul/desul/pull/168.
I ran into ICEs when trying to verify https://github.com/kokkos/kokkos/pull/8984 with clang-19 and Cuda 12.2.
It seems I don't even need #8984 to fix the build.

Even `icpx 2025.3.1` is only based on LLVM 21.1.

### CODE REVIEW

File: tpls/desul/include/desul/atomics/Fetch_Op_GCC.hpp [hunk 1]
```diff
@@ -58,11 +58,7 @@ DESUL_IMPL_GCC_HOST_ATOMIC_FETCH_OP(_or, std::is_integral)
 DESUL_IMPL_GCC_HOST_ATOMIC_FETCH_OP(_nand, std::is_integral)
 
 #if defined(__clang__)
-#if (__clang_major__ >= 17) && \
-    (!defined(__INTEL_LLVM_COMPILER) || __INTEL_LLVM_COMPILER >= 20240000)
```
Comment (masterleinad) [inline tpls/desul/include/desul/atomics/Fetch_Op_GCC.hpp:62]: Even icpx 2025.3.1 is only based on LLVM 21.1.

**Comment by rgayatri23** [comment]
I need #8984 to fix CUDA builds. 
However other atomic related ICE which occurred in Serial and OpenMP backends with clang/{19,20} like this one are fixed with the patch.
```
PLEASE ATTACH THE FOLLOWING FILES TO THE BUG REPORT:
Preprocessed source(s) and associated run script(s) are located at:
clang++: note: diagnostic msg: /tmp/TestSerial_AtomicOperations_float-sm_80-df0ef2.cu
clang++: note: diagnostic msg: /tmp/TestSerial_AtomicOperations_float-91e6f4.cu
clang++: note: diagnostic msg: /tmp/TestSerial_AtomicOperations_float-sm_80-df0ef2.sh
clang++: note: diagnostic msg:
```

I thought patches to DESUL go via the desul github right?

**Review by dalg24 — APPROVED** [review]

File: tpls/desul/include/desul/atomics/Fetch_Op_GCC.hpp [hunk 2]
```diff
@@ -58,14 +58,9 @@ DESUL_IMPL_GCC_HOST_ATOMIC_FETCH_OP(_or, std::is_integral)
...
-// the suppression is not necessary from Clang 19 onwards
-#pragma GCC diagnostic push
-#pragma GCC diagnostic ignored "-Watomic-alignment"
+#if (__clang_major__ * 100 + __clang_minor__) >= 2210
```
Comment (dalg24) [inline tpls/desul/include/desul/atomics/Fetch_Op_GCC.hpp]: Version number is wrong see desul/desul#169

**Review by dalg24 — CHANGES_REQUESTED** [review]

**Review by dalg24 — APPROVED** [review]

File: tpls/desul/include/desul/atomics/Fetch_Op_GCC.hpp (hunk 2 above)
Comment (masterleinad) [reply tpls/desul/include/desul/atomics/Fetch_Op_GCC.hpp]: Thanks for fixing!

**Review by tretre91 — APPROVED** [review]

**Review by JBludau — APPROVED** [review]
The changes look fine
Should we add a nightly with a latest Clang to catch stuff like that early?

**Comment by masterleinad** [comment]
Should also fix https://my.cdash.org/builds/3441583/build.
