### PR TITLE
`DualView` Guard modification flag increment against `impl_is_single_device`

### LINKED ISSUE #8277: `DualView` reports false modification flags if a single device is used
Discovered by @stanmoore1 and reported on slack. Copied here for documentation purposes:

Stan: I just found a bug in DualView
This line and similar: https://github.com/kokkos/kokkos/blob/develop/containers/src/Kokkos_DualView.hpp#L1012 should be guarded by if constexpr (!impl_dualview_is_single_device) (edited)
Otherwise the modified_flags gets incremented even for the Serial backend, and the need_sync_host() returns true on the CPU (edited) 
Which leads to unexpected behavior and is messing up some LAMMPS code (edited)
Looks like this is already fixed in https://github.com/kokkos/kokkos/pull/7993 since it goes though modify() instead of incrementing directly

### PR DESCRIPTION
**Pull request by JBludau**
Fixes https://github.com/kokkos/kokkos/issues/8277
Reported by @stanmoore1 on Slack https://kokkosteam.slack.com/archives/C5BGU5NDQ/p1753401051183099

Alternative to https://github.com/kokkos/kokkos/pull/7993 since we are close to the release it might be a good idea to minimize risk.

**TODO** I don't know a good way to test this -> Christian added a minimal test
Feel free to push to this branch

### CODE REVIEW

**Review by stanmoore1 — APPROVED** [review]
Thanks @JBludau!

File: containers/unit_tests/TestDualView.hpp [hunk 1]
```diff
@@ -775,6 +775,17 @@ TEST(TEST_CATEGORY, dualview_default_constructed) {
...
   dv.sync_device();
 }
+
+TEST(TEST_CATEGORY, dualview_resize_single_device) {
+  using dv_t = Kokkos::DualView<double*, TEST_EXECSPACE>;
+  dv_t dv("DV", 10);
+  dv.resize(20);
+  bool is_same_device =
+      std::is_same_v<typename dv_t::t_host, typename dv_t::t_dev>;
+  ASSERT_EQ(is_same_device, dv.need_sync_host());
```
Comment (JBludau) [inline containers/unit_tests/TestDualView.hpp]: don't we need a `!` here?

Comment (crtrott) [reply containers/unit_tests/TestDualView.hpp]: Yeah I screwed this up pushing fix and more complete test.

**Review by crtrott — APPROVED** [review]

**Comment by JBludau** [comment]
Test failure seems unrelated

**Review by Rombur — APPROVED** [review]

**Review by nmm0 — APPROVED** [review]
Looks good to me -- accounting-wise might be good to create an issue this closes instead of just linking to the slack message so people who run into this bug can easily search to see if it was addressed.

**Review by tcclevenger — APPROVED** [review]

**Review by masterleinad — APPROVED** [review]
Fine with me but I hope we can decide on https://github.com/kokkos/kokkos/pull/7993 soon.
