### PR TITLE
If `CMAKE_CXX_COMPILER_LAUNCHER` is set , do not enable `kokkos_launch_compiler`

### LINKED ISSUE #4821: Setting `CMAKE_CXX_COMPILER_LAUNCHER` breaks `kokkos_launch_compiler`
Attempting to compile a CMake project depending on Kokkos with the CMake variable `CMAKE_CXX_COMPILER_LAUNCHER` set to `ccache` leads to build failures (at least with CUDA enabled). Build output with `KOKKOS_DEBUG_LAUNCH_COMPILER=1`:
```
> ninja -j1 tests                                                                                                                              
                                                                                                                                               
[1/17] Building CXX object tests/CMakeFiles/asynchrony_test.dir/asynchrony.cpp.o                                                               
FAILED: tests/CMakeFiles/asynchrony_test.dir/asynchrony.cpp.o                                                                                  
/apps/daint/UES/simbergm/spack/opt/spack/cray-cnl7-haswell/gcc-11.2.0/kokkos-develop-6uzxrzjk2cd7e3t5nmbgfwhek5xsluty/bin/kokkos_launch_compile
r /apps/daint/UES/simbergm/spack/opt/spack/cray-cnl7-haswell/gcc-11.2.0/kokkos-develop-6uzxrzjk2cd7e3t5nmbgfwhek5xsluty/bin/nvcc_wrapper /apps/
daint/UES/simbergm/spack/lib/spack/env/gcc/g++ ccache /apps/daint/UES/simbergm/spack/lib/spack/env/gcc/g++ -DHPX_APPLICATION_EXPORTS -DHPX_APPL
ICATION_NAME_DEFAULT=asynchrony_test -DHPX_KOKKOS_CUDA_FUTURE_TYPE=0 -DHPX_PREFIX_DEFAULT=\"/apps/daint/UES/simbergm/spack/opt/spack/cray-cnl7-
haswell/gcc-11.2.0/hpx-1.7.1-2iro5e2o25fyrpku446o6tkkjulw4bba\" -DKOKKOS_DEPENDENCE -I/apps/daint/UES/simbergm/src/hpx-kokkos/src -isystem /app
s/daint/UES/simbergm/spack/opt/spack/cray-cnl7-haswell/gcc-11.2.0/hpx-1.7.1-2iro5e2o25fyrpku446o6tkkjulw4bba/include -isystem /apps/daint/UES/s
imbergm/spack/opt/spack/cray-cnl7-haswell/gcc-11.2.0/cuda-11.6.0-2ktngoaeb3mpv22nf2hlyzpirx6enu4v/include -isystem /apps/daint/UES/simbergm/spa
ck/opt/spack/cray-cnl7-haswell/gcc-11.2.0/boost-1.78.0-tysrpumihotokpynwc6mf2w2bz4xe3on/include -isystem /apps/daint/UES/simbergm/spack/opt/spa
ck/cray-cnl7-haswell/gcc-11.2.0/asio-1.20.0-v6ddoyrwskgpwyfrsf3kmrl3ycfnlr5f/include -isystem /apps/daint/UES/simbergm/spack/opt/spack/cray-cnl
7-haswell/gcc-11.2.0/hwloc-2.7.0-44knj6u72gqwytzghcp33jrmjqeveqsl/include -isystem /apps/daint/UES/simbergm/spack/opt/spack/cray-cnl7-haswell/g
cc-11.2.0/kokkos-develop-6uzxrzjk2cd7e3t5nmbgfwhek5xsluty/include -g -pthread -march=core-avx2 -mtune=core-avx2 -expt-extended-lambda -Wext-lam
bda-captures-this -expt-relaxed-constexpr -arch=sm_60 -std=c++14 -MD -MT tests/CMakeFiles/asynchrony_test.dir/asynchrony.cpp.o -MF tests/CMakeF
iles/asynchrony_test.dir/asynchrony.cpp.o.d -o tests/CMakeFiles/asynchrony_test.dir/asynchrony.cpp.o -c /apps/daint/UES/simbergm/src/hpx-kokkos
/tests/asynchrony.cpp                                                                                                                          
##### kokkos_launch_compiler executing: "ccache /apps/daint/UES/simbergm/spack/lib/spack/env/gcc/g++ -DHPX_APPLICATION_EXPORTS -DHPX_APPLICATIO
N_NAME_DEFAULT=asynchrony_test -DHPX_KOKKOS_CUDA_FUTURE_TYPE=0 -DHPX_PREFIX_DEFAULT="/apps/daint/UES/simbergm/spack/opt/spack/cray-cnl7-haswell
/gcc-11.2.0/hpx-1.7.1-2iro5e2o25fyrpku446o6tkkjulw4bba" -DKOKKOS_DEPENDENCE -I/apps/daint/UES/simbergm/src/hpx-kokkos/src -isystem /apps/daint/UES/simbergm/spack/opt/spack/cray-cnl7-haswell/gcc-11.2.0/hpx-1.7.1-2iro5e2o25fyrpku446o6tkkjulw4bba/include -isystem /apps/daint/UES/simbergm/
spack/opt/spack/cray-cnl7-haswell/gcc-11.2.0/cuda-11.6.0-2ktngoaeb3mpv22nf2hlyzpirx6enu4v/include -isystem /apps/daint/UES/simbergm/spack/opt/s
pack/cray-cnl7-haswell/gcc-11.2.0/boost-1.78.0-tysrpumihotokpynwc6mf2w2bz4xe3on/include -isystem /apps/daint/UES/simbergm/spack/opt/spack/cray-
cnl7-haswell/gcc-11.2.0/asio-1.20.0-v6ddoyrwskgpwyfrsf3kmrl3ycfnlr5f/include -isystem /apps/daint/UES/simbergm/spack/opt/spack/cray-cnl7-haswell/gcc-11.2.0/hwloc-2.7.0-44knj6u72gqwytzghcp33jrmjqeveqsl/include -isystem /apps/daint/UES/simbergm/spack/opt/spack/cray-cnl7-haswell/gcc-11.2.
0/kokkos-develop-6uzxrzjk2cd7e3t5nmbgfwhek5xsluty/include -g -pthread -march=core-avx2 -mtune=core-avx2 -expt-extended-lambda -Wext-lambda-capt
ures-this -expt-relaxed-constexpr -arch=sm_60 -std=c++14 -MD -MT tests/CMakeFiles/asynchrony_test.dir/asynchrony.cpp.o -MF tests/CMakeFiles/asy
nchrony_test.dir/asynchrony.cpp.o.d -o tests/CMakeFiles/asynchrony_test.dir/asynchrony.cpp.o -c /apps/daint/UES/simbergm/src/hpx-kokkos/tests/a
synchrony.cpp"... #####                                                                                                                        
g++: error: unrecognized command-line option '-Wext-lambda-captures-this'                                                                      g++: error: unrecognized command-line option '-arch=sm_60'                                                                                     
ninja: build stopped: subcommand failed.
```
Abbreviated build command: `kokkos_launch_compiler nvcc_wrapper g++ ccache g++ ...`. I suppose the extra `ccache` in between `g++` and `g++` throws off the detection for when to forward all arguments and when not to.

Is this a bug or "unsupported"? I found https://github.com/lammps/lammps/pull/1565 which seems to indicate that we can possibly do something to make this work outside of Kokkos, but I wanted to first check if this might be something that can be fixed here.

### PR DESCRIPTION
**Pull request by ajpowelsnl**
This PR adds another condition in setting `INTERNAL_USE_COMPILER_LAUNCHER` to prevent interaction with
`kokkos_launch_compiler` when `CMAKE_CXX_COMPILER_LAUNCHER` is set.  This change fixes #4821.

### CODE REVIEW

**Review by crtrott — APPROVED** [review]

**Comment by msimberg** [comment]
Works for me, as in I get an error during CMake configuration suggesting to use `nvcc_wrapper`, clang, or `kokkos_launch_compiler`. However, since the last one is not actually an option I would maybe suggest to error out earlier with a message specific to `CMAKE_CXX_COMPILER_LAUNCHER`. Do you think that's reasonable?

**Comment by ajpowelsnl** [comment]
> Works for me, as in I get an error during CMake configuration suggesting to use `nvcc_wrapper`, clang, or `kokkos_launch_compiler`. However, since the last one is not actually an option I would maybe suggest to error out earlier with a message specific to `CMAKE_CXX_COMPILER_LAUNCHER`. Do you think that's reasonable?

Hi @msimberg -- I've added the error condition you requested.  Please let us know if we can do anything further to help.

File: core/src/HIP/Kokkos_HIP_Parallel_Team.hpp [hunk 1]
```diff
@@ -1026,6 +1026,8 @@ class ParallelReduce<FunctorType, Kokkos::TeamPolicy<Properties...>,
         FunctorTeamShmemSize<FunctorType>::value(arg_functor, m_team_size);
     m_scratch_size[0] = m_shmem_size;
     m_scratch_size[1] = m_policy.scratch_size(1, m_team_size);
+    m_scratch_locks =
+        m_policy.space().impl_internal_space_instance()->m_scratch_locks;
```
Comment (masterleinad) [inline core/src/HIP/Kokkos_HIP_Parallel_Team.hpp:1030]: ...nor this...

File: core/unit_test/TestTeam.hpp [hunk 2]
```diff
@@ -849,6 +849,13 @@ struct TestScratchTeam {
         Functor(), result_type(&error_count));
     Kokkos::fence();
     ASSERT_EQ(error_count, 0);
+
+    Kokkos::parallel_reduce(
+        team_exec.set_scratch_size(1, Kokkos::PerTeam(team_scratch_size),
+                                   Kokkos::PerThread(thread_scratch_size)),
+        Functor(), Kokkos::Sum<typename Functor::value_type>(error_count));
+    Kokkos::fence();
+    ASSERT_EQ(error_count, 0);
```
Comment (masterleinad) [inline core/unit_test/TestTeam.hpp:858]: ...or this should be in this pull request.

File: cmake/kokkos_compiler_id.cmake [hunk 3]
```diff
@@ -40,9 +40,12 @@ IF(Kokkos_ENABLE_CUDA)
     # check if compiler was set to nvcc_wrapper
     kokkos_internal_have_compiler_nvcc(${CMAKE_CXX_COMPILER})
     # if launcher was found and nvcc_wrapper was not specified as
-    # compiler, set to use launcher. Will ensure CMAKE_CXX_COMPILER
+    # compiler AND `CMAKE_CXX_COMPILIER_LAUNCHER` is not set, set to use launcher. Will ensure CMAKE_CXX_COMPILER
     # is replaced by nvcc_wrapper
```
Comment (masterleinad) [inline cmake/kokkos_compiler_id.cmake:44]:
```suggestion
    # compiler and `CMAKE_CXX_COMPILIER_LAUNCHER` is not set, set to use launcher.
    # Will ensure CMAKE_CXX_COMPILER is replaced by nvcc_wrapper
```

File: cmake/kokkos_compiler_id.cmake [hunk 4]
```diff
@@ -40,9 +40,12 @@ IF(Kokkos_ENABLE_CUDA)
...
-    IF(Kokkos_COMPILE_LAUNCHER AND NOT INTERNAL_HAVE_COMPILER_NVCC AND NOT KOKKOS_CXX_COMPILER_ID STREQUAL Clang)
+    IF(Kokkos_COMPILE_LAUNCHER AND NOT INTERNAL_HAVE_COMPILER_NVCC AND NOT
+       CMAKE_CXX_COMPILER_LAUNCHER AND NOT KOKKOS_CXX_COMPILER_ID STREQUAL Clang)
+			MESSAGE(FATAL_ERROR "Cannot use CMAKE_CXX_COMPILER_LAUNCHER if the CMAKE_CXX_COMPILER is not able to compile CUDA code, i.e. nvcc_wrapper or
+clang++!")
```
Comment (masterleinad) [inline cmake/kokkos_compiler_id.cmake:48]: Don't use tabs.
```suggestion
    IF(Kokkos_COMPILE_LAUNCHER AND NOT INTERNAL_HAVE_COMPILER_NVCC AND NOT
       CMAKE_CXX_COMPILER_LAUNCHER AND NOT KOKKOS_CXX_COMPILER_ID STREQUAL Clang)
     MESSAGE(FATAL_ERROR "Cannot use CMAKE_CXX_COMPILER_LAUNCHER if the CMAKE_CXX_COMPILER is not able to compile CUDA code, i.e. nvcc_wrapper or
clang++!")
```

Comment (msimberg) [inline cmake/kokkos_compiler_id.cmake:48]:
```suggestion
    IF(Kokkos_COMPILE_LAUNCHER AND NOT INTERNAL_HAVE_COMPILER_NVCC AND NOT KOKKOS_CXX_COMPILER_ID STREQUAL Clang)
      IF(CMAKE_CXX_COMPILER_LAUNCHER)
        MESSAGE(FATAL_ERROR "Cannot use CMAKE_CXX_COMPILER_LAUNCHER if the CMAKE_CXX_COMPILER is not able to compile CUDA code, i.e. nvcc_wrapper or
clang++!")
      ENDIF()
```
?

File: core/unit_test/TestTeam.hpp (hunk 2 above)
Comment (ajpowelsnl) [reply core/unit_test/TestTeam.hpp:858]: For all cases of files that shouldn't be in this PR, I've checked out the `develop` versions of these files, and there doesn't seem to be any difference between the versions.  I will look back through the commits to see how these errant files ended up in this PR.

File: cmake/kokkos_compiler_id.cmake (hunk 4 above)
Comment (ajpowelsnl) [reply cmake/kokkos_compiler_id.cmake:48]: @msimberg -- I followed your suggestion.  Many thanks!

**Review by msimberg — APPROVED** [review]
Thanks @ajpowelsnl! This looks good to me now.

**Comment by masterleinad** [comment]
`CUDA-9.2-NVCC` failing in `default_exec.overlap_mdrange_policy` is spurious.

File: cmake/kokkos_compiler_id.cmake [hunk 5]
```diff
@@ -37,12 +37,16 @@ IF(Kokkos_ENABLE_CUDA)
...
     kokkos_internal_have_compiler_nvcc(${CMAKE_CXX_COMPILER})
-    # if launcher was found and nvcc_wrapper was not specified as
-    # compiler, set to use launcher. Will ensure CMAKE_CXX_COMPILER
-    # is replaced by nvcc_wrapper
+    # If launcher was found and nvcc_wrapper was not specified as
+    # compiler and `CMAKE_CXX_COMPILIER_LAUNCHER` is not set, set to use launcher.
+    # Will ensure CMAKE_CXX_COMPILER is replaced by nvcc_wrapper
     IF(Kokkos_COMPILE_LAUNCHER AND NOT INTERNAL_HAVE_COMPILER_NVCC AND NOT KOKKOS_CXX_COMPILER_ID STREQUAL Clang)
+      IF(CMAKE_CXX_COMPILER_LAUNCHER)
+      MESSAGE(FATAL_ERROR "Cannot use CMAKE_CXX_COMPILER_LAUNCHER if the CMAKE_CXX_COMPILER is not able to compile CUDA code, i.e. nvcc_wrapper or
```
Comment (masterleinad) [inline cmake/kokkos_compiler_id.cmake:47]:
```suggestion
        MESSAGE(FATAL_ERROR "Cannot use CMAKE_CXX_COMPILER_LAUNCHER if the CMAKE_CXX_COMPILER is not able to compile CUDA code, i.e. nvcc_wrapper or
```

**Comment by ajpowelsnl** [comment]
> `CUDA-9.2-NVCC` failing in `default_exec.overlap_mdrange_policy` is spurious.

OK, thanks for the head's up.

**Comment by ajpowelsnl** [comment]
Hi @dalg24 - would you please send this PR through CI again?  I believe the failure was spurious.
