### PR TITLE
Store sequential host init in unordered map

### LINKED ISSUE #8110: Cannot use SequentialHostInit with UnorderedMap
**Describe the bug**

Attempting to do:
```
UnorderedMap<int, int, HostSpace> map(view_alloc(SequentialHostInit), 4);
```
leads to compile errors because the `UnorderedMap` constructor appends `WithoutInitializing` to the property list passed to the constructor which hits a static assertion about not including both `WithoutInitializing` and `SequentialHostInit` in the same constructor properties.

**Please include the following for a minimal reproducer**
4.6.01 and develop both have the issue, can be reproduced with any compiler.

@crtrott @dalg24

### PR DESCRIPTION
**Pull request by JBludau**
Fixes https://github.com/kokkos/kokkos/issues/8110

This is an attempt to fix the `UnorderedMap` with `value_type=View_like_type` by storing if it was constructed with `SequentialHostInit` and using it for all functions that reallocate.

Another solution (which I found quite hard to implement) would be to add a functionality to remove `SequentialHostInit` (or any property) from `ViewCtorProp` ... the best thing I could think of for this is a meta template typelist and rewriting `ViewCtorProp`...I don't think that is worth it

- [x] needs testing

### CODE REVIEW

**Comment by JBludau** [comment]
@vbrunini could you check if it fixes your problem?

File: containers/src/Kokkos_UnorderedMap.hpp [hunk 1]
```diff
@@ -350,8 +354,8 @@ class UnorderedMap {
     /// properties.
     const auto prop_copy =
         Impl::with_properties_if_unset(arg_prop, std::string("UnorderedMap"));
-    const auto prop_copy_noinit =
-        Impl::with_properties_if_unset(prop_copy, Kokkos::WithoutInitializing);
+    const auto prop_copy_noinit = Impl::with_properties_if_unset_and_compatible(
```
Comment (masterleinad) [inline containers/src/Kokkos_UnorderedMap.hpp]: I would handle the incompatibility here directly. It's not clear what what effect this function call has and if we need to provide a comment we might just as well move the code here without further changes to `Kokkos_ViewCtor.hpp`.

Comment (JBludau) [reply containers/src/Kokkos_UnorderedMap.hpp]: done

File: containers/src/Kokkos_UnorderedMap.hpp [hunk 2]
```diff
@@ -362,14 +364,27 @@ class UnorderedMap {
...
+          prop_copy, Kokkos::WithoutInitializing);
+      m_hash_lists = size_type_view(
+          Kokkos::Impl::append_to_label(prop_copy_noinit, " - hash list"),
+          Impl::find_hash_size(capacity()));
+
+      m_next_index = size_type_view(
+          Kokkos::Impl::append_to_label(prop_copy_noinit, " - next index"),
+          capacity() + 1);  // +1 so that the *_at functions can always return a
+                            // valid reference
+    }
```
Comment (romintomasetti) [inline containers/src/Kokkos_UnorderedMap.hpp]: IMO this is just too much duplication to be acceptable.

**Review by romintomasetti — CHANGES_REQUESTED** [review]
Wondering about the maintainability of the proposed solution.

File: containers/src/Kokkos_UnorderedMap.hpp (hunk 2 above)
Comment (romintomasetti) [reply containers/src/Kokkos_UnorderedMap.hpp]: Though implementing a "property removal" mechanism seems indeed not an easy task, I guess it might prove useful in other (not encountered yet) situations.

Comment (JBludau) [reply containers/src/Kokkos_UnorderedMap.hpp]: We do not have a consensus yet if we even want to allow this ... UnorderedMap never promised to allow that.
The `WithoutInitializing` is just an internal performance optimization, so going the cheap way if we want to allow that could be deemed reasonable.

I tried to implement a recursion that removes the property but AFAIKT it would need to expand the parameter list into a template list and then instantiate the `ViewCtorProp` from this ... all of this complexity for a "might prove useful in other not yet encountered situations". If we have a strong reasoning/reuse of it then I agree but I don't see it yet.

Another solution I explored was having a `with_properties_if_unset_and_compatible` which would be an intermediate way of doing this (compatible would mean: non conflicting).

Comment (JBludau) [reply containers/src/Kokkos_UnorderedMap.hpp]: I tried to redesigned it a bit, what do you think?

Comment (masterleinad) [reply containers/src/Kokkos_UnorderedMap.hpp]: https://github.com/kokkos/kokkos/pull/8182/commits/4753f3b4b1675ee16703f043e9148cba5c8e2eac was fine with me.

File: containers/src/Kokkos_UnorderedMap.hpp [hunk 3]
```diff
@@ -382,6 +382,12 @@ class UnorderedMap {
     static_assert(
         !alloc_prop_t::has_pointer,
         "Allocation properties should not contain the 'pointer' property.");
+    static_assert(
+        alloc_prop_t::sequential_host_init &&
+            (SpaceAccessibility<
+                HostSpace, typename execution_space::memory_space>::accessible),
+        "SequentialHostInit only allowed if the UnorderedMap's MemorySpace is "
+        "accesible to the host.");
```
Comment (masterleinad) [inline containers/src/Kokkos_UnorderedMap.hpp]: We already have a `static_assert` at https://github.com/kokkos/kokkos/blob/28848dfa8fc1411873b6a663c4d29ba05712510e/core/src/View/Kokkos_ViewAlloc.hpp#L200.

Comment (JBludau) [reply containers/src/Kokkos_UnorderedMap.hpp]: I wanted to make it more apparent to users ... but we can definitely remove it

File: containers/src/Kokkos_UnorderedMap.hpp [hunk 4]
```diff
@@ -362,14 +403,15 @@ class UnorderedMap {
...
-        Impl::find_hash_size(capacity()));
+    m_hash_lists = allocate_with_property_if_compatible<size_type_view>(
+        Kokkos::Impl::append_to_label(prop_copy, " - hash list"),
+        WithoutInitializing, Impl::find_hash_size(capacity()));
 
-    m_next_index = size_type_view(
-        Kokkos::Impl::append_to_label(prop_copy_noinit, " - next index"),
-        capacity() + 1);  // +1 so that the *_at functions can always return a
-                          // valid reference
+    m_next_index = allocate_with_property_if_compatible<size_type_view>(
```
Comment (romintomasetti) [inline containers/src/Kokkos_UnorderedMap.hpp]: Why would you need sequential host initialization for views that are internal to `UnorderedMap` and are not supposed to contain problematic user types?

Comment (JBludau) [reply containers/src/Kokkos_UnorderedMap.hpp]: We don't need it. But instead of implementing something complex to remove `SequentialHostInit` from the `ViewCtorProp`, we just add the `WithoutInitializing` if it is not conflicting.

After all the `WithoutInitializing` is an internal optimization ... disabling it in cases that we never promised in our documentation but Trilinos is using is a reasonable approach.

Comment (romintomasetti) [reply containers/src/Kokkos_UnorderedMap.hpp]: I am not sure these changes are going in a direction that is maintainable neither aligned with standard practice. Sure, it might solve the user case, but it's not really a good solution IMO.

The fact that you need to store the `m_SequentialHostInit` as a `bool` member even though it is clearly a static property tied to the value type that the user puts in the unordered map feels awkward. Moreover, using `allocate_with_property_if_compatible` all over the place seems an avoidable compiler cost.

All in all, I think the "value type requiring a sequential host init" case raises the following bigger picture issue:
> Why isn't the `UnorderedMap` templated over some allocator traits as `std::unordered_map` does ?

I think breaking the `UnorderedMap` to introduce an additional template parameter that represents some sort of allocation property is more than required to make the whole thing closer to `std::` and readable.

What do you think ?

Comment (romintomasetti) [reply containers/src/Kokkos_UnorderedMap.hpp]: Note that for the view, this is hidden in the `SharedAllocationRecord` thingy, see *e.g.*:
- https://github.com/kokkos/kokkos/blob/28848dfa8fc1411873b6a663c4d29ba05712510e/core/src/impl/Kokkos_SharedAlloc.hpp#L30-L31
- https://github.com/kokkos/kokkos/blob/28848dfa8fc1411873b6a663c4d29ba05712510e/core/src/View/Kokkos_ViewMapping.hpp#L2802-L2807

Comment (JBludau) [reply containers/src/Kokkos_UnorderedMap.hpp]: I do see your point and am agreeing in principle. Nevertheless, this would completely break users (which is (AFAIK) the reason why `View` is not templated over the allocator traits and `SharedAllocationRecord` hides it away). I see that not keeping the allocator info around is only a halfway solution since it allows the `SharedAllocationRecord` to delete itself but `View` and types depending on it can not access the info how data was allocated.

This creates the exact problem like we see here: if you need to reallocate you don't know how to.
AFAIK we are not planning to make `View` and dependent types allocator-aware @crtrott @dalg24.

Thus the question arises: how do we handle this case of `UnorderedMap` with `View-like types` as `value_type`? It looks like it is used in some important codes. What I am trying to propose here is a minimal solution (you can call it hack) to just allow this for `UnorderedMap` ... as an reaction to reality, not because we necessarily want to.
But it is a draft since I am also not sure if it is a good idea in the first place ... We could just say: This has to be taken care of by users themselves since it is not aligned with what we promise. Effectively forcing users to construct and delete themselves

File: containers/src/Kokkos_UnorderedMap.hpp (hunk 3 above)
Comment (JBludau) [reply containers/src/Kokkos_UnorderedMap.hpp]: I removed it in https://github.com/kokkos/kokkos/pull/8182/commits/fc5c9179f991a603fc38f89fe47a40c04ea7ade0

**Comment by JBludau** [comment]
In the developer meeting we decided that we would like to support `View-like` types as `value_types` but will not go all the way to do allocators since it would require a large change in the implementation of `View`.

File: containers/src/Kokkos_UnorderedMap.hpp [hunk 5]
```diff
@@ -62,6 +62,40 @@
 
 namespace Kokkos {
 
+namespace {
```
Comment (masterleinad) [inline containers/src/Kokkos_UnorderedMap.hpp]: We shouldn't use anonymous namespaces in header files. That is generally problematic for C++20 modules.

File: containers/src/Kokkos_UnorderedMap.hpp [hunk 6]
```diff
@@ -62,6 +62,40 @@
...
+
+template <typename ViewType, typename... P, typename Property, typename... Args>
+auto allocate_with_property_if_compatible(
```
Comment (masterleinad) [inline containers/src/Kokkos_UnorderedMap.hpp]: I need to read through the implementation to understand what that does.
AFAICT, we basically only need
```C++
if constexpr (std::is_same_v<Property, Impl::WithoutInitializing_t> && alloc_prop_t::sequential_host_init)
  return ViewType(alloc_prop, std::forward<Args>(args)...);
else
  return ViewType(Impl::with_properties_if_unset(alloc_prop, property),
                    std::forward<Args>(args)...);
```
Why do we need the `SequentialHostInit path` branch?

File: containers/src/Kokkos_UnorderedMap.hpp [hunk 7]
```diff
@@ -331,7 +365,11 @@ class UnorderedMap {
   UnorderedMap(const Impl::ViewCtorProp<P...> &arg_prop,
                size_type capacity_hint = 0, hasher_type hasher = hasher_type(),
                equal_to_type equal_to = equal_to_type())
-      : m_bounded_insert(true), m_hasher(hasher), m_equal_to(equal_to) {
+      : m_bounded_insert(true),
+        m_hasher(hasher),
+        m_equal_to(equal_to),
+        m_SequentialHostInit(
```
Comment (masterleinad) [inline containers/src/Kokkos_UnorderedMap.hpp]:
```suggestion
        m_has_sequential_host_init(
```

File: containers/src/Kokkos_UnorderedMap.hpp (hunk 6 above)
Comment (JBludau) [reply containers/src/Kokkos_UnorderedMap.hpp]: that is for checking that we only use the SequentialHostInit if the Host can actually access the memory space.
But you are right, we could collapse it. I chose this version since I thought it would be more explicitly expressing what is happening

File: containers/src/Kokkos_UnorderedMap.hpp (hunk 7 above)
Comment (JBludau) [reply containers/src/Kokkos_UnorderedMap.hpp]: done in https://github.com/kokkos/kokkos/pull/8182/commits/ff2b98e9b2c34efeaaca977050fec4dd47e57f9d

File: containers/src/Kokkos_UnorderedMap.hpp (hunk 6 above)
Comment (JBludau) [reply containers/src/Kokkos_UnorderedMap.hpp]: I reformulated in https://github.com/kokkos/kokkos/pull/8182/commits/27c487269cff8f2f1efb7d4b3bb0a35ea272edca

File: containers/src/Kokkos_UnorderedMap.hpp (hunk 5 above)
Comment (JBludau) [reply containers/src/Kokkos_UnorderedMap.hpp]: moved to impl in https://github.com/kokkos/kokkos/pull/8182/commits/57ac960a7803cab17db20b7f8872c9dc4d8352ef

File: containers/src/Kokkos_UnorderedMap.hpp (hunk 6 above)
Comment (masterleinad) [reply containers/src/Kokkos_UnorderedMap.hpp]: I still don't understand when we need to check for SpaceAccessibility. If the user asked for SequentialHostinit we never remove that attribute anyway and would get an error if requesting a memory space that isn't host accessible anyway. Therefore, it doesn't matter that we try adding it later ourselves. That would only succeed if we used a host-accessible memory space before (and we shouldn't skip adding it). We only need to avoid adding WithoutInitializing if SequentialHostInit is already set.

**Review by masterleinad — COMMENTED** [review]
We still need a unit tests, preferrably with a `View` as `Value` type.

File: containers/src/Kokkos_UnorderedMap.hpp (hunk 6 above)
Comment (JBludau) [reply containers/src/Kokkos_UnorderedMap.hpp]: https://github.com/kokkos/kokkos/pull/8182/commits/61401f4371110fb0aae65ccdf68138960bd387a1 removes the accessibility check

Comment (JBludau) [reply containers/src/Kokkos_UnorderedMap.hpp]: But I think we need it since we have a runtime decision of adding `SequentialHostInit`. As the compiler will explore both paths in the ternary it will hit the `static_assert` checking for the accessibility and fail.

That being said: I don't understand yet why this is not failing in more builds ... It should fail in any device build except the MI300A but it passes for Cuda 11, while failing for rocm 5.7. If I compile it with rocm 6.0 in a container it passes ... Also the gitlab CI shows this a similar pattern

Comment (JBludau) [reply containers/src/Kokkos_UnorderedMap.hpp]: Ok, my best guess is that this comes down to dead code path removal in the compiler. Depending on when this is done during compilation, one branch of the ternary is never compiled thus never triggering the `static_assert`.

That being said, semantically we need to check for the space accessibility if we want to allow adding `SequentialHostInit` to `UnorderedMap` and store it during the runtime. The compiler will need to be able to compile the code independent of the runtime setting of `SequentialHostInit` without running into the `static_assert` in the internal view allocation. Some compilers pass the compilation but semantically it is still incorrect.

I readded the check.

Comment (masterleinad) [reply containers/src/Kokkos_UnorderedMap.hpp]: Fair enough with a good test case.

**Review by masterleinad — DISMISSED** [review]

**Comment by JBludau** [comment]
the force push was just to rebase on develop

File: containers/unit_tests/TestUnorderedMap.hpp [hunk 8]
```diff
@@ -560,6 +560,49 @@ TEST(TEST_CATEGORY, UnorderedMap_constructor_view_alloc) {
   ASSERT_TRUE(map.is_allocated());
 }
 
+//////////////////////////Tests for UnorderedMap with View as value_type
+
+/**
+ * @test This test ensures that an @ref UnorderedMap with View as value_type can
+ * be built with an execution space instance (using @ref view_alloc).
```
Comment (romintomasetti) [inline containers/unit_tests/TestUnorderedMap.hpp]: It seems you're not passing an execution space instance to the constructor.

File: containers/unit_tests/TestUnorderedMap.hpp [hunk 9]
```diff
@@ -560,6 +560,49 @@ TEST(TEST_CATEGORY, UnorderedMap_constructor_view_alloc) {
...
+ */
+TEST(TEST_CATEGORY, UnorderedMap_View_as_value) {
+  using map_type =
+      Kokkos::UnorderedMap<int, Kokkos::View<size_t *, TEST_EXECSPACE>,
+                           Kokkos::HostSpace>;
```
Comment (romintomasetti) [inline containers/unit_tests/TestUnorderedMap.hpp]: It will make it more readable when you insert values.
```suggestion
  using value_type = Kokkos::View<size_t *, TEST_EXECSPACE>;
  using map_type = Kokkos::UnorderedMap<int, value_type, Kokkos::HostSpace>;
```

File: containers/src/Kokkos_UnorderedMap.hpp [hunk 10]
```diff
@@ -331,7 +354,11 @@ class UnorderedMap {
   UnorderedMap(const Impl::ViewCtorProp<P...> &arg_prop,
                size_type capacity_hint = 0, hasher_type hasher = hasher_type(),
                equal_to_type equal_to = equal_to_type())
-      : m_bounded_insert(true), m_hasher(hasher), m_equal_to(equal_to) {
+      : m_bounded_insert(true),
+        m_hasher(hasher),
+        m_equal_to(equal_to),
+        m_sequential_host_init(
+            std::decay_t<decltype(arg_prop)>::sequential_host_init) {
```
Comment (romintomasetti) [inline containers/src/Kokkos_UnorderedMap.hpp]:
```suggestion
            std::remove_cvref_t<decltype(arg_prop)>::sequential_host_init) {
```

File: containers/src/Kokkos_UnorderedMap.hpp [hunk 11]
```diff
@@ -446,7 +472,13 @@ class UnorderedMap {
...
         (requested_capacity < curr_size) ? curr_size : requested_capacity;
 
-    insertable_map_type tmp(requested_capacity, m_hasher, m_equal_to);
+    auto tmp =
+        m_sequential_host_init
+            ? Impl::allocate_with_property_if_compatible<insertable_map_type>(
+                  view_alloc(), SequentialHostInit, requested_capacity,
+                  m_hasher, m_equal_to)
+            : insertable_map_type(view_alloc(), requested_capacity, m_hasher,
+                                  m_equal_to);
```
Comment (romintomasetti) [inline containers/src/Kokkos_UnorderedMap.hpp]:
```suggestion
            : insertable_map_type(requested_capacity, m_hasher, m_equal_to);
```

File: containers/src/Kokkos_UnorderedMap.hpp [hunk 12]
```diff
@@ -62,6 +62,29 @@
 
 namespace Kokkos {
 
+namespace Impl {
+
+template <typename ViewType, typename... P, typename Property, typename... Args>
+auto allocate_with_property_if_compatible(
+    const Impl::ViewCtorProp<P...> &alloc_prop,
+    [[maybe_unused]] const Property &property, Args &&...args) {
+  using alloc_prop_t = std::decay_t<decltype(alloc_prop)>;
```
Comment (romintomasetti) [inline containers/src/Kokkos_UnorderedMap.hpp]:
```suggestion
  using alloc_prop_t = std::remove_cvref_t<decltype(alloc_prop)>;
```

**Review by romintomasetti — DISMISSED** [review]
I'm still a bit disappointed that we don't go for allocators but I'll live with it :wink:

File: containers/unit_tests/TestUnorderedMap.hpp (hunk 8 above)
Comment (JBludau) [reply containers/unit_tests/TestUnorderedMap.hpp]: good catch ... fixed in https://github.com/kokkos/kokkos/pull/8182/commits/e5ec86407e4c3d5b6677b27fd7b8384d24ac3d06

**Comment by JBludau** [comment]
~~Right now it is contingent on `SharedSpace` ... should we extend it to MI300A?~~
that was just me not thinking it through

File: containers/src/Kokkos_UnorderedMap.hpp [hunk 13]
```diff
@@ -62,6 +62,29 @@
 
 namespace Kokkos {
 
+namespace Impl {
+
+template <typename ViewType, typename... P, typename Property, typename... Args>
+auto allocate_with_property_if_compatible(
+    const Impl::ViewCtorProp<P...> &alloc_prop,
+    [[maybe_unused]] const Property &property, Args &&...args) {
+  using alloc_prop_t = Impl::remove_cvref_t<decltype(alloc_prop)>;
```
Comment (nmm0) [inline containers/src/Kokkos_UnorderedMap.hpp:70]: I think

```suggestion
  using alloc_prop_t = Impl::ViewCtorProp<P...>;
```

Is slightly more readable

File: containers/src/Kokkos_UnorderedMap.hpp [hunk 14]
```diff
@@ -62,6 +62,29 @@
 
 namespace Kokkos {
 
+namespace Impl {
+
+template <typename ViewType, typename... P, typename Property, typename... Args>
+auto allocate_with_property_if_compatible(
```
Comment (nmm0) [inline containers/src/Kokkos_UnorderedMap.hpp]: I honestly would prefer if this was split into two functions -- one for `WithoutInitializing_t` and the other for `SequentialHostInit_t`. This function is named as if it were a general function (`allocate_with_property_if_compatible`), and at first I thought it should be moved to `Kokkos_ViewCtor`. However "compatible"  here just means that you can't have `WithoutInitializing_t` and the added property is `sequential_host_init`, or we added `SequentialHostInit_t` but the memory space is not host accessible.

I think it's better to design functions that do one thing.

This code would be greatly simplified if it was split into two functions, something like `allocate_without_initializing_if_valid` and `allocate_with_sequential_host_init_if_host_accessible` or something like that (names could use workshopping).

File: containers/src/Kokkos_UnorderedMap.hpp (hunk 13 above)
Comment (JBludau) [reply containers/src/Kokkos_UnorderedMap.hpp:70]: was kept for consistency with the rest of the file

**Review by nmm0 — APPROVED** [review]
Looks good to me!

**Comment by masterleinad** [comment]
```
In file included from /home/runner/_work/kokkos/kokkos/kokkos/containers/src/impl/Kokkos_UnorderedMap_impl.cpp:21:
/home/runner/_work/kokkos/kokkos/kokkos/containers/src/Kokkos_UnorderedMap.hpp:85:9: error: unused type alias 'alloc_prop_t' [-Werror,-Wunused-local-typedef]
  using alloc_prop_t = Impl::remove_cvref_t<decltype(alloc_prop)>;
        ^
1 error generated when compiling for gfx90a.
```

**Review by masterleinad — APPROVED** [review]
Looks OK to me.

File: containers/src/Kokkos_UnorderedMap.hpp (hunk 14 above)
Comment (JBludau) [reply containers/src/Kokkos_UnorderedMap.hpp]: done in https://github.com/kokkos/kokkos/pull/8182/commits/6ebe1e92e2a06a99a91ccc6ebd2c6dcaa565d0dc

**Comment by JBludau** [comment]
The CI failures are unrelated.
I removed the `blocks_promotion` since it is not really blocking but something we never promised `UnorderedMap` to be able to do. Thus it is more a convenience fix

**Comment by JBludau** [comment]
Retest this please

**Review by crtrott — APPROVED** [review]
I think this is a good compromise. Read through the discussion and looked all reasonable to me (i.e. the decisions made on some of the imp choices.).

**Comment by crtrott** [comment]
Will merge after rerunning the SYCL tests is finished.

**Comment by JBludau** [comment]
@dalg24 @crtrott Do we want this in the changelog? And in the documentation? I am kind of hesitant to put it in the documentation ...

**Comment by JBludau** [comment]
I put it in the changelog but am really hesitant for the documentation

**Comment by masterleinad** [comment]
> I put it in the changelog but am really hesitant for the documentation

I think we should document that `Views` as value type is supported (if the memory space for `UnorderedMap` is host-accessible).
