### PR TITLE
Converted a shared_ptr to a host view in UnorderedMap

### LINKED ISSUE #6066: Can no longer shallow copy `Kokkos::UnorderedMap` on Device
With latest Kokkos `develop` branch we can no longer shallow copy `Kokkos::UnorderedMap` on device. It fails with:

```
error: reference to __host__ function 'UnorderedMap' in __host__ __device__ function
```

### PR DESCRIPTION
**Pull request by ldh4**
In attempt to resolve #6066.

A shared_ptr for `m_size` was introduced in `UnorderedMap` in #5983 to resolve a memory corruption, but this made `UnorderedMap` no longer copyable on device.

Changed to use a host view in place of `shared_ptr`.

### CODE REVIEW

**Comment by masterleinad** [comment]
@crtrott suggested a `HostSharedPtr` in the meeting on Wednesday but I'm also OK with a `View`.

File: containers/src/Kokkos_UnorderedMap.hpp [hunk 1]
```diff
@@ -286,7 +286,8 @@ class UnorderedMap {
 
   enum { modified_idx = 0, erasable_idx = 1, failed_insert_idx = 2 };
   enum { num_scalars = 3 };
-  using scalars_view = View<int[num_scalars], LayoutLeft, device_type>;
+  using scalars_view     = View<int[num_scalars], LayoutLeft, device_type>;
+  using scalar_host_view = View<size_type[1], HostSpace>;
```
Comment (masterleinad) [inline containers/src/Kokkos_UnorderedMap.hpp:290]: I would use a zero-dimensional View instead since we are really wrapping a singular rather than a one-dimensional range consisting of one element.
```suggestion
  using scalar_host_view = View<size_type, HostSpace>;
```

File: containers/src/Kokkos_UnorderedMap.hpp [hunk 2]
```diff
@@ -401,10 +402,10 @@ class UnorderedMap {
   size_type size() const {
     if (capacity() == 0u) return 0u;
     if (modified()) {
-      *m_size = m_available_indexes.count();
+      m_size(0) = m_available_indexes.count();
```
Comment (masterleinad) [inline containers/src/Kokkos_UnorderedMap.hpp:405]:
```suggestion
      m_size() = m_available_indexes.count();
```

File: containers/src/Kokkos_UnorderedMap.hpp [hunk 3]
```diff
@@ -769,7 +770,7 @@ class UnorderedMap {
       tmp.m_bounded_insert    = src.m_bounded_insert;
       tmp.m_hasher            = src.m_hasher;
       tmp.m_equal_to          = src.m_equal_to;
-      *tmp.m_size             = *src.m_size;
+      tmp.m_size(0)           = src.m_size(0);
```
Comment (masterleinad) [inline containers/src/Kokkos_UnorderedMap.hpp:773]:
```suggestion
      tmp.m_size()           = src.m_size();
```

**Comment by ldh4** [comment]
> @crtrott suggested a `HostSharedPtr` in the meeting on Wednesday but I'm also OK with a `View`.

I must've missed that part. If there's any further preference for `HostSharedPtr` over a `View` here, I'll make a switch to it.

**Review by masterleinad — APPROVED** [review]

**Comment by ldh4** [comment]
Retest this please.

File: containers/src/Kokkos_UnorderedMap.hpp [hunk 4]
```diff
@@ -286,7 +286,8 @@ class UnorderedMap {
 
   enum { modified_idx = 0, erasable_idx = 1, failed_insert_idx = 2 };
   enum { num_scalars = 3 };
-  using scalars_view = View<int[num_scalars], LayoutLeft, device_type>;
+  using scalars_view     = View<int[num_scalars], LayoutLeft, device_type>;
+  using scalar_host_view = View<size_type, HostSpace>;
```
Comment (dalg24) [inline containers/src/Kokkos_UnorderedMap.hpp:290]: Not sure it is worth defining an alias since it is only used once.

File: containers/unit_tests/TestUnorderedMap.hpp [hunk 5]
```diff
@@ -480,6 +480,48 @@ TEST(TEST_CATEGORY, UnorderedMap_consistent_size) {
   ASSERT_EQ(2u, m.size());
 }
 
+namespace Impl {
```
Comment (dalg24) [inline containers/unit_tests/TestUnorderedMap.hpp:483]: Why are you introducing that nested namespace?

File: containers/unit_tests/TestUnorderedMap.hpp [hunk 6]
```diff
@@ -480,6 +480,48 @@ TEST(TEST_CATEGORY, UnorderedMap_consistent_size) {
...
+
+using map_type = Kokkos::UnorderedMap<int, void, Kokkos::DefaultExecutionSpace>;
```
Comment (dalg24) [inline containers/unit_tests/TestUnorderedMap.hpp:485]: Use `TEST_EXECSPACE`?

File: containers/unit_tests/TestUnorderedMap.hpp [hunk 7]
```diff
@@ -480,6 +480,48 @@ TEST(TEST_CATEGORY, UnorderedMap_consistent_size) {
...
+  KOKKOS_FUNCTION
+  void operator()(const int i) const { test_insert_to_map_copy(m_map, i); }
+};
+
+}  // namespace Impl
+
+TEST(TEST_CATEGORY, UnorderedMap_shallow_copyable_on_device) {
+  Impl::TestMapCopy test_map_copy;
+
+  Kokkos::parallel_for(1, test_map_copy);
```
Comment (dalg24) [inline containers/unit_tests/TestUnorderedMap.hpp:505]: Use `TEST_EXECSPACE`.  Otherwise we are testing the exact same thing for each backend that is enabled.

File: containers/unit_tests/TestUnorderedMap.hpp [hunk 8]
```diff
@@ -480,6 +480,48 @@ TEST(TEST_CATEGORY, UnorderedMap_consistent_size) {
   ASSERT_EQ(2u, m.size());
 }
 
+namespace Impl {
+
+using map_type = Kokkos::UnorderedMap<int, void, Kokkos::DefaultExecutionSpace>;
+
+KOKKOS_FUNCTION
+void test_insert_to_map_copy(map_type const &input_map, const int i) {
```
Comment (dalg24) [inline containers/unit_tests/TestUnorderedMap.hpp:488]: Does the insertion matter at all or is it just about calling the copy constructor on the device side?

File: containers/unit_tests/TestUnorderedMap.hpp [hunk 9]
```diff
@@ -480,6 +480,48 @@ TEST(TEST_CATEGORY, UnorderedMap_consistent_size) {
...
+TEST(TEST_CATEGORY, UnorderedMap_shallow_copyable_on_device) {
+  Impl::TestMapCopy test_map_copy;
+
+  Kokkos::parallel_for(1, test_map_copy);
+  ASSERT_EQ(1u, test_map_copy.m_map.size());
+}
+
+#if !defined(KOKKOS_ENABLE_CUDA) || \
+    (defined(KOKKOS_ENABLE_CUDA) && defined(KOKKOS_ENABLE_CUDA_LAMBDA))
+void test_unordered_map_device_capture() {
```
Comment (dalg24) [inline containers/unit_tests/TestUnorderedMap.hpp:511]: Would this test actually fail without this patch?

Comment (ldh4) [reply containers/unit_tests/TestUnorderedMap.hpp:507]: Yes, without this patch, compiling this lambda capture test will produce multiple warnings/errors like this:
`calling a __host__ function("std::__shared_count<( ::__gnu_cxx::_Lock_policy)2> ::~__shared_count") from a __host__ __device__ function("Kokkos::UnorderedMap<int, void,  ::Kokkos::Cuda,  ::Kokkos::pod_hash<int> ,  ::Kokkos::pod_equal_to<int> > ::~UnorderedMap [subobject]") is not allowed`.

It is a little different compile error output from the shallow_copy test above, but they are both produced by having a `shared_ptr` in `UnorderedMap` and are resolved with this patch.

File: containers/unit_tests/TestUnorderedMap.hpp (hunk 6 above)
Comment (ldh4) [reply containers/unit_tests/TestUnorderedMap.hpp]: Changed in [dd1bd50](https://github.com/kokkos/kokkos/pull/6073/commits/dd1bd50f4d5b1d191d28dbed23d36895fcafe05f).

File: containers/unit_tests/TestUnorderedMap.hpp (hunk 7 above)
Comment (ldh4) [reply containers/unit_tests/TestUnorderedMap.hpp]: Changed in [dd1bd50](https://github.com/kokkos/kokkos/pull/6073/commits/dd1bd50f4d5b1d191d28dbed23d36895fcafe05f).

File: containers/src/Kokkos_UnorderedMap.hpp [hunk 10]
```diff
@@ -286,7 +286,7 @@ class UnorderedMap {
 
   enum { modified_idx = 0, erasable_idx = 1, failed_insert_idx = 2 };
   enum { num_scalars = 3 };
-  using scalars_view = View<int[num_scalars], LayoutLeft, device_type>;
+  using scalars_view     = View<int[num_scalars], LayoutLeft, device_type>;
```
Comment (dalg24) [inline containers/src/Kokkos_UnorderedMap.hpp]: I bet that is not formatted properly ;)

Comment (ldh4) [reply containers/src/Kokkos_UnorderedMap.hpp]: Yep. Fixed.

File: containers/unit_tests/TestUnorderedMap.hpp [hunk 11]
```diff
@@ -480,6 +480,44 @@ TEST(TEST_CATEGORY, UnorderedMap_consistent_size) {
...
+  TestMapCopy::map_type map;
+
+  Kokkos::parallel_for(
+      1, KOKKOS_LAMBDA(int const &i) { map.insert(i); });
```
Comment (dalg24) [inline containers/unit_tests/TestUnorderedMap.hpp:511]: Must run it on the proper TEST_EXECSPACE

Comment (ldh4) [reply containers/unit_tests/TestUnorderedMap.hpp]: Fixed in [e9bedb2](https://github.com/kokkos/kokkos/pull/6073/commits/e9bedb2a9832efa3e81561842a753afea7d1f291).

**Review by dalg24 — APPROVED** [review]

**Review by nliber — APPROVED** [review]
