### PR TITLE
Fix cuda visibility problem in `ExecutionSpaceTrait`

### LINKED ISSUE #8493: Attribute warning in `ExecutionSpaceTrait`
In the wake of compiling on Hopper with cuda 12.8.1 to check the 128bit atomics this came up:
```
core/src/traits/Kokkos_ExecutionSpaceTrait.hpp: In instantiation of ‘struct Kokkos::Impl::ExecutionSpaceTrait::mixin_matching_trait<Kokkos::Serial, Kokkos::Impl::AnalyzeExecPolicy<void, Kokkos::IndexType<long int>, Kokkos::Impl::ViewValueFunctor<Kokkos::Device<Kokkos::Serial, Kokkos::HostSpace>, _GLOBAL__N__9bb5b31a_22_TestSerial_Atomics_cpp_cad38beb_3867969::SuperScalar<4> >::ConstructTag> >’:
/home/users/jakobbludau/kokkos_atomics/core/src/impl/Kokkos_AnalyzePolicy.hpp:116:8:   required from ‘struct Kokkos::Impl::AnalyzeExecPolicyUseMatcher<void, Kokkos::Impl::type_list<Kokkos::Impl::ExecutionSpaceTrait, Kokkos::Impl::IndexTypeTrait, Kokkos::Impl::ScheduleTrait, Kokkos::Impl::IterationPatternTrait, Kokkos::Impl::WorkItemPropertyTrait, Kokkos::Impl::LaunchBoundsTrait, Kokkos::Impl::OccupancyControlTrait, Kokkos::Impl::GraphKernelTrait, Kokkos::Impl::WorkTagTrait>, Kokkos::Serial, Kokkos::IndexType<long int>, Kokkos::Impl::ViewValueFunctor<Kokkos::Device<Kokkos::Serial, Kokkos::HostSpace>, _GLOBAL__N__9bb5b31a_22_TestSerial_Atomics_cpp_cad38beb_3867969::SuperScalar<4> >::ConstructTag>’
/home/users/jakobbludau/kokkos_atomics/core/src/impl/Kokkos_AnalyzePolicy.hpp:63:8:   required from ‘struct Kokkos::Impl::AnalyzeExecPolicy<void, Kokkos::Serial, Kokkos::IndexType<long int>, Kokkos::Impl::ViewValueFunctor<Kokkos::Device<Kokkos::Serial, Kokkos::HostSpace>, _GLOBAL__N__9bb5b31a_22_TestSerial_Atomics_cpp_cad38beb_3867969::SuperScalar<4> >::ConstructTag>’
/home/users/jakobbludau/kokkos_atomics/core/src/impl/Kokkos_AnalyzePolicy.hpp:166:8:   required from ‘struct Kokkos::Impl::ExecPolicyTraitsWithDefaults<Kokkos::Impl::AnalyzeExecPolicy<void, Kokkos::Serial, Kokkos::IndexType<long int>, Kokkos::Impl::ViewValueFunctor<Kokkos::Device<Kokkos::Serial, Kokkos::HostSpace>, _GLOBAL__N__9bb5b31a_22_TestSerial_Atomics_cpp_cad38beb_3867969::SuperScalar<4> >::ConstructTag> >’
/home/users/jakobbludau/kokkos_atomics/core/src/impl/Kokkos_AnalyzePolicy.hpp:182:8:   required from ‘struct Kokkos::Impl::PolicyTraits<Kokkos::Serial, Kokkos::IndexType<long int>, Kokkos::Impl::ViewValueFunctor<Kokkos::Device<Kokkos::Serial, Kokkos::HostSpace>, _GLOBAL__N__9bb5b31a_22_TestSerial_Atomics_cpp_cad38beb_3867969::SuperScalar<4> >::ConstructTag>’
/home/users/jakobbludau/kokkos_atomics/core/src/Kokkos_ExecPolicy.hpp:78:7:   required from ‘class Kokkos::RangePolicy<Kokkos::Serial, Kokkos::IndexType<long int>, Kokkos::Impl::ViewValueFunctor<Kokkos::Device<Kokkos::Serial, Kokkos::HostSpace>, _GLOBAL__N__9bb5b31a_22_TestSerial_Atomics_cpp_cad38beb_3867969::SuperScalar<4> >::ConstructTag>’
/home/users/jakobbludau/kokkos_atomics/core/src/View/Kokkos_ViewAlloc.hpp:103:12:   [ skipping 5 instantiation contexts, use -ftemplate-backtrace-limit=0 to disable ]
/home/users/jakobbludau/kokkos_atomics/core/src/Kokkos_View.hpp:688:274:   required from ‘Kokkos::View<DataType, Properties>::View(const Kokkos::Impl::ViewCtorProp<Args ...>&, std::enable_if_t<(! Kokkos::Impl::ViewCtorProp<Args ...>::has_pointer), const long unsigned int>, size_t, size_t, size_t, size_t, size_t, size_t, size_t) [with P = {std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >}; DataType = _GLOBAL__N__9bb5b31a_22_TestSerial_Atomics_cpp_cad38beb_3867969::SuperScalar<4>; Properties = {Kokkos::Serial}; std::enable_if_t<(! Kokkos::Impl::ViewCtorProp<Args ...>::has_pointer), const long unsigned int> = const long unsigned int; size_t = long unsigned int]’
/home/users/jakobbludau/kokkos_atomics/core/src/Kokkos_View.hpp:783:105:   required from ‘Kokkos::View<DataType, Properties>::View(std::enable_if_t<((sizeof... (Args) != (Kokkos::View<DataType, Properties>::rank() + 1)) && (is_constructible_v<long unsigned int, Args>&& ... && true)), const std::__cxx11::basic_string<char>&>, const Args ...) [with Args = {}; DataType = _GLOBAL__N__9bb5b31a_22_TestSerial_Atomics_cpp_cad38beb_3867969::SuperScalar<4>; Properties = {Kokkos::Serial}; std::enable_if_t<((sizeof... (Args) != (Kokkos::View<DataType, Properties>::rank() + 1)) && (is_constructible_v<long unsigned int, Args>&& ... && true)), const std::__cxx11::basic_string<char>&> = const std::__cxx11::basic_string<char>&]’
/home/users/jakobbludau/kokkos_atomics/core/unit_test/TestAtomics.hpp:166:50:   required from ‘T _GLOBAL__N__9bb5b31a_22_TestSerial_Atomics_cpp_cad38beb_3867969::AddLoop(int) [with T = _GLOBAL__N__9bb5b31a_22_TestSerial_Atomics_cpp_cad38beb_3867969::SuperScalar<4>; execution_space = Kokkos::Serial]’
/home/users/jakobbludau/kokkos_atomics/core/unit_test/TestAtomics.hpp:418:41:   required from ‘T _GLOBAL__N__9bb5b31a_22_TestSerial_Atomics_cpp_cad38beb_3867969::LoopVariant(int, int) [with T = _GLOBAL__N__9bb5b31a_22_TestSerial_Atomics_cpp_cad38beb_3867969::SuperScalar<4>; DeviceType = Kokkos::Serial]’
/home/users/jakobbludau/kokkos_atomics/core/unit_test/TestAtomics.hpp:449:37:   required from ‘void _GLOBAL__N__9bb5b31a_22_TestSerial_Atomics_cpp_cad38beb_3867969::Loop(int, int) [with T = _GLOBAL__N__9bb5b31a_22_TestSerial_Atomics_cpp_cad38beb_3867969::SuperScalar<4>; DeviceType = Kokkos::Serial]’
/home/users/jakobbludau/kokkos_atomics/core/unit_test/TestAtomics.hpp:552:41:   required from here
/home/users/jakobbludau/kokkos_atomics/core/src/traits/Kokkos_ExecutionSpaceTrait.hpp:46:8: error: ‘Kokkos::Impl::ExecutionSpaceTrait::mixin_matching_trait<Kokkos::Serial, Kokkos::Impl::AnalyzeExecPolicy<void, Kokkos::IndexType<long int>, Kokkos::Impl::ViewValueFunctor<Kokkos::Device<Kokkos::Serial, Kokkos::HostSpace>, _GLOBAL__N__9bb5b31a_22_TestSerial_Atomics_cpp_cad38beb_3867969::SuperScalar<4> >::ConstructTag> >’ declared with greater visibility than its base ‘Kokkos::Impl::AnalyzeExecPolicy<void, Kokkos::IndexType<long int>, Kokkos::Impl::ViewValueFunctor<Kokkos::Device<Kokkos::Serial, Kokkos::HostSpace>, _GLOBAL__N__9bb5b31a_22_TestSerial_Atomics_cpp_cad38beb_3867969::SuperScalar<4> >::ConstructTag>’ [-Werror=attributes]
   46 |   struct mixin_matching_trait : AnalyzeNextTrait {
      |        ^~~~~~~~~~~~~~~~~~~~
```
with 
```
-DKokkos_ENABLE_CUDA=ON 
-DKokkos_ARCH_HOPPER90=ON 
-DKokkos_ARCH_NATIVE=ON 
-DKokkos_ENABLE_BENCHMARKS=ON 
-DKokkos_ENABLE_TESTS=ON 
-DCMAKE_BUILD_TYPE=Release
 -DCMAKE_CXX_FLAGS=-Werror
```
system:
```
cuda 12.8.1, GH200 (hpsf)
```

### PR DESCRIPTION
**Pull request by JBludau**
fixes https://github.com/kokkos/kokkos/issues/8493. We see a `visibility` warning with cuda 12.8.
Disclaimer: I don't understand why it is complaining about visibility here but de-nesting the struct made it go away. I added a `fixme CUDA` since I did not see this with other compilers.

The HPSF CI change is only to test it in the CI and can be removed if we don't want to bump it.

### CODE REVIEW

File: core/src/traits/Kokkos_ExecutionSpaceTrait.hpp [hunk 1]
```diff
@@ -14,6 +14,29 @@ namespace Impl {
 
 //==============================================================================
 // <editor-fold desc="trait specification"> {{{1
+// Fixme CUDA: This struct was previously declared inside ExecutionSpaceTrait.
```
Comment (dalg24) [inline core/src/traits/Kokkos_ExecutionSpaceTrait.hpp]:
```suggestion
// FIXME_CUDA: This struct was previously declared inside ExecutionSpaceTrait.
```

**Review by masterleinad — COMMENTED** [review]
You should be able to remove the `-Wno-attributes` flag everywhere (and don't need to modify any CI compiler versions).

**Comment by ndellingwood** [comment]
snl-ci cuda/12.2 errors, [first snippet](https://github.com/kokkos/kokkos/actions/runs/18509884261/job/52815917737?pr=8558) 
```

/home/runner/_work/kokkos/kokkos/kokkos/core/src/traits/Kokkos_ExecutionSpaceTrait.hpp(27): error: identifier "show_extra_execution_space_erroneously_given_to_execution_policy" is undefined
        show_extra_execution_space_erroneously_given_to_execution_policy<
        ^

/home/runner/_work/kokkos/kokkos/kokkos/core/src/traits/Kokkos_ExecutionSpaceTrait.hpp(29): error: expected a ";"
                               typename base_t::execution_space>>{};
                                                                 ^

/home/runner/_work/kokkos/kokkos/kokkos/core/src/traits/Kokkos_ExecutionSpaceTrait.hpp(27): error: identifier "show_extra_execution_space_erroneously_given_to_execution_policy" is undefined
        show_extra_execution_space_erroneously_given_to_execution_policy<
        ^

/home/runner/_work/kokkos/kokkos/kokkos/core/src/traits/Kokkos_ExecutionSpaceTrait.hpp(29): error: expected a ";"
                               typename base_t::execution_space>>{};
                                                                 ^
```

File: .gitlab/alcf-gitlab-ci.yml [hunk 2]
```diff
@@ -18,7 +18,7 @@ Polaris:
     - export ENV_CMAKE_OPTIONS=""
     - export ENV_CMAKE_OPTIONS="${ENV_CMAKE_OPTIONS};-D CMAKE_CXX_COMPILER=`pwd`/bin/nvcc_wrapper"
     - export ENV_CMAKE_OPTIONS="${ENV_CMAKE_OPTIONS};-D CMAKE_VERBOSE_MAKEFILE=ON"
-    - export ENV_CMAKE_OPTIONS="${ENV_CMAKE_OPTIONS};-D CMAKE_CXX_FLAGS='-Werror=all-warnings -Werror -Wno-attributes'"
```
Comment (nmm0) [inline .gitlab/alcf-gitlab-ci.yml:21]: I don't fully understand the reason for this change and would rather it be in a separate PR if it doesn't fix the issue

**Review by nmm0 — COMMENTED** [review]
Looks good to me, but want to know more about the -Wno-attributes change and how it relates to the bug

File: .gitlab/alcf-gitlab-ci.yml (hunk 2 above)
Comment (masterleinad) [reply .gitlab/alcf-gitlab-ci.yml:21]: That is the warning that is fixed here.

**Review by nmm0 — APPROVED** [review]

**Review by masterleinad — APPROVED** [review]

**Review by crtrott — DISMISSED** [review]
This didn't seem to work, loads of broken builds. Just preemptive blocking so no-one (i.e. me) merges it accidentally.

**Comment by JBludau** [comment]
> This didn't seem to work, loads of broken builds. Just preemptive blocking so no-one (i.e. me) merges it accidentally.

yeah, if I understand the error correctly, ODR forbids the subclass to be in an anonymous namespace

**Comment by dalg24** [comment]
NVIDIA-RTX5080 build on HPSF CI
```
/builds/kokkos/kokkos/core/src/traits/Kokkos_ScheduleTrait.hpp:31:8: error: 'Kokkos::Impl::ScheduleTrait::mixin_matching_trait<Kokkos::Schedule<Kokkos::Dynamic>, Kokkos::Impl::AnalyzeExecPolicy<void, Kokkos::IndexType<long int>, _GLOBAL__N__243f261b_34_TestCuda_CommonPolicyInterface_cpp_b44e169a_12888::test_compile_time_parameters<Kokkos::RangePolicy>()::SomeTag> >' declared with greater visibility than its base 'Kokkos::Impl::AnalyzeExecPolicy<void, Kokkos::IndexType<long int>, _GLOBAL__N__243f261b_34_TestCuda_CommonPolicyInterface_cpp_b44e169a_12888::test_compile_time_parameters<Kokkos::RangePolicy>()::SomeTag>' [-Werror=attributes]
   31 |   struct mixin_matching_trait : AnalyzeNextTrait {
      |        ^~~~~~~~~~~~~~~~~~~~

**Comment by JBludau** [comment]
> Looks good to me, but want to know more about the -Wno-attributes change and how it relates to the bug

If someone that knows why we added warning-ignore please speak up. I can only guess.

How it relates to the bug (AFAIK/U):
So the problem here seems to be, that with the nested definition of `struct mixin_matching_trait` the visibility (e.g. `__attribute__((visibility(....)))`) of that struct is ignored. AFAIU in this context it indicates that due to the nesting of the `AnalyzeNextTrait` (that the `mixin_matching_trait` derives from) is only visible in the namespace of the class it is nested in. Since the definition is in a header, it might be compiled in multiple translation units and they might use different definitions (due to the templates) which would lead to undefined behavior (violated ODR), if the nested struct contained data and someone would actually get the struct out of the class. In that case it would potentially have different sizes in different translation units and if the linker has to fumble that together it might produce absolute chaos. But since it is only a trait and goes away at compile time, we never need the visibility and the linker would never need to know if it is a publicly exposed symbol or not. 

So AFAIKT we did not do anything wrong ignoring the warning (since none of the traits contains data), but the warning is a good hint, that what we were doing was kind silencing potentially multiple, clashing definitions of structs.

File: core/src/traits/Kokkos_ExecutionSpaceTrait.hpp (hunk 1 above)
Comment (JBludau) [reply core/src/traits/Kokkos_ExecutionSpaceTrait.hpp]: I removed the comment since it does not seem like a CUDA thing but more like a general, legit warning about something brittle we do

**Comment by masterleinad** [comment]
> So the problem here seems to be, that with the nested definition of `struct mixin_matching_trait` the visibility (e.g. `__attribute__((visibility(....)))`) of that struct is ignored. AFAIU in this context it indicates that due to the nesting of the `AnalyzeNextTrait` (that the `mixin_matching_trait` derives from) is only visible in the namespace of the class it is nested in. Since the definition is in a header, it might be compiled in multiple translation units and they might use different definitions (due to the templates) which would lead to undefined behavior (violated ODR), if the nested struct contained data and someone would actually get the struct out of the class. In that case it would potentially have different sizes in different translation units and if the linker has to fumble that together it might produce absolute chaos. But since it is only a trait and goes away at compile time, we never need the visibility and the linker would never need to know if it is a publicly exposed symbol or not.

That sounds to describe better what you had previsouly when moving some of the structs into an anoymous namespace. None of the major compilers indicate any problem and given our experience with `nvcc` it seems likely that the warninh i spurious. Eiher way, it's good if we can avoid all warnings.

**Review by masterleinad — APPROVED** [review]

**Comment by JBludau** [comment]
> That sounds to describe better what you had previsouly when moving some of the structs into an anoymous namespace. None of the major compilers indicate any problem and given our experience with `nvcc` it seems likely that the warninh i spurious. Eiher way, it's good if we can avoid all warnings.

You are probably right given that it agrees with bugreports on gcc 14 https://gcc.gnu.org/bugzilla/show_bug.cgi?id=70413

**Comment by JBludau** [comment]
retest this please

**Comment by JBludau** [comment]
retest this please

**Comment by JBludau** [comment]
CI failure seems to be related to the missing `typename`.
