### PR TITLE
Fix CUDA stream memory leak

### LINKED ISSUE #3167: Memory leak when using CUDA stream
We currently have a memory leak when using CUDA stream [here](https://github.com/kokkos/kokkos/blob/master/core/src/Cuda/Kokkos_Cuda_Instance.cpp#L814-L819). We cannot simply delete the object by the constructor because we pass it by copy everywhere. When we don't use a stream, we have a singleton that is correctly cleaned up in `Kokkos::finalize()`.

### PR DESCRIPTION
**Pull request by masterleinad**
Fixes #3167.

### CODE REVIEW

**Review by dalg24 — DISMISSED** [review]

File: core/src/Kokkos_Cuda.hpp [hunk 1]
```diff
@@ -249,12 +250,12 @@ class Cuda {
...
 
   inline Impl::CudaInternal* impl_internal_space_instance() const {
-    return m_space_instance;
+    return m_space_instance.get();
   }
   uint32_t impl_instance_id() const noexcept { return 0; }
 
  private:
-  Impl::CudaInternal* m_space_instance;
+  std::shared_ptr<Impl::CudaInternal> m_space_instance;
```
Comment (dhollman) [inline core/src/Kokkos_Cuda.hpp:258]: This adds overhead _everywhere_ in every application, even if they don't use streams.  Also, anyone I'm not sure we're comfortable with that. Also, any downstream users who are (probably by accident, but still) copying execution space instances on the device will now get `SEGFAULT`s in code that previously worked fine.

**Comment by Rombur** [comment]
This doesn't compile with UVM and the stream test fails for the other configurations.

**Review by dhollman — COMMENTED** [review]
I'd prefer not to have `std::shared_ptr` in something this fundamental. One option is we could use a `Kokkos::View<Impl::CudaInternal, Kokkos::HostSpace>` as a first step, and then conditionally do the finalize in the destructor of `Impl::CudaInternal` or something like that.

File: core/src/Kokkos_Cuda.hpp (hunk 1 above)
Comment (crtrott) [reply core/src/Kokkos_Cuda.hpp:258]: alternatively I would just reference count it explicitly (i.e. add an int, atomic increment it in copy and decrement it destructor (though that makes it non-trivial copyable)

Comment (dhollman) [reply core/src/Kokkos_Cuda.hpp:258]: no, if they try to copy. `std::shared_ptr` has a nontrivial copy constructor that CUDA would try to invoke on the device. Since a lot of our users ignore warnings, it would cause a crash.

Comment (dhollman) [reply core/src/Kokkos_Cuda.hpp:258]: > (though that makes it non-trivial copyable)

It's non-trivially copyable anyway. `std::shared_ptr` isn't trivially copyable.

Comment (crtrott) [reply core/src/Kokkos_Cuda.hpp:258]: maybe we should add a `desul::scoped_shared_ptr<AtomicScope>`

**Review by calewis — COMMENTED** [review]
I looked, but have nothing to add.  But I am trying to start the review process.

**Comment by masterleinad** [comment]
The `shared_ptr` implementation was failing because we seem to copy instances of this class on the device in the tasking framework (which is only enabled if `Kokkos` is compiled with relocatable device code) and the destructor would invoke a host function.
I couldn't get it to work with `Kokkos::View` since I was not able to figure out the correct combination of includes and forward declaration.
Hence, I went with @crtroot suggestion to basically reimplement the relevant parts of shared_ptr in the class (as a poor man's version). In particular, it is important that all the special member functions are actually `__host__ __device__` functions for the tests to pass. I disabled any reference counting on the device, though to not mess with the pointers.
If that solution is acceptable, I am happy to encapsulate it a little better.

File: core/src/Cuda/Kokkos_Cuda_Instance.cpp [hunk 2]
```diff
@@ -783,18 +781,76 @@ void Cuda::impl_finalize() {
...
+  if (m_counter) Kokkos::atomic_add(m_counter, 1);
+#endif
+  return *this;
+}
+
+KOKKOS_FUNCTION Cuda::~Cuda() noexcept {
+#ifndef KOKKOS_ACTIVE_EXECUTION_MEMORY_SPACE_CUDA
+  if (m_counter == nullptr) return;
+  Kokkos::atomic_sub(m_counter, 1);
+  if (*m_counter <= 0) {
```
Comment (dalg24) [inline core/src/Cuda/Kokkos_Cuda_Instance.cpp:842]: You need an atomic_sub_fetch or something

Comment (crtrott) [reply core/src/Cuda/Kokkos_Cuda_Instance.cpp:842]: this needs sub_fetch and then check whether its zero.

Comment (crtrott) [reply core/src/Cuda/Kokkos_Cuda_Instance.cpp:842]: `int count = atomic_sub_fetch(m_counter,1); if(count==0) …`

**Comment by masterleinad** [comment]
This seems to pass CI finally and I don't see any memory leaks in `core/unit_test/KokkosCore_UnitTest_CudaInterOpStreams anymore`.

File: core/src/Cuda/Kokkos_Cuda_Instance.cpp [hunk 3]
```diff
@@ -783,18 +779,76 @@ void Cuda::impl_finalize() {
...
+  if (m_counter) Kokkos::atomic_add(m_counter, 1);
+#endif
+  return *this;
+}
+
+KOKKOS_FUNCTION Cuda::~Cuda() noexcept {
+#ifndef KOKKOS_ACTIVE_EXECUTION_MEMORY_SPACE_CUDA
+  if (m_counter == nullptr) return;
+  int const count = Kokkos::atomic_fetch_sub(m_counter, 1);
+  if (count <= 1) {
```
Comment (crtrott) [inline core/src/Cuda/Kokkos_Cuda_Instance.cpp:840]: we should consider throwing if count is 0, since that would indicate a reference counting failure. We definitely shouldn't delete for anything other than 1.

File: core/src/Cuda/Kokkos_Cuda_Instance.cpp [hunk 4]
```diff
@@ -783,18 +779,76 @@ void Cuda::impl_finalize() {
...
+    delete m_counter;
+    m_counter = nullptr;
+    if (m_use_stream) {
```
Comment (crtrott) [inline core/src/Cuda/Kokkos_Cuda_Instance.cpp:843]: this check (and the variable m_use_stream) should be unnecessary. Either it was the singleton, and hence m_counter == nullptr and the code returned early, or it was constructed from a stream and needs to call finalize.

File: core/unit_test/cuda/TestCuda_InterOp_Streams.cpp [hunk 5]
```diff
@@ -193,7 +193,7 @@ TEST(cuda, raw_cuda_streams) {
   CUDA_SAFE_CALL(cudaDeviceSynchronize());
   cudaStreamDestroy(stream);
 
-  int* h_p = new int[100];
```
Comment (crtrott) [inline core/unit_test/cuda/TestCuda_InterOp_Streams.cpp:196]: ah does that resolve a leak?

**Review by crtrott — CHANGES_REQUESTED** [review]
Almost good to go. We should throw if the counter is ever returning zero (because it indicates a double free somewhere, and we don't need the m_use_stream, since m_counter==null implies m_use_stream==false and vice versa.

File: core/unit_test/cuda/TestCuda_InterOp_Streams.cpp (hunk 5 above)
Comment (masterleinad) [reply core/unit_test/cuda/TestCuda_InterOp_Streams.cpp:196]: Yes, we never freed the memory allocated here.

File: core/src/Cuda/Kokkos_Cuda_Instance.cpp (hunk 3 above)
Comment (masterleinad) [reply core/src/Cuda/Kokkos_Cuda_Instance.cpp:840]: I think we can avoid throwing here. If we arrive here and the counter is less than 1 someone else will cleanup and there is nothing left to do.

File: core/src/Cuda/Kokkos_Cuda_Instance.cpp (hunk 4 above)
Comment (masterleinad) [reply core/src/Cuda/Kokkos_Cuda_Instance.cpp:843]: Yes, I agree. I should have revisited after deciding how to handle the singleton case.

**Comment by masterleinad** [comment]
@crtrott I addressed your comments.

**Review by crtrott — APPROVED** [review]
