### PR TITLE
OpenMP: Fix TeamThreadRange parallel_scan with return value for team_size > 1

### LINKED ISSUE #6470: Add non-power-of-two team sizes to `TeamPolicy` `parallel_scan` tests
Follow-up to #6453 and #6303.
Based on the conversation [here](https://github.com/kokkos/kokkos/pull/6303#discussion_r1337172271).

Make sure to cover non-power-of-two team sizes when testing `parallel_scan` with return value. See existing tests:
https://github.com/kokkos/kokkos/blob/d458fdadb0f0687cfa7579478450d60ed33c08cf/core/unit_test/TestTeamScan.hpp#L68-L75

### PR DESCRIPTION
**Pull request by masterleinad**
Fixes #6470. We were missing to broadcast the accumulated value from the last team member.

### CODE REVIEW

File: core/unit_test/TestTeamScan.hpp [hunk 1]
```diff
@@ -185,7 +185,15 @@ struct TestTeamScanRetVal {
...
-    Kokkos::parallel_for(policy_type(M, Kokkos::AUTO), *this);
+    // Set team size explicitly to check whether non-power-of-two team sizes can
+    // be used.
+    if (ExecutionSpace().concurrency() > 10000)
+      Kokkos::parallel_for(policy_type(M, 127), *this);
+    else if (ExecutionSpace().concurrency() > 2)
+      Kokkos::parallel_for(policy_type(M, 3), *this);
+    else
+      Kokkos::parallel_for(policy_type(M, 1), *this);
+    Kokkos::fence();
```
Comment (ldh4) [inline core/unit_test/TestTeamScan.hpp:196]: There's a fence right below this. Is there any reason to add in an extra fence?

Comment (masterleinad) [reply core/unit_test/TestTeamScan.hpp]: No, fixed in b610a288bff1e5de9ef46f7c0ae901b38c9b2ae2.

**Review by cz4rs — APPROVED** [review]
Looks good to me.

`OpenMPTarget` failure is the usual `openmptarget.partitioning_by_vector` and is not related.

**Review by ldh4 — APPROVED** [review]

**Review by crtrott — APPROVED** [review]
