### PR TITLE
Disable check for IBM XL

### LINKED ISSUE #2601: Develop branch compilation error with cuda/9.2 + xl/16.1 post #2584 merge
Merge of #2584 resulted in failing nightly builds of the develop branch on White with cuda/9.2 and xl/16.1.1 as the host compiler due to `kokkos/core/unit_test/TestComplex.hpp(369)>: error: namespace "std" has no member "is_trivially_copyable`

Here is a more complete compile line:
```
<https://jenkins-son.sandia.gov/job/Kokkos_develop_white_cuda_92_xl_161_kepler/ws/kokkos/bin/nvcc_wrapper> -I./ -I<https://jenkins-son.sandia.gov/job/Kokkos_develop_white_cuda_92_xl_161_kepler/ws/kokkos/core/src> -I<https://jenkins-son.sandia.gov/job/Kokkos_develop_white_cuda_92_xl_161_kepler/ws/kokkos/containers/src> -I<https://jenkins-son.sandia.gov/job/Kokkos_develop_white_cuda_92_xl_161_kepler/ws/kokkos/algorithms/src> -I<https://jenkins-son.sandia.gov/job/Kokkos_develop_white_cuda_92_xl_161_kepler/ws/kokkos/core/src/eti> --std=c++11 -Xcudafe --diag_suppress=esa_on_defaulted_function_ignored -arch=sm_37 -Xcompiler -fopenmp -I./ -I<https://jenkins-son.sandia.gov/job/Kokkos_develop_white_cuda_92_xl_161_kepler/ws/kokkos/core/src> -I<https://jenkins-son.sandia.gov/job/Kokkos_develop_white_cuda_92_xl_161_kepler/ws/kokkos/containers/src> -I<https://jenkins-son.sandia.gov/job/Kokkos_develop_white_cuda_92_xl_161_kepler/ws/kokkos/algorithms/src> -I<https://jenkins-son.sandia.gov/job/Kokkos_develop_white_cuda_92_xl_161_kepler/ws/kokkos/core/src/eti> -I<https://jenkins-son.sandia.gov/job/Kokkos_develop_white_cuda_92_xl_161_kepler/ws/kokkos/tpls/gtest> -I<https://jenkins-son.sandia.gov/job/Kokkos_develop_white_cuda_92_xl_161_kepler/ws/kokkos/core/unit_test> -O3 -Wall -Wshadow -pedantic -Werror -Wsign-compare -Wtype-limits -Wuninitialized -ccbin xlc++  -c <https://jenkins-son.sandia.gov/job/Kokkos_develop_white_cuda_92_xl_161_kepler/ws/kokkos/core/unit_test/cuda/TestCuda_AtomicOperations_unsignedint.cpp>
<https://jenkins-son.sandia.gov/job/Kokkos_develop_white_cuda_92_xl_161_kepler/ws/kokkos/core/unit_test/TestComplex.hpp(369)>: error: namespace "std" has no member "is_trivially_copyable"
```

### PR DESCRIPTION
**Pull request by masterleinad**
Fixes #2601. We could in principle test with `has_trivial_copy_constructor` instead but that is not forward-compatible (and I didn't find any compatibility information that would help). Just as `clang` it reports compatibility with gnu 4.2.1 but gcc 4.2.1 needs `has_trivial_destructor` instead of `is_trivially_destructible`.

I also checked that the current version works with `pgi 19.9` and `pgi 18.10`.

### CODE REVIEW

File: core/unit_test/TestComplex.hpp [hunk 1]
```diff
@@ -361,6 +361,7 @@ TEST(TEST_CATEGORY, complex_trivially_copyable) {
   // Kokkos::complex<RealType> is trivially copyable when RealType is trivially
   // copyable
 
+#if !defined(__ibmxl__)
 #if !defined(__clang__)
```
Comment (dalg24) [inline core/unit_test/TestComplex.hpp]: please do `&&` instead of nested if.

**Review by dalg24 — CHANGES_REQUESTED** [review]

File: core/unit_test/TestComplex.hpp (hunk 1 above)
Comment (masterleinad) [reply core/unit_test/TestComplex.hpp]: These are doing different things. We still check with `clang` assuming that it has `std::is_trivially_copyable`, but we disable the check for `XL`.

**Comment by ndellingwood** [comment]
I kicked off a spot-check on White to test xl, all builds passed.

```
bash-4.2$ ../../scripts/testing_scripts/test_all_sandia ibm/16.1 --spot-check
Running on machine: white
Repository Status:  e38b725f02232767bee0b45e23082173e7e6b03c Disable check for IBM XL


Going to test compilers:  ibm/16.1.0
Testing compiler ibm/16.1.0
  Starting job ibm-16.1.0-OpenMP-release
  PASSED ibm-16.1.0-OpenMP-release
  Starting job ibm-16.1.0-Serial-release
  PASSED ibm-16.1.0-Serial-release
  Starting job ibm-16.1.0-OpenMP_Serial-release
  PASSED ibm-16.1.0-OpenMP_Serial-release
#######################################################
PASSED TESTS
#######################################################
ibm-16.1.0-OpenMP-release build_time=2825 run_time=413
ibm-16.1.0-OpenMP_Serial-release build_time=3354 run_time=642
ibm-16.1.0-Serial-release build_time=320 run_time=354
```

File: core/unit_test/TestComplex.hpp (hunk 1 above)
Comment (dalg24) [reply core/unit_test/TestComplex.hpp]: I don't see how having two separate directives makes that distinction.  Go ahead and add comments though.

**Review by dalg24 — APPROVED** [review]
