### PR TITLE
Fixup silent pointless comparison with zero in checked_narrow_cast

### LINKED ISSUE #3554: Intel compilation errors: KokkosExp_MDRangePolicy.hpp(123): error #186: pointless comparison of unsigned integer with zero
Intel nightly builds began failing to compile 10/29/2020 (see PR #3527) with error messages:

```bash
/home/jenkins/slave/workspace/Kokkos_develop_kokkos-dev_intel_1701/kokkos/core/src/KokkosExp_MDRangePolicy.hpp(123): error #186: pointless comparison of unsigned integer with zero
  (is_different_signedness && (arg < From{}) != (ret < To{}))) 
```

Sample reproducer:
```bash
module load sems-env sems-cmake/3.12.2 sems-intel/18.0.5

$KOKKOS_PATH/generate_makefile.bash --with-devices=OpenMP --arch=Kepler35 --compiler=icpc --cxxflags="-O3 -Wall -Wunused-parameter -Wshadow -pedantic -Werror -Wsign-compare -Wtype-limits -Wuninitialized " --cxxstandard="14" --kokkos-path=$KOKKOS_PATH --no-examples --with-options=enable_large_mem_tests
```

### PR DESCRIPTION
**Pull request by dalg24**
Fix #3554

https://godbolt.org/z/svrjjY

### CODE REVIEW

**Review by crtrott — APPROVED** [review]

File: core/src/KokkosExp_MDRangePolicy.hpp [hunk 1]
```diff
@@ -113,14 +113,30 @@ struct Rank {
 };
 
 namespace Impl {
+// NOTE comparaison below is encapsulated to silent warnings about pointless
```
Comment (masterleinad) [inline core/src/KokkosExp_MDRangePolicy.hpp:116]:
```suggestion
// NOTE the comparison below is encapsulated to silent warnings about pointless
```

**Review by masterleinad — COMMENTED** [review]
https://godbolt.org/z/5T9sv1 would be an alternative (as proposed in https://github.com/kokkos/kokkos/pull/3527#discussion_r512988174)

**Review by ndellingwood — APPROVED** [review]
I confirm this resolved the intel compilation failures reported
