### PR TITLE
Riscv stream fix

### LINKED ISSUE #8799: Stream benchmark breaks on low-memory devices
The Stream benchmark (part of the Performance tests) breaks on low-memory devices, preventing benchmarks from running.

### PR DESCRIPTION
**Pull request by prateekchawla168**
The stream benchmark (part of Perf tests) gets OOM-killed on low-memory devices. This PR keeps the original version if the `KOKKOS_ENABLE_LARGE_MEM_TESTS` option  is specified at compile time, else it defaults to a lower memory version.

Fixes #8799.

### CODE REVIEW

**Review by crtrott — APPROVED** [review]

File: core/perf_test/PerfTest_Stream.cpp [hunk 1]
```diff
@@ -215,11 +215,19 @@ static void or_skip(benchmark::State& state) {
 
 // As of May 2025, 10^8 doubles is larger than caches, but not so large as
 // to be inconvenient. Also run 11^8 for a quick check of convergence.
+// This value is only used if the available memory is > 6G, so the test defaults
+// to a low-memory mode
```
Comment (masterleinad) [inline core/perf_test/PerfTest_Stream.cpp]:
```suggestion
// This value is only used if the available memory is > 6GB, so the test defaults
// to a low-memory mode using 9^8 and 10^8 elements.
```

**Review by masterleinad — APPROVED** [review]

File: core/perf_test/PerfTest_Stream.cpp [hunk 2]
```diff
@@ -215,11 +215,19 @@ static void or_skip(benchmark::State& state) {
 
 // As of May 2025, 10^8 doubles is larger than caches, but not so large as
 // to be inconvenient. Also run 11^8 for a quick check of convergence.
+// This value is only used if the available memory is > 6GB, so the test defaults
+// to a low-memory mode using 9^8 and 10^8 elements.
```
Comment (dalg24) [inline core/perf_test/PerfTest_Stream.cpp]: Can someone walk me through the math here:
3 arrays of double of size N^8 + 1 mirror view which I expect does not allocate on RISC-V systems
which would yield
3 * 8 * 10^8 = 2.4 GB with N = 10
3 * 8 * 11^8 = 5.2 GB with N = 11

File: core/perf_test/PerfTest_Stream.cpp [hunk 3]
```diff
@@ -215,11 +215,19 @@ static void or_skip(benchmark::State& state) {
 
 // As of May 2025, 10^8 doubles is larger than caches, but not so large as
 // to be inconvenient. Also run 11^8 for a quick check of convergence.
```
Comment (dalg24) [inline core/perf_test/PerfTest_Stream.cpp]: @cwpearson would 9^8 (1 GB ?) and 10^8 (2.4 GB ?) do on GPU systems or do we want larger arrays as in the status quo?

Comment (cwpearson) [reply core/perf_test/PerfTest_Stream.cpp]: I think those are okay, but we may want to revisit when MI4XX becomes available. MI300A is already up to 256 MB.

File: core/perf_test/PerfTest_Stream.cpp (hunk 2 above)
Comment (prateekchawla168) [reply core/perf_test/PerfTest_Stream.cpp]: Yeah, the mirror view does not get allocated, but RISC-V systems are pretty low-memory boards with ~4 GB usable memory (see [here](https://docs.banana-pi.org/en/BPI-F3/BananaPi_BPI-F3#_hardware_spec) for an example), so the case of N = 11 gets OOM killed. This is why the recommendation is to use N = 9 and N = 10 for the (default) low-memory case. We have previously used the 4 GB case as the default target for performance testing in #8552 .

**Review by cwpearson — APPROVED** [review]
