### PR TITLE
Fix Kokkos_SIMD with AVX2 on 64-bit architectures

### LINKED ISSUE #6070: Unable to compile Kokkos_SIMD for BDW arch using GCC 8.5.0
I get the following error when trying to compile Kokkos_SIMD using GCC 8.5.0 on a Broadwell Architecture. The error might be reproducible on all AVX2 archs. 

- Compilers : GCC 8.5.0
- Kokkos version: Kokkos 4.0.0 (https://github.com/kokkos/kokkos/archive/refs/tags/4.0.00.zip)
- Platform and backend: Tried compiling for Broadwell architecture.
- cmake command: cmake3 -S . -B build -DCMAKE_BUILD_TYPE=Release -DKokkos_ARCH_BDW=ON
- cmake build output: 
```
In file included from /home/rk9481/cicc_issue_kokkos/build/_deps/kokkos-src/simd/src/Kokkos_SIMD.hpp:25,
                 from /home/rk9481/cicc_issue_kokkos/main.cpp:2:
/home/rk9481/cicc_issue_kokkos/build/_deps/kokkos-src/simd/src/Kokkos_SIMD_AVX2.hpp: In member function ‘void Kokkos::Experimental::simd<long int, Kokkos::Experimental::simd_abi::avx2_fixed_size<4> >::copy_from(const value_type*, Kokkos::Experimental::element_aligned_tag)’:
/home/rk9481/cicc_issue_kokkos/build/_deps/kokkos-src/simd/src/Kokkos_SIMD_AVX2.hpp:730:37: error: invalid conversion from ‘const value_type*’ {aka ‘const long int*’} to ‘const long long int*’ [-fpermissive]
     m_value = _mm256_maskload_epi64(ptr, static_cast<__m256i>(mask_type(true)));
                                     ^~~
In file included from /usr/lib/gcc/x86_64-redhat-linux/8/include/immintrin.h:43,
                 from /home/rk9481/cicc_issue_kokkos/build/_deps/kokkos-src/simd/src/Kokkos_SIMD_AVX2.hpp:25,
                 from /home/rk9481/cicc_issue_kokkos/build/_deps/kokkos-src/simd/src/Kokkos_SIMD.hpp:25,
                 from /home/rk9481/cicc_issue_kokkos/main.cpp:2:
/usr/lib/gcc/x86_64-redhat-linux/8/include/avx2intrin.h:1126:41: note:   initializing argument 1 of ‘__m256i _mm256_maskload_epi64(const long long int*, __m256i)’
 _mm256_maskload_epi64 (long long const *__X, __m256i __M )
                        ~~~~~~~~~~~~~~~~~^~~
In file included from /home/rk9481/cicc_issue_kokkos/build/_deps/kokkos-src/simd/src/Kokkos_SIMD.hpp:25,
                 from /home/rk9481/cicc_issue_kokkos/main.cpp:2:
/home/rk9481/cicc_issue_kokkos/build/_deps/kokkos-src/simd/src/Kokkos_SIMD_AVX2.hpp: In member function ‘void Kokkos::Experimental::simd<long int, Kokkos::Experimental::simd_abi::avx2_fixed_size<4> >::copy_to(Kokkos::Experimental::simd<long int, Kokkos::Experimental::simd_abi::avx2_fixed_size<4> >::value_type*, Kokkos::Experimental::element_aligned_tag) const’:
/home/rk9481/cicc_issue_kokkos/build/_deps/kokkos-src/simd/src/Kokkos_SIMD_AVX2.hpp:734:28: error: invalid conversion from ‘Kokkos::Experimental::simd<long int, Kokkos::Experimental::simd_abi::avx2_fixed_size<4> >::value_type*’ {aka ‘long int*’} to ‘long long int*’ [-fpermissive]
     _mm256_maskstore_epi64(ptr, static_cast<__m256i>(mask_type(true)), m_value);
                            ^~~
In file included from /usr/lib/gcc/x86_64-redhat-linux/8/include/immintrin.h:43,
                 from /home/rk9481/cicc_issue_kokkos/build/_deps/kokkos-src/simd/src/Kokkos_SIMD_AVX2.hpp:25,
                 from /home/rk9481/cicc_issue_kokkos/build/_deps/kokkos-src/simd/src/Kokkos_SIMD.hpp:25,
                 from /home/rk9481/cicc_issue_kokkos/main.cpp:2:
/usr/lib/gcc/x86_64-redhat-linux/8/include/avx2intrin.h:1157:36: note:   initializing argument 1 of ‘void _mm256_maskstore_epi64(long long int*, __m256i, __m256i)’
 _mm256_maskstore_epi64 (long long *__X, __m256i __M, __m256i __Y )
                         ~~~~~~~~~~~^~~
gmake[2]: *** [CMakeFiles/cicc_test.dir/build.make:76: CMakeFiles/cicc_test.dir/main.cpp.o] Error 1
gmake[1]: *** [CMakeFiles/Makefile2:280: CMakeFiles/cicc_test.dir/all] Error 2
gmake: *** [Makefile:136: all] Error 2
```
- Code:
```
  #include <Kokkos_Core.hpp>
#include <Kokkos_SIMD.hpp>
#include "small_mat_mul.hpp"

int main(){

    Kokkos::initialize();
    {
    }
    Kokkos::finalize();

    return 1;
}
```
I was using Kokkos_SIMD for another project and ran into this compilation error, so I tried to reproduce the error using a bare bones Kokkos code.

### PR DESCRIPTION
**Pull request by masterleinad**
Fixes #6070. ~~For better test coverage (and convenience for the user?), this pull request also enables the `avx2` overloads if `__AVX2__` is defined (which should be the case when the user sets `Kokkos_ARCH_AVX2` but also for `Kokkos_ARCH_NATIVE=ON`).~~

### CODE REVIEW

**Review by ibaned — APPROVED** [review]

**Comment by ibaned** [comment]
Does AVX2 get enabled if the user sets `Kokkos_ARCH_BDW=ON`?

**Comment by masterleinad** [comment]
> Does AVX2 get enabled if the user sets `Kokkos_ARCH_BDW=ON`?

Yes, https://github.com/kokkos/kokkos/blob/c09dd1c94861541b2f9651474ecdbec9e074dab7/cmake/kokkos_arch.cmake#L366-L376.

File: simd/src/Kokkos_SIMD_AVX2.hpp [hunk 1]
```diff
@@ -680,10 +680,12 @@ template <>
 class simd<std::int64_t, simd_abi::avx2_fixed_size<4>> {
   __m256i m_value;
 
+  static_assert(sizeof(long long) == 8);
+
  public:
   using value_type = std::int64_t;
   using abi_type   = simd_abi::avx2_fixed_size<4>;
-  using mask_type  = simd_mask<value_type, abi_type>;
+  using mask_type  = simd_mask<std::int64_t, abi_type>;
```
Comment (ldh4) [inline simd/src/Kokkos_SIMD_AVX2.hpp:688]: Is this change necessary, seeing that `value_type` was already `std::int64_t` from `using value_type = std::int64_t`?

Comment (masterleinad) [reply simd/src/Kokkos_SIMD_AVX2.hpp:688]: No, that was for another attempt. An alternative is
```
diff --git a/simd/src/Kokkos_SIMD_AVX2.hpp b/simd/src/Kokkos_SIMD_AVX2.hpp
index 80f96153d..ad4f53625 100644
--- a/simd/src/Kokkos_SIMD_AVX2.hpp
+++ b/simd/src/Kokkos_SIMD_AVX2.hpp
@@ -683,7 +683,7 @@ class simd<std::int64_t, simd_abi::avx2_fixed_size<4>> {
   static_assert(sizeof(long long) == 8);
 
  public:
-  using value_type = std::int64_t;
+  using value_type = long long;
   using abi_type   = simd_abi::avx2_fixed_size<4>;
   using mask_type  = simd_mask<std::int64_t, abi_type>;
   using reference  = value_type&;
@@ -729,12 +729,12 @@ class simd<std::int64_t, simd_abi::avx2_fixed_size<4>> {
   }
   KOKKOS_IMPL_HOST_FORCEINLINE_FUNCTION void copy_from(value_type const* ptr,
                                                        element_aligned_tag) {
-    m_value = _mm256_maskload_epi64(reinterpret_cast<long long const*>(ptr),
+    m_value = _mm256_maskload_epi64(ptr, static_cast<__m256i>(mask_type(true)));
   }
   KOKKOS_IMPL_HOST_FORCEINLINE_FUNCTION void copy_to(
       value_type* ptr, element_aligned_tag) const {
-    _mm256_maskstore_epi64(reinterpret_cast<long long*>(ptr),
+    _mm256_maskstore_epi64(ptr, static_cast<__m256i>(mask_type(true)), m_value);
   }
   KOKKOS_IMPL_HOST_FORCEINLINE_FUNCTION constexpr explicit operator __m256i()
```
avoiding the possible undefined behavior due to `reinterpret_cast`. Of course, this would change the value type and it's not quite clear to me if that's OK/better or not. Making `long long` a storage type or similar might be another option.

**Review by ldh4 — APPROVED** [review]

File: simd/src/Kokkos_SIMD_AVX2.hpp (hunk 1 above)
Comment (ldh4) [reply simd/src/Kokkos_SIMD_AVX2.hpp:688]: I think setting `value_type` to be `long long` is something that could revisited. If all compilers' implementation of all avx2 intrinsics consistently use `long long`, then it may be better to set `value_type` to be `long long`. But for now, I think we can proceed with having a `reinterpret_cast` here.

File: simd/src/Kokkos_SIMD_AVX2.hpp [hunk 2]
```diff
@@ -680,6 +680,8 @@ template <>
 class simd<std::int64_t, simd_abi::avx2_fixed_size<4>> {
   __m256i m_value;
 
+  static_assert(sizeof(long long) == 8);
```
Comment (dalg24) [inline simd/src/Kokkos_SIMD_AVX2.hpp:683]: Why did you add that assertion?

**Review by dalg24 — CHANGES_REQUESTED** [review]
If this PR is about fixing a bug (`_mm256_mask{load,store}_epi64` intrinsics expecting pointers to `long long` and us passing pointers to `value_type`) then drop the unrelated "convenience" changes.

File: simd/src/Kokkos_SIMD_AVX2.hpp (hunk 2 above)
Comment (masterleinad) [reply simd/src/Kokkos_SIMD_AVX2.hpp:683]: As a minimal safeguard that the `reinterpret_cast` is reasonable.

**Comment by masterleinad** [comment]
> If this PR is about fixing a bug (_mm256_mask{load,store}_epi64 intrinsics expecting pointers to long long and us passing pointers to value_type) then drop the unrelated "convenience" changes.

Here you go!

**Comment by dalg24** [comment]
Why was this bug not caught before?  Is there a gap in the testing (not necessarily the CI, presumably someone built on Broadwell before and it did not give a compile error)?

**Comment by ibaned** [comment]
I have done Broadwell builds with no errors before this fix... I'm not sure if it is compiler or arch specific...

**Comment by masterleinad** [comment]
> I have done Broadwell builds with no errors before this fix... I'm not sure if it is compiler or arch specific...

My testing shows that this would only have worked on Linux 32-bit architectures.

**Comment by masterleinad** [comment]
> @masterleinad meaning with the current develop you got a compile error? I am trying to determine whether we need to add unit tests (excluding the whether we need some more CI/nightly build)

You see this with current `develop` and current tests but we don't test any host architectures in our `GitHub` or `Jenkins` CI (that's part of the reason why I am proposing to let `Kokkos_ARCH_NATIVE` enable SIMD intrinsic).

**Review by dalg24 — APPROVED** [review]

**Comment by dalg24** [comment]
> this must be handled elsewhere.

To elaborate on this a bit more, whether to enable based on compiler defines rather than user-provided configure options is a question that we need to examine with care and it is beyond the scope of this PR.  I am not opposed to it, it is actually in my backlog, I was considering getting rid of that macro along with others such as `KOKKOS_ARCH_AMDAVX`, `KOKKOS_ARCH_AMD_AVX2`, `KOKKOS_ARCH_AVX512MIC`, or `KOKKOS_ARCH_AVX512XEON`.

**Comment by dalg24** [comment]
Retest this please
