### PR TITLE
Fixup constness change in CUDA Graph API

### LINKED ISSUE #3562: cuda/10.0 compilation errors: argument of type "const cudaGraphNode_t *" is incompatible with parameter of type "cudaGraphNode_t *"
Nightly cuda/10.0 + gcc/7.4 builds on Power8+Pascal60 began failing at compilation with error messages like below, indicating possible code updates from PR #3369; the problem is not occurring with cuda/10.1 + gcc/7.4 on the same system.

Error messages:
```bash
03:34:38 /home/jenkins/white/workspace/Kokkos_develop_white_cuda_10_gcc_740_pascal/kokkos/core/src/Cuda/Kokkos_Cuda_Graph_Impl.hpp(168): error: argument of type "const cudaGraphNode_t *" is incompatible with parameter of type "cudaGraphNode_t *"
03:34:38           detected during:
03:34:38             instantiation of "auto Kokkos::Experimental::GraphNodeRef<ExecutionSpace, Kernel, Predecessor>::_then_kernel(NextKernelDeduced &&) const [with ExecutionSpace=Kokkos::Cuda, Kernel=Kokkos::Experimental::TypeErasedTag, Predecessor=Kokkos::Experimental::TypeErasedTag, NextKernelDeduced=Kokkos::Impl::GraphNodeKernelImpl<Kokkos::Cuda, Kokkos::RangePolicy<Kokkos::Cuda, Kokkos::Impl::IsGraphKernelTag>, std::decay_t<Test::cuda_count_bugs::count_functor>, Kokkos::ParallelForTag>]" 
03:34:38 /home/jenkins/white/workspace/Kokkos_develop_white_cuda_10_gcc_740_pascal/kokkos/core/src/Kokkos_GraphNode.hpp(293): here
03:34:38             instantiation of "auto Kokkos::Experimental::GraphNodeRef<ExecutionSpace, Kernel, Predecessor>::then_parallel_for(std::__cxx11::string, Policy &&, Functor &&) const [with ExecutionSpace=Kokkos::Cuda, Kernel=Kokkos::Experimental::TypeErasedTag, Predecessor=Kokkos::Experimental::TypeErasedTag, Policy=Kokkos::RangePolicy<Kokkos::Cuda>, Functor=Test::cuda_count_bugs::count_functor, <unnamed>=0]" 
03:34:38 /home/jenkins/white/workspace/Kokkos_develop_white_cuda_10_gcc_740_pascal/kokkos/core/src/Kokkos_GraphNode.hpp(316): here
03:34:38             instantiation of "auto Kokkos::Experimental::GraphNodeRef<ExecutionSpace, Kernel, Predecessor>::then_parallel_for(std::__cxx11::string, std::size_t, Functor &&) const [with ExecutionSpace=Kokkos::Cuda, Kernel=Kokkos::Experimental::TypeErasedTag, Predecessor=Kokkos::Experimental::TypeErasedTag, Functor=Test::cuda_count_bugs::count_functor]" 
03:34:38 /home/jenkins/white/workspace/Kokkos_develop_white_cuda_10_gcc_740_pascal/kokkos/core/src/Kokkos_GraphNode.hpp(322): here
03:34:38             instantiation of "auto Kokkos::Experimental::GraphNodeRef<ExecutionSpace, Kernel, Predecessor>::then_parallel_for(std::size_t, Functor &&) const [with ExecutionSpace=Kokkos::Cuda, Kernel=Kokkos::Experimental::TypeErasedTag, Predecessor=Kokkos::Experimental::TypeErasedTag, Functor=Test::cuda_count_bugs::count_functor]" 
03:34:38 /home/jenkins/white/workspace/Kokkos_develop_white_cuda_10_gcc_740_pascal/kokkos/core/unit_test/TestGraph.hpp(122): here
03:34:38             instantiation of function "lambda [](auto)->auto [with <auto-1>=Kokkos::Experimental::GraphNodeRef<Kokkos::Cuda, Kokkos::Experimental::TypeErasedTag, Kokkos::Experimental::TypeErasedTag>]" 
03:34:38 /home/jenkins/white/workspace/Kokkos_develop_white_cuda_10_gcc_740_pascal/kokkos/core/src/Kokkos_Graph.hpp(165): here
03:34:38             instantiation of "Kokkos::Experimental::Graph<ExecutionSpace> Kokkos::Experimental::create_graph(ExecutionSpace, Closure &&) [with ExecutionSpace=Kokkos::Cuda, Closure=lambda [](auto)->auto]" 
03:34:38 /home/jenkins/white/workspace/Kokkos_develop_white_cuda_10_gcc_740_pascal/kokkos/core/src/Kokkos_Graph.hpp(175): here
03:34:38             instantiation of "Kokkos::Experimental::Graph<ExecutionSpace> Kokkos::Experimental::create_graph(Closure &&) [with ExecutionSpace=Kokkos::Cuda, Closure=lambda [](auto)->auto]" 
03:34:38 /home/jenkins/white/workspace/Kokkos_develop_white_cuda_10_gcc_740_pascal/kokkos/core/unit_test/TestGraph.hpp(121): here
03:34:38 
03:34:38 /home/jenkins/white/workspace/Kokkos_develop_white_cuda_10_gcc_740_pascal/kokkos/core/src/Cuda/Kokkos_Cuda_Graph_Impl.hpp(168): error: argument of type "const cudaGraphNode_t *" is incompatible with parameter of type "cudaGraphNode_t *"
```

Sample reproducer:
```bash
module load cmake/3.12.3 cuda/10.0.130 gcc/7.4.0 ibm/xl/16.1.1

$KOKKOS_PATH/generate_makefile.bash --with-devices=Cuda,Serial --arch=Power8,Pascal60 --compiler=$KOKKOS_PATH/bin/nvcc_wrapper --cxxflags="-O3 -Wall -Wunused-parameter -Wshadow -pedantic -Werror -Wsign-compare -Wtype-limits -Wuninitialized " --cxxstandard="14" --with-cuda --kokkos-path=$KOKKOS_PATH --no-examples --with-options=enable_large_mem_tests
```

### PR DESCRIPTION
**Pull request by dhollman**
Apparently, very early versions of the CudaGraphs API had less constness than the newer ones 🤷🏼‍♀️

Fix #3562 and #3559

### CODE REVIEW

**Review by crtrott — APPROVED** [review]

**Comment by crtrott** [comment]
Yeah I don't think its worth it to distinguish between versions here.

File: core/src/Cuda/Kokkos_Cuda_Graph_Impl.hpp [hunk 1]
```diff
@@ -159,10 +159,10 @@ struct GraphImpl<Kokkos::Cuda> {
     auto pred_ptr = GraphAccess::get_node_ptr(arg_pred_ref);
     KOKKOS_EXPECTS(bool(pred_ptr))
 
-    auto const& pred_cuda_node = pred_ptr->node_details_t::node;
+    auto& pred_cuda_node = pred_ptr->node_details_t::node;
```
Comment (dalg24) [inline core/src/Cuda/Kokkos_Cuda_Graph_Impl.hpp:162]:
```suggestion
    // clang-format off
    // NOTE const-qualifiers below are commented out because of an API break
    // from CUDA 10.0 to CUDA 10.1
    // cudaGraphAddDependencies(cudaGraph_t, cudaGraphNode_t*, cudaGraphNode_t*, size_t)
    // cudaGraphAddDependencies(cudaGraph_t, const cudaGraphNode_t*, const cudaGraphNode_t*, size_t)
    // clang-format on
    auto /*const*/& pred_cuda_node = pred_ptr->node_details_t::node;
```

File: core/src/Cuda/Kokkos_Cuda_Graph_Impl.hpp [hunk 2]
```diff
@@ -159,10 +159,10 @@ struct GraphImpl<Kokkos::Cuda> {
...
     KOKKOS_EXPECTS(bool(pred_cuda_node))
 
-    auto const& cuda_node = arg_node_ptr->node_details_t::node;
+    auto& cuda_node = arg_node_ptr->node_details_t::node;
```
Comment (dalg24) [inline core/src/Cuda/Kokkos_Cuda_Graph_Impl.hpp:165]:
```suggestion
    auto /*const*/& cuda_node = arg_node_ptr->node_details_t::node;
```

**Review by dalg24 — APPROVED** [review]
I would prefer if you applied my suggestion

**Comment by dalg24** [comment]
I confirm that API break happens between CUDA 10.0 and 10.1

**Review by DavidPoliakoff — APPROVED** [review]

File: core/src/Cuda/Kokkos_Cuda_Graph_Impl.hpp (hunk 2 above)
Comment (dhollman) [reply core/src/Cuda/Kokkos_Cuda_Graph_Impl.hpp:171]: I don't like this part as much in either case because it sort of implies that the `auto` is supposed to deduce `const`, but I'm okay with it for now.
