### PR TITLE
 Fix issue 3589 on Kepler35 and Clang7/Cuda9.2

### LINKED ISSUE #3589: cuda.memory_pool unit test failing with clang/7+cuda/9.2, Kepler35 arch
The `cuda.memory_pool` test began failing following merge of PR #3580

I reproduced the failure on kokkos-dev and did a bisection on merge commits to confirm,

Failing SHA: 1b432961fa2a5b7435d340425bb62988a98317cc

Passing SHA: 72375bfd47bb3101b4a698dc552e5583a57f393f

@crtrott are you able to take a look? Looks like more whack-a-mole after the zero-length reduction fixes :(

**Test failure output:**
```
18:45:01 /home/jenkins/slave/workspace/Kokkos_develop_kokkos-dev_clang_701_cuda_92/kokkos/core/unit_test/TestMemoryPool.hpp:326: Failure
18:45:01 Value of: long(stats.consumed_blocks)
18:45:01   Actual: 46666
18:45:01 Expected: (nfill - ndel)
18:45:01 Which is: 48829
18:45:01 [  FAILED  ] cuda.memory_pool (22 ms)
```

**Sample reproducer instructions (kokkos-dev):**
```bash
module load sems-env sems-cmake/3.12.2 sems-clang/7.0.1 sems-cuda/9.2

$KOKKOS_PATH/generate_makefile.bash --with-devices=Cuda,OpenMP --arch=Kepler35 --compiler=clang++ --cxxflags="-O3 -Wall -Wunused-parameter -Wshadow -pedantic -Werror -Wsign-compare -Wtype-limits -Wuninitialized " --cxxstandard="14" --ldflags="" --with-cuda --kokkos-path=$KOKKOS_PATH  --no-examples

# Corresponding cmake line
cmake -DCMAKE_CXX_COMPILER=clang++ -DCMAKE_CXX_FLAGS=”-O3 -Wall -Wunused-parameter -Wshadow -pedantic -Werror -Wsign-compare -Wtype-limits -Wuninitialized  --gcc-toolchain=/projects/sems/install/rhel7-x86_64/sems/compiler/gcc/5.3.0/base --cuda-path=/projects/sems/install/rhel7-x86_64/sems/compiler/cuda/9.2/base” -DKokkos_ENABLE_OPENMP=ON -DKokkos_ENABLE_CUDA=ON -DKokkos_ARCH_KEPLER35=ON -DKokkos_ENABLE_TESTS=ON -DKokkos_ENABLE_EXAMPLES=OFF -DCMAKE_VERBOSE_MAKEFILE=ON -DCMAKE_CXX_EXTENSIONS=OFF -DCMAKE_CXX_STANDARD=14 -DCMAKE_BUILD_TYPE=RELEASE $KOKKOS_PATH
```

### PR DESCRIPTION
**Pull request by janciesko**
Fix #3589

### CODE REVIEW

File: core/src/Cuda/Kokkos_Cuda_Parallel.hpp [hunk 1]
```diff
@@ -961,36 +961,43 @@ class ParallelReduce<FunctorType, Kokkos::RangePolicy<Traits...>, ReducerType,
...
-          m_result_ptr_device_accessible
-              ? reinterpret_cast<size_type*>(m_result_ptr)
-              : (m_unified_space ? m_unified_space : m_scratch_space);
+    }
 
-      if (threadIdx.y == 0) {
-        Kokkos::Impl::FunctorFinal<ReducerTypeFwd, WorkTagFwd>::final(
-            ReducerConditional::select(m_functor, m_reducer), shared);
-      }
+    if (m_policy.begin() != m_policy.end()) {
```
Comment (nliber) [inline core/src/Cuda/Kokkos_Cuda_Parallel.hpp:966]: My preference is for early `return`, as in `if (m_policy.begin() == m_policy.end()) return;`, because it is a little easier to reason about (you don't have to look to the end of highly indented code to see if there is an `else` clause).

File: core/src/Cuda/Kokkos_Cuda_Parallel.hpp [hunk 2]
```diff
@@ -961,36 +961,43 @@ class ParallelReduce<FunctorType, Kokkos::RangePolicy<Traits...>, ReducerType,
...
+
+          if (threadIdx.y == 0) {
+            Kokkos::Impl::FunctorFinal<ReducerTypeFwd, WorkTagFwd>::final(
+                ReducerConditional::select(m_functor, m_reducer), shared);
+          }
 
-      if (CudaTraits::WarpSize < word_count.value) {
-        __syncthreads();
-      }
+          if (CudaTraits::WarpSize < word_count.value) {
```
Comment (nliber) [inline core/src/Cuda/Kokkos_Cuda_Parallel.hpp:989]: It looks like some tabs got in there.

**Review by nliber — APPROVED** [review]

**Comment by crtrott** [comment]
Do I see that right that its just splitting:

```
if(cA) {
  // A
} else if(cB) {
  // B
}
```
into 
```
if(cA) {
  // A
}
if(cB) {
  // B
}
```

**Comment by janciesko** [comment]
Yes, that is right. This is a superficial fix to make this pass on Kepler. Issue: If the first conditional body changes the output of the second conditional, then the path is different from the formulation with the `else if() ` statement which fails on Kepler. This passes all tests now but the issue might be a data race somewhere deeper.

File: core/src/Cuda/Kokkos_Cuda_Parallel.hpp (hunk 1 above)
Comment (janciesko) [reply core/src/Cuda/Kokkos_Cuda_Parallel.hpp:966]: Returning in the conditional loop body is equivalent to using a if-then-else which is equivalent to the original code that we want to fix. This seems like a deeper-rooted problem that manifests on Kepler, probably related to how threads synch and/or a data race.

File: core/src/Cuda/Kokkos_Cuda_Parallel.hpp (hunk 2 above)
Comment (janciesko) [reply core/src/Cuda/Kokkos_Cuda_Parallel.hpp:989]: fixed

**Review by crtrott — APPROVED** [review]

**Comment by crtrott** [comment]
Retest this please.
