### PR TITLE
Fix bug {pow, log}(Kokkos::complex)

### LINKED ISSUE #3865: Kokkos::pow(complex) and Kokkos::log(complex) give wrong results
I have observed that the ```Kokkos::pow``` and ```Kokkos::log``` with complex arguments produce wrong results when ```z.real()<0```. The reason could be that ```atan()``` (returns values in the interval ```[-pi/2, pi/2]```) is used in these functions. This can be resolved by using ```atan2()``` instead (```atan2()``` returns the four-quadrant inverse tangent in the interval ```[-pi,pi]```.

Reproducer:
```
#include <cstdio>
#include <cstdlib>
#include <Kokkos_Core.hpp>

int main( int argc, char* argv[] )
{
  Kokkos::initialize( argc, argv );
  {
    using ViewType     = Kokkos::View<Kokkos::complex<double>*, Kokkos::LayoutLeft, Kokkos::CudaSpace>;
    using HostViewType = typename ViewType::HostMirror;

    ViewType d_pow, d_log;
    HostViewType h_pow, h_log;

    d_pow  = ViewType("d_pow", 2);
    d_log  = ViewType("d_log", 2);
    h_pow  = Kokkos::create_mirror_view(d_pow);
    h_log  = Kokkos::create_mirror_view(d_log);

    Kokkos::parallel_for(Kokkos::RangePolicy<Kokkos::Cuda>(0, 1), KOKKOS_LAMBDA(const int i) {
      d_pow(0) = Kokkos::pow(Kokkos::complex<double>( +3.0,1.0),3.0);
      d_pow(1) = Kokkos::pow(Kokkos::complex<double>( -3.0,1.0),3.0);
      d_log(0) = Kokkos::log(Kokkos::complex<double>( +3.0,1.0));
      d_log(1) = Kokkos::log(Kokkos::complex<double>( -3.0,1.0));	  
    });

    Kokkos::deep_copy(h_pow, d_pow);
    Kokkos::deep_copy(h_log, d_log);

    std::cout << "pow(+3+1i,3)=" << h_pow(0) << ", (MATLAB ref. result =  18+26i)" << std::endl;
    std::cout << "pow(-3+1i,3)=" << h_pow(1) << ", (MATLAB ref. result = -18+26i)" << std::endl;
    std::cout << "log(+3+1i)=" << h_log(0) << ", (MATLAB ref. result = 1.15129 + 0.321751i)" << std::endl;
    std::cout << "log(-3+1i)=" << h_log(1) << ", (MATLAB ref. result = 1.15129 + 2.819842i)" << std::endl;
  }
  Kokkos::finalize();
  return 0;
}
```  

Output:
```
pow(+3+1i,3)=(18,26), (MATLAB ref. result =  18+26i)
pow(-3+1i,3)=(18,-26), (MATLAB ref. result = -18+26i)
log(+3+1i)=(1.15129,0.321751), (MATLAB ref. result = 1.15129 + 0.321751i)
log(-3+1i)=(1.15129,-0.321751), (MATLAB ref. result = 1.15129 + 2.819842i)
```

### PR DESCRIPTION
**Pull request by dalg24**
Fix #3865

### CODE REVIEW

File: core/src/Kokkos_Complex.hpp [hunk 1]
```diff
@@ -720,7 +720,7 @@ KOKKOS_INLINE_FUNCTION Kokkos::complex<RealType> pow(const complex<RealType>& x,
   using std::pow;
   using std::sin;
 #endif
-  RealType phi = atan(x.imag() / x.real());
+  RealType phi = atan2(x.imag(), x.real());
```
Comment (masterleinad) [inline core/src/Kokkos_Complex.hpp:723]: Don't you also have to import `sycl::atan2` instead of `sycl::atan` and `std::atan2` instead of `syd::atan`?

Comment (dalg24) [reply core/src/Kokkos_Complex.hpp:723]: Fixed.
Note that we should really be using the math functions from `Kokkos::Experimental::`

**Review by masterleinad — APPROVED** [review]
Looks OK.
