### PR TITLE
[3.7.01] Fix initialization of Cuda lock arrays 

### LINKED ISSUE #5596: Crash in Kokkos::Initialize from #4682
After updating to 3.7, we are seeing a crash in `Kokkos::Initialize` in LAMMPS with a `DEBUG` build and shared libs. I bisected the issue to https://github.com/kokkos/kokkos/pull/4682, which matches the error messages. If we use a `RELEASE` build or don't enable shared libs, then the code runs fine.

```
what():  Desul::Error: init_lock_arrays_cuda: post init kernel error(cudaErrorLaunchFailure): unspecified launch failure

***FAULT Warp Illegal Address
+++ID CUDA count 832 grid 3 block (0,0,0) thread (0,0,0) dev0/sm0/warp2/lane0
+++STACK
desul::(anonymousnamespace)::init_lock_arrays_cuda_kernel<<<(512,1,1),(256,1,1)>>>()@/lammps_master/lib/kokkos/tpls/desul/src/Lock_Array_CUDA.cpp:32

========= Invalid __global__ write of size 4
=========     at 0x000000d0 in /lammps_master/lib/kokkos/tpls/desul/src/Lock_Array_CUDA.cpp:31:desul::_GLOBAL__N__50_tmpxft_0001a4f7_00000000_7_Lock_Array_CUDA_cpp1_ii_4d2bf3a0::init_lock_arrays_cuda_kernel(void)
=========     by thread (238,0,0) in block (80,0,0)
=========     Address 0x000143b8 is out of bounds
=========     Saved host backtrace up to driver entry point at kernel launch time
```

### PR DESCRIPTION
**Pull request by masterleinad**
Cherry-picking  #5619 to fix #5596

### CODE REVIEW

File: tpls/desul/include/desul/atomics/Lock_Array_Cuda.hpp [hunk 1]
```diff
@@ -138,42 +138,33 @@ namespace {
 static int lock_array_copied = 0;
 inline int eliminate_warning_for_lock_array() { return lock_array_copied; }
 }  // namespace
-
-#ifdef __CUDACC_RDC__
-inline
-#else
-static
```
Comment (crtrott) [inline tpls/desul/include/desul/atomics/Lock_Array_Cuda.hpp:145]: can we try instead of reverting here: a namespace { and then close that namespace again? It looks like something is lost here anything.

**Review by crtrott — DISMISSED** [review]

**Comment by masterleinad** [comment]
```diff
diff --git a/lib/kokkos/tpls/desul/include/desul/atomics/Lock_Array_Cuda.hpp b/lib/kokkos/tpls/desul/include/desul/atomics/Lock_Array_Cuda.hpp
index 2166fa3cb7..cc4d5a317b 100644
--- a/lib/kokkos/tpls/desul/include/desul/atomics/Lock_Array_Cuda.hpp
+++ b/lib/kokkos/tpls/desul/include/desul/atomics/Lock_Array_Cuda.hpp
@@ -137,7 +137,6 @@ namespace Impl {
 namespace {
 static int lock_array_copied = 0;
 inline int eliminate_warning_for_lock_array() { return lock_array_copied; }
-}  // namespace
 
 #ifdef __CUDACC_RDC__
 inline
@@ -156,7 +155,7 @@ static
   }
   lock_array_copied = 1;
 }
-
+}
 }  // namespace Impl
 }  // namespace des
```
still gives me
```
> ../build/lmp -in in.lj -k on g 1 -sf kk -pk kokkos
LAMMPS (3 Nov 2022)
KOKKOS mode is enabled (src/KOKKOS/kokkos.cpp:106)
  will use up to 1 GPU(s) per node
terminate called after throwing an instance of 'std::runtime_error'
  what():  Desul::Error: init_lock_arrays_cuda: post init kernel error(cudaErrorIllegalAddress): an illegal memory access was encountered
Aborted (core dumped)
```

**Comment by ndellingwood** [comment]
@dalg24 @crtrott @ajpowelsnl  is this PR still intended to go into the 3.7.01 patch and blocker for release?

**Comment by ajpowelsnl** [comment]
> @dalg24 @crtrott @ajpowelsnl is this PR still intended to go into the 3.7.01 patch and blocker for release?

My understanding is that it's still up for discussion -- I don't know if the problem is well understood yet.  @masterleinad might be able to share additional insight.

**Comment by ndellingwood** [comment]
@ajpowelsnl thanks for the update. Once determined/resolved so this is no longer a blocker on 3.7.01 we can move forward with prepping the release PRs and Trilinos snapshot

File: tpls/desul/include/desul/atomics/Lock_Array_Cuda.hpp (hunk 1 above)
Comment (crtrott) [reply tpls/desul/include/desul/atomics/Lock_Array_Cuda.hpp:145]: tried this myself too I think we should revert

**Comment by ajpowelsnl** [comment]
To confirm, this PR fixes #5596, and possibly also #5269?  Also, this fix **did not** require reverting #4682, correct?  Final question -- does this topic need further discussion in the meeting today?

**Comment by masterleinad** [comment]
Reproducer using `LAMMPS`:
```
git clone https://github.com/lammps/lammps.git
cd lammps
mkdir build
cd build
cmake -C ../cmake/presets/basic.cmake -C ../cmake/presets/kokkos-cuda.cmake -D BUILD_SHARED_LIBS=on -DPKG_KOKKOS=ON -DCMAKE_BUILD_TYPE=DEBUG -DKokkos_ARCH_VOLTA70=ON -DKokkos_ARCH_PASCAL60=OFF ../cmake/
make -j16
cd ../bench
../build/lmp -in in.lj -k on g 1 -sf kk -pk kokkos
```

**Review by dalg24 — APPROVED** [review]
