### PR TITLE
Clang 22 ICE: add a more restrictive guard on DynViewAPI testing

### LINKED ISSUE #8884: Compiler crash with LLVM 22 based compilers
**Describe the bug**

Compiling Kokkos with ROCm 7.2+ WITHOUT HIP enabled results in a compiler crash. This is the same compiler crash that was identified when compiling WITH HIP. However, when configured without HIP enabled, the problematic code is included because none of the macros below are defined:
```
 697   static void run_operator_test_rank67() {
 698     // FIXME_HIP The test triggers an internal compiler error in hipcc
 699 #if !(defined(KOKKOS_ENABLE_HIP) || \
 700       (HIP_VERSION_MAJOR == 7 && HIP_VERSION_MINOR == 2))
 701     TestViewOperator_LeftAndRight<int, device, 7>::testit(2, 3, 4, 2, 3, 4, 2);
 702 #endif
 703     TestViewOperator_LeftAndRight<int, device, 6>::testit(2, 3, 4, 2, 3, 4);
 704   }
```
These changes (https://github.com/kokkos/kokkos/pull/8837, https://github.com/kokkos/kokkos/pull/8875) were intended to fix this problem, but the problem is with upstream clang.

**Please include the following for a minimal reproducer**

compiler: amdclang++ 7.2.0, which is clang 22.0 under the hood
kokkos release: current develop
platform: building serial or openmp back ends
cmake: 
```
cmake -B build -S . -DCMAKE_BUILD_TYPE=Release \
-DCMAKE_CXX_COMPILER=amdclang++ \
-DKokkos_ENABLE_OPENMP=ON \
-DKokkos_ENABLE_SERIAL=ON \
-DKokkos_ENABLE_TESTS=ON
```
gives output:
```
-- Setting default Kokkos CXX standard to 20
-- The CXX compiler identification is Clang 22.0.0
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Check for working CXX compiler: /opt/rocm/bin/amdclang++ - skipped
-- Detecting CXX compile features
-- Detecting CXX compile features - done
-- Kokkos version: 5.0.99
-- The project name is: Kokkos
-- Using bundled GoogleTest version
-- Configured git information in /home/khuck/src/kokkos/build/generated/Kokkos_Version_Info.cpp
-- Kokkos is configured for CMake languages CXX compilation (using Clang version 22.0.0)
-- Using -std=gnu++20 for C++20 extensions as feature
-- Built-in Execution Spaces:
--     Device Parallel: NoTypeDefined
--     Host Parallel: Kokkos::OpenMP
--       Host Serial: SERIAL
--
-- Architectures:
-- Found OpenMP_CXX: -fopenmp=libomp (found suitable version "5.1", minimum required is "3.0")
-- Found OpenMP: TRUE (found suitable version "5.1", minimum required is "3.0") found components: CXX
-- Using bundled desul_atomics copy (desul/desul@5e8dd8b549c0de391acb77535a40aa5668c35d01)
-- Performing Test KOKKOS_LINK_OPTIONS_CHECK
-- Performing Test KOKKOS_LINK_OPTIONS_CHECK - Success
-- Using bundled mdspan copy (kokkos/mdspan@5d4eb209c77f4744980c0b0c2af44636cc81b08b)
-- Found Python3: /usr/bin/python3 (found version "3.12.3") found components: Interpreter
-- Sources TestOpenMP.cpp
-- Kokkos Backends: OPENMP;SERIAL
-- Configuring done (5.6s)
-- Generating done (0.3s)
```
`cmake --build build --parallel 8 --target Kokkos_ContainersUnitTest_OpenMP` or `_Serial` will result in crash.

### PR DESCRIPTION
**Pull request by JBludau**
closes https://github.com/kokkos/kokkos/issues/8884

Clang 22 (the compiler underneath ROCm/7.2) has an ICE in compiling the `DynViewAPI.hpp` for testing.
The previous guard was skipping the test for `HIP` but it is also present when just enabling host backends with `amdclang++` (see the linked issue)
This PR reworks the guard to exclude the failing Clang version from compiling independent of the backend.

### CODE REVIEW

**Review by masterleinad — APPROVED** [review]

**Review by crtrott — CHANGES_REQUESTED** [review]
I don't think this is a good idea. There is not even an LLVM 22 release yet. That means ROCM is based on some development version of LLVM and this bug might be specific to the ROCM toolchain.

**Comment by JBludau** [comment]
Clang 22.1.0-rc3 shows the same issue building with the `Serial` backend enabled

**Comment by crtrott** [comment]
Let's wait to see how this looks in the actual release, given the information that this was reported upstream.

**Comment by crtrott** [comment]
Release supposedly comes this week anyway.

File: containers/unit_tests/TestDynViewAPI.hpp [hunk 1]
```diff
@@ -695,9 +695,8 @@ class TestDynViewAPI {
   }
 
   static void run_operator_test_rank67() {
-    // FIXME_HIP The test triggers an internal compiler error in hipcc
-#if !(defined(KOKKOS_ENABLE_HIP) || \
-      (HIP_VERSION_MAJOR == 7 && HIP_VERSION_MINOR > 1))
+    // FIXME_CLANG 22 The test triggers an internal compiler error in clang 22.
+#if !defined(KOKKOS_COMPILER_CLANG) || (KOKKOS_COMPILER_CLANG != 2200)
```
Comment (JBludau) [inline containers/unit_tests/TestDynViewAPI.hpp]:
```suggestion
#if !defined(KOKKOS_COMPILER_CLANG) || (KOKKOS_COMPILER_CLANG < 2200)
```

**Comment by JBludau** [comment]
still failing with clang 22.1.0 on a `SERIAL` build
I changed the guard so we exclude the test for clang>2200

**Review by crtrott — APPROVED** [review]

**Review by janciesko — APPROVED** [review]
