### PR TITLE
core/unit_test: Only use even numbers in bhalf reductions

### LINKED ISSUE #4719: OpenMP reduction data race with bhalf_t
When working on #4543 I found what appears to be a data race in the OpenMP backend.

Reproducer using kokkos develop at 20a090b:
Uncomment the following code:
https://github.com/kokkos/kokkos/blob/20a090bf6a7268f6d46521b686e46da3b40e925a/core/unit_test/TestReducers_d.hpp#L84-L95
```
module purge; module load sems-env sems-gcc/7.3.0 sems-cmake/3.19.1 cuda/11.0
../generate_makefile.bash --cxxflags=-Werror --arch=SNB,Volta70 --with-serial --with-cuda=$CUDA_PATH --with-openmp --compiler=$HOME/KOKKOS.base/kokkos/bin/nvcc_wrapper --kokkos-path=$HOME/KOKKOS.base/kokkos --prefix=$HOME/KOKKOS.base/kokkos/install &> generated_makefile.bash.out
make
core/unit_test/KokkosCore_UnitTest_OpenMP --gtest_filter=*openmp_cuda11_reduction_bug_with_bhalf_t*
Kokkos::OpenMP::initialize WARNING: OMP_PROC_BIND environment variable not set
  In general, for best performance with OpenMP 4.0 or better set OMP_PROC_BIND=spread and OMP_PLACES=threads
  For best performance with OpenMP 3.1 set OMP_PROC_BIND=true
  For unit testing set OMP_PROC_BIND=false
Note: Google Test filter = *openmp_cuda11_reduction_bug_with_bhalf_t*
[==========] Running 1 test from 1 test suite.
[----------] Global test environment set-up.
[----------] 1 test from openmp
[ RUN      ] openmp.openmp_cuda11_reduction_bug_with_bhalf_t
/path/to/kokkos/core/unit_test/TestReducers.hpp:321: Failure
Expected equality of these values:
  sum_scalar
    Which is: 276.000000
  reference_sum
    Which is: 274.000000
[  FAILED  ] openmp.openmp_cuda11_reduction_bug_with_bhalf_t (0 ms)
[----------] 1 test from openmp (0 ms total)

[----------] Global test environment tear-down
[==========] 1 test from 1 test suite ran. (0 ms total)
[  PASSED  ] 0 tests.
[  FAILED  ] 1 test, listed below:
[  FAILED  ] openmp.openmp_cuda11_reduction_bug_with_bhalf_t

 1 FAILED TEST
```

### PR DESCRIPTION
**Pull request by e10harvey**
Fixes #4719.

### CODE REVIEW

File: core/unit_test/TestReducers.hpp [hunk 1]
```diff
@@ -295,8 +295,24 @@ struct TestReducers {
...
     for (int i = 0; i < N; i++) {
-      int denom   = sizeof(Scalar) <= 2 ? 10 : 100;
-      h_values(i) = (Scalar)(rand() % denom);
+      int denom = sizeof(Scalar) <= 2 ? 10 : 100;
+      // clang-format off
+      // For bhalf, we start overflowing integer values at 2^8.
+      //            after 2^8,  we loose representation of odd numbers;
+      //            after 2^9,  we loose representation of odd and even numbers in position 1.
+      //            after 2^10, we loose representation of odd and even numbers in position 1-3.
+      //            after 2^11, we loose representation of odd and even numbers in position 1-7.
```
Comment (PhilMiller) [inline core/unit_test/TestReducers.hpp:304]: Loose -> lose

**Review by PhilMiller — APPROVED** [review]

**Comment by crtrott** [comment]
This needs warning fixes.

**Comment by crtrott** [comment]
Retest this please

**Review by crtrott — APPROVED** [review]

**Review by masterleinad — APPROVED** [review]

**Review by nliber — APPROVED** [review]
