### PR TITLE
Fix running parallel_reduce with TeamPolicy for large ranges

### LINKED ISSUE #4531: Kernels using TeamPolicy with certain dimensions won't execute
There seems to be an issue when using a TeamPolicy with a league size X and team size Y whenever X*Y mod 2^32 > 2^31. This occurs even when the IndexType used by the policy is an int64_t or uint64_t. See the below code which replicates the issue:
```
#include <Kokkos_Core.hpp>

using Device = Kokkos::Device<Kokkos::DefaultExecutionSpace, typename Kokkos::DefaultExecutionSpace::memory_space>;
using team_policy_t = Kokkos::TeamPolicy<Kokkos::IndexType<uint64_t>, typename Device::execution_space>;
using member_t = typename team_policy_t::member_type;

struct range_count {
    KOKKOS_INLINE_FUNCTION
    void operator() (const member_t& t, uint64_t& update) const {
        const uint64_t i = t.league_rank();
        Kokkos::single(Kokkos::PerTeam(t), [&] (){
            update++;
        });
    }
};

void driver(){
    range_count count_functor;
    uint64_t range = (2LU << 23) - 1;
    uint64_t result = 0;
    Kokkos::parallel_reduce("count range", team_policy_t(range, 128), count_functor, result);
    //correct
    printf("Number of teams executed for range %lu: %lu\n", range, result);
    range = 2LU << 23;
    Kokkos::parallel_reduce("count range", team_policy_t(range, 128), count_functor, result);
    //incorrect
    printf("Number of teams executed for range %lu: %lu\n", range, result);
    range = (2LU << 24);
    Kokkos::parallel_reduce("count range", team_policy_t(range, 128), count_functor, result);
    //incorrect
    printf("Number of teams executed for range %lu: %lu\n", range, result);
    range = (2LU << 24) + 1;
    Kokkos::parallel_reduce("count range", team_policy_t(range, 128), count_functor, result);
    //correct
    printf("Number of teams executed for range %lu: %lu\n", range, result);
}

int test() {
    Kokkos::initialize();
    {
        driver();
    }
    Kokkos::finalize();
    return 0;
}

int main(int argc, char** args) {
    return test();
}
```

### PR DESCRIPTION
**Pull request by masterleinad**
Fixes #4531. Specifically, the lines
```
const auto nwork = static_cast<typename Policy::index_type>(m_league_size) * m_team_size;
```
fix the issue (for `CUDA` and `HIP`). The other changes to the types of `nwork` are just for consistency.

### CODE REVIEW

**Comment by masterleinad** [comment]
Retest this please.

**Comment by masterleinad** [comment]
This seems to work on all backends now. Note that I had to change the argument type of `scratch_space` for `SYCL` to `std::size_t` to make it work. We should discuss (maybe as a follow-up) if we want to make this consistent for all backends and switch to `std::size_t` or find a different solutiuon.

File: core/src/Cuda/Kokkos_Cuda_Parallel.hpp [hunk 1]
```diff
@@ -1822,15 +1822,15 @@ class ParallelReduce<FunctorType, Kokkos::TeamPolicy<Properties...>,
   }
 
   inline void execute() {
-    const int nwork            = m_league_size * m_team_size;
+    const bool do_work         = m_league_size > 0 && m_team_size > 0;
```
Comment (dalg24) [inline core/src/Cuda/Kokkos_Cuda_Parallel.hpp:1825]: Did you consider
```suggestion
    const typename Policy::size_type nwork = m_league_size * m_team_size;
```
?

Comment (masterleinad) [reply core/src/Cuda/Kokkos_Cuda_Parallel.hpp:1825]: That doesn't work because the product is still done with `int`s. At assignment the product is already wrong.
We could cast one of the operands on the right-hand side but that might still not be enough, see https://github.com/kokkos/kokkos/issues/4531#issuecomment-970595549.
In the end, it is much better to just avoid doing these multiplications if we can.

**Comment by masterleinad** [comment]
The changes for `SYCL` are also discussed in https://github.com/kokkos/kokkos/pull/4551.

**Review by janciesko — COMMENTED** [review]
LGTM

**Review by rgayatri23 — APPROVED** [review]

**Review by crtrott — APPROVED** [review]
