### PR TITLE
Fix subview construction between managed and unmanaged Views

### LINKED ISSUE #8965: Create an unmanaged subview from a view is broken (rank-1)
Creating an unmanaged subview of a view as follows used to work until 8cfdfd8abe48b57cfb1b887fd8c9e3d77f990b51 from @crtrott :
```c++
TEST(TEST_CATEGORY, unmanaged_subview_from_view_is_broken) {
  using memory_space = typename TEST_EXECSPACE::memory_space;
  using view_t    = Kokkos::View<double*, memory_space>;
  using view_um_t = Kokkos::View<double*, memory_space, Kokkos::MemoryTraits<Kokkos::Unmanaged>>;

  constexpr size_t size = 10;
  constexpr Kokkos::pair<size_t, size_t> range {0, 5};

  const view_t values("values", size);

  const view_um_t subview_from_view(values       , range); // Does not compile...
  const view_um_t subview_from_raw (values.data(), range.second); // OK !
}
```

Reverting 8cfdfd8abe48b57cfb1b887fd8c9e3d77f990b51 makes the above code compile just fine. The question is, since there wasn't any test that captured the regression:
> Is it allowed to create an unmanaged view from a view as done above?

If so, this needs a fix @crtrott :wink: 

Compiler output:
```bash
In file included from /workspaces/kokkos/core/src/Kokkos_View.hpp:15,
                 from /workspaces/kokkos/core/src/Kokkos_Parallel.hpp:18,
                 from /workspaces/kokkos/core/src/OpenMP/Kokkos_OpenMP.hpp:19,
                 from /workspaces/kokkos/core/src/decl/Kokkos_Declare_OPENMP.hpp:8,
                 from /workspaces/kokkos/build-with-gcc-OpenMP/KokkosCore_Config_DeclareBackend.hpp:7,
                 from /workspaces/kokkos/core/src/Kokkos_Core.hpp:32,
                 from /workspaces/kokkos/core/unit_test/TestGraph.hpp:8,
                 from /workspaces/kokkos/build-with-gcc-OpenMP/core/unit_test/openmp/TestOpenMP_Graph.cpp:2:
/workspaces/kokkos/core/src/View/Kokkos_BasicView.hpp: In instantiation of 'Kokkos::Impl::BV::BasicView<ElementType, Extents, LayoutPolicy, AccessorPolicy>::BasicView(Kokkos::Impl::SubViewCtorTag, const Kokkos::Impl::BV::BasicView<OtherT, OtherE, OtherL, OtherA>&, SliceSpecifiers ...) [with OtherElementType = double; OtherExtents = Kokkos::extents<long unsigned int, 18446744073709551615>; OtherLayoutPolicy = Kokkos::Experimental::layout_right_padded<18446744073709551615>; OtherAccessorPolicy = Kokkos::Impl::SpaceAwareAccessor<Kokkos::HostSpace, Kokkos::Impl::ReferenceCountedAccessor<double, Kokkos::HostSpace, Kokkos::default_accessor<double> > >; SliceSpecifiers = {Kokkos::pair<long unsigned int, long unsigned int>}; ElementType = double; Extents = Kokkos::extents<long unsigned int, 18446744073709551615>; LayoutPolicy = Kokkos::Experimental::layout_right_padded<18446744073709551615>; AccessorPolicy = Kokkos::Impl::SpaceAwareAccessor<Kokkos::HostSpace, Kokkos::default_accessor<double> >]':
/workspaces/kokkos/core/src/Kokkos_View.hpp:846:63:   required from 'Kokkos::View<DataType, Properties>::View(const Kokkos::View<RT, RP ...>&, Arg0, Args ...) [with RT = double*; RP = {Kokkos::HostSpace}; Arg0 = Kokkos::pair<long unsigned int, long unsigned int>; Args = {}; DataType = double*; Properties = {Kokkos::HostSpace, Kokkos::MemoryTraits<1>}]'
  846 |       : base_t(Impl::subview_ctor_tag, src_view, arg0, args...) {}
      |                                                               ^
/workspaces/kokkos/core/unit_test/TestGraph.hpp:1472:57:   required from here
 1472 |   const view_um_t subview_from_view(values       , range); // Does not compile
      |                                                         ^
/workspaces/kokkos/core/src/View/Kokkos_BasicView.hpp:600:34: error: cannot convert 'Kokkos::Impl::SpaceAwareAccessor<Kokkos::HostSpace, Kokkos::Impl::ReferenceCountedAccessor<double, Kokkos::HostSpace, Kokkos::default_accessor<double> > >::data_handle_type' {aka 'Kokkos::Impl::ReferenceCountedDataHandle<double, Kokkos::HostSpace>'} to 'Kokkos::Impl::BV::BasicView<double, Kokkos::extents<long unsigned int, 18446744073709551615>, Kokkos::Experimental::layout_right_padded<18446744073709551615>, Kokkos::Impl::SpaceAwareAccessor<Kokkos::HostSpace, Kokkos::default_accessor<double> > >::data_handle_type' {aka 'double*'} in assignment
  600 |     m_ptr = src_view.m_acc.offset(src_view.m_ptr, sub_mapping_result.offset);
      |             ~~~~~~~~~~~~~~~~~~~~~^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
      |                                  |
      |                                  Kokkos::Impl::SpaceAwareAccessor<Kokkos::HostSpace, Kokkos::Impl::ReferenceCountedAccessor<double, Kokkos::HostSpace, Kokkos::default_accessor<double> > >::data_handle_type {aka Kokkos::Impl::ReferenceCountedDataHandle<double, Kokkos::HostSpace>}
In file included from /workspaces/kokkos/core/src/View/Kokkos_ViewTraits.hpp:19,
                 from /workspaces/kokkos/core/src/View/Kokkos_BasicView.hpp:18:
/workspaces/kokkos/core/src/View/MDSpan/Kokkos_MDSpan_Accessor.hpp:304:12: note: explicit conversion function was not considered
  304 |   explicit operator pointer() const noexcept { return m_handle; }
      |            ^~~~~~~~
```

### PR DESCRIPTION
**Pull request by masterleinad**
Fixes #8965.

### CODE REVIEW

**Review by janciesko — APPROVED** [review]

File: core/unit_test/TestSubView_c16.hpp [hunk 1]
```diff
@@ -0,0 +1,51 @@
...
+#include <gtest/gtest.h>
+#include <Kokkos_Macros.hpp>
+#ifdef KOKKOS_ENABLE_EXPERIMENTAL_CXX20_MODULES
+import kokkos.core;
+#else
+#include <Kokkos_Core.hpp>
+#endif
+
+namespace {
+TEST(TEST_CATEGORY, view_subview_managed_unmanaged) {
```
Comment (dalg24) [inline core/unit_test/TestSubView_c16.hpp]: What does "managed unmanaged" mean?
Please suggest an alternate name and add a comment saying what that test is about.

File: core/unit_test/TestSubView_c16.hpp [hunk 2]
```diff
@@ -0,0 +1,51 @@
...
+  Kokkos::View<int**, LL> a1("A1", N, N);
+  Kokkos::View<int**, LL, Kokkos::MemoryTraits<Kokkos::Unmanaged>> a1_unmanaged(
+      a1.data(), N, N);
+  {
+    // Using subview dims (ALL, 1). For a LayoutLeft,
+    // any subview layout should be appropriate.
+    (void)Kokkos::View<int*, LL, Kokkos::MemoryTraits<Kokkos::Unmanaged>>(
+        a1, Kokkos::ALL, 1);
+    (void)Kokkos::View<int*, LS, Kokkos::MemoryTraits<Kokkos::Unmanaged>>(
+        a1, Kokkos::ALL, 1);
```
Comment (dalg24) [inline core/unit_test/TestSubView_c16.hpp:30]: Any particular reason to prefer View constructors over the subview() free function?

Comment (masterleinad) [reply core/unit_test/TestSubView_c16.hpp:30]: The issue was with the View constructor, not with the `subview` free function. Using the `subview` free function, would rather test View convertibility.

Comment (dalg24) [reply core/unit_test/TestSubView_c16.hpp:30]: I see. Thx

File: core/unit_test/TestSubView_c16.hpp (hunk 1 above)
Comment (masterleinad) [reply core/unit_test/TestSubView_c16.hpp]:
```suggestion
// Test that the subview constructor works for constructing subviews from
// Views where one of them has the Kokkos::Unmanaged memory trait
TEST(TEST_CATEGORY, view_create_unmanaged_subview_from_managed) {
```

Comment (dalg24) [reply core/unit_test/TestSubView_c16.hpp]: That's better.  I did not apply because I suspect L13 is too long.  Did you check the format?

Comment (masterleinad) [reply core/unit_test/TestSubView_c16.hpp]: I didn't but it seems it would have been fine (just pushed from the terminal). 🙂

**Comment by masterleinad** [comment]
```
[CUDA-11.8-Clang-15] 5: [ RUN      ] cuda.reducers_half_t
[CUDA-11.8-Clang-15] 5: /var/jenkins/workspace/Kokkos_PR-8967/core/unit_test/TestReducers.hpp:589: Failure
[CUDA-11.8-Clang-15] 5: Expected equality of these values:
[CUDA-11.8-Clang-15] 5:   prod_scalar
[CUDA-11.8-Clang-15] 5:     Which is: 52480.000000
[CUDA-11.8-Clang-15] 5:   reference_prod
[CUDA-11.8-Clang-15] 5:     Which is: 52512.000000
```
seems unrelated.

File: core/unit_test/TestSubView_c16.hpp [hunk 3]
```diff
@@ -0,0 +1,53 @@
...
+
+    (void)Kokkos::View<int*, LL>(a1_unmanaged, Kokkos::ALL, 1);
+    (void)Kokkos::View<int*, LS>(a1_unmanaged, Kokkos::ALL, 1);
```
Comment (Adrien-Tab) [inline core/unit_test/TestSubView_c16.hpp:33]: Should LR be allowed for (all, 1) subview of LL, as the comment in `Test_subview_c15` suggests ?

**Review by Adrien-Tab — APPROVED** [review]
Maybe those tests could be moved to `kokkos_CoreUnitTest_ViewSupport,` they don't seem to test `Kokkos::subview()`

File: core/unit_test/TestSubView_c16.hpp (hunk 3 above)
Comment (masterleinad) [reply core/unit_test/TestSubView_c16.hpp:33]: Yes, but it doesn't even work in the `c15` test (and it's not entirley the focus here). If you want I can add it here commented out as well.

**Comment by masterleinad** [comment]
> Maybe those tests could be moved to `kokkos_CoreUnitTest_ViewSupport,` they don't seem to test `Kokkos::subview()`

No strong opinion. I added it here since `c15` is quite similar (but doesn't test different memory traits).

File: core/unit_test/TestSubView_c16.hpp (hunk 3 above)
Comment (Adrien-Tab) [reply core/unit_test/TestSubView_c16.hpp:33]: Yes, so we don't forget about it "if" the other thing gets fixed

**Review by crtrott — APPROVED** [review]

**Comment by crtrott** [comment]
I think we need to reorder all the subview tests let's do that separately.
