### PR TITLE
Fix a segfault with GCC 12

### LINKED ISSUE #8187: SegFault for OpenMP ViewSupport unit test
The unit test failed as part of a docker build on Google cloud (gcloud builds submit). Some details from the Dockerfile:
RUN wget https://github.com/kokkos/kokkos/download/4.5.01/kokkos-4.5.01.tar.gz && tar xvf kokkos-4.5.01.tar.gz && cd kokkos-4.5.01 && mkdir build && export OMP_PROC_BIND=false && cmake -B build -DCMAKE_BUILD_TYPE=Release -DKokkos_ENABLE_CUDA=OFF -DKokkos_ENABLE_HIP=OFF -DKokkos_ENABLE_SYCL=OFF -DKokkos_ENABLE_OPENMP=ON -DKokkos_ENABLE_TESTS=ON && cmake --build build && ctest --test-dir build --output-on-failure && cmake --install build

Same issue encountered with release 4.6.01
Compiler: GNU 12.2.1
OpenMP: 4.5

I'm assuming Google Cloud build uses x86_64 architecture. Operating system fedora:36 . I can provide the Dockerfile upon request.
Thank you.
Best regards, 
Silviu

### PR DESCRIPTION
**Pull request by tretre91**
This PR is intended to fix #8187 ~~(for the moment there is a single commit adding a gcc12.3 ci run to make sure it is detected)~~

Several tests are failing when using GCC 12.{2,3,4}. It looks like a compiler bug, as it doesn't happen with clang or with gcc versions <=12.1 or >=13.1, the constructor of `SharedAllocTracker` (shown below) is not called, which later causes a dereference of a null pointer when trying to call its `get_label()` method
https://github.com/kokkos/kokkos/blob/3e7dfc68cc1fb371c345ef42cb0f0d97caee8b81/core/src/impl/Kokkos_SharedAlloc.hpp#L609-L610

Making the `SharedAllocTracker` constructor non-constexpr seems to fix the issue, ~~afaict none of the classes using `SharedAllocTracker` have a constexpr constructor, so I guess it would be safe to make it non-constexpr~~ nvcc needs it to be constexpr, making it constexpr only when `KOKKOS_COMPILER_GCC` is off or corresponds to the non-faulty versions seems to work

The first failing commit is d77422167c2ef09e6f26fb90cebe5b3f3dc91575 (which introduced the basic view tests)

### CODE REVIEW

**Comment by tretre91** [comment]
The failure can be seen here https://github.com/kokkos/kokkos/actions/runs/16076149873/job/45372794972

File: core/src/impl/Kokkos_SharedAlloc.hpp [hunk 1]
```diff
@@ -606,8 +606,14 @@ union SharedAllocationTracker {
   KOKKOS_FORCEINLINE_FUNCTION
   ~SharedAllocationTracker(){KOKKOS_IMPL_SHARED_ALLOCATION_TRACKER_DECREMENT}
 
-  KOKKOS_FORCEINLINE_FUNCTION constexpr SharedAllocationTracker()
-      : m_record_bits(DO_NOT_DEREF_FLAG) {}
+  KOKKOS_FORCEINLINE_FUNCTION
+#if !defined(KOKKOS_COMPILER_GNU) || (KOKKOS_COMPILER_GNU < 1220) || \
+    (KOKKOS_COMPILER_GNU > 1240)
+      constexpr
+#endif
```
Comment (masterleinad) [inline core/src/impl/Kokkos_SharedAlloc.hpp]: Can you add a comment explaining the issue?

**Comment by masterleinad** [comment]
> nvcc needs it to be constexpr, making it constexpr only when `KOKKOS_COMPILER_GCC` is off or corresponds to the non-faulty versions seems to work

Why does `nvcc` (only) need it to be `constexpr`?

**Review by masterleinad — DISMISSED** [review]

**Comment by tretre91** [comment]
> > nvcc needs it to be constexpr, making it constexpr only when `KOKKOS_COMPILER_GCC` is off or corresponds to the non-faulty versions seems to work
> 
> Why does `nvcc` (only) need it to be `constexpr`?

I need to reproduce this locally, but I got the following error in the CI:
```
/builds/kokkos/kokkos/core/src/View/Kokkos_BasicView.hpp(179): error #20011-D: calling a __host__ function("Kokkos::Impl::ReferenceCountedDataHandle<int,  ::Kokkos::HostSpace> ::ReferenceCountedDataHandle()") from a __host__ __device__ function("Kokkos::Impl::BV::BasicView<int,  ::Kokkos::extents<unsigned long, (unsigned long)18446744073709551615ul > ,  ::Kokkos::Experimental::layout_right_padded<(unsigned long)18446744073709551615ul> ,  ::Kokkos::Impl::SpaceAwareAccessor< ::Kokkos::HostSpace,  ::Kokkos::Impl::ReferenceCountedAccessor<int,  ::Kokkos::HostSpace,  ::Kokkos::default_accessor<int> > > > ::BasicView") is not allowed
```

My guess would be that it's because `SharedAllocationTracker` is used inside `ReferenceCountedDataHandle` which is neither marked `constexpr` nor `KOKKOS_FUNCTION` (it is `KOKKOS_DEFAULTED_FUNCTION`, which is an empty macro), so for it to be device callable it somehow needs `SharedAllocTracker` to be `constexpr`.

File: core/src/impl/Kokkos_SharedAlloc.hpp [hunk 2]
```diff
@@ -606,8 +606,19 @@ union SharedAllocationTracker {
...
+  KOKKOS_FORCEINLINE_FUNCTION
+#if !defined(KOKKOS_COMPILER_GNU) || (KOKKOS_COMPILER_GNU < 1220) || \
+    (KOKKOS_COMPILER_GNU > 1240)
+      // FIXME_GCC: The ViewSupport test fails with gcc 12.2, 12.3 and 12.4
+      // because this constructor is optimized out, which leads to a nullptr
+      // dereference. Removing the constexpr fixes the issue but nvcc complains,
+      // so we keep the constexpr but only when using anything other than those
+      // three faulty gcc versions.
+      constexpr
+#endif
```
Comment (masterleinad) [inline core/src/impl/Kokkos_SharedAlloc.hpp]: Doesn't that mean that we also need to guard for `nvcc`? What happens if we use `gcc-12` with `Cuda`? Do we have a version that would compile and passes the tests?

**Comment by tpadioleau** [comment]
Anyone understands why we get the warning `calling host function from device function` when we remove the `constexpr` qualification from the `SharedAllocationTracker` constructor ?
```
/builds/kokkos/kokkos/core/src/View/Kokkos_BasicView.hpp(179): error #20011-D: calling a __host__ function("Kokkos::Impl::ReferenceCountedDataHandle<int,  ::Kokkos::HostSpace> ::ReferenceCountedDataHandle()") from a __host__ __device__ function("Kokkos::Impl::BV::BasicView<int,  ::Kokkos::extents<unsigned long, (unsigned long)18446744073709551615ul > ,  ::Kokkos::Experimental::layout_right_padded<(unsigned long)18446744073709551615ul> ,  ::Kokkos::Impl::SpaceAwareAccessor< ::Kokkos::HostSpace,  ::Kokkos::Impl::ReferenceCountedAccessor<int,  ::Kokkos::HostSpace,  ::Kokkos::default_accessor<int> > > > ::BasicView") is not allowed
Remark: The warnings can be suppressed with "-diag-suppress <warning-number>"
1 error detected in the compilation of "/builds/kokkos/kokkos/build/containers/unit_tests/serial/TestSerial_WithoutInitializing.cpp".
gmake[2]: *** [containers/unit_tests/CMakeFiles/Kokkos_ContainersUnitTest_Serial.dir/build.make:244: containers/unit_tests/CMakeFiles/Kokkos_ContainersUnitTest_Serial.dir/serial/TestSerial_WithoutInitializing.cpp.o] Error 1
gmake[2]: *** Waiting for unfinished jobs....
```

see the log https://gitlab.spack.io/kokkos/kokkos/-/jobs/17280388

**Comment by masterleinad** [comment]
> Anyone understands why we get the warning `calling host function from device function` when we remove the `constexpr` qualification from the `SharedAllocationTracker` constructor ?

I guess we just have to provide a non-defaulted default contructor with the correct annotations.

**Comment by crtrott** [comment]
> > Anyone understands why we get the warning `calling host function from device function` when we remove the `constexpr` qualification from the `SharedAllocationTracker` constructor ?
> 
> I guess we just have to provide a non-defaulted default contructor with the correct annotations.

You mean in the ReferenceCountedDataHandle? If we do it with ifdef guards please. And comments on both sides that these workarounds are connected.

**Comment by crtrott** [comment]
Do we need to add a new config for testing, or can we move one to catch this?

**Comment by tpadioleau** [comment]
> I guess we just have to provide a non-defaulted default contructor with the correct annotations.

You think this is a nvcc bug then ?

I am not convinced by the `constexpr` annotation for this constructor as the destructor is not trivial, I don't think we can call `constexpr SharedAllocationTracker foo` ?

**Comment by crtrott** [comment]
I looked at the ReferenceCounted handle thingy and the default ctor looks fine. It's defaulted so it should be ok to be called from host/device. So it looks like an issue with NVCC would be interesting to see if this issue only happens with certain versions of NVCC.

**Comment by maartenarnst** [comment]
See also: 
- https://github.com/kokkos/kokkos/issues/7464

File: core/src/impl/Kokkos_SharedAlloc.hpp (hunk 2 above)
Comment (tretre91) [reply core/src/impl/Kokkos_SharedAlloc.hpp]: I tried with cuda 12.4 + gcc 12.2 and it works

**Comment by tretre91** [comment]
> Do we need to add a new config for testing, or can we move one to catch this?

I haven't tried yet but according to #7464 this bug also happens on arm, so we might be able to catch this in one of the arm64 configs instead of adding a new one

File: core/src/impl/Kokkos_SharedAlloc.hpp (hunk 2 above)
Comment (masterleinad) [reply core/src/impl/Kokkos_SharedAlloc.hpp]: So it's only problematic for older `nvcc` versions that aren't compatible with `gcc-12`?

**Review by dalg24 — DISMISSED** [review]

**Review by masterleinad — DISMISSED** [review]
I'd like a response to https://github.com/kokkos/kokkos/pull/8223/files#r2192912157.

File: core/src/impl/Kokkos_SharedAlloc.hpp (hunk 2 above)
Comment (tretre91) [reply core/src/impl/Kokkos_SharedAlloc.hpp]: I don't think there was in issue with nvcc, I only observed the issue with gcc and the serial, openmp and threads backend (the nvcc issue discussed below appears if we unconditionally remove the constexpr, like I was doing in https://github.com/kokkos/kokkos/pull/8223/commits/c6034531a70eeda6647586992eb8a086ca55c439, I guess it messes up something in nvcc's device pass)

I ran the tests with and without the fix today on nvcc 12.1, 12.2, 12.4, 12.6.3, 12.8 + gcc 12.2 and there was no issue

Comment (tretre91) [reply core/src/impl/Kokkos_SharedAlloc.hpp]: However, I'm not that familiar with nvcc's host and device passes, so I don't know if the `KOKKOS_COMPILER_GNU` is enabled during the host pass, which would mean that this fix removes the constexpr during the host pass but not the device pass? And if so, I don't know if it could be problematic

**Comment by tretre91** [comment]
> > Do we need to add a new config for testing, or can we move one to catch this?
> 
> I haven't tried yet but according to #7464 this bug also happens on arm, so we might be able to catch this in one of the arm64 configs instead of adding a new one

The failure can effectively be caught in the arm ci (see [here](https://github.com/tretre91/test/actions/runs/16162610676/job/45617830152)), should I remove the config I added and use `g++-12` into one of the arm ci instead? (the only x86 GCC configs explicitly included in the matrix are the c++23 and 32bit ones, it didn't feel right to modify them)

File: core/src/impl/Kokkos_SharedAlloc.hpp (hunk 2 above)
Comment (dalg24) [reply core/src/impl/Kokkos_SharedAlloc.hpp]: There is a compiler pass with GCC

Consider the following source code:
```C++
#include <Kokkos_Macros.hpp>

#ifdef KOKKOS_COMPILER_GNU
#error I was here
#endif
```
It will error out at compile time with our standard CUDA build that uses nvcc_wrapper

**Comment by dalg24** [comment]
~~We do need to add or modify some CI build in this PR~~
Ugg I don;t know why I could not see the CI changes any more.  I have been using the experimental GH feature maybe that's why I missed it.  Anyway sorry about the noise.

**Review by dalg24 — APPROVED** [review]
Approving so we can run the Sandia CI

**Comment by tretre91** [comment]
> On 2nd thought I don't think I understand what is going on

The `ViewSupport` test fails with a segfault on the serial, openmp and threads backends when compiling with gcc 12.2, 12.3 and 12.4
After debugging, the default constructor of `SharedAllocationTracker` is not called, which leads to a nullptr dereference when the `get_label` function is called later in the test
Removing the constexpr annotation on the constructor fixes this issue. In its current state, this PR disables this constexpr when compiling with gcc 12.2, 12.3 and 12.4 (this doesn't apply to nvcc + gcc12 as there is seemingly no issue with this setup and nvcc needs this constructor to be constexpr to not get [this warning](https://github.com/kokkos/kokkos/pull/8223#issuecomment-3045751429))

This PR also adds a CI build using g++-12 (gcc 12.3). If necessary, instead of adding a new build, we could modify one of the existing ones (the arm64 gcc openmp one for example) to use g++-12

**Review by masterleinad — APPROVED** [review]
FIne with me.

**Comment by dalg24** [comment]
Make sure to add an entry to the changelog under bug fix, something like "Workaround compiler bug with GCC 12.{2,3,4} causing segfaults with the View shared allocation tracker"

File: .github/workflows/continuous-integration-linux.yml [hunk 3]
```diff
@@ -136,6 +142,9 @@ jobs:
       - name: maybe_set_hpx_vars
         if: ${{ matrix.backend == 'HPX' }}
         run: echo "HPX_HANDLE_FAILED_NEW=0" >> $GITHUB_ENV
+      - name: maybe_install_gcc_12
+        if: ${{ matrix.cxx == 'g++-12' }}
+        run: sudo apt-get install -y g++-12
```
Comment (junghans) [inline .github/workflows/continuous-integration-linux.yml:147]: This should really be moved to kokkos/ci-containers.
