### PR TITLE
Fix incorrect `MDRangePolicy` iterations when the rank is higher than 4 for Cuda

### LINKED ISSUE #7697: MDRangePolicy rank >= 4 CUDA running loop-body incorrect number of times
When using an MDRangePolicy with rank >= 4 (so the block sizes for two dimensions are packed into a single entry of the 3D cuda grid), the associated loop body can be run more times than anticipated. This is due to the code that does the packing (https://github.com/kokkos/kokkos/blob/3a1d9e828c6601b96d8978fa8d1a7c68114bb24d/core/src/Cuda/Kokkos_Cuda_Parallel_MDRange.hpp#L165) correctly checks the grid size for each dimension (queried from the CUDA API), whilst the code that does the unpacking (https://github.com/kokkos/kokkos/blob/3a1d9e828c6601b96d8978fa8d1a7c68114bb24d/core/src/impl/KokkosExp_IterateTileGPU.hpp#L279) assumes that the max number of blocks along any axis of the grid is 65535. 

For all current CUDA devices, max_blocks[0] will be 2^31-1, so the packing code will pack up to that many blocks, but the unpacker will cap `numbl*` to 65535 (in IterateTileGPU.hpp). This likely affects other GPU devices too.

The code below shows that some cells get incremented more than once when using an MDRange.
Changing either the length of the first dimension of the View (and loops) or the tilesize so that there are fewer than 65535 tiles fixes the issue. By chance, this example works correctly when `Iterate::Left` is chosen for the inner iteration direction. This would not be the case if the first and second dimensions of the View/loop were swapped.

**Please include the following for a minimal reproducer**

1. Compilers (with versions): nvhpc24.5 from docker image: nvhpc:24.5-devel-cuda12.4-ubuntu22.04
2. Kokkos release or commit used (i.e., the sha1 number): Tested on 4.4.1 and 4.5.1. Code is unchanged on main.
3. Platform, architecture and backend. Linux (WSL), CUDA
4. CMake configure command: `-DKokkos_ENABLE_SERIAL=ON -DKokkos_ENABLE_CUDA=ON -DKokkos_ARCH_AMPERE86=ON -DKokkos_ENABLE_THREADS=ON -DKokkos_ENABLE_CUDA_CONSTEXPR=ON -DKokkos_ENABLE_CUDA_LAMBDA=ON -DKokkos_ENABLE_COMPILE_AS_CMAKE_LANGUAGE=ON -DCMAKE_BUILD_TYPE=Release`
5. Output from CMake configure command
6. Minimum, complete code needed to reproduce the bug:
```c++
#include <Kokkos_Core.hpp>

#include <cstdio>
#include <iostream>

typedef float fp_t;

typedef Kokkos::LayoutRight Layout;
template <class T, typename... Args>
using KView = Kokkos::View<T, Layout, Args...>;

typedef Kokkos::DefaultExecutionSpace::memory_space DefaultMemSpace;
typedef Kokkos::HostSpace HostSpace;

typedef Kokkos::View<fp_t*    , Layout> Fp1d;
typedef Kokkos::View<fp_t**   , Layout> Fp2d;
typedef Kokkos::View<fp_t***  , Layout> Fp3d;
typedef Kokkos::View<fp_t**** , Layout> Fp4d;
typedef Kokkos::View<fp_t*****, Layout> Fp5d;

template <int R, typename... Args>
// Wrong
using MDRange = Kokkos::MDRangePolicy<Kokkos::Rank<R, Kokkos::Iterate::Right, Kokkos::Iterate::Right>, Args...>;
// Correct
// using MDRange = Kokkos::MDRangePolicy<Kokkos::Rank<R, Kokkos::Iterate::Right, Kokkos::Iterate::Left>, Args...>;
// Correct
// using MDRange = Kokkos::MDRangePolicy<Kokkos::Rank<R>, Args...>;

int main(int argc, char* argv[]) {
  Kokkos::initialize(argc, argv);
  Kokkos::DefaultExecutionSpace().print_configuration(std::cout);
  {
    auto arr_mdr = Fp4d("stuff", 1024*1024, 1, 1, 1);
    auto arr_flat = Fp4d("stuff", 1024*1024, 1, 1, 1);

    Kokkos::parallel_for(
      "MDR Loop",
      MDRange<4>(
        {0, 0, 0, 0},
        {1024 * 1024, 1, 1, 1}
      ),
      KOKKOS_LAMBDA (int x, int y, int z, int w) {
        Kokkos::atomic_add(&arr_mdr(x, y, z, w), 1.0f);
      }
    );

    Kokkos::parallel_for(
      "Flat Loop",
      1024 * 1024,
      KOKKOS_LAMBDA (int x) {
        Kokkos::atomic_add(&arr_flat(x, 0, 0, 0), 1.0f);
      }
    );
    Kokkos::fence();

    fp_t max_mdr = 0.0f;
    fp_t max_flat = 0.0f;
    Kokkos::parallel_reduce(
      "Check MDR",
      MDRange<4>(
        {0, 0, 0, 0},
        {1024 * 1024, 1, 1, 1}
      ),
      KOKKOS_LAMBDA (int x, int y, int z, int w, float& lmax) {
        fp_t val = arr_mdr(x, y, z, w);
        if (val > lmax) {
          lmax = val;
        }
      },
      Kokkos::Max<fp_t>(max_mdr)
    );
    Kokkos::parallel_reduce(
      "Check flat",
      1024 * 1024,
      KOKKOS_LAMBDA (int x, float& lmax) {
        fp_t val = arr_flat(x, 0, 0, 0);
        if (val > lmax) {
          lmax = val;
        }
      },
      Kokkos::Max<fp_t>(max_flat)
    );

    Kokkos::fence();
    printf("Max mdr: %f, flat: %f. Expected 1.0\n", max_mdr, max_flat);
  }
  Kokkos::finalize();
  return 0;
}
```
7. Command line needed to reproduce the bug
8. `KokkosCore_config.h` header file (generated during the build):
```c++

#if !defined(KOKKOS_MACROS_HPP) || defined(KOKKOS_CORE_CONFIG_H)
#error \
    "Do not include KokkosCore_config.h directly; include Kokkos_Macros.hpp instead."
#else
#define KOKKOS_CORE_CONFIG_H
#endif

// KOKKOS_VERSION % 100 is the patch level
// KOKKOS_VERSION / 100 % 100 is the minor version
// KOKKOS_VERSION / 10000 is the major version
#define KOKKOS_VERSION 40501
#define KOKKOS_VERSION_MAJOR 4
#define KOKKOS_VERSION_MINOR 5
#define KOKKOS_VERSION_PATCH 1

/* Execution Spaces */
#define KOKKOS_ENABLE_SERIAL
/* #undef KOKKOS_ENABLE_OPENMP */
/* #undef KOKKOS_ENABLE_OPENACC */
/* #undef KOKKOS_ENABLE_OPENMPTARGET */
#define KOKKOS_ENABLE_THREADS
#define KOKKOS_ENABLE_CUDA
/* #undef KOKKOS_ENABLE_HIP */
/* #undef KOKKOS_ENABLE_HPX */
/* #undef KOKKOS_ENABLE_SYCL */

/* General Settings */
#define KOKKOS_ENABLE_CXX17
/* #undef KOKKOS_ENABLE_CXX20 */
/* #undef KOKKOS_ENABLE_CXX23 */
/* #undef KOKKOS_ENABLE_CXX26 */

/* #undef KOKKOS_ENABLE_CUDA_RELOCATABLE_DEVICE_CODE */
/* #undef KOKKOS_ENABLE_CUDA_UVM */
#define KOKKOS_ENABLE_CUDA_LAMBDA  // deprecated
#define KOKKOS_ENABLE_CUDA_CONSTEXPR
/* #undef KOKKOS_ENABLE_IMPL_CUDA_MALLOC_ASYNC */
/* #undef KOKKOS_ENABLE_IMPL_CUDA_UNIFIED_MEMORY */
/* #undef KOKKOS_ENABLE_HIP_RELOCATABLE_DEVICE_CODE */
/* #undef KOKKOS_ENABLE_HIP_MULTIPLE_KERNEL_INSTANTIATIONS */
/* #undef KOKKOS_ENABLE_IMPL_HIP_MALLOC_ASYNC */
/* #undef KOKKOS_ENABLE_SYCL_RELOCATABLE_DEVICE_CODE */
/* #undef KOKKOS_IMPL_SYCL_DEVICE_GLOBAL_SUPPORTED */
/* #undef KOKKOS_ENABLE_OPENACC_FORCE_HOST_AS_DEVICE */
/* #undef KOKKOS_ENABLE_IMPL_HPX_ASYNC_DISPATCH */
/* #undef KOKKOS_ENABLE_DEBUG */
/* #undef KOKKOS_ENABLE_DEBUG_DUALVIEW_MODIFY_CHECK */
/* #undef KOKKOS_ENABLE_DEBUG_BOUNDS_CHECK */
/* #undef KOKKOS_ENABLE_TUNING */
#define KOKKOS_ENABLE_DEPRECATED_CODE_4
#define KOKKOS_ENABLE_DEPRECATION_WARNINGS
/* #undef KOKKOS_ENABLE_LARGE_MEM_TESTS */
#define KOKKOS_ENABLE_COMPLEX_ALIGN
/* #undef KOKKOS_OPT_RANGE_AGGRESSIVE_VECTORIZATION */
/* #undef KOKKOS_ENABLE_AGGRESSIVE_VECTORIZATION */
#define KOKKOS_ENABLE_IMPL_MDSPAN
#define KOKKOS_ENABLE_IMPL_REF_COUNT_BRANCH_UNLIKELY
/* #undef KOKKOS_ENABLE_IMPL_VIEW_OF_VIEWS_DESTRUCTOR_PRECONDITION_VIOLATION_WORKAROUND */
/* #undef KOKKOS_ENABLE_ATOMICS_BYPASS */

/* TPL Settings */
/* #undef KOKKOS_ENABLE_HWLOC */
#define KOKKOS_ENABLE_LIBDL
/* #undef KOKKOS_ENABLE_LIBQUADMATH */
/* #undef KOKKOS_ENABLE_ONEDPL */
/* #undef KOKKOS_ENABLE_ROCTHRUST */

/* #undef KOKKOS_ARCH_ARMV80 */
/* #undef KOKKOS_ARCH_ARMV8_THUNDERX */
/* #undef KOKKOS_ARCH_ARMV81 */
/* #undef KOKKOS_ARCH_ARMV8_THUNDERX2 */
/* #undef KOKKOS_ARCH_ARMV9_GRACE */
/* #undef KOKKOS_ARCH_A64FX */
/* #undef KOKKOS_ARCH_AVX */
/* #undef KOKKOS_ARCH_AVX2 */
/* #undef KOKKOS_ARCH_AVX512XEON */
/* #undef KOKKOS_ARCH_ARM_NEON */
/* #undef KOKKOS_ARCH_KNC */
/* #undef KOKKOS_ARCH_AVX512MIC */
/* #undef KOKKOS_ARCH_POWER7 */
/* #undef KOKKOS_ARCH_POWER8 */
/* #undef KOKKOS_ARCH_POWER9 */
/* #undef KOKKOS_ARCH_RISCV_SG2042 */
/* #undef KOKKOS_ARCH_RISCV_RVA22V */
/* #undef KOKKOS_ARCH_INTEL_GEN */
/* #undef KOKKOS_ARCH_INTEL_DG1 */
/* #undef KOKKOS_ARCH_INTEL_GEN9 */
/* #undef KOKKOS_ARCH_INTEL_GEN11 */
/* #undef KOKKOS_ARCH_INTEL_GEN12LP */
/* #undef KOKKOS_ARCH_INTEL_XEHP */
/* #undef KOKKOS_ARCH_INTEL_PVC */
/* #undef KOKKOS_ARCH_INTEL_GPU */
/* #undef KOKKOS_ARCH_KEPLER */
/* #undef KOKKOS_ARCH_KEPLER30 */
/* #undef KOKKOS_ARCH_KEPLER32 */
/* #undef KOKKOS_ARCH_KEPLER35 */
/* #undef KOKKOS_ARCH_KEPLER37 */
/* #undef KOKKOS_ARCH_MAXWELL */
/* #undef KOKKOS_ARCH_MAXWELL50 */
/* #undef KOKKOS_ARCH_MAXWELL52 */
/* #undef KOKKOS_ARCH_MAXWELL53 */
/* #undef KOKKOS_ARCH_PASCAL */
/* #undef KOKKOS_ARCH_PASCAL60 */
/* #undef KOKKOS_ARCH_PASCAL61 */
/* #undef KOKKOS_ARCH_VOLTA */
/* #undef KOKKOS_ARCH_VOLTA70 */
/* #undef KOKKOS_ARCH_VOLTA72 */
/* #undef KOKKOS_ARCH_TURING75 */
#define KOKKOS_ARCH_AMPERE
/* #undef KOKKOS_ARCH_AMPERE80 */
#define KOKKOS_ARCH_AMPERE86
/* #undef KOKKOS_ARCH_ADA89 */
/* #undef KOKKOS_ARCH_HOPPER */
/* #undef KOKKOS_ARCH_HOPPER90 */
/* #undef KOKKOS_ARCH_AMD_ZEN */
/* #undef KOKKOS_ARCH_AMD_ZEN2 */
/* #undef KOKKOS_ARCH_AMD_ZEN3 */
/* #undef KOKKOS_ARCH_AMD_GFX906 */
/* #undef KOKKOS_ARCH_AMD_GFX908 */
/* #undef KOKKOS_ARCH_AMD_GFX90A */
/* #undef KOKKOS_ARCH_AMD_GFX940 */
/* #undef KOKKOS_ARCH_AMD_GFX942 */
/* #undef KOKKOS_ARCH_AMD_GFX942_APU */
/* #undef KOKKOS_ARCH_AMD_GFX1030 */
/* #undef KOKKOS_ARCH_AMD_GFX1100 */
/* #undef KOKKOS_ARCH_AMD_GFX1103 */
/* #undef KOKKOS_ARCH_AMD_GPU */
/* #undef KOKKOS_ARCH_VEGA */
/* #undef KOKKOS_ARCH_VEGA906 */
/* #undef KOKKOS_ARCH_VEGA908 */
/* #undef KOKKOS_ARCH_VEGA90A */
/* #undef KOKKOS_ARCH_NAVI */
/* #undef KOKKOS_ARCH_NAVI1030 */
/* #undef KOKKOS_ARCH_NAVI1100 */

/* #undef KOKKOS_IMPL_32BIT */

```

### PR DESCRIPTION
**Pull request by pzehner**
This PR aims to solve an issue where a multidimensional range of 4 or more is incorrectly iterated, leading to some iterations being evaluated more than once.

Fixes #7697.

### Context

I'd like first to give a bit of context. Kokkos encodes `MDRangePolicy` dimensions within Cuda $x$, $y$, and $z$ dimensions:

| Rank | Dimensions encoded in $x$ | Dimensions encoded in $y$ | Dimensions encoded in $z$ |
|-|-|-|-|
| 2 | 1 | 2 | |
| 3 | 1 | 2 | 3 |
| 4 | 1, 2 | 3 | 4 |
| 5 | 1, 2 | 3, 4 | 5 |
| 6 | 1, 2 | 3, 4 | 5, 6 |

Let us take rank 4 by instance, and use the Cuda backend.

Here, this means that the number of threads per block in $x$ is the product of the tiles for dimensions 1 and 2, and that the number of blocks per grid in $x$ is the product of the number of tiles for dimensions 1 and 2. As Cuda limits the number of threads per block and the number of blocks per grid, Kokkos checks the number of threads per block, and limits the number of blocks per grid. This limitation comes in play if the iteration range exceeds the number of threads of the device. Note that the Cuda limits are not the same on the $x$, $y$, and $z$ dimensions. This step, which is named *packing* in the issue, [takes place on the host](https://github.com/kokkos/kokkos/blob/3a1d9e828c6601b96d8978fa8d1a7c68114bb24d/core/src/Cuda/Kokkos_Cuda_Parallel_MDRange.hpp#L160-L174), and the limits are [fetched from the Cuda API](https://github.com/kokkos/kokkos/blob/3a1d9e828c6601b96d8978fa8d1a7c68114bb24d/core/src/Cuda/Kokkos_Cuda_Parallel_MDRange.hpp#L98-L99).

Then, the threads on the device will execute for-loops to handle the packed dimensions 1 and 2, and to handle the possibly exceeding iteration range. Depending on the inner iteration order, the threads iterate over the $z$ blocks, then over the $y$ blocks, then over the "virtual blocks" for dimension 2, then over the "virtual blocks" for dimension 1 (here for the left iteration order). The "virtual blocks" are a partitioning of the $x$ dimension to contain dimensions 1 and 2 in it. The combined number of "virtual blocks" must fit within the maximum number of blocks per grid on the $x$ dimension. Their number is deduced from the number of tiles for dimensions 1 and 2 and from the maximum number of blocks per grid on the $x$ dimension. This step, named *unpacking* in the issue, [takes place on the device](https://github.com/kokkos/kokkos/blob/3a1d9e828c6601b96d8978fa8d1a7c68114bb24d/core/src/impl/KokkosExp_IterateTileGPU.hpp#L284-L330), where the Cuda API cannot be fetched.

Now, the problem reported in #7697 is that when performing the packing, the number of blocks per grid on the $x$ dimension is fetched from the [Cuda API](https://docs.nvidia.com/cuda/cuda-c-programming-guide/#features-and-technical-specifications-technical-specifications-per-compute-capability), and the value is $2^{31} - 1$. But when performing the unpacking, the number of blocks per grid for any dimension is [hardcoded](https://github.com/kokkos/kokkos/blob/3a1d9e828c6601b96d8978fa8d1a7c68114bb24d/core/src/impl/KokkosExp_IterateTileGPU.hpp#L279) to $2^{16} - 1$. When the combined number of tiles for dimension 1 and 2 is larger than $2^{16} - 1$, this difference makes the "virtual blocks" smaller than what they should, and makes the threads iterate more than necessary, leading to some iterations being evaluated more than once. Note that the maximum number of blocks per grid for the $x$ dimension [used to be](https://en.wikipedia.org/wiki/CUDA#Technical_specification) $2^{16} - 1$ up to the last CC 2.x.

For higher ranks, the number of blocks per grid on the $y$ and $z$ dimensions is $2^{16} - 1$ both when fetched from the Cuda API, and for the hardcoded value. So the described problem will not happen if the number of tiles for dimension 3 and more is larger than $2^{16} - 1$.

The packing code is specific to each device backend (Cuda, HIP, and SYCL). The Cuda and HIP backends perform similarly. The SYCL backend, on the other hand, delegates the checks and the limitations to SYCL itself, according to a discussion with @masterleinad, for the reason we will see later.

The unpacking code is common to the three backends.

### Reproduction of the bug

This PR adds tests which check that views of rank 4 and higher with a large enough number of elements for each dimension are correctly iterated, for any iteration order (i.e., LL, LR, LR, RR). To this aim, each element of the view is atomically incremented, then the minimum and maximum value of the view is verified to be 1. The problem reported in the issue was reproduced for the Cuda backend for:

| Rank | Number of elements of the view | Inner iteration order |
|-|-|-|
| 4 | $2^{20} \times 1 \times 1 \times 1$ | Right |
| 4 | $1 \times 2^{20} \times 1 \times 1$ | Left |
| 5 | $2^{20} \times 1 \times 1 \times 1 \times 1$ | Right |
| 5 | $1 \times 2^{20} \times 1 \times 1 \times 1$ | Left |
| 6 | $2^{20} \times 1 \times 1 \times 1 \times 1 \times 1$ | Right |
| 6 | $1 \times 2^{20} \times 1 \times 1 \times 1 \times 1$ | Left |

Where $2^{20}$ is a large number of elements suggested in the issue.

Experimentally, the minimum number of elements to obtain the bug were found to be, on an NVIDIA A500 GPU:

| Rank | Number of elements of the view | Tiling | Inner iteration order |
|-|-|-|-|
| 4 | $(2^{16} - 1) \cdot 2 + 1 \times 1 \times 1 \times 1$ | $16 \times 2 \times 2 \times 2$ | Right |
| 4 | $1 \times (2^{16} - 1) \cdot 2 + 1 \times 1 \times 1$ | $2 \times 2 \times 2 \times 16$ | Left |
| 5 | $(2^{16} - 1) \cdot 2 + 1 \times 1 \times 1 \times 1 \times 1$ | $16 \times 2 \times 2 \times 2 \times 2$ | Right |
| 5 | $1 \times (2^{16} - 1) \cdot 2 + 1 \times 1 \times 1 \times 1$ | $2 \times 2 \times 2 \times 2 \times 16$ | Left |
| 6 | $2^{16} \times 1 \times 1 \times 1 \times 1 \times 1$ | $16 \times 2 \times 2 \times 2 \times 2 \times 2$ | Right |
| 6 | $1 \times (2^{16} - 1) \cdot 2 + 1 \times 1 \times 1 \times 1 \times 1$ | $2 \times 2 \times 2 \times 2 \times 2 \times 16$ | Left |

When the expected number of elements for the largest dimension was evaluated to $(2^{16} - 1) \times 16 + 1 \lessapprox 2^{20}$ (i.e. hardcoded maximum number of blocks per grid times the size of the tile plus one). *Note that I am not sure of this value.*

Note the different number of elements for rank 6 and iteration order right, for which the reason could not be identified.

### Reason of the bug

The problem is that the maximum number of blocks per grid (aka maximum grid size) for the code executed on the device is hardcoded with one single value for all dimensions, while the actual value varies by not only the dimension but also the programing model:

| Programming model | Max. num. of blocks per grid for $x$ | Max. num of blocks per grid for $y$ | Max. num. of blocks per grid for $z$ | Note |
|-|-|-|-|-|
| Cuda | $2^{31} - 1$ | $2^{16} - 1 $ | $2^{16} - 1 $ | Stable from CC 5.0 to 12.0 (latest) |
| HIP | $2^{32} - 1$, $2^{31} - 1$ | $2^{32} - 1$, $2^{16}$ | $2^{32} - 1$, $2^{16}$ | Discrepancy between the specs and the API |
| SYCL | | | | Not specified in the specs |

Sources for [Cuda](https://docs.nvidia.com/cuda/cuda-c-programming-guide/#features-and-technical-specifications-technical-specifications-per-compute-capability); for HIP and SYCL, see the details below.

Consequently, the problem also occurs for HIP and for SYCL (this was tested). However, due to the uncertainties to fetch the accurate maximum number of blocks per grid for these programming models (see details below), we will first only fix the issue for the Cuda backend. We note that the value has been constant since at least CC 3.0.

<details>
<summary>
HIP case
</summary>

The [HIP documentation](https://rocm.docs.amd.com/projects/HIP/en/latest/reference/hardware_features.html) gives $2^{32} - 1$ for $x$, $y$, and $z$, but we got test failures, with iterations not being evaluated this time.

We directly checked `Kokkos::DefaultExecutionSpace().hip_device_prop().maxGridSize` with the following test code:

```cpp
#include <Kokkos_Core.hpp>

int main() {
    Kokkos::ScopeGuard kokkos;

#if defined(KOKKOS_ENABLE_CUDA)
    auto const maxblocks = Kokkos::DefaultExecutionSpace().cuda_device_prop().maxGridSize;
#elif defined(KOKKOS_ENABLE_HIP)
    auto const maxblocks = Kokkos::DefaultExecutionSpace().hip_device_prop().maxGridSize;
#else
#error "Programming model not supported"
#endif

    Kokkos::printf("Maxblocks: %d, %d, %d\n", maxblocks[0], maxblocks[1], maxblocks[2]);
}
```

On MI250 and MI300A, we obtained values which are much closer to what Cuda allows:

```text
Maxblocks: 2147483647, 65536, 65536
```

In other words, $2^{31} - 1$, $2^{16}$, and $2^{16}$ (note the difference of 1 with Cuda for $y$ and $z$, however).

@Rombur discussed about this difference with an AMD engineer, who reported he successfully launched a dummy kernel on one thread per block and $2^{32} - 1$ blocks per grid, for any dimension. According to him, the HIP API does not give accurate values. He is currently investigating the reasons why.

@Rombur opened an [issue](https://github.com/ROCm/clr/issues/140) on ROCm repository about this problem.

</details>

<details>
<summary>
SYCL case
</summary>

Note that SYCL does not specify the maximum number of blocks per grid in its specs, and it's not possible to query them officially. There is a [proposal to include them in the specs](https://github.com/KhronosGroup/SYCL-Docs/issues/386), and a [workaround to query them using OneAPI experimental functions](https://github.com/intel/llvm/blob/sycl/sycl/doc/extensions/experimental/sycl_ext_oneapi_max_work_group_query.md). However, the experimental function gives results which are in contradiction with what `ze_info` gives.

Call to `ze_info`:

```text
 Device Name                                     Intel(R) Data Center GPU Max 1550
  Device Type                                     GPU
  Vendor ID                                       0x8086
  Device ID                                       0xbd6
  Subdevice ID                                    0x0
  Core Clock Rate                                 1600MHz
  Maximum Memory Allocation Size                  130535129088 (121.57GiB)
  Maximum Hardware Contexts                       65536
  Maximum Command Queue Priority                  0
  Number Threads Per EU                           8
  Physical EU SIMD Width                          16
  Number EU Per SubSlice                          8
  Number SubSlices Per Slice                      56
  Number Slices                                   2
  Timer Resolution                                12500000clks
  Compute properties:
    Maximum workgroup size                        1024
    Maximum workgroup sizes (X, Y, Z)             1024x1024x1024
    Maximum workgroup count (X, Y, Z)             4294967295x4294967295x4294967295
    Maximum Shared Local Memory Size Per Group    131072 (128KiB)
    Subgroup Sizes Supported                      16 32
  Module properties:
    SPIR-V supported version                      1.3
    Flags                                         fp16 fp64 int64_atomics dp4a
    fp16 properties:
      Denormals                                   yes
      Infinity and NaN                            yes
      Round to nearest even                       yes
      Round to zero                               yes
      Round to infinity                           yes
      IEEE754-2008 fused multiply-add             yes
      Correctly-rounded Div Sqrt                  no
      Support is emulated in software             no
    fp32 properties:
      Denormals                                   yes
      Infinity and NaN                            yes
      Round to nearest even                       yes
      Round to zero                               yes
      Round to infinity                           yes
      IEEE754-2008 fused multiply-add             yes
      Correctly-rounded Div Sqrt                  yes
      Support is emulated in software             no
    fp64 properties:
      Denormals                                   yes
      Infinity and NaN                            yes
      Round to nearest even                       yes
      Round to zero                               yes
      Round to infinity                           yes
      IEEE754-2008 fused multiply-add             yes
      Correctly-rounded Div Sqrt                  yes
      Support is emulated in software             no
    Maximum kernel arguments size                 2048 (2KiB)
    Print buffer size                             4194304 (4MiB)
  Device Name                                     Intel(R) Data Center GPU Max 1550
  Device Type                                     GPU
  Vendor ID                                       0x8086
  Device ID                                       0xbd6
  Subdevice ID                                    0x0
  Core Clock Rate                                 1600MHz
  Maximum Memory Allocation Size                  130535129088 (121.57GiB)
  Maximum Hardware Contexts                       65536
  Maximum Command Queue Priority                  0
  Number Threads Per EU                           8
  Physical EU SIMD Width                          16
  Number EU Per SubSlice                          8
  Number SubSlices Per Slice                      56
  Number Slices                                   2
  Timer Resolution                                12500000clks
  Compute properties:
    Maximum workgroup size                        1024
    Maximum workgroup sizes (X, Y, Z)             1024x1024x1024
    Maximum workgroup count (X, Y, Z)             4294967295x4294967295x4294967295
    Maximum Shared Local Memory Size Per Group    131072 (128KiB)
    Subgroup Sizes Supported                      16 32
  Module properties:
    SPIR-V supported version                      1.3
    Flags                                         fp16 fp64 int64_atomics dp4a
    fp16 properties:
      Denormals                                   yes
      Infinity and NaN                            yes
      Round to nearest even                       yes
      Round to zero                               yes
      Round to infinity                           yes
      IEEE754-2008 fused multiply-add             yes
      Correctly-rounded Div Sqrt                  no
      Support is emulated in software             no
    fp32 properties:
      Denormals                                   yes
      Infinity and NaN                            yes
      Round to nearest even                       yes
      Round to zero                               yes
      Round to infinity                           yes
      IEEE754-2008 fused multiply-add             yes
      Correctly-rounded Div Sqrt                  yes
      Support is emulated in software             no
    fp64 properties:
      Denormals                                   yes
      Infinity and NaN                            yes
      Round to nearest even                       yes
      Round to zero                               yes
      Round to infinity                           yes
      IEEE754-2008 fused multiply-add             yes
      Correctly-rounded Div Sqrt                  yes
      Support is emulated in software             no
    Maximum kernel arguments size                 2048 (2KiB)
    Print buffer size                             4194304 (4MiB
```

So, $2^{32} - 1$, on an Intel GPU Max 1550.

Use of experimental function:

```text
Intel(R) Data Center GPU Max 1550
Max number groups: x_max: 2147483647 y_max: 2147483647 z_max: 2147483647
Max global number groups: 2147483647
```

So, $2^{31} - 1$, on an Intel GPU Max 1550 as well.

We found out that the [implementation of the function](https://github.com/intel/llvm/blob/c0c91aa2235f7ba0f2aa3603667890ebe626b2c2/sycl/source/detail/device_info.hpp#L1120) just returns `std::numeric_limits<int>()` invariably.

We consequently tested to reach the limit manually with a SYCL code. Below is a code that runs a parallel loop with one thread per work group (or one thread per block in Cuda terminology), for a given loop size:

```cpp
#include <iostream>
#include <sycl/sycl.hpp>

//##define SIZE 2147483647  // 2^31 - 1
//#define SIZE 2147483648  // 2^31
#define SIZE 4294967295  // 2^32 - 1
//#define SIZE 4294967296  // 2^32

int main() {
    sycl::queue Q;
    std::cout << "Using device: " << Q.get_device().get_info<sycl::info::device::name>() << "\n";

    const sycl::range global_size{SIZE};
    const sycl::range local_size{1};

    Q.submit([&](sycl::handler &cgh) {
        cgh.parallel_for(
            sycl::nd_range{global_size, local_size},
            [=](auto itm) {
                auto a = 1+1;
        }   // end lambda in parallel_for
        );      // end parallel_for nd_range
    }).wait();         // end Q.submit

    return 0;
}
```

When the size is strictly higher than $2^{31} - 1$, the compiled code crashes, requesting to use `-fno-sycl-id-queries-fit-in-int` during compilation. On an Intel GPU Max 1550, we obtained the following behavior:

| Size | Without `-fno-sycl-id-queries-fit-in-int` | With `-fno-sycl-id-queries-fit-in-int` |
|-|-|-|
| $2^{31} - 1$ | Run | Run |
| $2^{31}$ | Crash | Run |
| $2^{32} - 1$ | Crash | Run |
| $2^{32} $ | Crash | Crash |

So we conclude that, at least for this GPU, the hardware limitation is $2^{32} - 1$, but there is a software limit of $2^{31} - 1$.

Eventually, as extracted above from a discussion with masterleinad, since packing/unpacking is not performed for SYCL, we do not need to worry about this backend anymore.

</details>

### Fix

This PR proposes a fix for the Cuda backend only, by differentiating the maximum number of blocks per grid for the $x$ dimension ($2^{31} - 1$) from the other two ($2^{16} - 1$), during the unpacking step on the device. It still relies on hardcoded values, which are extracted from the Cuda specs (listed above) and are checked against API values.

To avoid duplication of code, the hardcoded values are defined only once in the file.

With the provided fix, the tests introduced by the PR pass.

### Future fix

A better solution is to not rely on hardcoded values, and to get the values fetched from the API on the device instead. This would be proposed in a new PR.

### Progress

- [x] Add tests:
  - [x] Rank 4;
  - [x] Rank 5;
  - [x] Rank 6;
- [x] Fix:
  - [x] Rank 4;
  - [x] Rank 5;
  - [x] Rank 6;
- [x] Set hard-coded values:
  - [x] For Cuda;
  - ~For HIP~ (discrepancies between documentation and observed values); and
  - ~For SYCL~ (cannot be fetched).

### CODE REVIEW

File: core/src/impl/KokkosExp_IterateTileGPU.hpp [hunk 1]
```diff
@@ -276,17 +276,18 @@ struct DeviceIterateTile<4, PolicyType, Functor, Tag> {
       : m_policy(policy_), m_func(f_) {}
 #endif
 
-  static constexpr index_type max_blocks = 65535;
+  static constexpr index_type max_blocks_x = 2147483647;
+  static constexpr index_type max_blocks   = 65535;
```
Comment (masterleinad) [inline core/src/impl/KokkosExp_IterateTileGPU.hpp:280]: Note that this file is sued for Cuda, HIP and SYCL so make sure this works for all three backends.

Comment (pzehner) [reply core/src/impl/KokkosExp_IterateTileGPU.hpp:280]: It may not work if the actual max grid sizes are different, indeed, I'll check that.

Comment (pzehner) [reply core/src/impl/KokkosExp_IterateTileGPU.hpp]: Set for Cuda and HIP, but SYCL remains to be done.

Comment (masterleinad) [reply core/src/impl/KokkosExp_IterateTileGPU.hpp]: The SYCL implementation for MDRangePolicy currently assumes that there is no limit so just set it to the maximum value for `index_type`.
We should also add the test from the issue.

File: core/src/impl/KokkosExp_IterateTileGPU.hpp [hunk 2]
```diff
@@ -38,6 +38,19 @@ struct EmulateCUDADim3 {
 };
 #endif
 
+#if defined(KOKKOS_ENABLE_CUDA)
+#define MAX_BLOCKS_X 2147483647;
```
Comment (Rombur) [inline core/src/impl/KokkosExp_IterateTileGPU.hpp:42]: You should use a different name, maybe something like `KOKKOS_IMPL_MAX_BLOCKS_X`. Also the `;` is unnecessary and it triggers an error with HIP at line 292.

Comment (pzehner) [reply core/src/impl/KokkosExp_IterateTileGPU.hpp:42]: Ah, shoo, I'll fix that.

File: core/src/impl/KokkosExp_IterateTileGPU.hpp [hunk 3]
```diff
@@ -38,6 +38,19 @@ struct EmulateCUDADim3 {
...
+#define MAX_BLOCKS 65535
+#elif defined(KOKKOS_ENABLE_HIP)
+#define MAX_BLOCKS_X 4294967295
+#define MAX_BLOCKS 4294967295
+#elif defined(KOKKOS_ENABLE_SYCL)
+#define MAX_BLOCKS_X 4294967295
+#define MAX_BLOCKS 4294967295
+#else
+#error("Programming model not supported")
+#endif
```
Comment (masterleinad) [inline core/src/impl/KokkosExp_IterateTileGPU.hpp:52]: I'd rather define these constants in a separate namespace as global variables or as static variables in a class.

**Comment by crtrott** [comment]
I don't get how this fixes anything other than by making one of the iteration numbers really large, so if you don't exceed it everything is fine. Wouldn't this still fail if one were to use say int64 for the index type and exceed the 2B iteration range?

**Comment by crtrott** [comment]
I.e. I do not see how the underlying fault in the computation is fixed.

File: core/src/impl/KokkosExp_IterateTileGPU.hpp (hunk 3 above)
Comment (pzehner) [reply core/src/impl/KokkosExp_IterateTileGPU.hpp:52]: The value used to be defined for each `DeviceIterateTile` sruct, but I thought it was a lot of duplicated code. What namespace are you thinking about? `Kokkos::Constants`?

File: core/src/impl/KokkosExp_IterateTileGPU.hpp [hunk 4]
```diff
@@ -38,6 +38,19 @@ struct EmulateCUDADim3 {
...
+#define MAX_BLOCKS 65535;
+#elif defined(KOKKOS_ENABLE_HIP)
+#define MAX_BLOCKS_X 4294967295;
+#define MAX_BLOCKS 4294967295;
+#elif defined(KOKKOS_ENABLE_SYCL)
+#define MAX_BLOCKS_X 4294967295;
+#define MAX_BLOCKS 4294967295;
+#else
+#error("Programming model not supported")
+#endif
```
[the remark this answers is not in the document]
Comment (pzehner) [reply core/src/impl/KokkosExp_IterateTileGPU.hpp]: For Cuda and HIP, these limits were obtained from the documentation. As far as I know, they are not specified as the maximum value of a specific type.

**Comment by pzehner** [comment]
@crtrott I tried to do a test using `int64` and an iteration range of 2,200,000,000 elements on an A100. The test pass successfully.

File: core/src/impl/KokkosExp_IterateTileGPU.hpp (hunk 3 above)
Comment (masterleinad) [reply core/src/impl/KokkosExp_IterateTileGPU.hpp:52]: Maybe, `Kokkos::Impl::mdrange_max_blocks[_x]` or `Kokkos::Impl::iterate_tile_gpu_max_blocks[_x]` or with an extra namespace like `Kokkos::Impl::MDRange::max_blocks[_x]` or `Kokkos::Impl::IterateTileGPU::max_blocks[_x]`. I'd probably go for one of the first two.

Comment (pzehner) [reply core/src/impl/KokkosExp_IterateTileGPU.hpp]: Ok, I used your first proposal.

File: core/src/impl/KokkosExp_IterateTileGPU.hpp (hunk 2 above)
Comment (pzehner) [reply core/src/impl/KokkosExp_IterateTileGPU.hpp]: Fixed.

**Comment by pzehner** [comment]
I updated the description to be as detailed as possible, in order to make the problem and the fix more clear.

File: core/unit_test/TestMDRange_e.hpp [hunk 5]
```diff
@@ -24,6 +24,12 @@ TEST(TEST_CATEGORY, mdrange_4d) {
   TestMDRange_4D<TEST_EXECSPACE>::test_reduce4(100, 10, 10, 10);
 #endif
   TestMDRange_4D<TEST_EXECSPACE>::test_for4(100, 10, 10, 10);
+#ifdef KOKKOS_ENABLE_CUDA
+  TestMDRange_4D<TEST_EXECSPACE>::test_for4_eval_once(1024 * 1024, 1, 1, 1);
+  TestMDRange_4D<TEST_EXECSPACE>::test_for4_eval_once(1, 1024 * 1024, 1, 1);
+  TestMDRange_4D<TEST_EXECSPACE>::test_for4_eval_once(1, 1, 1024 * 1024, 1);
+  TestMDRange_4D<TEST_EXECSPACE>::test_for4_eval_once(1, 1, 1, 1024 * 1024);
+#endif
```
Comment (masterleinad) [inline core/unit_test/TestMDRange_e.hpp:32]: What happens with other backends?

Comment (pzehner) [reply core/unit_test/TestMDRange_e.hpp:32]: It fails for HIP when I tested it. I could not for SYCL.

Comment (pzehner) [reply core/unit_test/TestMDRange_e.hpp:32]: Just asked a colleague to run it on SYCL, it fails too.

File: core/unit_test/TestMDRange.hpp [hunk 6]
```diff
@@ -2057,6 +2074,54 @@ struct TestMDRange_4D {
...
+      printf(
+          " Errors in test_for4_eval_once for shape (%d, %d, %d, %d) and "
+          "iterate %s; min = %d, max = %d\n\n",
+          N0, N1, N2, N3, iterate_msg, min_max_value.min_val,
+          min_max_value.max_val);
+    }
+
+    ASSERT_EQ(min_max_value.min_val, 1);
+    ASSERT_EQ(min_max_value.max_val, 1);
+    ASSERT_EQ(sum_value, N0 * N1 * N2 * N3);
```
Comment (masterleinad) [inline core/unit_test/TestMDRange.hpp:2123]:
```suggestion
    ASSERT_EQ(min_max_value.min_val, 1) << "error for shape (" << N0, N1, N2, N3 << ") and iteration " << iterate_msg;
    ASSERT_EQ(min_max_value.max_val, 1) << "error for shape (" << N0, N1, N2, N3 << ") and iteration " << iterate_msg;
    ASSERT_EQ(sum_value, N0 * N1 * N2 * N3) << "error for shape (" << N0, N1, N2, N3 << ") and iteration " << iterate_msg;
```
similarly elsewhere.

File: core/unit_test/TestMDRange.hpp [hunk 7]
```diff
@@ -2057,6 +2074,54 @@ struct TestMDRange_4D {
...
+    using range_type =
+        typename Kokkos::MDRangePolicy<ExecSpace, Kokkos::Rank<4, Outer, Inner>,
+                                       Kokkos::IndexType<int>, AtomicTag>;
+    using point_type = typename range_type::point_type;
+
+    range_type range(point_type{{0, 0, 0, 0}}, point_type{{N0, N1, N2, N3}});
+
+    TestMDRange_4D functor(N0, N1, N2, N3);
+
+    parallel_for(range, functor);
```
Comment (masterleinad) [inline core/unit_test/TestMDRange.hpp:2108]: I don't like the unqualified calls here too much but I see this is pre-existent.

File: core/src/impl/KokkosExp_IterateTileGPU.hpp [hunk 8]
```diff
@@ -38,6 +38,16 @@ struct EmulateCUDADim3 {
 };
 #endif
 
+#if defined(KOKKOS_ENABLE_CUDA)
+// see:
+// https://docs.nvidia.com/cuda/cuda-c-programming-guide/#features-and-technical-specifications-technical-specifications-per-compute-capability
+constexpr int mdrange_max_blocks_x = 2147483647;  // 2^31 - 1
+constexpr int mdrange_max_blocks   = 65535;       // 2^16 - 1
```
Comment (masterleinad) [inline core/src/impl/KokkosExp_IterateTileGPU.hpp:45]: Why don't you just use these constants in `core/src/Cuda/Kokkos_Cuda_Parallel_MDRange.hpp` and check that they don't exceed ` m_rp.space().cuda_device_prop().maxGridSize;`?

File: core/src/impl/KokkosExp_IterateTileGPU.hpp [hunk 9]
```diff
@@ -272,22 +288,23 @@ struct DeviceIterateTile<4, PolicyType, Functor, Tag> {
...
   void exec_range() const {
+    // LL
     if (PolicyType::inner_direction == Iterate::Left) {
-      const index_type temp0  = m_policy.m_tile_end[0];
-      const index_type temp1  = m_policy.m_tile_end[1];
-      const index_type numbl0 = (temp0 <= max_blocks ? temp0 : max_blocks);
+      const index_type temp0 = m_policy.m_tile_end[0];
+      const index_type temp1 = m_policy.m_tile_end[1];
+      const index_type numbl0 =
+          (temp0 <= mdrange_max_blocks_x ? temp0 : mdrange_max_blocks_x);
```
[the remark this answers is not in the document]
Comment (pzehner) [reply core/src/impl/KokkosExp_IterateTileGPU.hpp:302]: I plan to do a PR to add comments to `KokkosExp_IterateTileGPU.hpp`, maybe it would be a good place to change this there. I would like to keep this PR focused on fixing the corresponding issue.

File: core/unit_test/TestMDRange.hpp (hunk 6 above)
Comment (pzehner) [reply core/unit_test/TestMDRange.hpp:2123]: Are you sure the `"error for shape (" << N0, N1, N2, N3 << ") and iteration "` syntax is valid?

File: core/unit_test/TestMDRange.hpp (hunk 7 above)
Comment (pzehner) [reply core/unit_test/TestMDRange.hpp:2108]: I tried to keep the consistency of the file.

File: core/src/impl/KokkosExp_IterateTileGPU.hpp (hunk 8 above)
Comment (pzehner) [reply core/src/impl/KokkosExp_IterateTileGPU.hpp:45]: As I said in the (long) description of this PR, this is a temporary fix. I plan to improve it in a next PR.

File: core/unit_test/TestMDRange.hpp (hunk 6 above)
Comment (masterleinad) [reply core/unit_test/TestMDRange.hpp:2123]: It's not valid syntax. My point is that you can adjust append to `ASSERT_EQ` instead of printing to `stdout`.

File: core/src/impl/KokkosExp_IterateTileGPU.hpp (hunk 8 above)
Comment (masterleinad) [reply core/src/impl/KokkosExp_IterateTileGPU.hpp:45]: I'd rather make these values consistent/compatible in one go since that's exactly the issue fixed here. There certainly are benefits to have the values available at compile-time and it's sufficient for us not too exceed the API values.

File: core/unit_test/TestMDRange.hpp (hunk 6 above)
Comment (pzehner) [reply core/unit_test/TestMDRange.hpp:2123]: Right. I experimented a bit, but it started to be a lot of duplicated code.

File: core/src/impl/KokkosExp_IterateTileGPU.hpp (hunk 8 above)
Comment (pzehner) [reply core/src/impl/KokkosExp_IterateTileGPU.hpp:45]: I can add this check, I guess. But this will be changed in the next PR...

Comment (masterleinad) [reply core/src/impl/KokkosExp_IterateTileGPU.hpp:45]: Again, why don't you just fix it all in one go (for Cuda) if you already know what a better solution is?

**Review by masterleinad — APPROVED** [review]
Fine with me.

File: core/src/Cuda/Kokkos_Cuda_Parallel_MDRange.hpp [hunk 10]
```diff
@@ -95,8 +95,21 @@ class ParallelFor<FunctorType, Kokkos::MDRangePolicy<Traits...>, Kokkos::Cuda> {
...
+        m_rp.space().cuda_device_prop().maxGridSize;
+
+    // maximum numebr of blocks per grid hard-coded for unpacking on device
+    const int maxblocks[3] = {mdrange_max_blocks_x, mdrange_max_blocks,
+                              mdrange_max_blocks};
+
+    // check hard-coded values are compatible with API values
+    KOKKOS_ASSERT(maxblocks[0] <= static_cast<int>(maxblocks_api[0]));
+    KOKKOS_ASSERT(maxblocks[1] <= static_cast<int>(maxblocks_api[1]));
+    KOKKOS_ASSERT(maxblocks[2] <= static_cast<int>(maxblocks_api[2]));
```
[the remark this answers is not in the document]
Comment (pzehner) [reply core/src/Cuda/Kokkos_Cuda_Parallel_MDRange.hpp:109]: Do you still want to add a better assert mechanism? This is a part of the PR I plan to remove on the next PR. I can create an issue to think about better asserts in production, if you want.

[the remark this answers is not in the document]
Comment (masterleinad) [reply core/src/Cuda/Kokkos_Cuda_Parallel_MDRange.hpp:109]: Only chanage it if there are other changes requested. I don't think we necessarily need another assertion mechanism. In most cases we want to provide custom error messages anyway and the
```
if (!condition)
  Kokkos::abort(message)
```
pattern is simple enough.

[the remark this answers is not in the document]
Comment (pzehner) [reply core/src/Cuda/Kokkos_Cuda_Parallel_MDRange.hpp:109]: Ok, I keep it in mind. I haven't had other feedback so far.

**Review by crtrott — APPROVED** [review]

**Comment by dalg24** [comment]
Please add to the 4.6 changelog
