### PR TITLE
Fix using ScratchSpace in deep_copy

### LINKED ISSUE #2723: deep_copy scalar into scratch View fails to compile
in trilinos/trilinos#6747, @tasmith4 writes:

For the following statement:

      Kokkos::deep_copy(multiDimViews[i]->get_scratch_view_1D(0), i+1);

we get this build error after updating to the latest Trilinos (develop branch):

```
/tmp/tasmit/exawind/install/intel/trilinos/include/Kokkos_CopyViews.hpp(1430): error #373: "Kokkos::ScratchMemorySpace<ExecSpace>::ScratchMemorySp
ace() [with ExecSpace=Kokkos::OpenMP]" (declared at line 79 of "/tmp/tasmit/exawind/install/intel/trilinos/include/Kokkos_ScratchSpace.hpp") is in
accessible
              typename ViewType::memory_space().name()),
              ^
          detected during instantiation of "void Kokkos::deep_copy(const Kokkos::View<DT, DP...> &, Kokkos::ViewTraits<DT, DP...>::const_value_typ
e &, std::enable_if<std::is_same<Kokkos::ViewTraits<DT, DP...>::specialize, void>::value, void>::type *) [with DT=double *, DP=<Kokkos::LayoutRigh
t, sierra::nalu::DeviceShmem, Kokkos::MemoryUnmanaged>]" at line 137 of "/tmp/tasmit/exawind/source/nalu-wind/unit_tests/UnitTestCopyAndInterleave
.C"
```

Our code has not changed recently -- is there something we need to change in how we call `Kokkos::deep_copy`?

### PR DESCRIPTION
**Pull request by masterleinad**
Fixes #2723, partially addresses #2233.
Memory spaces should have a `name()` static member function.

### CODE REVIEW

File: core/unit_test/TestDeepCopy.hpp [hunk 1]
```diff
@@ -211,4 +211,41 @@ TEST(TEST_CATEGORY, deep_copy_alignment) {
...
+
+  TestDeviceTeamPolicy policy(1, threads_per_team);
+  auto team_exec = policy.set_scratch_size(1, Kokkos::PerTeam(bytes_per_team),
+                                           Kokkos::PerThread(bytes_per_thread));
+
+  const int N = 8;
+
+  Kokkos::parallel_for(
+      team_exec,
+      KOKKOS_LAMBDA(
```
Comment (dalg24) [inline core/unit_test/TestDeepCopy.hpp]: Lambda won't work with NVCC because gtest wraps the function in a class in the body of a private member function.  Also this would need to be within a preprocessor directive that checks whether lambda are enabled :(

**Review by dhollman — COMMENTED** [review]
Why are we making this change? I thought the general trend was towards using instance methods whenever possible, since we're moving towards instances of spaces in general. I don't see a reason to make this change.

File: core/src/Kokkos_ScratchSpace.hpp [hunk 2]
```diff
@@ -91,6 +91,8 @@ class ScratchMemorySpace {
   typedef typename ExecSpace::array_layout array_layout;
   typedef typename ExecSpace::size_type size_type;
 
+  static constexpr const char* name() { return "ScratchMemorySpace"; }
```
Comment (dhollman) [inline core/src/Kokkos_ScratchSpace.hpp]: This is fine, but we don't need to scatter `::name()` all over the code just because `name()` happens to be static here. We can also get to it through the instance method

Comment (dalg24) [reply core/src/Kokkos_ScratchSpace.hpp]: Which of the specific changes proposed here do you have problem with?
They all were calling the default constructor to call `name()`.

Comment (dhollman) [reply core/src/Kokkos_ScratchSpace.hpp]: Yeah, and there's nothing wrong with that. We're allowing ourselves the freedom to make this an instance method in the future. The cost of default construct plus instance member is the same as calling the class member, so why not give ourselves that freedom in the future?

Comment (masterleinad) [reply core/src/Kokkos_ScratchSpace.hpp]: The default constructor for `ScratchMemorySpace` is private so we would need to address that as well here. 
We are not arguing about `name()` being `static` or not. Why would choosing to call it as class member restrict us?

Comment (dalg24) [reply core/src/Kokkos_ScratchSpace.hpp]: > We're allowing ourselves the freedom to make this an instance method in the future.

Fair enough.  @masterleinad would you please drop all changes but the addition of the member function to `ScratchMemorySpace`

Comment (dalg24) [reply core/src/Kokkos_ScratchSpace.hpp]: > We are not arguing about name() being static or not.

True, @dhollman it is not about how WE call it, if we declare it to be `static` we can't prevent users to call it as a static function.

Comment (dhollman) [reply core/src/Kokkos_ScratchSpace.hpp]: Yeah good point. We probably should make it an instance member, actually, to keep people from calling it as a static function wherever possible.

Also, why is the default constructor private? Do we really want to remove `default_constructible` from the memory space guarantees? If we can't do anything reasonable for the `ScratchMemorySpace` default constructor, then we probably should stop using default constructors in generic contexts, but that's a much bigger problem. Right now, all models of `Space` have default constructors.

Comment (dalg24) [reply core/src/Kokkos_ScratchSpace.hpp]: > Yeah good point. We probably should make it an instance member, actually, to keep people from calling it as a static function wherever possible.

You mean public static data member instead of a member function?

Comment (dalg24) [reply core/src/Kokkos_ScratchSpace.hpp]: > Also, why is the default constructor private? Do we really want to remove `default_constructible` from the memory space guarantees? If we can't do anything reasonable for the `ScratchMemorySpace` default constructor, then we probably should stop using default constructors in generic contexts, but that's a much bigger problem. Right now, all models of `Space` have default constructors.

I agree but I don't think it should be fixed in that PR.

Comment (masterleinad) [reply core/src/Kokkos_ScratchSpace.hpp]: We could initialize all the sizes to 0 and the pointers to `nullptr`s if you feel strongly about it.
In my opinion, there is no strong reason to make it instance member function now and would make all class member functions `static` that can be.

Comment (crtrott) [reply core/src/Kokkos_ScratchSpace.hpp]: All the `name()` functions of spaces are static member functions. This needs to be a static member function too. And no we cannot change this to a non-static member function, this is part of the public interface and is used in user code.

**Review by dalg24 — APPROVED** [review]
