### PR TITLE
Fix Trilinos nightly failure due to `create_mirror*` refactor

### LINKED ISSUE #7125: Trilinos nightly failure, create_mirror_view incompatibilities with Sacado
**Describe the bug**

Nightly builds of Trilinos fail to compile with apparent incompatibilities following `create_mirror_view` updates with #7061

**Output snip**:
```
17:43:17 /home/jenkins/blake-new/workspace/KokkosEco_Trilinos_Blake_LLVM1507_Serial_debug/Trilinos/packages/sacado/test/UnitTests/Fad_Kokkos_CommTests_Serial.cpp:54:1: error: no matching function for call to 'create_mirror_view'
17:43:17 FAD_KOKKOS_COMM_TESTS_SERIAL(Fad_DFadType, Fad_DFad)
17:43:17 ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
17:43:17 /home/jenkins/blake-new/workspace/KokkosEco_Trilinos_Blake_LLVM1507_Serial_debug/Trilinos/packages/sacado/test/UnitTests/Fad_CommTests.hpp:1211:3: note: expanded from macro 'FAD_KOKKOS_COMM_TESTS_SERIAL'
17:43:17   FAD_KOKKOS_COMM_TESTS_DEV(FadType, FAD, Serial)
17:43:17   ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
17:43:17 /home/jenkins/blake-new/workspace/KokkosEco_Trilinos_Blake_LLVM1507_Serial_debug/Trilinos/packages/sacado/test/UnitTests/Fad_CommTests.hpp:930:22: note: expanded from macro 'FAD_KOKKOS_COMM_TESTS_DEV'
17:43:17   HostViewType h_x = Kokkos::create_mirror_view(x);                     \
17:43:17                      ^~~~~~~~~~~~~~~~~~~~~~~~~~
17:43:17 /home/jenkins/blake-new/workspace/KokkosEco_Trilinos_Blake_LLVM1507_Serial_debug/Trilinos/kokkos/core/src/Kokkos_CopyViews.hpp:3608:6: note: candidate template ignored: requirement 'std::is_void_v<Kokkos::Impl::ViewSpecializeSacadoFad>' was not satisfied [with T = Sacado::Fad::Exp::GeneralFad<Sacado::Fad::Exp::DynamicStorage<double>> *, P = <Kokkos::Serial>]
17:43:17 auto create_mirror_view(const Kokkos::View<T, P...>& src) {
...
```

**Please include the following for a minimal reproducer**

**Reproducer configuration notes**:
The error occurs with all backends, below is a configuration with llvm/15 and Serial backend
```bash
# Repo prep
git clone -b develop https://github.com/trilinos/Trilinos.git
TRILINOS_DIR=$PWD/Trilinos
git clone -b develop https://github.com/kokkos/kokkos.git
KOKKOS_DIR=$PWD/kokkos
git clone -b develop https://github.com/kokkos/kokkos-kernels.git
KOKKOSKERNELS_DIR=$PWD/kokkos-kernels

cd $TRILINOS_DIR
ln -s ${KOKKOS_DIR}/kokkos kokkos
ln -s ${KOKKOSKERNELS_DIR}/kokkos-kernels kokkos-kernels
cd -

mkdir -p Build
cd Build

# Setup environment - Blake testbed "all" queue shown here
module load cmake llvm openblas/0.3.23

# Configure Trilinos
cmake \
  -D CMAKE_INSTALL_PREFIX="${TRILINOS_INSTALL_DIR}" \
  -D CMAKE_CXX_COMPILER="`which clang++`" \
  -D CMAKE_C_COMPILER="`which clang`" \
  -D CMAKE_Fortran_COMPILER="`which gfortran`" \
  -D CMAKE_CXX_FLAGS="-g -fPIC" \
  -D CMAKE_C_FLAGS="-g -fPIC" \
  -D CMAKE_Fortran_FLAGS="-g -fPIC" \
  -D CMAKE_BUILD_TYPE:STRING=DEBUG \
  -D BUILD_SHARED_LIBS:BOOL=OFF \
  -DTPL_ENABLE_MPI=OFF \
  -DTPL_ENABLE_BLAS:BOOL=ON \
   -DBLAS_LIBRARY_DIRS:FILEPATH=${OPENBLAS_ROOT}/lib \
   -DBLAS_LIBRARY_NAMES:STRING="openblas" \
  -DTPL_ENABLE_LAPACK:BOOL=ON \
   -DLAPACK_INCLUDE_DIRS:FILEPATH=${OPENBLAS_ROOT}/include \
   -DLAPACK_LIBRARY_DIRS:FILEPATH=${OPENBLAS_ROOT}/lib \
   -DLAPACK_LIBRARY_NAMES:STRING="openblas" \
  -DTrilinos_ENABLE_ALL_PACKAGES=OFF \
  -DTrilinos_ENABLE_ALL_OPTIONAL_PACKAGES=OFF \
  -DTrilinos_ENABLE_TESTS=ON \
  -DTrilinos_MUST_FIND_ALL_TPL_LIBS=TRUE \
  -DTrilinos_ENABLE_COMPLEX=ON \
  -DTrilinos_ENABLE_OpenMP=OFF \
  -DTrilinos_ENABLE_Kokkos=ON \
  -D Kokkos_ENABLE_SERIAL=ON \
   -D Kokkos_ENABLE_TESTS=ON \
  -D Kokkos_ARCH_SKX=ON \
   -D Kokkos_ENABLE_IMPL_MDSPAN=OFF \
  -DTrilinos_ENABLE_KokkosKernels=ON \
   -D KokkosKernels_ENABLE_TESTS=ON \
  -DTrilinos_ENABLE_Tpetra=ON \
   -D Tpetra_ENABLE_TESTS=ON \
  -DTrilinos_ENABLE_Sacado=ON \
   -D Sacado_ENABLE_TESTS=ON \
  -DTrilinos_ENABLE_Stokhos=ON \
   -D Stokhos_ENABLE_TESTS=ON \
  -DTrilinos_ENABLE_Intrepid2=ON \
   -D Intrepid2_ENABLE_TESTS=ON \
  -DTrilinos_ENABLE_Adelus=ON \
   -D Adelus_ENABLE_TESTS:BOOL=ON \
  -DTrilinos_ENABLE_Compadre=ON \
   -D Compadre_ENABLE_TESTS=ON \
  -DTrilinos_ENABLE_Panzer=ON \
   -D Panzer_ENABLE_TESTS=ON \
  -DTrilinos_ENABLE_Amesos2=ON \
   -D Amesos2_ENABLE_TESTS=ON \
  -DTrilinos_ENABLE_Zoltan2=ON \
   -D Zoltan2_ENABLE_TESTS=ON \
  -DTrilinos_ENABLE_Teuchos=ON \
   -D Teuchos_ENABLE_TESTS=ON \
  -DTrilinos_ENABLE_Ifpack2=ON \
   -D Ifpack2_ENABLE_TESTS=ON \
\
  -DTPL_ENABLE_Matio=OFF \
\
-DKokkos_SOURCE_DIR_OVERRIDE:STRING=kokkos \
-DKokkosKernels_SOURCE_DIR_OVERRIDE:STRING=kokkos-kernels \
\
$TRILINOS_DIR

# Compile
make -j20
```

* The above example is the full configuration tested, but only Kokkos and Sacado likely need to be enabled above

### PR DESCRIPTION
**Pull request by pzehner**
This PR aims to fix #7125.

- [x] Release `specialize` checks on public interfaces of `create_mirror_view` that were mistakenly added;
- [x] Allow `Impl::create_mirror_view` to either call `Impl::create_mirror` or `create_mirror` (and its possible overloads); and
- [x] Generalize the fix for containers.

What to do after:

- Add tests for views that are `specialize`d, to ensure the problem doesn't occur again.

### CODE REVIEW

**Comment by pzehner** [comment]
@ndellingwood reporting the following errors now:

```
/home/ndellin/trilinos/Trilinos/kokkos/core/src/Kokkos_CopyViews.hpp:3584:14: error: no matching function for call to 'create_mirror'
      return Kokkos::create_mirror(arg_prop, src);
             ^~~~~~~~~~~~~~~~~~~~~
/home/ndellin/trilinos/Trilinos/kokkos/core/src/Kokkos_CopyViews.hpp:3607:16: note: in instantiation of function template specialization 'Kokkos::Impl::create_mirror_view<const Sacado::MP::Vector<Stokhos::StaticFixedStorage<int, double, 16, Kokkos::Serial>> **, Kokkos::LayoutLeft, Kokkos::Device<Kokkos::Serial, Kokkos::HostSpace>, Kokkos::MemoryTraits<1>>' requested here
  return Impl::create_mirror_view(src, view_alloc());
               ^
/home/ndellin/trilinos/Trilinos/kokkos-kernels/blas/impl/KokkosBlas3_trsm_spec.hpp:108:50: note: in instantiation of function template specialization 'Kokkos::create_mirror_view<const Sacado::MP::Vector<Stokhos::StaticFixedStorage<int, double, 16, Kokkos::Serial>> **, Kokkos::LayoutLeft, Kokkos::Device<Kokkos::Serial, Kokkos::HostSpace>, Kokkos::MemoryTraits<1>>' requested here
    typename AViewType::HostMirror h_A = Kokkos::create_mirror_view(A);
                                                 ^
/home/ndellin/trilinos/Trilinos/kokkos-kernels/blas/src/KokkosBlas3_trsm.hpp:150:54: note: in instantiation of member function 'KokkosBlas::Impl::TRSM<Kokkos::Serial, Kokkos::View<const Sacado::MP::Vector<Stokhos::StaticFixedStorage<int, double, 16, Kokkos::Serial>> **, Kokkos::LayoutLeft, Kokkos::Device<Kokkos::Serial, Kokkos::HostSpace>, Kokkos::MemoryTraits<1>>, Kokkos::View<Sacado::MP::Vector<Stokhos::StaticFixedStorage<int, double, 16, Kokkos::Serial>> **, Kokkos::LayoutLeft, Kokkos::Device<Kokkos::Serial, Kokkos::HostSpace>, Kokkos::MemoryTraits<1>>, false, false>::trsm' requested here
  KokkosBlas::Impl::TRSM<execution_space, AVT, BVT>::trsm(
                                                     ^
/home/ndellin/trilinos/Trilinos/kokkos-kernels/sparse/impl/KokkosSparse_sptrsv_solve_impl.hpp:3153:31: note: in instantiation of function template specialization 'KokkosBlas::trsm<Kokkos::Serial, Kokkos::View<Sacado::MP::Vector<Stokhos::StaticFixedStorage<int, double, 16, Kokkos::Serial>> **, Kokkos::LayoutLeft, Kokkos::Device<Kokkos::Serial, Kokkos::HostSpace>, Kokkos::MemoryTraits<1>>, Kokkos::View<Sacado::MP::Vector<Stokhos::StaticFixedStorage<int, double, 16, Kokkos::Serial>> **, Kokkos::LayoutLeft, Kokkos::Device<Kokkos::Serial, Kokkos::HostSpace>, Kokkos::MemoryTraits<1>>>' requested here
                  KokkosBlas::trsm(space, "L", "L", "N", &unit_diag, one, Ljj,
                              ^
/home/ndellin/trilinos/Trilinos/kokkos-kernels/sparse/impl/KokkosSparse_sptrsv_solve_spec.hpp:146:25: note: in instantiation of function template specialization 'KokkosSparse::Impl::Experimental::lower_tri_solve<Kokkos::Serial, KokkosSparse::Experimental::SPTRSVHandle<const unsigned long, const int, const Sacado::MP::Vector<Stokhos::StaticFixedStorage<int, double, 16, Kokkos::Serial>>, Kokkos::Serial, Kokkos::HostSpace, Kokkos::HostSpace>, Kokkos::View<const unsigned long *, Kokkos::LayoutLeft, Kokkos::Device<Kokkos::Serial, Kokkos::HostSpace>, Kokkos::MemoryTraits<3>>, Kokkos::View<const int *, Kokkos::LayoutLeft, Kokkos::Device<Kokkos::Serial, Kokkos::HostSpace>, Kokkos::MemoryTraits<3>>, Kokkos::View<const Sacado::MP::Vector<Stokhos::StaticFixedStorage<int, double, 16, Kokkos::Serial>> *, Kokkos::LayoutLeft, Kokkos::Device<Kokkos::Serial, Kokkos::HostSpace>, Kokkos::MemoryTraits<3>>, Kokkos::View<const Sacado::MP::Vector<Stokhos::StaticFixedStorage<int, double, 16, Kokkos::Serial>> *, Kokkos::LayoutLeft, Kokkos::Device<Kokkos::Serial, Kokkos::HostSpace>, Kokkos::MemoryTraits<3>>, Kokkos::View<Sacado::MP::Vector<Stokhos::StaticFixedStorage<int, double, 16, Kokkos::Serial>> *, Kokkos::LayoutLeft, Kokkos::Device<Kokkos::Serial, Kokkos::HostSpace>, Kokkos::MemoryTraits<1>>>' requested here
          Experimental::lower_tri_solve(space, *sptrsv_handle, row_map, entries,
                        ^
/home/ndellin/trilinos/Trilinos/kokkos-kernels/sparse/src/KokkosSparse_sptrsv.hpp:434:26: note: in instantiation of member function 'KokkosSparse::Impl::SPTRSV_SOLVE<Kokkos::Serial, KokkosKernels::Experimental::KokkosKernelsHandle<const unsigned long, const int, const Sacado::MP::Vector<Stokhos::StaticFixedStorage<int, double, 16, Kokkos::Serial>>, Kokkos::Serial, Kokkos::HostSpace, Kokkos::HostSpace>, Kokkos::View<const unsigned long *, Kokkos::LayoutLeft, Kokkos::Device<Kokkos::Serial, Kokkos::HostSpace>, Kokkos::MemoryTraits<3>>, Kokkos::View<const int *, Kokkos::LayoutLeft, Kokkos::Device<Kokkos::Serial, Kokkos::HostSpace>, Kokkos::MemoryTraits<3>>, Kokkos::View<const Sacado::MP::Vector<Stokhos::StaticFixedStorage<int, double, 16, Kokkos::Serial>> *, Kokkos::LayoutLeft, Kokkos::Device<Kokkos::Serial, Kokkos::HostSpace>, Kokkos::MemoryTraits<3>>, Kokkos::View<const Sacado::MP::Vector<Stokhos::StaticFixedStorage<int, double, 16, Kokkos::Serial>> *, Kokkos::LayoutLeft, Kokkos::Device<Kokkos::Serial, Kokkos::HostSpace>, Kokkos::MemoryTraits<3>>, Kokkos::View<Sacado::MP::Vector<Stokhos::StaticFixedStorage<int, double, 16, Kokkos::Serial>> *, Kokkos::LayoutLeft, Kokkos::Device<Kokkos::Serial, Kokkos::HostSpace>, Kokkos::MemoryTraits<1>>, false, false>::sptrsv_solve' requested here
        XType_Internal>::sptrsv_solve(space, &tmp_handle, rowmap_i, entries_i,
                         ^
/home/ndellin/trilinos/Trilinos/kokkos-kernels/sparse/src/KokkosSparse_sptrsv.hpp:472:3: note: in instantiation of function template specialization 'KokkosSparse::Experimental::sptrsv_solve<Kokkos::Serial, KokkosKernels::Experimental::KokkosKernelsHandle<const unsigned long, const int, Sacado::MP::Vector<Stokhos::StaticFixedStorage<int, double, 16, Kokkos::Serial>>, Kokkos::Serial, Kokkos::HostSpace, Kokkos::HostSpace>, Kokkos::View<const unsigned long *, Kokkos::LayoutLeft, Kokkos::Device<Kokkos::Serial, Kokkos::HostSpace>, Kokkos::MemoryTraits<0>>, Kokkos::View<int *, Kokkos::LayoutLeft, Kokkos::Device<Kokkos::Serial, Kokkos::HostSpace>, Kokkos::MemoryTraits<0>>, Kokkos::View<Sacado::MP::Vector<Stokhos::StaticFixedStorage<int, double, 16, Kokkos::Serial>> *, Kokkos::LayoutRight, Kokkos::Device<Kokkos::Serial, Kokkos::HostSpace>, void>, Kokkos::View<const Sacado::MP::Vector<Stokhos::StaticFixedStorage<int, double, 16, Kokkos::Serial>> *, Kokkos::LayoutLeft, Kokkos::Device<Kokkos::Serial, Kokkos::HostSpace>, Kokkos::MemoryTraits<0>>, Kokkos::View<Sacado::MP::Vector<Stokhos::StaticFixedStorage<int, double, 16, Kokkos::Serial>> *, Kokkos::LayoutLeft, Kokkos::Device<Kokkos::Serial, Kokkos::HostSpace>, Kokkos::MemoryTraits<0>>>' requested here
  sptrsv_solve(my_exec_space, handle, rowmap, entries, values, b, x);
...
```

**Comment by pzehner** [comment]
@ndellingwood It seems that lines are missing from the backtrace, can you give us the entirety of it?

**Comment by ndellingwood** [comment]
@pzehner sorry about that, I clipped the output snip to early, here you go:

```
/home/ndellin/trilinos/Trilinos/kokkos/core/src/Kokkos_CopyViews.hpp:3584:14: error: no matching function for call to 'create_mirror'
      return Kokkos::create_mirror(arg_prop, src);
             ^~~~~~~~~~~~~~~~~~~~~
/home/ndellin/trilinos/Trilinos/kokkos/core/src/Kokkos_CopyViews.hpp:3607:16: note: in instantiation of function template specialization 'Kokkos::Impl::create_mirror_view<const Sacado::MP::Vector<Stokhos::StaticFixedStorage<int, double, 16, Kokkos::Serial>> **, Kokkos::LayoutLeft, Kokkos::Device<Kokkos::Serial, Kokkos::HostSpace>, Kokkos::MemoryTraits<1>>' requested here
  return Impl::create_mirror_view(src, view_alloc());
               ^
/home/ndellin/trilinos/Trilinos/kokkos-kernels/blas/impl/KokkosBlas3_trsm_spec.hpp:108:50: note: in instantiation of function template specialization 'Kokkos::create_mirror_view<const Sacado::MP::Vector<Stokhos::StaticFixedStorage<int, double, 16, Kokkos::Serial>> **, Kokkos::LayoutLeft, Kokkos::Device<Kokkos::Serial, Kokkos::HostSpace>, Kokkos::MemoryTraits<1>>' requested here
    typename AViewType::HostMirror h_A = Kokkos::create_mirror_view(A);
                                                 ^
/home/ndellin/trilinos/Trilinos/kokkos-kernels/blas/src/KokkosBlas3_trsm.hpp:150:54: note: in instantiation of member function 'KokkosBlas::Impl::TRSM<Kokkos::Serial, Kokkos::View<const Sacado::MP::Vector<Stokhos::StaticFixedStorage<int, double, 16, Kokkos::Serial>> **, Kokkos::LayoutLeft, Kokkos::Device<Kokkos::Serial, Kokkos::HostSpace>, Kokkos::MemoryTraits<1>>, Kokkos::View<Sacado::MP::Vector<Stokhos::StaticFixedStorage<int, double, 16, Kokkos::Serial>> **, Kokkos::LayoutLeft, Kokkos::Device<Kokkos::Serial, Kokkos::HostSpace>, Kokkos::MemoryTraits<1>>, false, false>::trsm' requested here
  KokkosBlas::Impl::TRSM<execution_space, AVT, BVT>::trsm(
                                                     ^
/home/ndellin/trilinos/Trilinos/kokkos-kernels/sparse/impl/KokkosSparse_sptrsv_solve_impl.hpp:3153:31: note: in instantiation of function template specialization 'KokkosBlas::trsm<Kokkos::Serial, Kokkos::View<Sacado::MP::Vector<Stokhos::StaticFixedStorage<int, double, 16, Kokkos::Serial>> **, Kokkos::LayoutLeft, Kokkos::Device<Kokkos::Serial, Kokkos::HostSpace>, Kokkos::MemoryTraits<1>>, Kokkos::View<Sacado::MP::Vector<Stokhos::StaticFixedStorage<int, double, 16, Kokkos::Serial>> **, Kokkos::LayoutLeft, Kokkos::Device<Kokkos::Serial, Kokkos::HostSpace>, Kokkos::MemoryTraits<1>>>' requested here
                  KokkosBlas::trsm(space, "L", "L", "N", &unit_diag, one, Ljj,
                              ^
/home/ndellin/trilinos/Trilinos/kokkos-kernels/sparse/impl/KokkosSparse_sptrsv_solve_spec.hpp:146:25: note: in instantiation of function template specialization 'KokkosSparse::Impl::Experimental::lower_tri_solve<Kokkos::Serial, KokkosSparse::Experimental::SPTRSVHandle<const unsigned long, const int, const Sacado::MP::Vector<Stokhos::StaticFixedStorage<int, double, 16, Kokkos::Serial>>, Kokkos::Serial, Kokkos::HostSpace, Kokkos::HostSpace>, Kokkos::View<const unsigned long *, Kokkos::LayoutLeft, Kokkos::Device<Kokkos::Serial, Kokkos::HostSpace>, Kokkos::MemoryTraits<3>>, Kokkos::View<const int *, Kokkos::LayoutLeft, Kokkos::Device<Kokkos::Serial, Kokkos::HostSpace>, Kokkos::MemoryTraits<3>>, Kokkos::View<const Sacado::MP::Vector<Stokhos::StaticFixedStorage<int, double, 16, Kokkos::Serial>> *, Kokkos::LayoutLeft, Kokkos::Device<Kokkos::Serial, Kokkos::HostSpace>, Kokkos::MemoryTraits<3>>, Kokkos::View<const Sacado::MP::Vector<Stokhos::StaticFixedStorage<int, double, 16, Kokkos::Serial>> *, Kokkos::LayoutLeft, Kokkos::Device<Kokkos::Serial, Kokkos::HostSpace>, Kokkos::MemoryTraits<3>>, Kokkos::View<Sacado::MP::Vector<Stokhos::StaticFixedStorage<int, double, 16, Kokkos::Serial>> *, Kokkos::LayoutLeft, Kokkos::Device<Kokkos::Serial, Kokkos::HostSpace>, Kokkos::MemoryTraits<1>>>' requested here
          Experimental::lower_tri_solve(space, *sptrsv_handle, row_map, entries,
                        ^
/home/ndellin/trilinos/Trilinos/kokkos-kernels/sparse/src/KokkosSparse_sptrsv.hpp:434:26: note: in instantiation of member function 'KokkosSparse::Impl::SPTRSV_SOLVE<Kokkos::Serial, KokkosKernels::Experimental::KokkosKernelsHandle<const unsigned long, const int, const Sacado::MP::Vector<Stokhos::StaticFixedStorage<int, double, 16, Kokkos::Serial>>, Kokkos::Serial, Kokkos::HostSpace, Kokkos::HostSpace>, Kokkos::View<const unsigned long *, Kokkos::LayoutLeft, Kokkos::Device<Kokkos::Serial, Kokkos::HostSpace>, Kokkos::MemoryTraits<3>>, Kokkos::View<const int *, Kokkos::LayoutLeft, Kokkos::Device<Kokkos::Serial, Kokkos::HostSpace>, Kokkos::MemoryTraits<3>>, Kokkos::View<const Sacado::MP::Vector<Stokhos::StaticFixedStorage<int, double, 16, Kokkos::Serial>> *, Kokkos::LayoutLeft, Kokkos::Device<Kokkos::Serial, Kokkos::HostSpace>, Kokkos::MemoryTraits<3>>, Kokkos::View<const Sacado::MP::Vector<Stokhos::StaticFixedStorage<int, double, 16, Kokkos::Serial>> *, Kokkos::LayoutLeft, Kokkos::Device<Kokkos::Serial, Kokkos::HostSpace>, Kokkos::MemoryTraits<3>>, Kokkos::View<Sacado::MP::Vector<Stokhos::StaticFixedStorage<int, double, 16, Kokkos::Serial>> *, Kokkos::LayoutLeft, Kokkos::Device<Kokkos::Serial, Kokkos::HostSpace>, Kokkos::MemoryTraits<1>>, false, false>::sptrsv_solve' requested here
        XType_Internal>::sptrsv_solve(space, &tmp_handle, rowmap_i, entries_i,
                         ^
/home/ndellin/trilinos/Trilinos/kokkos-kernels/sparse/src/KokkosSparse_sptrsv.hpp:472:3: note: in instantiation of function template specialization 'KokkosSparse::Experimental::sptrsv_solve<Kokkos::Serial, KokkosKernels::Experimental::KokkosKernelsHandle<const unsigned long, const int, Sacado::MP::Vector<Stokhos::StaticFixedStorage<int, double, 16, Kokkos::Serial>>, Kokkos::Serial, Kokkos::HostSpace, Kokkos::HostSpace>, Kokkos::View<const unsigned long *, Kokkos::LayoutLeft, Kokkos::Device<Kokkos::Serial, Kokkos::HostSpace>, Kokkos::MemoryTraits<0>>, Kokkos::View<int *, Kokkos::LayoutLeft, Kokkos::Device<Kokkos::Serial, Kokkos::HostSpace>, Kokkos::MemoryTraits<0>>, Kokkos::View<Sacado::MP::Vector<Stokhos::StaticFixedStorage<int, double, 16, Kokkos::Serial>> *, Kokkos::LayoutRight, Kokkos::Device<Kokkos::Serial, Kokkos::HostSpace>, void>, Kokkos::View<const Sacado::MP::Vector<Stokhos::StaticFixedStorage<int, double, 16, Kokkos::Serial>> *, Kokkos::LayoutLeft, Kokkos::Device<Kokkos::Serial, Kokkos::HostSpace>, Kokkos::MemoryTraits<0>>, Kokkos::View<Sacado::MP::Vector<Stokhos::StaticFixedStorage<int, double, 16, Kokkos::Serial>> *, Kokkos::LayoutLeft, Kokkos::Device<Kokkos::Serial, Kokkos::HostSpace>, Kokkos::MemoryTraits<0>>>' requested here
  sptrsv_solve(my_exec_space, handle, rowmap, entries, values, b, x);
  ^
/home/ndellin/trilinos/Trilinos/packages/ifpack2/src/Ifpack2_LocalSparseTriangularSolver_def.hpp:929:35: note: in instantiation of function template specialization 'KokkosSparse::Experimental::sptrsv_solve<KokkosKernels::Experimental::KokkosKernelsHandle<const unsigned long, const int, Sacado::MP::Vector<Stokhos::StaticFixedStorage<int, double, 16, Kokkos::Serial>>, Kokkos::Serial, Kokkos::HostSpace, Kokkos::HostSpace>, Kokkos::View<const unsigned long *, Kokkos::LayoutLeft, Kokkos::Device<Kokkos::Serial, Kokkos::HostSpace>, Kokkos::MemoryTraits<0>>, Kokkos::View<int *, Kokkos::LayoutLeft, Kokkos::Device<Kokkos::Serial, Kokkos::HostSpace>, Kokkos::MemoryTraits<0>>, Kokkos::View<Sacado::MP::Vector<Stokhos::StaticFixedStorage<int, double, 16, Kokkos::Serial>> *, Kokkos::LayoutRight, Kokkos::Device<Kokkos::Serial, Kokkos::HostSpace>, void>, Kokkos::View<const Sacado::MP::Vector<Stokhos::StaticFixedStorage<int, double, 16, Kokkos::Serial>> *, Kokkos::LayoutLeft, Kokkos::Device<Kokkos::Serial, Kokkos::HostSpace>, Kokkos::MemoryTraits<0>>, Kokkos::View<Sacado::MP::Vector<Stokhos::StaticFixedStorage<int, double, 16, Kokkos::Serial>> *, Kokkos::LayoutLeft, Kokkos::Device<Kokkos::Serial, Kokkos::HostSpace>, Kokkos::MemoryTraits<0>>>' requested here
      KokkosSparse::Experimental::sptrsv_solve(kh_.getRawPtr(), ptr, ind, val, Y_lcl_1d, X_lcl_1d);
                                  ^
/home/ndellin/trilinos/Trilinos/packages/stokhos/src/sacado/kokkos/vector/Kokkos_View_MP_Vector_Fwd.hpp:132:1: note: candidate function template not viable: no known conversion from 'const Impl::ViewCtorProp<>' to 'Kokkos::Impl::WithoutInitializing_t' for 1st argument
create_mirror(Kokkos::Impl::WithoutInitializing_t wi,
^
/home/ndellin/trilinos/Trilinos/packages/stokhos/src/sacado/kokkos/vector/Kokkos_View_MP_Vector_Fwd.hpp:143:1: note: candidate function template not viable: no known conversion from 'const Impl::ViewCtorProp<>' to 'Kokkos::Impl::WithoutInitializing_t' for 1st argument
create_mirror(Kokkos::Impl::WithoutInitializing_t wi,
^
/home/ndellin/trilinos/Trilinos/packages/stokhos/src/sacado/kokkos/vector/Kokkos_View_MP_Vector_Fwd.hpp:121:1: note: candidate template ignored: requirement 'Kokkos::is_space<Kokkos::Impl::ViewCtorProp<>>::value' was not satisfied [with Space = Kokkos::Impl::ViewCtorProp<>, T = const Sacado::MP::Vector<Stokhos::StaticFixedStorage<int, double, 16, Kokkos::Serial>> **, P = <Kokkos::LayoutLeft, Kokkos::Device<Kokkos::Serial, Kokkos::HostSpace>, Kokkos::MemoryTraits<1>>]
create_mirror(const Space&,
^
/home/ndellin/trilinos/Trilinos/kokkos/core/src/Kokkos_CopyViews.hpp:3530:6: note: candidate template ignored: requirement 'std::is_void_v<Kokkos::Experimental::Impl::ViewMPVectorContiguous>' was not satisfied [with T = const Sacado::MP::Vector<Stokhos::StaticFixedStorage<int, double, 16, Kokkos::Serial>> **, P = <Kokkos::LayoutLeft, Kokkos::Device<Kokkos::Serial, Kokkos::HostSpace>, Kokkos::MemoryTraits<1>>]
auto create_mirror(Kokkos::Impl::WithoutInitializing_t wi,
     ^
/home/ndellin/trilinos/Trilinos/kokkos/core/src/Kokkos_CopyViews.hpp:3540:6: note: candidate template ignored: requirement 'Kokkos::is_space<Kokkos::Impl::ViewCtorProp<>>::value' was not satisfied [with Space = Kokkos::Impl::ViewCtorProp<>, T = const Sacado::MP::Vector<Stokhos::StaticFixedStorage<int, double, 16, Kokkos::Serial>> **, P = <Kokkos::LayoutLeft, Kokkos::Device<Kokkos::Serial, Kokkos::HostSpace>, Kokkos::MemoryTraits<1>>]
auto create_mirror(Space const&, Kokkos::View<T, P...> const& src) {
     ^
/home/ndellin/trilinos/Trilinos/kokkos/core/src/Kokkos_CopyViews.hpp:3549:6: note: candidate template ignored: requirement 'std::is_void_v<Kokkos::Experimental::Impl::ViewMPVectorContiguous>' was not satisfied [with T = const Sacado::MP::Vector<Stokhos::StaticFixedStorage<int, double, 16, Kokkos::Serial>> **, P = <Kokkos::LayoutLeft, Kokkos::Device<Kokkos::Serial, Kokkos::HostSpace>, Kokkos::MemoryTraits<1>>, ViewCtorArgs = <>]
auto create_mirror(Impl::ViewCtorProp<ViewCtorArgs...> const& arg_prop,
     ^
/home/ndellin/trilinos/Trilinos/packages/stokhos/src/sacado/kokkos/vector/Kokkos_View_MP_Vector_Fwd.hpp:103:1: note: candidate function template not viable: requires single argument 'src', but 2 arguments were provided
create_mirror(const Kokkos::View<T,P...> & src);
^
/home/ndellin/trilinos/Trilinos/packages/stokhos/src/sacado/kokkos/vector/Kokkos_View_MP_Vector_Fwd.hpp:113:1: note: candidate function template not viable: requires single argument 'src', but 2 arguments were provided
create_mirror(const Kokkos::View<T,P...> & src);
^
/home/ndellin/trilinos/Trilinos/kokkos/core/src/Kokkos_CopyViews.hpp:3522:6: note: candidate function template not viable: requires single argument 'src', but 2 arguments were provided
auto create_mirror(Kokkos::View<T, P...> const& src) {
     ^
/home/ndellin/trilinos/Trilinos/packages/stokhos/src/sacado/kokkos/vector/Kokkos_View_MP_Vector_Fwd.hpp:152:2: note: candidate function template not viable: requires 3 arguments, but 2 were provided
 create_mirror(
 ^
/home/ndellin/trilinos/Trilinos/kokkos/core/src/Kokkos_CopyViews.hpp:3559:6: note: candidate function template not viable: requires 3 arguments, but 2 were provided
auto create_mirror(Kokkos::Impl::WithoutInitializing_t wi, Space const&,
     ^
1 error generated.
```

**Comment by pzehner** [comment]
Could you try with the latest commit?

**Comment by ndellingwood** [comment]
@pzehner rebuilding now

**Comment by ndellingwood** [comment]
@pzehner the change helped make progress past the previous issue, I'm seeing an new issue:

```
FAILED: packages/sacado/test/UnitTests/CMakeFiles/Sacado_FadKokkosAtomicTests_Serial.dir/Fad_KokkosAtomicTests_Serial.cpp.o
/projects/x86-64-icelake-rocky8/compilers/llvm/15.0.7/gcc/8.5.0/base/i7ryam5/bin/clang++ -DKOKKOS_DEPENDENCE -I/home/ndellin/trilinos/Trilinos/Build/Blake-serial-llvm1507 -I/home/ndellin/trilinos/Trilinos/packages/sacado/test/utils -I/home/ndellin/trilinos/Trilinos/Build/Blake-serial-llvm1507/packages/sacado/src -I/home/ndellin/trilinos/Trilinos/packages/sacado/src -I/home/ndellin/trilinos/Trilinos/packages/sacado/src/new_design -I/home/ndellin/trilinos/Trilinos/packages/sacado/src/template -I/home/ndellin/trilinos/Trilinos/packages/sacado/src/parameter -I/home/ndellin/trilinos/Trilinos/packages/sacado/src/mpl -I/home/ndellin/trilinos/Trilinos/Build/Blake-serial-llvm1507/kokkos/core/src -I/home/ndellin/trilinos/Trilinos/kokkos/core/src -I/home/ndellin/trilinos/Trilinos/Build/Blake-serial-llvm1507/kokkos -I/home/ndellin/trilinos/Trilinos/kokkos/core/src/../../tpls/desul/include -I/home/ndellin/trilinos/Trilinos/kokkos/core/src/../../tpls/mdspan/include -I/home/ndellin/trilinos/Trilinos/Build/Blake-serial-llvm1507/kokkos/containers/src -I/home/ndellin/trilinos/Trilinos/kokkos/containers/src -I/home/ndellin/trilinos/Trilinos/Build/Blake-serial-llvm1507/kokkos/algorithms/src -I/home/ndellin/trilinos/Trilinos/kokkos/algorithms/src -I/home/ndellin/trilinos/Trilinos/Build/Blake-serial-llvm1507/kokkos/simd/src -I/home/ndellin/trilinos/Trilinos/kokkos/simd/src -I/home/ndellin/trilinos/Trilinos/Build/Blake-serial-llvm1507/packages/teuchos/core/src -I/home/ndellin/trilinos/Trilinos/packages/teuchos/core/src -I/home/ndellin/trilinos/Trilinos/packages/teuchos/numerics/src -I/home/ndellin/trilinos/Trilinos/packages/teuchos/comm/src -I/home/ndellin/trilinos/Trilinos/packages/teuchos/parameterlist/src -I/home/ndellin/trilinos/Trilinos/Build/Blake-serial-llvm1507/packages/teuchos/parameterlist/src -I/home/ndellin/trilinos/Trilinos/packages/teuchos/parser/src -I/home/ndellin/trilinos/Trilinos/Build/Blake-serial-llvm1507/packages/teuchos/kokkoscomm/src -I/home/ndellin/trilinos/Trilinos/packages/teuchos/kokkoscomm/src -I/home/ndellin/trilinos/Trilinos/Build/Blake-serial-llvm1507/packages/teuchos/kokkoscompat/src -I/home/ndellin/trilinos/Trilinos/packages/teuchos/kokkoscompat/src -isystem /projects/x86-64-icelake-rocky8/tpls/openblas/0.3.20/clang/15.0.7/base/3as4mmu/include -g -fPIC -g -std=c++17 -march=skylake-avx512 -mtune=skylake-avx512 -MD -MT packages/sacado/test/UnitTests/CMakeFiles/Sacado_FadKokkosAtomicTests_Serial.dir/Fad_KokkosAtomicTests_Serial.cpp.o -MF packages/sacado/test/UnitTests/CMakeFiles/Sacado_FadKokkosAtomicTests_Serial.dir/Fad_KokkosAtomicTests_Serial.cpp.o.d -o packages/sacado/test/UnitTests/CMakeFiles/Sacado_FadKokkosAtomicTests_Serial.dir/Fad_KokkosAtomicTests_Serial.cpp.o -c /home/ndellin/trilinos/Trilinos/packages/sacado/test/UnitTests/Fad_KokkosAtomicTests_Serial.cpp
In file included from /home/ndellin/trilinos/Trilinos/packages/sacado/test/UnitTests/Fad_KokkosAtomicTests_Serial.cpp:29:
In file included from /home/ndellin/trilinos/Trilinos/packages/teuchos/core/src/Teuchos_UnitTestHarness.hpp:51:
In file included from /home/ndellin/trilinos/Trilinos/packages/teuchos/core/src/Teuchos_UnitTestBase.hpp:51:
In file included from /home/ndellin/trilinos/Trilinos/packages/teuchos/core/src/Teuchos_Describable.hpp:45:
In file included from /home/ndellin/trilinos/Trilinos/packages/teuchos/core/src/Teuchos_VerbosityLevel.hpp:51:
In file included from /home/ndellin/trilinos/Trilinos/packages/teuchos/core/src/Teuchos_Assert.hpp:46:
In file included from /home/ndellin/trilinos/Trilinos/packages/teuchos/core/src/Teuchos_TestForException.hpp:49:
In file included from /home/ndellin/trilinos/Trilinos/packages/teuchos/core/src/Teuchos_TypeNameTraits.hpp:65:
In file included from /home/ndellin/trilinos/Trilinos/packages/teuchos/core/src/Teuchos_ConfigDefs.hpp:85:
In file included from /usr/lib/gcc/x86_64-redhat-linux/8/../../../../include/c++/8/string:40:
In file included from /usr/lib/gcc/x86_64-redhat-linux/8/../../../../include/c++/8/bits/char_traits.h:39:
In file included from /usr/lib/gcc/x86_64-redhat-linux/8/../../../../include/c++/8/bits/stl_algobase.h:64:
In file included from /usr/lib/gcc/x86_64-redhat-linux/8/../../../../include/c++/8/bits/stl_pair.h:59:
In file included from /usr/lib/gcc/x86_64-redhat-linux/8/../../../../include/c++/8/bits/move.h:55:
/usr/lib/gcc/x86_64-redhat-linux/8/../../../../include/c++/8/type_traits:1000:56: error: incomplete type 'Kokkos::Impl::UnsupportedKokkosArrayLayout' used in type trait expression
      : public __bool_constant<__is_assignable(_Tp, _Up)>
                                                       ^
/usr/lib/gcc/x86_64-redhat-linux/8/../../../../include/c++/8/type_traits:2799:43: note: in instantiation of template class 'std::is_assignable<Kokkos::mdspan<double, Kokkos::extents<unsigned long, 18446744073709551615, 18446744073709551615>, Kokkos::Experimental::layout_left_padded<18446744073709551615>, Kokkos::Impl::SpaceAwareAccessor<Kokkos::HostSpace, Kokkos::default_accessor<double>>>, Kokkos::Impl::UnsupportedKokkosArrayLayout>' requested here
  inline constexpr bool is_assignable_v = is_assignable<_Tp, _Up>::value;
                                          ^
/home/ndellin/trilinos/Trilinos/kokkos/core/src/Kokkos_View.hpp:1744:46: note: in instantiation of variable template specialization 'std::is_assignable_v<Kokkos::mdspan<double, Kokkos::extents<unsigned long, 18446744073709551615, 18446744073709551615>, Kokkos::Experimental::layout_left_padded<18446744073709551615>, Kokkos::Impl::SpaceAwareAccessor<Kokkos::HostSpace, Kokkos::default_accessor<double>>>, Kokkos::Impl::UnsupportedKokkosArrayLayout>' requested here
            typename = std::enable_if_t<std::is_assignable_v<
                                             ^
/home/ndellin/trilinos/Trilinos/kokkos/core/src/Kokkos_View.hpp:1748:36: note: in instantiation of default argument for 'operator mdspan<type-parameter-0-0, type-parameter-0-1, type-parameter-0-2, type-parameter-0-3><double, Kokkos::extents<unsigned long, 18446744073709551615, 18446744073709551615>, Kokkos::Experimental::layout_left_padded<18446744073709551615>, Kokkos::Impl::SpaceAwareAccessor<Kokkos::HostSpace, Kokkos::default_accessor<double>>>' required here
  KOKKOS_INLINE_FUNCTION constexpr operator mdspan<
                                   ^~~~~~~~~~~~~~~~
/home/ndellin/trilinos/Trilinos/packages/sacado/src/KokkosExp_View_Fad.hpp:408:67: note: while substituting deduced template arguments into function template 'operator mdspan<type-parameter-0-0, type-parameter-0-1, type-parameter-0-2, type-parameter-0-3>' [with OtherElementType = double, OtherExtents = Kokkos::extents<unsigned long, 18446744073709551615, 18446744073709551615>, OtherLayoutPolicy = Kokkos::Experimental::layout_left_padded<18446744073709551615>, OtherAccessor = Kokkos::Impl::SpaceAwareAccessor<Kokkos::HostSpace, Kokkos::default_accessor<double>>, $4 = (no value)]
  typename PODViewDeepCopyType< View<DT,DP...> >::type dst_array( dst );
                                                                  ^
/home/ndellin/trilinos/Trilinos/packages/sacado/src/KokkosExp_View_Fad.hpp:408:56: note: while substituting deduced template arguments into function template 'View' [with U = (no value)]
  typename PODViewDeepCopyType< View<DT,DP...> >::type dst_array( dst );
                                                       ^
/home/ndellin/trilinos/Trilinos/packages/sacado/src/KokkosExp_View_Fad.hpp:435:11: note: in instantiation of function template specialization 'Kokkos::deep_copy<Kokkos::Serial, Sacado::Fad::Exp::GeneralFad<Sacado::Fad::Exp::StaticFixedStorage<double, 5>> *, Kokkos::LayoutContiguous<Kokkos::LayoutLeft, 1>, Kokkos::Serial, Sacado::Fad::Exp::GeneralFad<Sacado::Fad::Exp::StaticFixedStorage<double, 5>> *, Kokkos::LayoutContiguous<Kokkos::LayoutLeft, 1>, Kokkos::Device<Kokkos::Serial, Kokkos::HostSpace>, Kokkos::Experimental::EmptyViewHooks>' requested here
  Kokkos::deep_copy(exec_space(), dst, src);
          ^
/home/ndellin/trilinos/Trilinos/packages/sacado/test/UnitTests/Fad_KokkosAtomicTests.hpp:286:11: note: in instantiation of function template specialization 'Kokkos::deep_copy<Sacado::Fad::Exp::GeneralFad<Sacado::Fad::Exp::StaticFixedStorage<double, 5>> *, Kokkos::LayoutContiguous<Kokkos::LayoutLeft, 1>, Kokkos::Serial, Sacado::Fad::Exp::GeneralFad<Sacado::Fad::Exp::StaticFixedStorage<double, 5>> *, Kokkos::LayoutContiguous<Kokkos::LayoutLeft, 1>, Kokkos::Device<Kokkos::Serial, Kokkos::HostSpace>, Kokkos::Experimental::EmptyViewHooks>' requested here
  Kokkos::deep_copy(v, h_v);
          ^
/home/ndellin/trilinos/Trilinos/packages/sacado/test/UnitTests/Fad_KokkosAtomicTests.hpp:324:13: note: in instantiation of function template specialization 'testAtomic<Sacado::Fad::Exp::GeneralFad<Sacado::Fad::Exp::StaticFixedStorage<double, 5>>, Kokkos::LayoutContiguous<Kokkos::LayoutLeft, 1>, Kokkos::Serial, true, AddTag>' requested here
  success = testAtomic<FadType, Layout, Device, true>(AddTag(), out);
            ^
/home/ndellin/trilinos/Trilinos/kokkos/core/src/Kokkos_View.hpp:379:8: note: forward declaration of 'Kokkos::Impl::UnsupportedKokkosArrayLayout'
struct UnsupportedKokkosArrayLayout;
       ^
In file included from /home/ndellin/trilinos/Trilinos/packages/sacado/test/UnitTests/Fad_KokkosAtomicTests_Serial.cpp:29:
In file included from /home/ndellin/trilinos/Trilinos/packages/teuchos/core/src/Teuchos_UnitTestHarness.hpp:51:
In file included from /home/ndellin/trilinos/Trilinos/packages/teuchos/core/src/Teuchos_UnitTestBase.hpp:51:
In file included from /home/ndellin/trilinos/Trilinos/packages/teuchos/core/src/Teuchos_Describable.hpp:45:
In file included from /home/ndellin/trilinos/Trilinos/packages/teuchos/core/src/Teuchos_VerbosityLevel.hpp:51:
In file included from /home/ndellin/trilinos/Trilinos/packages/teuchos/core/src/Teuchos_Assert.hpp:46:
In file included from /home/ndellin/trilinos/Trilinos/packages/teuchos/core/src/Teuchos_TestForException.hpp:49:
In file included from /home/ndellin/trilinos/Trilinos/packages/teuchos/core/src/Teuchos_TypeNameTraits.hpp:65:
In file included from /home/ndellin/trilinos/Trilinos/packages/teuchos/core/src/Teuchos_ConfigDefs.hpp:85:
In file included from /usr/lib/gcc/x86_64-redhat-linux/8/../../../../include/c++/8/string:40:
In file included from /usr/lib/gcc/x86_64-redhat-linux/8/../../../../include/c++/8/bits/char_traits.h:39:
In file included from /usr/lib/gcc/x86_64-redhat-linux/8/../../../../include/c++/8/bits/stl_algobase.h:64:
In file included from /usr/lib/gcc/x86_64-redhat-linux/8/../../../../include/c++/8/bits/stl_pair.h:59:
In file included from /usr/lib/gcc/x86_64-redhat-linux/8/../../../../include/c++/8/bits/move.h:55:
/usr/lib/gcc/x86_64-redhat-linux/8/../../../../include/c++/8/type_traits:1000:56: error: incomplete type 'Kokkos::Impl::UnsupportedKokkosArrayLayout' used in type trait expression
      : public __bool_constant<__is_assignable(_Tp, _Up)>
... # repeat of the above
```

**Comment by tpadioleau** [comment]
@ndellingwood Is it a different configuration than what you provided in the issue ? In particular, did you turn on 
the option `Kokkos_ENABLE_IMPL_MDSPAN` ?

**Comment by pzehner** [comment]
We could build Sacado serial tests (i.e. the target that builds the file where the error occurs) successfully using GCC with `Kokkos_ENABLE_IMPL_MDSPAN` disabled or enabled.

We then switched to Clang with `Kokkos_ENABLE_IMPL_MDSPAN` enabled, and got the error message you showed. We checked out to commit a6e7f0d1f50eff13322d04002189df210e1fcfd8 (i.e. before #7061 merge commit) and obtained the same error message again. We deduce from this that this specific error is not related to #7061.

**Comment by crtrott** [comment]
Yeah I think that is unrelated. So this PR should be made ready, fix the create_mirror thing and then we can go sort out the to_mdspan thing

**Comment by ndellingwood** [comment]
@pzehner @tpadioleau you are right; in the nightly clang job I still have mdspan temporarily disabled, but I did not have that set in my local manual build. I apologize for the configuration mismatch
Like @crtrott mentioned can this be moved from Draft/WIP to ready for review and test? Thank you for the fast responses addressing the issue

**Comment by ndellingwood** [comment]
I'll open a new issue regarding the mdspan-related issues in the clang build of Trilinos containing the https://github.com/kokkos/kokkos/pull/7126#issuecomment-2223501140 details

File: core/src/Kokkos_CopyViews.hpp [hunk 1]
```diff
@@ -3564,6 +3564,54 @@ auto create_mirror(Kokkos::Impl::WithoutInitializing_t wi, Space const&,
...
+    } else if constexpr (sizeof...(ViewCtorArgs) == 2 &&
+                         ViewProp::has_memory_space && !ViewProp::initialize) {
+      // if there is two view constructor args and they have a memory space and
+      // a without initializing mark, call the specific public function
+      return Kokkos::create_mirror(
+          typename Kokkos::Impl::WithoutInitializing_t{},
+          typename ViewProp::memory_space{}, src);
+    } else {
+      // if there are other constructor args, call the generic public function
+      return Kokkos::create_mirror(arg_prop, src);
```
Comment (crtrott) [inline core/src/Kokkos_CopyViews.hpp:3606]: Ah so the reason that we don't call this always is that Sacado has the overload which say takes "WithoutInitializing_t" but not a general ViewCtorProp?

**Comment by masterleinad** [comment]
> I'll open a new issue regarding the mdspan-related issues in the clang build of Trilinos containing the [#7126 (comment)](https://github.com/kokkos/kokkos/pull/7126#issuecomment-2223501140) details

```diff
diff --git a/core/src/Kokkos_View.hpp b/core/src/Kokkos_View.hpp
index 8c31ae94f..cf4814a8d 100644
--- a/core/src/Kokkos_View.hpp
+++ b/core/src/Kokkos_View.hpp
@@ -1740,11 +1740,15 @@ class View : public ViewTraits<DataType, Properties...> {
   //----------------------------------------
   // Conversion to MDSpan
   template <class OtherElementType, class OtherExtents, class OtherLayoutPolicy,
-            class OtherAccessor,
-            typename = std::enable_if_t<std::is_assignable_v<
-                mdspan<OtherElementType, OtherExtents, OtherLayoutPolicy,
-                       OtherAccessor>,
-                typename Impl::MDSpanViewTraits<traits>::mdspan_type>>>
+            class OtherAccessor, class Dummy = typename Impl::MDSpanViewTraits<traits>::mdspan_type, 
+            typename = std::enable_if_t<
+                   std::conditional_t<std::is_same_v<Impl::UnsupportedKokkosArrayLayout, Dummy>, 
+                                      std::false_type, 
+                                      std::is_assignable<
+                                        mdspan<OtherElementType, OtherExtents, OtherLayoutPolicy,
+                                          OtherAccessor>,
+                                        Dummy>
+                                     >::value>>
   KOKKOS_INLINE_FUNCTION constexpr operator mdspan<
       OtherElementType, OtherExtents, OtherLayoutPolicy, OtherAccessor>() {
     using mdspan_type = typename Impl::MDSpanViewTraits<traits>::mdspan_type;
```
would fix the issue.

File: core/src/Kokkos_CopyViews.hpp (hunk 1 above)
Comment (tpadioleau) [reply core/src/Kokkos_CopyViews.hpp:3606]: That is also our understanding of the issue. It seems there are multiple overloads of the `create_mirror` function https://github.com/trilinos/Trilinos/blob/d71aa67247678321da0b4ca2e822f28b8aed8db4/packages/sacado/src/Kokkos_View_Fad_Fwd.hpp#L102 but no overload with `ViewCtorProp`.

Comment (masterleinad) [reply core/src/Kokkos_CopyViews.hpp:3606]: Yes, `Sacado` didn't follow suit when we introduced the `CiewCtorProp` overloads.

Comment (tpadioleau) [reply core/src/Kokkos_CopyViews.hpp:3606]: Could we come up with a rule about this set of overloads ? For example if a user defines `Kokkos::create_mirror(Kokkos::Impl::WithoutInitializing_t, View)` then it must also define `Kokkos::create_mirror(Kokkos::Impl::ViewCtorProp<Kokkos::Impl::WithoutInitializing_t> const&, View)`

Comment (pzehner) [reply core/src/Kokkos_CopyViews.hpp]: How likely would it be for Sacado to implement the missing `create_mirror`?

**Review by masterleinad — APPROVED** [review]
Looks good to me.

**Comment by pzehner** [comment]
I think this fixes the problem encountered in Trilinos. With @tpadioleau, we propose to start the reviewing as it, then to create a separate PR for the test of `sepcialize`d views.

**Comment by ndellingwood** [comment]
I retested the llvm/15 build of Trilinos in the OP (with Kokkos_ENABLE_IMPL_MDSPAN=OFF set) with sha 89969e11cfa9e77c0367404294a13ed6a36f01f0 of this PR and I was able to compile without any issues 👍

File: core/src/Kokkos_CopyViews.hpp (hunk 1 above)
Comment (masterleinad) [reply core/src/Kokkos_CopyViews.hpp]: > How likely would it be for Sacado to implement the missing create_mirror?

I don't think that will happen if it's not absolutely necessary.

Comment (tpadioleau) [reply core/src/Kokkos_CopyViews.hpp]: So Kokkos must not assume any `specialize` overload right ? Can a user overload `Kokkos::create_mirror(Kokkos::Impl::ViewCtorProp<Kokkos::Impl::WithoutInitializing_t> const&, View)` but not `Kokkos::create_mirror(Kokkos::Impl::WithoutInitializing_t, View)` ?

Comment (masterleinad) [reply core/src/Kokkos_CopyViews.hpp]: None of that is formalized anywhere and Sacado is the only one using `specialize` to the best of my knowledge.

Comment (tpadioleau) [reply core/src/Kokkos_CopyViews.hpp]: Greping Trilinos, it seems that Stokhos also relies on this feature.

Comment (masterleinad) [reply core/src/Kokkos_CopyViews.hpp]: Yeah, `Stokhos` depends on `Sacado` and I tend to refer to them as the same. 🙂

**Review by tpadioleau — APPROVED** [review]

**Review by nliber — APPROVED** [review]
