### PR TITLE
Threads: Fix serial resizing scratch space 

### LINKED ISSUE #4878: Segfaults for Threads+HWLOC on Linux
While looking into #4842, I discovered that tests segfault if HWLOC is used together with the `Threads` backend, at least on our `linux` CI, i.e. `.github/workflows/continuous-integration-workflow.yml` and I can reproduce that locally.

### LINKED ISSUE #5107: Kokkos::parallel_reduce fails for --kokkos-threads>1
**Describe the bug**
Kokkos::parallel_reduce fails when using C++ threads backend and --kokkos-threads>1. Specifically, a Segmentation fault error occurs.

**Please also include the following items to support reproducing the bug**
1. compilers (with versions)
gcc/9.4.0

2. Kokkos release or commit used (i.e., the sha1 number)
commit b52f8c835f4df003954dad66d9761094f8baa66c

3. platform and backend
Linux, C++ threads

4. cmake configure command
OPTIONS=(
-D CMAKE_BUILD_TYPE=Release
-D CMAKE_INSTALL_PREFIX="${KOKKOS_INSTALL_DIR}"
-D CMAKE_CXX_STANDARD=17
-D Kokkos_ENABLE_THREADS=ON
-D Kokkos_ENABLE_TESTS=OFF
-D BUILD_TESTING=OFF
)

5. output from cmake command
-- Setting default Kokkos CXX standard to 17
-- The CXX compiler identification is GNU 9.4.0
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Check for working CXX compiler: /projects/opt/centos8/x86_64/gcc/9.4.0/bin/g++ - skipped
-- Detecting CXX compile features
-- Detecting CXX compile features - done
-- Setting policy CMP0074 to use <Package>_ROOT variables
-- The project name is: Kokkos
-- Using -std=gnu++17 for C++17 extensions as feature
-- Built-in Execution Spaces:
--     Device Parallel: NoTypeDefined
--     Host Parallel: Kokkos::Threads
--       Host Serial: NONE
-- 
-- Architectures:
-- Found TPLLIBDL: /usr/lib64/libdl.so  
-- Looking for C++ include pthread.h
-- Looking for C++ include pthread.h - found
-- Performing Test CMAKE_HAVE_LIBC_PTHREAD
-- Performing Test CMAKE_HAVE_LIBC_PTHREAD - Failed
-- Looking for pthread_create in pthreads
-- Looking for pthread_create in pthreads - not found
-- Looking for pthread_create in pthread
-- Looking for pthread_create in pthread - found
-- Found Threads: TRUE  
-- Found TPLTHREADS: TRUE  
-- Kokkos Devices: THREADS, Kokkos Backends: THREADS
-- Configuring done
-- Generating done
-- Build files have been written to: 

6. code needed to reproduce the bug
```
#include <stdio.h>

int main(int argc, char *argv[])
{
  Kokkos::initialize(argc, argv);
  { // kokkos scope

  int n = 10;
  CArrayKokkos<int> arr(n);

  Kokkos::parallel_for(n,
    KOKKOS_LAMBDA(const int i)
    {
      arr(i) = i;
    });

  int max_value;
  Kokkos::parallel_reduce(n,
    KOKKOS_LAMBDA(const int i, int &loc_max_value)
    {
      int value = arr(i);
      if(value > loc_max_value) loc_max_value = value;
    }, Kokkos::Max<int>(max_value) );
  printf("Max value = %d, should be %d\n", max_value, n-1);

  } // end kokkos scope
  Kokkos::finalize();

  return 0;
}
```
7. command line needed to reproduce the bug
`./a.out --kokkos-threads=2` or `./a.out --kokkos-threads>1`

7. please also attach the `KokkosCore_config.h` header file (generated during the build);
```

#if !defined(KOKKOS_MACROS_HPP) || defined(KOKKOS_CORE_CONFIG_H)
#error \
    "Do not include KokkosCore_config.h directly; include Kokkos_Macros.hpp instead."
#else
#define KOKKOS_CORE_CONFIG_H
#endif

// KOKKOS_VERSION % 100 is the patch level
// KOKKOS_VERSION / 100 % 100 is the minor version
// KOKKOS_VERSION / 10000 is the major version
#define KOKKOS_VERSION 30600

/* Execution Spaces */
/* #undef KOKKOS_ENABLE_SERIAL */
/* #undef KOKKOS_ENABLE_OPENMP */
/* #undef KOKKOS_ENABLE_OPENMPTARGET */
#define KOKKOS_ENABLE_THREADS
/* #undef KOKKOS_ENABLE_CUDA */
/* #undef KOKKOS_ENABLE_HIP */
/* #undef KOKKOS_ENABLE_HPX */
/* #undef KOKKOS_ENABLE_MEMKIND */
/* #undef KOKKOS_ENABLE_LIBRT */
/* #undef KOKKOS_ENABLE_SYCL */

#ifndef __CUDA_ARCH__
/* #undef KOKKOS_ENABLE_TM */
/* #undef KOKKOS_USE_ISA_X86_64 */
/* #undef KOKKOS_USE_ISA_KNC */
/* #undef KOKKOS_USE_ISA_POWERPCLE */
/* #undef KOKKOS_USE_ISA_POWERPCBE */
#endif

/* General Settings */
/* #undef KOKKOS_ENABLE_CXX14 */
#define KOKKOS_ENABLE_CXX17
/* #undef KOKKOS_ENABLE_CXX20 */

/* #undef KOKKOS_ENABLE_CUDA_RELOCATABLE_DEVICE_CODE */
/* #undef KOKKOS_ENABLE_CUDA_UVM */
/* #undef KOKKOS_ENABLE_CUDA_LAMBDA */
/* #undef KOKKOS_ENABLE_CUDA_CONSTEXPR */
/* #undef KOKKOS_ENABLE_CUDA_LDG_INTRINSIC */
/* #undef KOKKOS_ENABLE_IMPL_CUDA_MALLOC_ASYNC */
/* #undef KOKKOS_ENABLE_HIP_RELOCATABLE_DEVICE_CODE */
/* #undef KOKKOS_ENABLE_HIP_MULTIPLE_KERNEL_INSTANTIATIONS */
/* #undef KOKKOS_ENABLE_HPX_ASYNC_DISPATCH */
/* #undef KOKKOS_ENABLE_DEBUG */
/* #undef KOKKOS_ENABLE_DEBUG_DUALVIEW_MODIFY_CHECK */
/* #undef KOKKOS_ENABLE_DEBUG_BOUNDS_CHECK */
/* #undef KOKKOS_ENABLE_COMPILER_WARNINGS */
/* #undef KOKKOS_ENABLE_PROFILING_LOAD_PRINT */
/* #undef KOKKOS_ENABLE_TUNING */
#define KOKKOS_ENABLE_DEPRECATED_CODE_3
#define KOKKOS_ENABLE_DEPRECATION_WARNINGS
/* #undef KOKKOS_ENABLE_LARGE_MEM_TESTS */
/* #undef KOKKOS_ENABLE_DUALVIEW_MODIFY_CHECK */
#define KOKKOS_ENABLE_COMPLEX_ALIGN
#define KOKKOS_ENABLE_IMPL_DESUL_ATOMICS
/* #undef KOKKOS_OPT_RANGE_AGGRESSIVE_VECTORIZATION */
/* #undef KOKKOS_ENABLE_AGGRESSIVE_VECTORIZATION */

/* TPL Settings */
/* #undef KOKKOS_ENABLE_HWLOC */
/* #undef KOKKOS_USE_LIBRT */
/* #undef KOKKOS_ENABLE_HBWSPACE */
#define KOKKOS_ENABLE_LIBDL
/* #undef KOKKOS_ENABLE_LIBQUADMATH */
/* #undef KOKKOS_IMPL_CUDA_CLANG_WORKAROUND */

/* #undef KOKKOS_COMPILER_CUDA_VERSION */

/* #undef KOKKOS_ARCH_SSE42 */
/* #undef KOKKOS_ARCH_ARMV80 */
/* #undef KOKKOS_ARCH_ARMV8_THUNDERX */
/* #undef KOKKOS_ARCH_ARMV81 */
/* #undef KOKKOS_ARCH_ARMV8_THUNDERX2 */
/* #undef KOKKOS_ARCH_AMD_AVX2 */
/* #undef KOKKOS_ARCH_AVX */
/* #undef KOKKOS_ARCH_AVX2 */
/* #undef KOKKOS_ARCH_AVX512XEON */
/* #undef KOKKOS_ARCH_KNC */
/* #undef KOKKOS_ARCH_AVX512MIC */
/* #undef KOKKOS_ARCH_POWER7 */
/* #undef KOKKOS_ARCH_POWER8 */
/* #undef KOKKOS_ARCH_POWER9 */
/* #undef KOKKOS_ARCH_INTEL_GEN */
/* #undef KOKKOS_ARCH_INTEL_DG1 */
/* #undef KOKKOS_ARCH_INTEL_GEN9 */
/* #undef KOKKOS_ARCH_INTEL_GEN11 */
/* #undef KOKKOS_ARCH_INTEL_GEN12LP */
/* #undef KOKKOS_ARCH_INTEL_XEHP */
/* #undef KOKKOS_ARCH_INTEL_GPU */
/* #undef KOKKOS_ARCH_KEPLER */
/* #undef KOKKOS_ARCH_KEPLER30 */
/* #undef KOKKOS_ARCH_KEPLER32 */
/* #undef KOKKOS_ARCH_KEPLER35 */
/* #undef KOKKOS_ARCH_KEPLER37 */
/* #undef KOKKOS_ARCH_MAXWELL */
/* #undef KOKKOS_ARCH_MAXWELL50 */
/* #undef KOKKOS_ARCH_MAXWELL52 */
/* #undef KOKKOS_ARCH_MAXWELL53 */
/* #undef KOKKOS_ARCH_PASCAL */
/* #undef KOKKOS_ARCH_PASCAL60 */
/* #undef KOKKOS_ARCH_PASCAL61 */
/* #undef KOKKOS_ARCH_VOLTA */
/* #undef KOKKOS_ARCH_VOLTA70 */
/* #undef KOKKOS_ARCH_VOLTA72 */
/* #undef KOKKOS_ARCH_TURING75 */
/* #undef KOKKOS_ARCH_AMPERE */
/* #undef KOKKOS_ARCH_AMPERE80 */
/* #undef KOKKOS_ARCH_AMPERE86 */
/* #undef KOKKOS_ARCH_AMD_ZEN */
/* #undef KOKKOS_ARCH_AMD_ZEN2 */
/* #undef KOKKOS_ARCH_AMD_ZEN3 */
/* #undef KOKKOS_ARCH_VEGA */
/* #undef KOKKOS_ARCH_VEGA900 */
/* #undef KOKKOS_ARCH_VEGA906 */
/* #undef KOKKOS_ARCH_VEGA908 */
/* #undef KOKKOS_ARCH_VEGA90A */
```

**Any additional info**
Please provide any additional context about the issue here.

### PR DESCRIPTION
**Pull request by masterleinad**
Fixes #5107. Fixes #4878. This pull request reverts parts of #4499 and makes sure that we call 
```
s_threads_process.m_pool_state = ThreadsExec::Active;
```
after deallocating scratch space (if necessary) to avoid deadlocking.

### CODE REVIEW

**Comment by dalg24** [comment]
I assume you meant [#487{6 -> 8}](https://github.com/kokkos/kokkos/pull/4878)

**Comment by masterleinad** [comment]
> I assume you meant [#487{6 -> 8}](https://github.com/kokkos/kokkos/pull/4878)

Yes, thanks.

File: core/src/Threads/Kokkos_ThreadsExec.cpp [hunk 1]
```diff
@@ -438,14 +445,6 @@ void *ThreadsExec::root_reduce_scratch() {
 void ThreadsExec::execute_resize_scratch(ThreadsExec &exec, const void *) {
   using Record = Kokkos::Impl::SharedAllocationRecord<Kokkos::HostSpace, void>;
```
[the remark this answers is not in the document]
Comment (masterleinad) [reply core/src/Threads/Kokkos_ThreadsExec.cpp]: See 5ab11f6a0.

File: core/src/Threads/Kokkos_ThreadsExec.cpp [hunk 2]
```diff
@@ -399,27 +399,68 @@ bool ThreadsExec::wake() {
 
 //----------------------------------------------------------------------------
 
-void *ThreadsExec::root_reduce_scratch() {
-  return s_threads_process.reduce_memory();
-}
+void ThreadsExec::first_touch_allocate_thread_private_scratch_in_serial() {
```
Comment (crtrott) [inline core/src/Threads/Kokkos_ThreadsExec.cpp:402]: I think this one actually should be `resize_scratch_serial` (since it does the entire resize dealloc + alloc)

File: core/src/Threads/Kokkos_ThreadsExec.cpp [hunk 3]
```diff
@@ -399,27 +399,68 @@ bool ThreadsExec::wake() {
...
+  memory_fence();
+}
+
+//----------------------------------------------------------------------------
+
+void *ThreadsExec::root_reduce_scratch() {
+  return s_threads_process.reduce_memory();
+}
+
+void ThreadsExec::first_touch_allocate_thread_private_scratch(ThreadsExec &exec,
```
Comment (crtrott) [inline core/src/Threads/Kokkos_ThreadsExec.cpp:454]: jup this name is good.

**Review by crtrott — CHANGES_REQUESTED** [review]
Just one more thing: you renamed one function to many. The resize_thread_scratch_serial name for the outer function was actually good. See my comments

**Review by crtrott — APPROVED** [review]

**Review by dalg24 — APPROVED** [review]
