### PR TITLE
#4517: DynamicView: Fix deallocation extent

### LINKED ISSUE #4517: Slow deallocation of DynamicView
The de-allocation of DynamicView has slowed down significantly due to the recent refactor (https://github.com/kokkos/kokkos/pull/4129). 

It seems the issue might be that the deallocation is no longer performed in a parallel_for.

### PR DESCRIPTION
**Pull request by lifflander**
Fixes #4517

### CODE REVIEW

**Comment by lifflander** [comment]
This change fixes the performance issues that were observed in EMPIRE

**Comment by PhilMiller** [comment]
Was the code previously just deallocating some huge number of garbage entries that it shouldn't have been?

**Comment by rppawlo** [comment]
Thanks @lifflander for finding this! We have verified that this fixes the empire issues.

@ndellingwood - when this merges into kokkos, can you snapshot into trilinos. This shoudl get the empire sync of trilinos going again!

**Comment by lifflander** [comment]
> Was the code previously just deallocating some huge number of garbage entries that it shouldn't have been?

Yes, they are nullptr... so just wasting time. Before I changed the code, the deallocator was going over all the entries also but it tested for nullptr before actually calling the deallocator.

**Review by PhilMiller — APPROVED** [review]

**Comment by masterleinad** [comment]
Looks like this makes the unit tests segfault.

File: containers/src/Kokkos_DynamicView.hpp [hunk 1]
```diff
@@ -173,7 +173,8 @@ struct ChunkedArrayManager {
     void execute() {
       // Destroy the array of chunk pointers.
       // Two entries beyond the max chunks are allocation counters.
-      for (unsigned i = 0; i < m_chunk_max; i++) {
+      auto const len = *reinterpret_cast<size_t*>(m_chunks + m_chunk_max + 1);
```
Comment (dalg24) [inline containers/src/Kokkos_DynamicView.hpp:176]:
```suggestion
      auto const len = static_cast<size_t>(m_chunks + m_chunk_max + 1);
```
also why do you even bother changing the type of the counter loop below?

Comment (dalg24) [inline containers/src/Kokkos_DynamicView.hpp:176]: This feels so sketchy.  Why is it not something like
```suggestion
      size_t const len = *(m_chunks + m_chunk_max + 1);
```
Also what was wrong with `unsigned`?

Comment (lifflander) [reply containers/src/Kokkos_DynamicView.hpp:176]: m_chunks is a pointer type that is abused to store a numerical value.

Comment (lifflander) [reply containers/src/Kokkos_DynamicView.hpp:176]: https://github.com/kokkos/kokkos/blob/a1d045da4cc299217e2831f71dedff72e4f2aecf/containers/src/Kokkos_DynamicView.hpp#L356-L360

**Comment by lifflander** [comment]
I accidentally picked the wrong entry for deallocation:
- `m_chunks + m_chunk_max` -> number of chunks used
- `m_chunks + m_chunk_max + 1` -> extent (number of chunks * chunk_size)

**Review by PhilMiller — APPROVED** [review]

**Comment by PhilMiller** [comment]
The CI failure from Jenkins is spurious relative to this PR - 
```
1: [ RUN      ] openmp.reducers_half_t
1: /var/jenkins/workspace/Kokkos/core/unit_test/TestReducers.hpp:398: Failure
1: Expected equality of these values:
1:   prod_scalar
1:     Which is: 13120.000000
1:   reference_prod
1:     Which is: 13128.000000
1: [  FAILED  ] openmp.reducers_half_t (0 ms)
```

It probably represents an independent issue to be investigated, though.

File: containers/src/Kokkos_DynamicView.hpp [hunk 2]
```diff
@@ -173,7 +173,8 @@ struct ChunkedArrayManager {
     void execute() {
       // Destroy the array of chunk pointers.
       // Two entries beyond the max chunks are allocation counters.
-      for (unsigned i = 0; i < m_chunk_max; i++) {
+      size_t const len = *reinterpret_cast<size_t*>(m_chunks + m_chunk_max);
```
Comment (masterleinad) [inline containers/src/Kokkos_DynamicView.hpp:176]:
```suggestion
      uintptr_t const len = *reinterpret_cast<uintptr_t*>(m_chunks + m_chunk_max);
```
just to be conforming with access in other locations. Also, I would very much prefer if the allocation counters are stored in separate variables (inside `ChunkedArrayManager`). The need to `reinterpret_cast` here feels pretty sketchy and is confusing regarding readability.

Comment (lifflander) [reply containers/src/Kokkos_DynamicView.hpp]: Ok, I've made the change to `uintptr_t`

Comment (lifflander) [reply containers/src/Kokkos_DynamicView.hpp]: I agree that allocating them separately would be increase code readability, but this PR is not making this worse (i.e., DynamicView has been this way since the beginning). Due to how critical this is for EMPIRE right now, I would like to get this moved forward as is and then push for refactoring later in improve code readability.

**Review by masterleinad — APPROVED** [review]

**Comment by PhilMiller** [comment]
Retest this please

**Comment by ndellingwood** [comment]
Cherry-picked to 3.5 with #4538
